### ISSUE TITLE
Can we add a option like -m or --mfa-token

### ISSUE THREAD

**Issue by ChrisFernandez** [99designs/aws-vault#101]
Hey actually got it running on linux just fine.. but now we have one issue...
Can we add an option to input from CLI the password to unencrypt the ~/awsvault/keys/${profile_name}

like:

`-m, --mfa-token=MFA-TOKEN`

something like:

`-p, --password=password to unencrypt credentials`

this is so in our bash script we can ask for it.

**Comment by lox** [comment]
Sounds dangerous, I'd much prefer to go down the gpg-agent route for that.

What's the use case?

**Comment by ChrisFernandez** [comment]
yes is dangerous but the way we use it is not... example:
```
 read -p "Enter password: " pass
    local credentials=$(command)
```
we will add another bash stdin to decrypt the secret file on the fly, never gets saved, just like the token.

**Comment by ChrisFernandez** [comment]
Was reading the code to implemented myself locally, and found this: :+1: 
`if password := os.Getenv("AWS_VAULT_FILE_PASSPHRASE"); password != "" {`

so now I can read a promp and pass this env variable on the fly to aws-vault
this is a temp hack, still will be nice to have the flag -P as an option.

**Comment by ChrisFernandez** [comment]
bump :)

**Comment by lox** [comment]
I'm not keen. Passwords via arguments are generally a bad idea IMHO.

Isn't then ENV just as good?

**Comment by lox** [comment]
We could add an env for the MFA token, although at that point, why have an
MFA? :)

**Comment by ChrisFernandez** [comment]
hello the MFA never gets written to disk, we have a custom bash script that  glues AWS SDK/AWS Vault and some internal app's and more scripts the reason I was looking for a flag is to be able to pass from stdin a MFA and password prompt in our other scripts that call aws-vault, so basically is as like using the vault but instead of aws-vault asking for the mfa token, passwd is our script that passes that info  to aws-vault... in the meantime we are hacking it using the AWS_VAULT_FILE_PASSPHASE we get the info from and $argument and pass it to aws-vault with that. but will be so much cleaner with a switch.

**Comment by ChrisFernandez** [comment]
closing this.
