### ISSUE TITLE
`aws-vault` docs should cite limitations of GetSessionToken and how to solve

### ISSUE THREAD

**Issue by ChristopherHackett** [99designs/aws-vault#1056]
Buried in the [AWS documentation](https://docs.aws.amazon.com/STS/latest/APIReference/API_GetSessionToken.html) it says:

> The temporary security credentials created by GetSessionToken can be used to make API calls to any AWS service with the following exceptions:
>     You cannot call any IAM API operations unless MFA authentication information is included in the request.
>     You cannot call any AWS STS API except AssumeRole or GetCallerIdentity.

This causes confusion to users of `aws-vault` who are using an IAM user in their profile. When they attempt to use calls for IAM they get `InvalidClientTokenId`.

```
[profile a]
region=us-east-2
```
``` bash
$ aws-vault exec a -- aws iam list-users

An error occurred (InvalidClientTokenId) when calling the ListUsers operation: The security token included in the request is invalid
```

AWS documentation[ for this error](https://docs.aws.amazon.com/STS/latest/APIReference/CommonErrors.html) is poor:

>  InvalidClientTokenId
>     The X.509 certificate or AWS access key ID provided does not exist in our records.
>     HTTP Status Code: 403

Users of `aws-vault` should have a clear way to understand why they get the InvalidClientTokenId error and be directed to one of the following options
a. (recommended) Attach mfa to the IAM user and configure a profile to use MFA
b. (discouraged) Use `--no-session` to bypass the use of GetSessionToken

I'll look at making a PR but if there is any input anyone wants to make first it will be taken onboard.

**Comment by mtibben** [comment]
I believe there are references to these limitations in the USAGE doc
