### ISSUE TITLE
Latest AWS CLI configure sso creates a profile that aws-vault doesn't understand

### ISSUE THREAD

**Issue by simondroscher** [99designs/aws-vault#1079]
- [x] I am using the latest release of AWS Vault
- [x] I have provided my `.aws/config` (redacted if necessary)
- [x] I have provided the debug output using `aws-vault --debug` (redacted if necessary)

If you have the latest aws cli (1.9.0), when you create a profile using `aws --profile test configure sso` it creates a profile like this:
```
[profile test]
sso_session = session
sso_account_id = XXXXXXXX
sso_role_name = ReadOnly
region = us-east-1

[sso-session session]
sso_start_url = https://XXXXXXX.awsapps.com/start/
sso_region = us-east-1
```

aws-vault doesn't seem to read this correctly and gives `credentials missing` errors:

```
2022/11/22 13:31:15 aws-vault v6.6.0
2022/11/22 13:31:15 Loading config file /Users/XXXX/.aws/config
2022/11/22 13:31:15 Parsing config file /Users/XXXX/.aws/config
2022/11/22 13:31:15 [keyring] Considering backends: [keychain]
2022/11/22 13:31:15 Profile 'default' missing in config file
2022/11/22 13:31:15 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2022/11/22 13:31:15 [keyring] Found 2 results
aws-vault: error: exec: Error getting temporary credentials: profile test: credentials missing
```

The _workaround_ is to press enter at the prompt when creating the profile:
```
SSO session name (Recommended):
WARNING: Configuring using legacy format (e.g. without an SSO session).
Consider re-running "configure sso" command and providing a session name.
```

Took me a long time to figure out this was the problem and find the above workaround, so it would nice if aws-vault could read the new sso profile format

**Comment by dima-vm** [comment]
I've created PR for that: https://github.com/99designs/aws-vault/pull/1088
Please try `go build`-ing it, should work.

**Comment by mtibben** [comment]
Fixed in https://github.com/99designs/aws-vault/pull/1088
