### ISSUE TITLE
aws-vault error: exec: failed to get credentials for my-user: operation error STS: GetSessionToken, failed to resolve service endpoint, an AWS region is required, but was not found

### ISSUE THREAD

**Issue by ceedjaey6236** [99designs/aws-vault#1094]
- [ ] I am using the latest release of AWS Vault
- [ ] I have provided my `.aws/config` (redacted if necessary)
- [ ] I have provided the debug output using `aws-vault --debug` (redacted if necessary)

**Comment by mtibben** [comment]
> an AWS region is required, but was not found
