### ISSUE TITLE
[Feature] Ability to control SSO browser opening separately from `--stdout` option

### ISSUE THREAD

**Issue by moltar** [99designs/aws-vault#1102]
Use case: I have a helper script that opens a new Firefox container for each profile, thereby allowing multiple sessions at the same time.

This script uses the `-s` option to get the session URL and then pipes the output into the `firefox-container` script.

However, I am not running the script from the terminal. It runs inside an Alfred Workflow, which does not print the output anywhere, so I cannot see the SSO login link.

This used to work fine in `<@6.6.1`, and it broke when #892 was introduced.

In my use case opening the browser for SSO was necessary, and then all of the session URLs I wanted to go into STDOUT to be captured into a variable.

Here's my script:

```sh
AWS_PROFILE=$1
AWS_LOGIN_URL=$(/usr/local/bin/aws-vault login -s "$AWS_PROFILE")

"$HOME/bin/firefox-container" --name "aws-$AWS_PROFILE" --orange --fingerprint "$AWS_LOGIN_URL"
```

It now breaks, because SSO login URL is piped into STDERR and is no longer opening the browser.

```
❯ ./launch.sh profile-name
+ AWS_PROFILE=profile-name
++ /usr/local/bin/aws-vault login -s profile-name
Open the SSO authorization page in a browser (use Ctrl-C to abort)
https://device.sso.region.amazonaws.com/?user_code=XYZ-XYZ
```

---

Relevant issues:

- #892
- #868
- #1069
- #959
- #755

**Comment by mtibben** [comment]
Reverted in [v6.6.2](https://github.com/99designs/aws-vault/releases/tag/v6.6.2)

**Comment by moltar** [comment]
Stale not
