### ISSUE TITLE
Add "entrypoint" feature

### ISSUE THREAD

**Issue by Toshimichi0915** [99designs/aws-vault#1141]
- [X] I am using the latest release of AWS Vault
- [ ] I have provided my `.aws/config` (redacted if necessary)
- [ ] I have provided the debug output using `aws-vault --debug` (redacted if necessary)

Currently, aws-vault does not have "entrypoint" for `exec` command - a default shell used for executing command.

This causes issues on some situations. For example, pipe (|) and redirect (>) cannot be used directly because these features are not supported by syscall.

This causes issues on Windows machine as well. In my case, I had to type this long command:

```
aws-vault exec <username> "--" powershell "CMD"
```

The reason I have to double quote `CMD` is because otherwise variables quoted by `$()` will be expanded before executing the problem. And I *can't* double quote `powershell` because aws-vault uses the first argument as syscall executable (which does not include space and arguments).

This is quite annoying and takes some time to know what's going on. Especially now that AWS tools requires Powershell , the problem will start to affect more and more.

To tackle this issue, We can add "entrypoint" feature, just like Docker. Users now have the ability to decide which shell they want to use, and the settings will be used on `aws-vault exec` command.

For Windows, the entrypoint can simply be

```
powershell
```

And for Linux,

```
/bin/sh -c
```

should be used.

**Comment by mtibben** [comment]
> For example, pipe (|) and redirect (>) cannot be used directly because these features are not supported by syscall

Can you provide an example of this?

**Comment by Toshimichi0915** [comment]
> > For example, pipe (|) and redirect (>) cannot be used directly because these features are not supported by syscall
> 
> Can you provide an example of this?

```
aws-vault exec <profile> -- ./<random exe name> "> test"
```

We have to avoid this issue by
```
aws-vault exec <profile> -- ./<random exe name> > test (use pipe feature of the current shell, not ideal when "--debug" flag is on)
```

```
aws-vault exec <profile> -- </bin/sh | powershell> "./<random exe name> > test"
```

**Comment by mtibben** [comment]
> ```
> aws-vault exec <profile> -- ./<exe_file> "> test 2>&1"
> ```

Why is the redirect quoted - does the following not work?
```
aws-vault exec <profile> -- ./<exe_file> > test 2>&1
```

**Comment by Toshimichi0915** [comment]
Thank you for your response. 😃

> > ```
> > aws-vault exec <profile> -- ./<exe_file> "> test 2>&1"
> > ```
> 
> Why is the redirect quoted

I posted this as an wrong example that doesn't work.

> Does the following not work?
> 
> ```
> aws-vault exec <profile> -- ./<exe_file> > test 2>&1
> ```
> 
> > `(not ideal when "--debug" flag is on, because stderr will be dirty)`
> 
> But why would `--debug` be used in conjunction with a redirect? That flag should only be necessary when debugging aws-vault itself

When MFA is enabled users will be asked to enter their MFA code. so redirecting can still cause problems even when "--debug" flag is not set.

**Comment by mtibben** [comment]
Yeah if mfa is required, it's essentially an interactive terminal. There are 2 possible approaches to this
1.  use `--mfa-token` to keep the command non-interactive
2. use a subshell with `aws-vault exec PROFILE` and then launch your command

But yes I take your point that it's not ideal in that scenario. I'll think about this a bit more

**Comment by mtibben** [comment]
This scenario has now been addressed in #1149

If aws-vault encounters a non-tty, it will attempt to use an alternative MFA prompt automatically.

For example, this command results in GUI prompt for MFA
```
$ aws-vault exec role-wth-mfa-prompt -- echo woot > test.log 2>&1
```

@Toshimichi0915 does this resolve the issue for you?

**Comment by Toshimichi0915** [comment]
It solved most of the addressed issues but I want default shell to be customizable; I want to use `powershell` instead of `cmd.exe`, which I think makes "entrypoint" feature request still valid

**Comment by mtibben** [comment]
@Toshimichi0915 there is no default shell. AWS vault is exec-ing without a shell

**Comment by Toshimichi0915** [comment]
> @Toshimichi0915 there is no default shell. AWS vault is exec-ing without a shell

https://github.com/99designs/aws-vault/blob/ba79e47d6e85e280bca71015168330bae1543e6b/cli/exec.go#L308

I'm talking about this line

**Comment by mtibben** [comment]
That exec.go default shell is only used when to create a subshell. It's when a command _isn't_ specified

> I can't execute this command for example because echo isn't executable, and is rather a part of cmd.exe/powershell

Correct. `aws-vault exec cmd.exe "echo 'Hello, world'"` would be the way to execute a shell.

Don't get me wrong, I agree that this could be a legitimate feature. The question to me is whether this is a "necessary" feature. Any feature added creates new complexity. At the moment it seems there are simple alternatives vs adding a new mode of execution

**Comment by mtibben** [comment]
While this is an interesting feature, it's questionable whether this is a necessary feature. Any feature added creates new complexity and maintenance burden. At the moment it seems there are simple-enough alternatives vs adding a whole new mode of execution.
