### ISSUE TITLE
Beta testers wanted for v7

### ISSUE THREAD

**Issue by mtibben** [99designs/aws-vault#1144]
The v7 pre-release is now ready for more widespread testing.

If you use aws-vault regularly, I'd encourage you to test the v7 beta and report any issues.

https://github.com/99designs/aws-vault/releases

/cc @FernandoMiguel @sftim @dima-vm @LouisTsiattalou @jmczerk

**Comment by FernandoMiguel** [comment]
Daily user here
Curious to see how `--server` changes impact me

**Comment by aryounce** [comment]
I'll give this a try. We're heavy users @getstrake and welcome the `--server` changes.

**Comment by mtibben** [comment]
Great thanks! Please do also try the new `--ec2-server` behaviour also (new help messages, and proxy process is always ended)

**Comment by mtibben** [comment]
v7.0.0-rc6 is the latest, please report any issues as we now validate that profile configs don't have more than one credential source

**Comment by dharrigan** [comment]
Hi,

Using the latest from master, now with the config validation (rc5 + rc6). My aws config file which has worked for years no longer validates. Here is a snippet (with some data changed to protect confidentiality)

```
[profile foo]
region         = eu-west-1
mfa_serial     = arn:aws:iam::9999999999999:mfa/david

[profile foo:staging]
role_arn       = arn:aws:iam::1111111111111:role/admin
source_profile = foo
region         = eu-west-2
mfa_serial     = arn:aws:iam::9999999999999:mfa/david

[profile foo:production]
role_arn       = arn:aws:iam::2222222222222:role/admin
source_profile = foo
region         = eu-west-2
mfa_serial     = arn:aws:iam::9999999999999:mfa/david
```

Now gives this error:

`aws-vault exec foo:staging -- aws s3 ls`

`aws-vault: error: exec: Error getting temporary credentials: profile 'foo:staging' has more than one source of credentials`

Examining the documentation (which hasn't been updated yet, perhaps to align with the new way?) doesn't show much difference. Am I missing something?

aws-vault v7.0.0-rc4 works fine

Thank you.

**Comment by dharrigan** [comment]
Hi! Great, works a treat. Thank you! :-)

**Comment by mtibben** [comment]
v7 released
