### ISSUE TITLE
AWS command completion with aws-vault

### ISSUE THREAD

**Issue by shivaman** [99designs/aws-vault#115]
Because I am shit at typing, I use the [AWS CLI command completion](http://docs.aws.amazon.com/cli/latest/userguide/cli-command-completion.html) a lot, which I miss with aws-vault. I see an issue on bash completion which looks like it has been fixed. Is there a workaround I am not seeing to get the AWS CLI command completion working?

**Comment by mtibben** [comment]
Ah yes I've run into this before. In my `.bash_profile` I have
```
complete -C aws_completer aws
complete -C aws_completer sudo
complete -C aws_completer aws-vault
```

Does that work for you?

**Comment by FernandoMiguel** [comment]
Try aws-shell 
It works fine with aws-vault

**Comment by lox** [comment]
This is a dupe of https://github.com/99designs/aws-vault/issues/70 btw.

**Comment by lox** [comment]
Good example of a bash auto complete over there. I haven't given it much focus because I use zsh.

**Comment by shivaman** [comment]
@mtibben 's solution worked for me. I am using zsh and added the statements to aws_zsh_completer.sh. I now have autocomplete.

**Comment by dserodio** [comment]
@mtibben's solution (thanks!) only works partially, because I use aws-vault with both aws-cli and [awless](https://github.com/wallix/awless/). I can only make it work with either one or another.
