### ISSUE TITLE
aws-vault server mode with 2FA

### ISSUE THREAD

**Issue by shivaman** [99designs/aws-vault#116]
In an attempt to get AWS command completion workarounds (previous issue), I was trying to get the server mode going. I have`aws-vault exec profile —server ` which drops me into a prompt, from where I can get the metadata with `curl localhost:9099`. But aws commands fail with credential validation. I have MFA enables for the profile. Is that a limitation of the tool, or am I missing something here?

**Comment by lox** [comment]
What does `aws configure list` show you when in that shell?

**Comment by lox** [comment]
In fact, `aws --debug configure list` will give you details on what was tried.

**Comment by shivaman** [comment]
User error 👍 

For anyone else who might run into this, I had a credentials with dummy keys. SInce in server mode it spoofs the metadata server which come last in the order of priorities, it was picking up my dummy keys. All good now. Thanks heaps for a great tool and the prompt help.
