### ISSUE TITLE
`export` hangs on [keyring] No results found

### ISSUE THREAD

**Issue by Ketouem** [99designs/aws-vault#1180]
OS: macOS Ventura 13.2.1
Installation method: Homebrew Cask

- [x] I am using the latest release of AWS Vault
```
aws-vault --version
v7.0.1
```
- [x] I have provided my `.aws/config` (redacted if necessary)
```
[profile admin]
region = eu-west-3
output=json
mfa_serial=arn:aws:iam::XXXXXXX:mfa/cyril.thomas
credential_process=aws-vault --prompt=osascript export --format=json admin
```
- [x] I have provided the debug output using `aws-vault --debug` (redacted if necessary)
```
aws-vault --debug export --no-session --format=json admin
2023/03/06 23:26:20 aws-vault v7.0.1
2023/03/06 23:26:20 Using prompt driver: terminal
2023/03/06 23:26:20 Loading config file /Users/cyril/.aws/config
2023/03/06 23:26:20 Parsing config file /Users/cyril/.aws/config
2023/03/06 23:26:20 [keyring] Considering backends: [keychain]
2023/03/06 23:26:20 Profile 'default' missing in config file
2023/03/06 23:26:20 profile admin: using credential process
2023/03/06 23:26:20 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2023/03/06 23:26:20 [keyring] Found 2 results
2023/03/06 23:26:20 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2023/03/06 23:26:20 [keyring] Found 2 results
2023/03/06 23:26:20 [keyring] Querying keychain for service="aws-vault", account="credential_process,ZGFsbWEtYWRtaW4,,-62135596800", keychain="aws-vault.keychain"
2023/03/06 23:26:20 [keyring] No results found
[...]
aws-vault: error: exec: Failed to get credentials for admin: running command "aws-vault export --no-session --format=json admin": exit status 1 (repeated n numerous times)
```

Syscall tracking:
<img width="1227" alt="Screenshot 2023-03-06 at 23 31 48" src="https://user-images.githubusercontent.com/4333817/223262958-39b9bae3-5907-4f23-b9bd-7468a3d8327f.png">

I've already tried to reinstall `aws-vault`, unfortunately the problem is still there...

**Comment by mtibben** [comment]
You have an infinite loop as aws-vault v7 will use `credential_process` as a valid credential source

**Comment by mtibben** [comment]
> [profile admin]
> region = eu-west-3
> output=json
> mfa_serial=arn:aws:iam::XXXXXXX:mfa/cyril.thomas
> credential_process=aws-vault --prompt=osascript export --format=json admin

Can you explain the use-case of this config? Why do you use `credential_process` here at all?

**Comment by phr3nzii** [comment]
I am also hitting this issue.

The use case is to have aws-vault manage the AWS credentials when using any command line tool. I don't want to store my credentials in plain text in `~/.aws/credentials`, so I store them using aws-vault. Without the `credential_process` set command line tools don't know where to get my AWS credentials, and so I cannot simply run, for example, `aws s3 ls`, instead I would have to run `aws-vault exec profile -- aws s3 ls`.

This worked perfectly in 6.6.2

**Comment by Ketouem** [comment]
> > * [x]   I have provided my `.aws/config` (redacted if necessary)
> > 
> > ```
> > [profile admin]
> > region = eu-west-3
> > output=json
> > mfa_serial=arn:aws:iam::XXXXXXX:mfa/cyril.thomas
> > credential_process=aws-vault --prompt=osascript export --format=json admin
> > ```
> 
> @Ketouem Can you explain the use-case of this config? Why do you use `credential_process` here at all?

I'm trying to avoid any plain text credentials within the `~/.aws` folder.

**Comment by nilsalex** [comment]
Same here, I and every other aws-vault user I know use `credential_process` to tell AWS clients how to obtain credentials from aws-vault.

**Comment by vsimon** [comment]
Hi, I'm also experiencing this issue, providing my profile snippet which does contain `credential_process` to avoid storing plain text credentials on-disk.

```
[profile admin]
region=us-east-1
credential_process=aws-vault exec --json --prompt=osascript --duration=12h admin
mfa_serial=arn:aws:iam::1234567890:mfa/username
```

**Comment by mtibben** [comment]
A pre-release fix has been released [v7.0.2-beta1 release](https://github.com/99designs/aws-vault/releases/tag/v7.0.2-beta1). Can you please test this and confirm that it fixes this issue @Ketouem

**Comment by im-bpriestman** [comment]
Works for me. Thanks!

**Comment by mtibben** [comment]
Fixed in https://github.com/99designs/aws-vault/pull/1183
