### ISSUE TITLE
Unable to find steps to download for Linux ARM Machines

### ISSUE THREAD

**Issue by anshitbansal21** [99designs/aws-vault#1225]
The setup process I have earlier used is for homebrew on my mac, but homebrew is not supported for Linux ARM. Can anyone guide me here on how to download and setup the Linux ARM latest release which can be found here -> https://github.com/99designs/aws-vault/releases/latest

This is probably an easy thing that I am not able to understand. It will be very helpful if someone can help me with the setup steps!

**Comment by FernandoMiguel** [comment]
you want [aws-vault-linux-arm64](https://github.com/99designs/aws-vault/releases/download/v7.2.0/aws-vault-linux-arm64)
just download that and put it in any of your $PATH

**Comment by anshitbansal21** [comment]
Thank you so much @FernandoMiguel! I did try this was doing something stupid previously, it worked now! :smile:
