### ISSUE TITLE
Install instructions for Windows in README

### ISSUE THREAD

**Issue by pda** [99designs/aws-vault#124]
`README.md` should briefly show how to install on Windows. I think actual usage on Windows is roughly covered by `USAGE.md` (i.e. it's the same as on unixish systems). I'd PR these install instructions instead of opening an issue, but I have no idea how to install aws-vault on Windows ;)

(Side-note: #123 will lead to Windows releases with `.exe` file extension, making installation a little more obvious, I think. But people may still be expecting it's an installer, not the program itself.)

**Comment by mtibben** [comment]
Might be worth adding aws-vault to [scoop](http://scoop.sh/) for a brew-like experience on Windows. Makes for simple install instructions, and scoop can worry about installing, where to put the binary etc.

**Comment by lox** [comment]
Never heard of scoop, https://chocolatey.org/ has some reasonable traction.

**Comment by Devin82m** [comment]
Is there any traction on this? Some of us don't have a choice but to use Windows at work and aws-vault would be incredibly useful, my team has to manage 6 different AWS accounts (each of us have a user in each AWS account). I would prefer to use Linux, but can't currently justify it with as many Windows servers we have to support.

**Comment by mtibben** [comment]
No traction, PRs welcome

**Comment by amitsaha** [comment]
We have been downloading the `.exe`, and have been running it in server mode for local AWS access and it has been working well. I could add that admittedly straightforward instructions as a PR if you want to look.

**Comment by lox** [comment]
Super exciting! I'll check it out, thanks for your efforts @gusztavvargadr!

**Comment by virgilwashere** [comment]
For anyone else getting to this Issue via a search.

Specify the version on the install line to get package still in moderation...

`carob install aws-vault --version=4.5.1`

(`carob` is an admin wrapper for `choco`)

I'm actually writing up installation instructions for my team, so I'll submit a copy back here when I'm done.  I'm using WSL Ubuntu on Windows 10, and I'm trying to get this all working with one authoritative `aws-vault` instance.

**Comment by gusztavvargadr** [comment]
@virgilwashere great tip, yes, it takes a couple of days until they approve new packages (it just got the green light btw, see https://chocolatey.org/packages/aws-vault/4.5.1).

**Comment by mtibben** [comment]
This appears to be fixed
