### ISSUE TITLE
Document how to blow everything away

### ISSUE THREAD

**Issue by kevinburke** [99designs/aws-vault#125]
If I run `aws-vault list`, I see several open sessions. But I'm not sure where these sessions are being loaded from.

**Comment by FernandoMiguel** [comment]
I would love a way to clear those sessions but dont know how

**Comment by lox** [comment]
The sessions should be timed out, you can forcefully remove them with `aws-vault rm myprofile ----sessions-only`.

**Comment by FernandoMiguel** [comment]
Great.
that worked just fine.

Any idea they were left there for so long?

**Comment by lox** [comment]
It's normal, they will be expired anyway. We should garbage collect them
anyway.

**Comment by StevenACoffman** [comment]
Pedantic correction for later copy-pasting people:

`aws-vault rm myprofile --sessions-only`
