### ISSUE TITLE
aws-vault exec subshell should be configurable

### ISSUE THREAD

**Issue by OlivierGraciannette** [99designs/aws-vault#1254]
`aws-vault exec` subshell should be configurable in `~/.aws/config` (or somewhere else).

For example, I use kitty terminal as long as fish on Mac, and my terminal is directly configured to run fish. But as soon as I use `aws-vault` the subshell given is `ZSH`. I'm currently forced to create a `$HOME/.zshrc` file with an `exec fish` in it to have my `aws-vault` subshell giving me back fish. Reminder zsh is preinstalled on Mac.

It doesn't make any sense and should be explicitly configurable in a file.

**Comment by ryan-shaw** [comment]
This sounds like you need to set your default shell https://support.apple.com/en-gb/guide/terminal/trml113/mac

**Comment by OlivierGraciannette** [comment]
Hi,

okay that did the tricks, weird but okay.

Thank you.
