### ISSUE TITLE
windows: MFA prompt doesn't wait for input

### ISSUE THREAD

**Issue by pda** [99designs/aws-vault#126]
Reported by a coworker:

```
C:\Users\example\Downloads>aws-vault-windows-386.exe --debug exec example-read-only
2017/06/06 03:59:43 Parsing config file C:\Users\example\.aws\config
2017/06/06 03:59:43 Looking up keyring for example
Enter passphrase to unlock C:\Users\example\.awsvault\keys:
2017/06/06 03:59:47 Session not found in keyring
Enter token for arn:aws:iam::123456789012:mfa/example: 2017/06/06 03:59:47 Getting new session token for profile example
aws-vault: error: Failed to get credentials: InvalidParameter: 1 validation error(s) found.
- minimum field size of 6, GetSessionTokenInput.TokenCode.
```

Note that the “Enter token for …” prompt appears, but does not wait for input, instead proceeding with an empty MFA token.

Looking at [this code](https://github.com/99designs/aws-vault/blob/6dea3135e97629406b91d420d3d648771e43618c/provider.go#L203-L219) it seems `p.MfaPrompt()` must be returning a token and no error. I'm confident that`p.MfaPrompt` is a reference to [`prompt.Terminal()`](https://github.com/99designs/aws-vault/blob/6dea3135e97629406b91d420d3d648771e43618c/prompt/terminal.go#L10). I think `text, err := reader.ReadString('\n')` is returning `"", nil` or `"\n", nil` despite no user input. I was considering looping until a non-empty string was read, but that might be obnoxious (e.g. it'd break “enter blank string for default”). Or, flushing stdin prior to prompting for input, but I don't know if there's a portable way to do that?

I don't have a Windows machine to test this on. Perhaps nobody has ever used aws-vault with MFA in Windows?

Edit: windows `\r\n` newlines are an obvious suspect, but the `ReadString('\n')` combined with `TrimSpace()` should handle that?

**Comment by lox** [comment]
> I don't have a Windows machine to test this on. Perhaps nobody has ever used aws-vault with MFA in Windows?

☝🏻

Looks like there are lots of more portable ways of reading strings in golang: https://stackoverflow.com/questions/20895552/how-to-read-input-from-console-line

**Comment by joho** [comment]
I've got a windows PC at home and would be happy to try a couple to PR against this.

**Comment by williamdenton** [comment]
I'm using v4 on windows 10 and MFA works fine when assuming roles

**Comment by evolutionise** [comment]
Also encountering this issue on Windows 10.  

Have attempted to fix by removing all existing credentials, deleting and readding profiles, rotating profiles. I tried using aws-vault from Powershell and from MinGW None of these things made any difference. I got a copy of the binary @williamdenton has been using, and it still doesn't work on my machine.  Neither of us know why. 

I noticed a similar issue where, immediately after adding a new profile, it would proceed to execute the command without waiting for the passphrase to be entered.  The second time I ran the same command, it would wait.

**Comment by danbrake** [comment]
I am having the same issue on Windows 10 v4.2.0. Is there a fix or workaround? I have tried reentering credentials and reinstalling. 

After I enter the passphrase I see the prompt to enter a MFA token and the error message associated with submitting without a MFA token. It does not wait for user input after the following:
Enter token for arn:aws:iam::000000000000:mfa/example

Output:
```C:\Users\example>aws-vault exec dev -- aws ec2 describe-instances
Enter passphrase to unlock C:\Users\example/.awsvault/keys/:
Enter token for arn:aws:iam::000000000000:mfa/example: aws-vault: error: Failed to get credentials for dev: InvalidParameter: 1 validation error(s) found.
- minimum field size of 6, GetSessionTokenInput.TokenCode.
```

**Comment by danbrake** [comment]
Quick note on this... after cloning the repo to have a look at the issue I noticed that you can pass the MFA token in when you run aws-vault by using a "-m" flag. The issue is still there if you try and run without passing the token but it is a workaround for anyone having the same issue.

The following now works for me:

'''aws-vault exec dev -m 340793 -- aws ec2 describe-instances'''

**Comment by lox** [comment]
Sorry folks, I lack the bandwidth to do windows testing on this at present, but would happily collaborate on a PR!

**Comment by biswaranjanb** [comment]
Is this issue resolved ?
