### ISSUE TITLE
No CI?

### ISSUE THREAD

**Issue by lox** [99designs/aws-vault#135]
I see travis files and some ci scripts, but no status on merge requests? @Vektah?

**Comment by joho** [comment]
CI is set up, but we've been unable to enable the github integration due to the lack of fine grained control in the oauth permissions between our org and travis.

**Comment by joho** [comment]
See https://travis-ci.org/99designs/aws-vault

**Comment by lox** [comment]
Oh. Gross?

**Comment by joho** [comment]
Gross.

**Comment by lox** [comment]
If only some awesome CI company would start supporting public build pages.
