### ISSUE TITLE
What should `aws-vault list` show?

### ISSUE THREAD

**Issue by lox** [99designs/aws-vault#137]
Currently `aws-vault list` will show all keys in the aws-vault keychain. This includes sessions. 

I've been thinking of breaking out: `aws-vault list-profiles`, `aws-vault list-sessions` and then have `aws-vault list` show only the credentials that are stored. The alternative would be to have `aws-vault list` have a `--profiles` and `--session` flag. 

Feels?

**Comment by mtibben** [comment]
Or even just `aws-vault profiles` and `aws-vault sessions` ?

**Comment by mtibben** [comment]
Although `add` and `remove` implicitly act on profiles..

**Comment by mtibben** [comment]
Or maybe like you said, `list` lists profiles, `list --sessions` lists sessions

**Comment by mtibben** [comment]
Thinking about this again.. would a table layout make sense here? e.g. 
```
$ aws-vault list
99designs  master   11111111111111111111
99designs  session  22222222222222222222
99designs  session  33333333333333333333
99designs  session  44444444444444444444
home       master   55555555555555555555
home       session  55555555555555555555
```

**Comment by lox** [comment]
There are three different things, a profile, master keys and session keys. The relationship between profile and session master keys ends up being via `source_profile`. Confusing to represent and think about. 

My big thing is that there isn't anything good to use to get a list of profiles from, which makes cli autocomplete hard.

**Comment by mtibben** [comment]
Right... so for our subcommands we currently have
```
  add <profile>
  list
  rotate <profile>
  exec <profile> [<cmd>] [<args>...]
  remove <profile>
  login <profile>
  server
```
Given that all commands act on a profile, I would think `list` should just list profiles - that's the entity you're working with. 

Then to see sessions you could just add
``
  sessions [profile]
```
which would list sessions, maybe in a table format like above?

**Comment by lox** [comment]
Yeah, I think you are right.

**Comment by lox** [comment]
So @mtibben, I guess the interesting thing about that is what is the source of profiles? Is it what profiles you have listed in your `~/.aws/config` file, or is it the credentials you have in your keyring? Or both? Say if I have `profile1`,`profile2` and `profile3` in my `~/.aws/config` and then I use `aws-vault add profile4`, should a subsequent list show profiles 1-3 or profiles 1-4?

**Comment by lox** [comment]
It's hard to know which should be definitive, the profiles listed in `~/.aws/config` or your keyring.
