### ISSUE TITLE
adding new profile with existing key

### ISSUE THREAD

**Issue by FernandoMiguel** [99designs/aws-vault#149]
I've a few profiles already setup
they have the same key from an IAM account, and then assume role to switch to another aws account / role

I'm now adding a new profile. But since I no longer have the key, I have to issue a new one and readd it to all existing profiles.

Is there a way i can just have a base profile with the keys, and then dependant profiles that assume roles?

#~/.aws/config
```
[profile default]
region = eu-west-1

[profile iam]
mfa_serial = arn:aws:iam::XXX:mfa/F
region = eu-west-1

[profile dev]
mfa_serial = arn:aws:iam::XXX:mfa/F
role_arn = arn:aws:iam::XXXXX:role/crossaccount-role
region = eu-west-1

[profile prod]
mfa_serial = arn:aws:iam::XXX:mfa/F
role_arn = arn:aws:iam::XXXX:role/crossaccount-role
region = eu-west-1
```

**Comment by mtibben** [comment]
Hey @FernandoMiguel, does the documentation at http://docs.aws.amazon.com/cli/latest/userguide/cli-roles.html help? I think you're just missing the `source_profile` on your dependant profiles

**Comment by FernandoMiguel** [comment]
@mtibben but when I'm adding a new profile to aws-vault, it will ask for API creds, which I dont want to re-supply. I just want to have one pair per AWS account (in this case our AWS IAM account) and then assume roles for each set of privs and accounts.


If i was to add a new profile to my ~/.aws/config
```
[profile prod-s3]
role_arn = arn:aws:iam::XXXX:role/crossaccount-role-s3
source_profile = prod
```

and then add to aws-vault, i get:
```
$ aws-vault add prod-s3
Enter Access Key ID: <BLANK>
Enter Secret Access Key: <BLANK>
Added credentials to profile "prod-s3" in vault
$ aws-vault exec prod-s3 -- aws s3 ls
aws-vault: error: No credentials found for profile "prod-s3"
```

**Comment by FernandoMiguel** [comment]
ah see what was the problem.
one of the accounts add previously existing tokens and was failing.
once i deleted all keys and profiles, it worked.

thanks.

**Comment by lox** [comment]
@FernandoMiguel so it looks like the issue is you are trying to add credentials to profiles that use another profile's credentials. It's confusing, sorry! You should only have credentials for profile `prod` and then `prod-s3` will use those via the `source_profile` directive in your config.

@mtibben we should make add fail with a nice message if there is a source_profile in the config.

**Comment by FernandoMiguel** [comment]
@lox @mtibben am I correct in assuming this would be the correct structure?
https://github.com/FernandoMiguel/AWS-Trust-CrossAccounts/blob/master/dot_aws/config

thanks
