### ISSUE TITLE
Support supplemental env vars

### ISSUE THREAD

**Issue by focusaurus** [99designs/aws-vault#150]
Feature request for discussion. Not even sure if this is technically possible, too much scope, or if there's some reason it's a bad idea, but how about supporting arbitrary other environment variables which could be used for other project-specific settings (API keys, db credentials, etc).

Currently I have to keep some of these in a 1password secure note and set them into my shell all the time.

**Comment by joho** [comment]
I think it's out of the scope of this tool, but we have extracted enough of the tool for talking to the various OS keychain/keyrings into a [separate library](https://github.com/99designs/keyring) that you could probably build one that could do it without too much hassle.

**Comment by focusaurus** [comment]
OK thanks!
