### ISSUE TITLE
On delete and re-add of profile keys don't change

### ISSUE THREAD

**Issue by rickw** [99designs/aws-vault#159]
I'm changing keys in a profile and they don't change. ```aws-vault rm x``` then ```aws-vault add x``` with new keys just ads the vault with the old keys. I'm on high sierra.

I delete the keychain_db file and it has no effect. After I re-add it uses the old values.

EDIT2:

It doesn't seem to matter what profile name I choose, I get the same old keys.

**Comment by lox** [comment]
Mind trying this against the latest master, I think I've fixed it.

**Comment by mtibben** [comment]
This should be fixed on v4.1.0. Can you confirm @rickw? If it's not please re-open this issue

**Comment by rickw** [comment]
Apologies, I have completely stopped using `aws-vault`. If I get a change I'll check if it works now.

**Comment by rickw** [comment]
Ok, so it seems to work now. The vault name doesn't go away on remove but it's cleaned out and anything new stored under it is used going forward. (thanks)
