### ISSUE TITLE
Metadata Server on Windows

### ISSUE THREAD

**Issue by williamdenton** [99designs/aws-vault#166]
My primary dev environment is windows, so I had a look to see what it would take to get the server running on windows.

Currently windows server is explicitly disabled as there is no code to install the network alias:

https://github.com/99designs/aws-vault/blob/eb8b1dcd07a88a16b1ec889976927122a798c583/server/alias_windows.go#L7-L9

if I update that to:

```go

func installNetworkAlias() ([]byte, error) {
	exec.Command("netsh", "interface", "ipv4", "add", "address", "Loopback Pseudo-Interface 1", "169.254.169.254", "255.255.0.0")
	return []byte{}, nil
}

```

installs the interface (when run from an elevated (administrator/sudo) prompt. So far so good. Its a hack as it doesn't respect the output of that command and im not 💯 on the interface name being portable to other machines also running it a second time will fail (but that doesn't matter)

Next problem is the internals of the server mode try to start the server in the background using `sudo`, this is no use on windows:

https://github.com/99designs/aws-vault/blob/eb8b1dcd07a88a16b1ec889976927122a798c583/server/server.go#L72-L81

If I comment out that block and then call `aws-vault server` from exec the server is started, albeit nested

```ps
aws-vault exec -s profile -- aws-vault server
```

It works!

But not in a way that I'd be comfortable creating a PR for. So I'm looking for feedback on how to approach this to get it running on windows in a way that can be merged. I've got lots of people that would love to use this in my team and my workaround https://github.com/williamdenton/awslocalmetadata that I was using before trying to get this working can be killed.

**Comment by lox** [comment]
This looks awesome @williamdenton! If you wanted to put this into a PR, we'd be happy to accept it. Partial windows support is better than none for the metadata server!
