### ISSUE TITLE
aws-vault exec exits 0 when trying to run nonexistent command

### ISSUE THREAD

**Issue by kevinburkeotto** [99designs/aws-vault#167]
If I run `aws-vault exec dev -- nonexistentcommand`, I get a 0 return code. Same if cmd exists but is not executable. Investigating now.

I would expect it to return a nonzero code.

**Comment by lox** [comment]
We should do a `LookPath` on the input command here:
https://github.com/99designs/aws-vault/blob/master/cli/exec.go#L146

Then return an error if it doesn't exist.

**Comment by lox** [comment]
If you have time to submit a PR that would be welcomed, otherwise I'll look into it when I get a spare minute. Thanks for the report @kevinburkeotto.

**Comment by kevinburke** [comment]
Here's the problem

```
	if err := cmd.Start(); err != nil {
		fmt.Println("start error")
		app.Errorf("%v", err)
		return
	}
```

We exit 0 there when we should exit 1 or 2 or whatever.

I'm not sure LookPath checks file permissions, it's probably better just to treat an error running `Start` as an error.

**Comment by kevinburke** [comment]
We could replace with `app.Fatalf` which is what I think we want anyway.

```
// Errorf prints an error message to w in the format "<appname>: error: <message>".
func (a *Application) Errorf(format string, args ...interface{}) {
	fmt.Fprintf(a.errorWriter, a.Name+": error: "+format+"\n", args...)
}

// Fatalf writes a formatted error to w then terminates with exit status 1.
func (a *Application) Fatalf(format string, args ...interface{}) {
	a.Errorf(format, args...)
	a.terminate(1)
}
```

**Comment by kevinburke** [comment]
```
// Terminate specifies the termination handler. Defaults to os.Exit(status).
// If nil is passed, a no-op function will be used.
func (a *Application) Terminate(terminate func(int)) *Application {
	if terminate == nil {
		terminate = func(int) {}
	}
	a.terminate = terminate
	return a
}
```
