### ISSUE TITLE
Lost password

### ISSUE THREAD

**Issue by raguay** [99designs/aws-vault#171]
Hi,

I didn't realize it was assigning a password on the first run and I forgot to write it down. Now, I can't access anything with it. How do I do a complete erase of the different credentials for it to start over on the whole process? I'm running on a macOS system using the keychain.

**Comment by FernandoMiguel** [comment]
it tends to be your keychain/login password, unless you create a new keychain.
anyway, open keychain app and delete the **NEW** keychain

or  remove the profiles and add again

**Comment by raguay** [comment]
There isn't a **NEW** keychain. I tried to delete the profiles, it asked for the password and would not accept my default one. So I hit cancel. When I re-listed the profiles, the profile was removed? Recreating the profiles and trying to use it still says that it can't access the keychain. Not sure how to fix it.

**Comment by lox** [comment]
Have a look in `ls ~/Library/Keychains/`, there will be an `aws-vault.keychain`. Delete it.

**Comment by daluu** [comment]
would be nice if this was mentioned in README, etc., not all users know the details.

**Comment by julianwki** [comment]
just foir the records: you don't need to delete the keychain to change pw. do the following:

1. open keychain access app on mac
2. file -> add keychain
3. choose `~/Library/Keychains/aws-vault.keychain`

the `aws-vault` can be chosen on the left inside the app. pw can be changed via context menu.

**Comment by danielnmai** [comment]
@julianwki it's the same with deleting the keychain if you don't know the password anyway.
