### ISSUE TITLE
Credential encryption on Windows

### ISSUE THREAD

**Issue by wgj** [99designs/aws-vault#176]
I don't know the best place to ask this, so apologies if it's unwelcome :)

My team and I are big fans of aws-vault. Some of us are starting to use it on Windows, and our compliance office wanted more information on how the credentials are being stored. I've gathered that you're using EFS, but on Windows 7 there seems to be several standards available (I don't know what I'm talking about, just glanced at the Wikipedia entry).

Would you mind giving a brief statement on how credentials are stored with Windows?

**Comment by joho** [comment]
Definitely welcome and a good question.

@lox can correct me if I'm wrong, but the default setting on windows is to use the encrypted file store, which is built on top of one of the encryption options in the jwt family.

https://github.com/99designs/keyring/blob/master/file.go#L83-L135 are the relevant lines, which you can see call out to https://github.com/dvsekhvalnov/jose2go using the `PBES2_HS256_A128KW` algorithm. https://tools.ietf.org/html/draft-ietf-jose-json-web-algorithms-40 has some further reading.

I wonder if we can make this a bit easier to figure out/pass on to security teams in the docs.

**Comment by lox** [comment]
Yup, at present we don't use a native credential store on Windows. We should though, I created https://github.com/99designs/aws-vault/issues/177. 

@joho is correct. We store your master credentials in an encrypted file in `~/.awsvault`. It's secured with PBES2 (RFC 2898) with HMAC SHA-256 as the PRF and AES Key Wrap (RFC 3394) using 128 bit keys for the encryption scheme. Users are prompted for the passphrase on each use.

**Comment by wgj** [comment]
Thank you for the explanation, and looking forward to #177.
