### ISSUE TITLE
Rotate keys prepends "null" to profile name

### ISSUE THREAD

**Issue by wgj** [99designs/aws-vault#178]
``` bash
~ $ aws-vault rotate profilename --debug
2017/11/03 15:54:59 Loading config file /Users/wgj/.aws/config
2017/11/03 15:54:59 Parsing config file /Users/wgj/.aws/config
Rotating credentials for profile "profilename"
2017/11/03 15:54:59 Looking up keyring for profilename
2017/11/03 15:55:00 Found old access key  ****************HU7Q for user profilename
2017/11/03 15:55:00 Skipping session token and using master credentials directly
2017/11/03 15:55:00 Using old credentials to create a new access key
aws-vault: error: Failed to get credentials for profilename: AccessDenied: User: arn:aws:iam::...:user/profilename is not authorized to perform: iam:CreateAccessKey on resource: user nullprofilename with an explicit deny
	status code: 403, request id: 056dee02-c0ea-11e7-b99a-d10857d455ef
~ $ aws-vault --version
v4.1.0

```

``` bash
~ $ aws-vault exec profilename -- /Users/wgj/Library/Python/2.7/bin/aws iam 
create-access-key --user-name profilename
{
    "AccessKey": {
        "UserName": "profilename", 
        "Status": "Active", 
        "CreateDate": "2017-11-06T18:57:03.757Z", 
        "SecretAccessKey": "...", 
        "AccessKeyId": "..."
    }
}
```

Maybe it's just a printf bug, but it looks like my login is getting concatenated with `"null"`.

**Comment by lox** [comment]
Could you tell us a bit more about `profilename`? Is it an assumed role, or a normal profile?

**Comment by lox** [comment]
I can reproduce this with a non-assumed IAM user. It's weird, because the docs say:

> If you do not specify a user name, IAM determines the user name implicitly based on the AWS access key ID signing the request. Because this action works for access keys under the AWS account, you can use this action to manage root credentials even if the AWS account has no associated users.

It doesn't seem to be the case though.

**Comment by lox** [comment]
Ah-hah. It's because you don't have permissions to rotate your credentials. Check out this reference policy: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_iam_credentials_console.html

**Comment by lox** [comment]
I have no idea where `profilename with an explicit deny` is coming from though.

**Comment by lox** [comment]
Is this too verbose as an error?

> aws-vault: error: AccessDenied: Check your credentials have permission to list and update access keys. See https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_iam_credentials_console.html for more details.

**Comment by wgj** [comment]
> Could you tell us a bit more about profilename? 

profilename is an regular IAM user with credentials, i.e., not a role.

> Ah-hah. It's because you don't have permissions to rotate your credentials. 
>I have no idea where profilename with an explicit deny is coming from though.

The policies attached to profilename are restrictive, so I wouldn't be able to request `"Action": ["iam:*AccessKey*"]` from our compliance office, but I would be able to ask for specific actions.

Seeing as how there isn't a `RotateAccessKey`, I presume the permissions you suggest the IAM user doesn't have are `CreateAccessKey` and `DeleteAccessKey`:

``` bash
~ $ aws-vault exec profilename -- ~/bin/awscli iam create-access-key
{
    "AccessKey": {
        "UserName": "profilename", 
        "Status": "Active", 
        "CreateDate": "2017-11-07T20:40:14.324Z", 
        "SecretAccessKey": "...", 
        "AccessKeyId": "..KKGA"
    }
}
~ $ aws-vault exec WestonJ0 -- ~/bin/awscli iam delete-access-key --access-key-
id ..KKGA
~ $ *dust*
```

> Is this too verbose as an error?

I have permissions for ListAccessKeys and UpdateAccessKey, so the error message verbosity is fine, but not relevant to the issue I'm experiencing, which seems to be calling CreateAccessKey on user null:

``` bash
~ $ aws-vault rotate WestonJ0
Rotating credentials for profile "profilename"
aws-vault: error: Failed to get credentials for profilename: AccessDenied: User: arn:aws:iam::...:user/profilename is not authorized to perform: iam:CreateAccessKey on resource: user null with an explicit deny
	status code: 403, request id: a685b45a-c3fa-11e7-b1cd-efe0f80a8752
```

**Comment by lox** [comment]
It’s a poor error from AWS, null means the user that is associated with your connecting credentials.

**Comment by wgj** [comment]
Ah okay. I can use awscli's CreateAccessKey with or without UserName. But if I'm synthethizing all the comments here (and per this [comment](https://github.com/99designs/aws-vault/issues/178#issuecomment-342436099)) aws-sdk-go fails when CreateAccessKey is used without UserName. Is that current idea?

**Comment by lox** [comment]
No, I don't actually think this is an aws-vault bug. The aws-sdk-go passes around strings as pointers so that it can have nil strings. A nil string as the username for `CreateAccessKey` uses the username of the calling credentials: https://docs.aws.amazon.com/IAM/latest/APIReference/API_CreateAccessKey.html

I think this is purely a permissions bug, but we could do a better job of making it clear what is happening. Check out #180.

**Comment by lox** [comment]
Sorry you ran into this! Hopefully with the IAM permissions in the README in that PR you will be able to get it working.
