### ISSUE TITLE
Enhancement: allow specification of assume-role-ttl (and maybe other options) in .aws/config

### ISSUE THREAD

**Issue by damonmaria** [99designs/aws-vault#179]
I'm often running commands on a certain profile that take longer than 15 minutes, and I keep forgetting to specify `--assume-role-ttl=1h`. Would be nice if this option (and maybe others) could be specified with the profile in `.aws/config`.

**Comment by FernandoMiguel** [comment]
+1

**Comment by lox** [comment]
Yup, that sounds sensible.

**Comment by spider-network** [comment]
+1

**Comment by frezbo** [comment]
you can get it working by setting the ENV vars: 
`AWS_SESSION_TTL` - for session token and 
`AWS_ASSUME_ROLE_TTL` - for assume role

**Comment by mtibben** [comment]
FYI this was fixed back in [v5.0.0](https://github.com/99designs/aws-vault/releases/tag/v5.0.0) with support for `duration_seconds`
