### ISSUE TITLE
Rotate does not MFA authenticate

### ISSUE THREAD

**Issue by wgj** [99designs/aws-vault#182]
When using `rotate`, IAM API usage does not use authenticate with MFA. Expected use case is to use MFA if `mfa_serial` is defined in `~/.aws/config`. 

Jumping off #178 and #180, our IAM policy is to require MFA authentication for editing Access Keys (which was the root cause of the error in #178, my attempts to isolate `aws-vault rotate` were with MFA'd sessions).

I considered thinking of this as not-99designs' problem, but I'm fairly confident that we would always want MFA required for `CreateAccessKey` and `DeleteAccessKey` ([this article](https://duo.com/blog/potential-gaps-in-suggested-amazon-web-services-security-policies-for-mfa) is pretty hot in our office).

**Comment by lox** [comment]
I absolutely consider this our problem, sorry if I've indicated otherwise! Strongly agree that everything should have MFA, it's basically why we wrote `aws-vault`!

One of the nuances with rotate and profiles is that you need to use `aws-vault rotate <profile_with_role>` vs `aws-vault rotate <profile_with_creds>`. Then that should work. 

For instance, I have a root profile with no permissions except assuming a role, and then a profile with that assumed role (and MFA) that I use.

**Comment by lox** [comment]
@wgj I'm not sure if there is anything we can action here, did my above suggestion work for you?

**Comment by wgj** [comment]
@lox sorry for the late response, and thank you for following up.

The error appears to persist while using the profile's role:

``` bash
~ $ aws-vault rotate superuser-role
Rotating credentials for profile "superuser-role"
Enter token for arn:aws:iam::2,,7:mfa/wgj:
aws-vault: error: Failed to get credentials for wgj (source profile for superuser-role): AccessDenied: User: arn:aws:sts::2..7:assumed-role/superuser-role/1..0 is not authorized to perform: iam:CreateAccessKey on resource: user wgj with an explicit deny
	status code: 403, request id: c9153a42-e134-11e7-9cbb-ed65d45e5eff
```

Whereas using `aws-vault exec` and aws-cli directly is fine:
``` bash
~ $ aws-vault exec superuser-role -- awscli iam create-access-key --user-name wgj
{
    "AccessKey": {
        "UserName": "wgj", 
        "Status": "Active", 
        "CreateDate": "2017-12-15T02:51:43.951Z", 
        "SecretAccessKey": "almostleftthisinlol", 
        "AccessKeyId": "AKIA..Q"
    }
}
```

Our IAM policy is to deny actions without MFA Authentication (It's at the bottom, leaving in all conditions incase they are also relevant):

```
"Statement": [
        {
            "Action": "*",
            "Resource": "*",
            "Effect": "Allow",
            "Sid": "SuperUseEverything"
        },
        {
            "Condition": {
                "Bool": {
                    "aws:SecureTransport": "false"
                }
            },
            "Action": "*",
            "Resource": "*",
            "Effect": "Deny",
            "Sid": "DenyInsecureAccess"
        },
        {
            "Condition": {
                "BoolIfExists": {
                    "aws:MultiFactorAuthPresent": "false"
                }
            },
            "Action": "*",
            "Resource": "*",
            "Effect": "Deny",
            "Sid": "DenyNonMfaAccess"
        }, 
```

From Cloudtrail, we can see that successful `create-access-key` calls (i.e., `aws-vault exec`) have `mfaAuthenticated`:

```
  	 userIdentity:	{
    	 accessKeyId:	 ASIA..A	
    	 accountId:	 2..7	
    	 arn:	 arn:aws:iam::2..7:user/wgj	
    	 principalId:	 AI..I	
    	 sessionContext:	{		
      	 attributes:	{		
        	 creationDate:	 2017-12-15T01:39:07Z	
        	 mfaAuthenticated:	 true	
      	      	}	
    	}	
    	 type:	 IAMUser	
    	 userName:	 wgj	
```

Whereas unsuccessful calls (i.e., `aws-vault rotate`) do not:
```
 	 userIdentity:	{		
    	 accessKeyId:	 AKIA..A	
    	 accountId:	 2..7	
    	 arn:	 arn:aws:iam::2..7:user/wgj	
    	 principalId:	 AI..I	
    	 type:	 IAMUser	
    	 userName:	 wgj	
  
```

**Comment by wgj** [comment]
Any update on this? I think this issue has been mis-triaged, and seems to be the same as #190.

**Comment by natefaerber** [comment]
@wgj , grab my branch and do a `go build`.  That build will allow you to rotate your key.

https://github.com/99designs/aws-vault/pull/265

**Comment by endzyme** [comment]
https://github.com/99designs/aws-vault/issues/182 linking similar issues
