### ISSUE TITLE
`aws-vault add` borks ~/.aws/config when using s3v4 signatures

### ISSUE THREAD

**Issue by sjauld** [99designs/aws-vault#187]
This one is a little bit difficult because the [AWS documentation around s3v4 signatures](http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingAWSSDK.html) and [cli configuration](http://docs.aws.amazon.com/cli/latest/userguide/cli-config-files.html) is not amazing.

To reproduce:-
1. Check that it works as expected
    ```
    $ aws configure set default.s3.signature_version s3v4
    $ cat ~/.aws/config
    [default]
    s3 =
        signature_version = s3v4
    ...
    $ aws-vault exec my-profile -- aws s3 ls my-bucket
        PRE my-folder/
        PRE my-other-folder/
    ```
2. See what happens when aws-vault modifies the config file
    ``` 
    $ aws-vault add bob
    Enter Access Key ID: mygreatkey
    Enter Secret Access Key: itsasecret
    Added credentials to profile "bob" in vault 
    $ cat ~/.aws/config
    [default]
    s3=
    signature_version=s3v4
    ...
    $ aws-vault exec my-profile -- aws s3 ls my-bucket
    'str' object has no attribute 'get'
    ```

Trial and error seems to indicate that a whitespace character is required before signature_version for this config to work. Not sure s3v4 is the only configuration setting this affects or if other AWS services have similar config settings. I'll see if I can put a fix into Config.

**Comment by lox** [comment]
I'd try deleting `s3 =` and then see if it works without indentation.

**Comment by lox** [comment]
Which region are you encountering that needs you to manually set the signature version? Might be worth just updating the aws cli?

**Comment by sjauld** [comment]
1. Tried deleting s3 =, no luck :(

2.
    Before updating cli: 
    ```
    $ aws --version
    aws-cli/1.11.136 Python/2.7.10 Darwin/16.7.0 botocore/1.5.39
    $ aws-vault exec bob -- aws s3 cp s3://my-bucket/my-file-encrypted-with-aws-kms ./file
    download failed: s3://my-bucket/my-file-encrypted-with-aws-kms to ./file An error occurred (InvalidArgument) when calling the GetObject operation: Requests specifying Server Side Encryption with AWS KMS managed keys require AWS Signature Version 4. You can enable AWS Signature Version 4 by running the command:
    aws configure set s3.signature_version s3v4
    ```
    After updating cli:
    ```
    $ aws --version
    aws-cli/1.11.187 Python/2.7.10 Darwin/16.7.0 botocore/1.7.45
    $ aws-vault exec bob -- aws s3 cp s3://my-bucket/my-file-encrypted-with-aws-kms ./file
    download: s3://my-bucket/my-file-encrypted-with-aws-kms to ./file
    ```

Problem solved! Hopefully s3 is the only service using this sort of ~/.aws/config hack...

Also interesting, the new cli tool still allows you to run `aws configure set default.s3.signature_version s3v4` which will still cause `aws-vault add profile` to bork the config file.

**Comment by lox** [comment]
Hmmm, this is a strange one. Sounds mostly like an `aws-cli` bug, but I'd love to figure out if there is a way that we can work around it.

**Comment by lox** [comment]
Wow. So the aws config isn't an ini file: http://docs.aws.amazon.com/cli/latest/topic/config-vars.html#nested-values

😱

**Comment by lox** [comment]
https://github.com/go-ini/ini/issues/131
