### ISSUE TITLE
manually codesigning fixes issue on yosemite

### ISSUE THREAD

**Issue by devn** [99designs/aws-vault#196]
I was getting this over and over again:

```
~> aws-vault --debug exec default -- aws s3 ls
2017/11/28 21:09:31 Loading config file /Users/me/.aws/config
2017/11/28 21:09:31 Parsing config file /Users/me/.aws/config
2017/11/28 21:09:31 Looking for sessions for default / 4h0m0s
2017/11/28 21:09:31 Session not found in keyring
2017/11/28 21:09:31 Looking up keyring for default
2017/11/28 21:09:31 Error from keyring The specified item could not be found in the keyring.
2017/11/28 21:09:31 Failed to find credentials for profile "default" in keyring
aws-vault: error: Failed to get credentials for default: The specified item could not be found in the keyring.
```

I checked out `console.app` and saw the following every time I tried to use `aws-vault exec myprofile ...`:
```
11/28/17 9:06:12.000 PM kernel[0]: AMFI: Error! There is a null code directory pointer. This is an unexpected condition.
11/28/17 9:06:12.000 PM kernel[0]: proc 1949: load code signature error 4 for file "aws-vault-darwin-amd64"
```

I manually generated a code signing certificate and signed `/usr/local/Caskroom/aws-vault/4.1.0` via the Keychain Assistant by following these instructions: http://andresabino.com/2015/04/14/codesign-gdb-on-mac-os-x-yosemite-10-10-2/

After this, it worked swimmingly. Anyway, just thought if anyone else is struggling with the same thing this might be worth a try.

**Comment by devn** [comment]
Maybe worth mentioning that I did reinstall aws-vault twice, and rebooted once.

**Comment by mtibben** [comment]
I can't reproduce this on Sierra or High Sierra, after some quick googling it does sound like a codesigning issue which seems to have been more present in 2014 correlating with Yosemite release. 

[This answer](https://apple.stackexchange.com/questions/147019/how-can-i-fix-this-codesigning-error) suggests that the issue may be related to copying a file over an existing one, and the related macos services not keeping track of the updated signature / file location.

So it seems on Yosemite you might need to 1. put the binary in place, and 2. reboot to get things working

If I can help further to resolve this, feel free to reopen or comment further
