### ISSUE TITLE
Enhancement: Allow whitelisting of senders to metadata service with the --server option

### ISSUE THREAD

**Issue by clintoncampbell** [99designs/aws-vault#198]
As it is defined right now, the local metadata service stub is attached to 169.254.169.254 and addressable by any host on the local link (leveraging static ARP entries to associate the target's MAC address). It's quite easy, on most networks, to identify potential targets and enumerate the service across multiple hosts.

While I can implement some local firewall rules to lock this down, that provision is out of reach for many developers. Ideally, the server would default to rejecting any outside traffic and provide a basic level of protection for the simple use case.

**Comment by lox** [comment]
Isn't `169.254.169.254` non-routable?

**Comment by lox** [comment]
I'd love to figure out a way to do this if possible!

**Comment by lox** [comment]
It also binds to the loopback interface doesn't it? I couldn't think of any way for network traffic to access it when I was implementing it. Hostile web pages could possibly interact with it with CSRF though.

**Comment by clintoncampbell** [comment]
169.254/16 is not routable but it is available on the LAN unless there is some sort of client isolation in use. Client isolation is pretty rare outside larger enterprises and campuses. Inbound firewall ought to provide some protection, but that's not as ubiquitous as it ought to be, e.g., off by default on macOS and some linux distros. 

At least on macOS, the metadata address doesn't seem to be tightly bound to loopback, and I could imagine this behavior being somewhat platform dependent. The easy test is to have a colleague on the same wireless or ethernet set a static arp entry binding the metadata address to your NIC before hitting the path in a browser or curl. 

The upside is that the machine (at least on macOS) does not appear to respond to ARP or MDNS requests, so it does require knowledge of the target's MAC. However, most machines tend to be fairly chatty when they join the network as they try to identify shared resources.

My first thought on a cross-platform solution would be to look at the sender IP in the server and reject anything that doesn't come from 169.254.169.254. This should allow anything (VM or container) on the localhost to communicate as long as NAT is running. Outside users may be able to spoof inbound traffic, but the response won't (or shouldn't) leave the machine.

The more robust solution would be to use native firewall functionality, but I don't think there's a cross platform solution (though it would be really freaking cool). Not sure I can get to it for a couple of days, but I'll let you know if I come up with a good _pf_ option for macOS. _iptables_ on Linux ought to be fairly easy as well. Will post back if I think of any other options!

**Comment by clintoncampbell** [comment]
Forgot to mention this, but I'm definitely more concerned about developers on public wireless than I am your typical office LAN. I'm certainly guilty of spinning up a container/VM dev environment and forgetting about it in the background. I'm hoping that the timeout on keychain access would provide some protection against this, but I don't want to depend on it completely.

**Comment by lox** [comment]
https://github.com/99designs/aws-vault/blob/39284c5d468c06dc66838f2d32fc77090d92b87c/server/alias_darwin.go#L8

How would network traffic make it to `lo0` in this case? If there was a way to access that from the network, I'd say that is a huge security issue. 

Worth noting, the daemon listening on that port exists only to forward traffic to a short-lived credential servier (`http://127.0.0.1:9099`) that aws-vault runs when you run it with `--server`. This means that it's only serving credentials whilst you have a process running.

**Comment by clintoncampbell** [comment]
We did actually verify this in office before I posted originally, so it’s definitely possible from a remote machine on LAN when the server is running on a default macOS build. It’s been awhile since I worked on an IP stack, but I think the problem is rooted in how forwarding and routing algorithms handle the loopback along with under-specification of link local networking in that domain. 

While 127.0.0.0/8 is prevented from being forwarded on any of the standard interfaces, networking professionals will sometimes assign non-local address aliases to the entire host by attaching to loopback, ensuring that they’ll be visible on any attached interface. I wasn’t actually familiar with the practice until I dug into routing algorithms a bit more deeply. I was completely surprised to learn that loopback could support this use case and that it doesn’t require forwarding to be set up between the associated interfaces and l0.

I can’t tell you the implementation particulars, but my takeaway is that host treats loopback aliases as a special case. It’s not forwarding the packets from one network segment to another, which would be a violation of the link local specification, it’s simply recognizing the address as an on-host address and passing the packet along to the process. This issue probably doesn’t (shouldn’t) apply inside of AWS since Amazon engineers are running a customized stack. 

I definitely want to test some solutions, but I do believe that turning on the host firewall will prevent an attack. That said, I would be hesitant to rely solely on host firewalls. I’m looking into this for a client who relies primarily on an external dev team and doesn’t have much reach onto the local development environment.

I looked at the server implementation, and I’m digging into golang tcp implementation. Might be some middleware that could drop connections originating off loopback? That’d be somewhat cleaner and more robust than filtering IP inside the http session. If that doesn’t exist, I think the IP filter inside the http handler would do the trick.

**Comment by clintoncampbell** [comment]
Here’s a scenario that uses a routable vip on loopback for loadbalancing ... https://unix.stackexchange.com/questions/127905/skip-routing-via-lo-interface-for-outgoing-packets

Not exactly the same, but it demonstrates that the host will accept packets addressed to a loopback alias.

**Comment by lox** [comment]
> We did actually verify this in office before I posted originally, so it’s definitely possible from a remote machine on LAN when the server is running on a default macOS build. It’s been awhile since I worked on an IP stack, but I think the problem is rooted in how forwarding and routing algorithms handle the loopback along with under-specification of link local networking in that domain.

Thanks so much for doing this testing @clintoncampbell! Really appreciate the detail too. Definitely sounds like we should figure out a way to mitigate this, having temporary credentials available on the LAN is terrible.

**Comment by clintoncampbell** [comment]
Just ran a few more tests. The built-in firewall will block only if you are selecting the option to block all incoming traffic. 

<img width="780" alt="screen shot 2017-12-05 at 10 26 25 am" src="https://user-images.githubusercontent.com/7392492/33625629-010408c8-d9ad-11e7-8138-9a286a900341.png">

I expected it would be enough to remove the option for allowing traffic to signed applications, but the requests went right on through (and continued after we removed the option to allow all built-in software too). 

<img width="780" alt="screen shot 2017-12-05 at 10 26 51 am" src="https://user-images.githubusercontent.com/7392492/33625645-19d716ce-d9ad-11e7-89b3-2d3eec839f8e.png">

It's a shame those more convenient configurations don't work. Sadly, I've been in security long enough to know that most people (even developers) will turn it off as soon as something breaks. There's a reason macOS still ships with the firewall disabled.

**Comment by clintoncampbell** [comment]
Digging through the _net_ package, I'm not seeing any way to grab the MAC address of an incoming connection. This leaves us with filtering on IP address. 

I've only tested a couple of configurations, but I see src:169.254.169.254 and dst:169.254.169.254 when sniffing traffic on a connection from a local docker container (bridged connection). I cannot connect at all from a VM on a NAT-based virtual interface (which is to be expected since 169.254/16 cannot be routed).

https://github.com/jpillora/ipfilter may be an easy way to test the efficacy of IP filtering. Though I'd typically prefer wrapping the TCP connection rather than the HTTP connection, I don't imagine performance is going to be an issue here. :) From a security standpoint, whitelisting 169.254.169.254 (and possibly other local addresses) should be reasonable. While you could attempt to spoof your source from another machine on the network, you'll never get past the first leg of the TCP handshake since the target will pass the response back to its own stack.

**Comment by lox** [comment]
I'm going to close this for now, thanks so much for the detail write-up and report @clintoncampbell! If you have suggestions for firewall rules, we'd super appreciate it! 🙌🏻
