### ISSUE TITLE
Cannot compile using Go tip on Macs

### ISSUE THREAD

**Issue by kevinburkeotto** [99designs/aws-vault#200]
See https://github.com/keybase/go-keychain/issues/19 for more information. I'm not sure whether the error lies in the Go source tree or go-keychain is doing something it shouldn't.

**Comment by mtibben** [comment]
This is working with stable go, and go devs seem to [be aware of the issue]( https://github.com/golang/go/issues/22900). Feel free to re-open if this problem is still present by the time we get to Go RC stage

**Comment by kevinburkeotto** [comment]
I'd like to keep this issue open. The only action Go devs appeared to take was to update the C code in that library; no one's working on changing the compiler or cgo to make this work.

**Comment by mtibben** [comment]
Yes I've left the issue open at https://github.com/keybase/go-keychain/issues/19, lets discuss there
