### ISSUE TITLE
Unclear installation path for Linux

### ISSUE THREAD

**Issue by afedulov** [99designs/aws-vault#203]
There is a downloadable binary for Linux, but it is not clear how to use it. After giving it +x permissions and trying to execute nothing happens - process just hangs. Is this binary usable or is the only way to install on Linux currently is to build from sources?

**Comment by mtibben** [comment]
Hey @afedulov you should be able to install it with 
```bash
$ curl -L https://github.com/99designs/aws-vault/releases/download/v4.1.0/aws-vault-linux-amd64 > /usr/local/bin/aws-vault
$ chmod +x /usr/local/bin/aws-vault
$ aws-vault --version
v4.1.0
```

**Comment by adiian** [comment]
This is how you can install the latest version(works on linux):

```
curl -Lo aws-vault https://github.com/99designs/aws-vault/releases/download/$(curl -s https://api.github.com/repos/99designs/aws-vault/releases/latest | grep tag_name | cut -d '"' -f 4)/aws-vault-linux-amd64
chmod +x ./aws-vault
sudo mv ./aws-vault /usr/local/bin/
```
Should work on mac too it there is a mac build to replace aws-vault-linux-amd64 with...

**Comment by wedneyyuri** [comment]
@mtibben can we add these instructions to the readme?
