### ISSUE TITLE
Gatekeeper and short name

### ISSUE THREAD

**Issue by wgj** [99designs/aws-vault#204]
Feel like I'm doing something dumb here, but I want to use `aws-vault` instead of `aws-vault-darwin-amd64`, but when I rename or symlink, MacOS claims `aws-vault` is from an unidentified developer. This isn't the case for `aws-vault-darwin-amd64`. I'm guessing I want the `make sign` artifacts and not the`make release` artifacts?

MacOS 10.13.2
aws-vault v4.1.0 (from GitHub Releases)

**Comment by mtibben** [comment]
@wgj You could symlink aws-vault to aws-vault-darwin-amd64 (that's what brew is doing).

Thoughts @lox? Should we be signing aws-vault instead of aws-vault-darwin-amd64?

**Comment by lox** [comment]
Interesting, I didn't realize that code signing took the name of the binary into account. Are you certain that symlink isn't working @wgj?

**Comment by wgj** [comment]
I think the symlink is a red herring, and it's to do with the path/my ignorance of GateKeeper :) :

Relative path is "unidentified":
```
aws-vault exec $AWS_PROFILE -- awscli s3 ls
```

Qualified path is "identified":
```
~/bin/aws-vault exec $AWS_PROFILE -- awscli s3 ls
```

Do you guys not run into this issue?

**Comment by wgj** [comment]
> Interesting, I didn't realize that code signing took the name of the binary into account. Are you certain that symlink isn't working @wgj?

The filename will fill in the blank for the identifier (executable's identifier, not the developer's identifier). But given the "path" comment above, I don't think this detail turned out to be relevant.

**Comment by wgj** [comment]
Never mind :(

```
~ $ which aws-vault
/Users/wgjohnson/Documents/go/bin/aws-vault
```
