### ISSUE TITLE
Question: STS usage - getting federation token

### ISSUE THREAD

**Issue by gbataille** [99designs/aws-vault#216]
Hey guys,

first, thanks for this tool, I find it really nice.

My problem: in my application, I have an API that is supposed to return a set of temporary credentials with specific limited access. For that, my code will try to get a federation token from STS. But because I'm logging in to AWS through a temporary set of credentials already, I'm not authorized to get a federation token.
Do you have any way to make this work? that basically prevents me to run this bit of functionality from my local setup

thanks

**Comment by lox** [comment]
Sounds like you will need to use `aws-vault exec --no-session` which will expose the root credentials rather than an STS session.

**Comment by gbataille** [comment]
Hey, thanks for the quick answer. that works indeed.

I haven't seen it documented. is it?
If not, should I do a PR (maybe this week end)?

In term of security, the root credentials are still given only to the wrapped process, as env variable. And then with aws-vault, it's easy to rotate your creds. So I guess that on a developer machine, it's quite acceptable to use (although I would recommend that it should not be the default), right?

**Comment by lox** [comment]
It's not documented, generally because we discourage it's usage. In certain cases like this it makes sense though.

**Comment by lox** [comment]
I'm going to close this one, would happily receive a PR for docs if you have time!
