### ISSUE TITLE
windows 10- Failed to run it with --server mode

### ISSUE THREAD

**Issue by Wesam18** [99designs/aws-vault#217]
Running aws-vault with --server mode is failing and show below error 
``` aws-vault: error: exec: "": executable file not found in %PATH% ``` 

OS: Windows 10
Command used:  ``` aws-vault exec work --session-ttl=8h --assume-role-ttl=1h --server ``` where ``` work `` is the profile name.

**Comment by lox** [comment]
Could you try `aws-vault exec work --session-ttl=8h --assume-role-ttl=1h --server -- CMD.EXE` and let us know if that works?

**Comment by Wesam18** [comment]
Yes, that work

**Comment by amitsaha** [comment]
Needed the workaround suggested by @lox - but it seems like it's working otherwise!

**Comment by amitsaha** [comment]
Just one note: Powershell ISE doesn't work  - not sure why.

**Comment by Agraphie** [comment]
I have the same problem actually. It can be fixed with the above command. Maybe we should detect whether we are running windows and `command` is an empty string and then just set `command=cmd`?

**Comment by steelx** [comment]
works with Cmder terminal as well
`aws-vault exec dev-admin -- cmder.exe`

and have the following environments:
![image](https://user-images.githubusercontent.com/3184210/113240761-f49e5b80-92ca-11eb-820a-b2151ca35e20.png)

**Comment by adamosimpson21** [comment]
I have attempted to run aws-vault exec myProfile -- CMD.EXE and it kicks me out of my WSL2 instance OR it goes back to my windows terminal (if I ctrl C I go back to WSL2). Normal aws-vault exec myProfile gets the executable not found in %PATH% as above 
![image](https://user-images.githubusercontent.com/13780256/137677181-69089890-7b0a-4daa-95cd-fe9971e528a0.png)

**Comment by sandeeppnaik** [comment]
I am experiencing the same as @adamosimpson21's error
