### ISSUE TITLE
list --profiles picks up non-profile entries from config

### ISSUE THREAD

**Issue by philpennock** [99designs/aws-vault#229]
My `~/.aws/config` contains `[default]` and `[preview]` sections, but `aws-vault --profiles` is picking those up as profile names, ignoring the absence of the `profile` keyword which is required in this file.

```
% aws-vault --version
v4.2.0
```

**Comment by lox** [comment]
```
 ▲ ~ aws-vault --profiles
aws-vault: error: unknown long flag '--profiles', try --help
```

??

**Comment by lox** [comment]
Do you mean `aws-vault list`?

**Comment by philpennock** [comment]
Uh yes, sorry.

**Comment by lox** [comment]
So `default` is expected, as you can have credentials stored against it. `preview` is not, and is probably a bug. Does that sound right to you?

**Comment by philpennock** [comment]
Ideally, `default` only shown if there _are_ credentials stored against it, but I haven't explored to see if that's feasible.

(Sorry, before filing the bug I did consider just submitting a patch but my first step was to try to build from master and that failed on a bunch of macOS headers, and I lack macOS programming knowledge to debug to even get to where I could start).
