### ISSUE TITLE
Unable to get session token with secret-service or kwallet backends on Fedora

### ISSUE THREAD

**Issue by pgrzesik** [99designs/aws-vault#231]
Hello,

maybe you'll be able to help because currenly I'm out of ideas.
I'm trying to setup aws-vault on Fedora 27 and unfortunatelly both for secret-service and kwallet backends I'm not able to correctly get session token while using `aws-vault exec <profile>`. Here's a corresponding error

```
2018/03/03 23:49:57 Getting new session token for profile <profile>
aws-vault: error: Failed to get credentials for <profile>: InvalidClientTokenId: The security token included in the request is invalid.
```

It's working with `file` backend, but the fact that I have to use password everytime makes this backend too much of a hassle for daily usage. 

What might be causing this issue ?

Regards

**Comment by crielly** [comment]
```
[crielly@ilos ~]$ aws-vault --version
v4.1.0
[crielly@ilos ~]$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 27 (Twenty Seven)
Release:	27
Codename:	TwentySeven
```

Working fine for me via this process: https://www.tastycidr.net/using-aws-vault-with-linux/

**Comment by pgrzesik** [comment]
@crielly Thanks a lot for the article - works smoothly, I might've missed that somehow while digging for answer.
