### ISSUE TITLE
GPG backend

### ISSUE THREAD

**Issue by oarmstrong** [99designs/aws-vault#232]
I saw in #23 that GPG secret storage was planned but the issue was closed for specific issues and I was unable to locate an issue for GPG storage.

I don't think much more needs to be said. If this sits around until the weekend without anyone else picking it up I can take a crack at it.

**Comment by lox** [comment]
That will happen via a password-store keyring backend, check out https://github.com/99designs/keyring/pull/15

**Comment by lox** [comment]
Feedback on that approach welcomed!

**Comment by withnale** [comment]
I think a direct integration with GPG would be best. For one, this allows these credentials to be tracked with git and therefore synced across multiple machines.

Whilst I like password-store (and already use it) I use that for other things and don't really want to integrate the two, where in some circumstances I will want my full password-store on a machine and in other circumstances not - much easier to have a configured AWS vault specific backend GPG dir.

Like @oarmstrong I'm happy to have a crack at the native GPG backend.

**Comment by oarmstrong** [comment]
I'd personally be fine with using password-store as the backend, but for simplicity and customisability's sake having them separate works better in my mind. I'm with @withnale on this one.

If we got something working, would @lox be comfortable merging that as well as the password-store backend?
