### ISSUE TITLE
SAML-based authentication using AssumeRoleWithSAML

### ISSUE THREAD

**Issue by johnkeates** [99designs/aws-vault#235]
Would it be a complex task to add support for authenticating against a SAML IdP to get tokens from STS?

I imagine it would be something like calling the IdP page to get the nonce/csrf token, and then posting the creds to the IdP, redirecting to AWS, which then hands out the tokens, which probably need to be refreshed periodically to stay active.

**Comment by errygg** [comment]
+1

**Comment by lox** [comment]
I suspect it might end up being pretty complicated. Segment ended up creating a fork of aws-vault specifically for this + Okta which might be worth checking out: 

https://segment.com/blog/secure-access-to-100-aws-accounts/

**Comment by rverma-nikiai** [comment]
+1 for this. There is a project https://github.com/cevoaustralia/aws-google-auth which is quiet relevant. Although it would be great if these capabilities are also part of vault since vault doesn't support reading from existing credential file

**Comment by cullenmcdermott** [comment]
Would it be possible to utilize parts of [saml2aws](https://github.com/Versent/saml2aws) to accomplish this?

**Comment by lox** [comment]
Thoughts @wolfeidau? The other route would be to integrate 99designs/keyring as a common backend for the two tools.

**Comment by wolfeidau** [comment]
I would LOVE to use `99designs/keyring` for https://github.com/Versent/saml2aws, I am using some pretty messy stuff now via CGO and it is a nightmare.

Will take a look at a bit of a refactor of this, thanks for the note @lox

**Comment by majormoses** [comment]
We are looking at switching over our aws auth to using okta as a provider and are gonna be looking at the segment project as well as this one: https://github.com/oktadeveloper/okta-aws-cli-assume-role

**Comment by brendanheywood** [comment]
+1

**Comment by Vad1mo** [comment]
Why don't we add a [Go Plugin System over RPC](https://github.com/hashicorp/go-plugin) to AWS-VAULT and then in the second step one could add different SAML Provider such https://github.com/Versent/saml2aws  to AWS-VAULT.

No forking of AWS-VAULT needed and the codebase would still be lean.

**Comment by hydrajump** [comment]
Is support for SAML for ADFS authentication something that the aws-vault maintainers are open to or is it best to fork aws-vault and maybe do what aws-okta had done?

**Comment by mtibben** [comment]
Hey folks, SSO support has just been merged in #549. Try out the pre-release at https://github.com/99designs/aws-vault/releases/tag/v5.5.0-alpha3 and let us know how it goes

**Comment by hlascelles** [comment]
I have been using it just fine for a couple of weeks (built from this branch) and it has been working great! 

However today, it suddenly stopped working, with, as far as I can tell, no changes by me. I tried the alpha official build and it gave the same error:

```
❯ aws-vault-linux-amd64 exec sso-login --debug -- aws sts get-caller-identity
2020/04/21 18:31:32 aws-vault v5.5.0-alpha3
2020/04/21 18:31:32 [keyring] Considering backends: [secret-service kwallet pass file]
2020/04/21 18:31:32 Loading config file /home/myuser/.aws/config
2020/04/21 18:31:32 Parsing config file /home/myuser/.aws/config
2020/04/21 18:31:32 Looking for sessions for sso-login
2020/04/21 18:31:32 Looking up all keys in keyring
aws-vault: error: Failed to get credentials for sso-login : Session token not found or invalid
	status code: 401, request id: 
```

I've tried clearing all sessions in aws-vault, and no dice.

I've `export`'ed the ENV from the AWS console, and they work fine. I've been reading that aws cli caches details in `~/.aws/cli/cache` but I don't have that.

Nothing `apt` updated at the time... I am at a loss. What should I try next?

**Comment by hlascelles** [comment]
Hmm! It just "started working again", also with no changes by me, really.

It all started breaking about 9 hours after I started working, then started working another hour after that. Does that help narrow down the problem?

**Comment by mtibben** [comment]
> However today, it suddenly stopped working, with, as far as I can tell, no changes by me.

Maybe @itsdalmo has some thoughts on how to debug this?

**Comment by hydrajump** [comment]
> Hey folks, SSO support has just been merged in #549. Try out the pre-release at https://github.com/99designs/aws-vault/releases/tag/v5.5.0-alpha3 and let us know how it goes

This is a silly question but since the above comment was posted in this issue I have to ask. Does this mean that aws-vault supports other SAML providers than AWS SSO, e.g. ADFS?

**Comment by FernandoMiguel** [comment]
I would love to see Azure AD support

**Comment by johnkeates** [comment]
> I would love to see Azure AD support

If Azure AD can do normal SAML it should be easy enough to add that. If Azure AD's SAML is like AD Federation (classical) then it might be problematic depending on how you assign your roles to from the IdP to the AWS User.

**Comment by statik** [comment]
I believe there is a useful path here by configuring AWS-SSO to connect with Azure AD, and then aws-vault could authenticate against AWS-SSO (which would have Azure AD as the identity source). Some descriptions of the integration here: https://aws.amazon.com/blogs/aws/the-next-evolution-in-aws-single-sign-on/

**Comment by hlascelles** [comment]
So that error has again happened today:

```
ws-vault: error: exec: Failed to get credentials for sso-network-services-administrator: : Session token not found or invalid
	status code: 401, request id: 
```

It's around the same time of day too (ie, probably around the same length of time since I did the browser sign in. I think 6 hours?). I will take exact timings next time.

**Comment by mtibben** [comment]
Perhaps a bug in the cached credentials?

**Comment by mtibben** [comment]
@hlascelles I believe this issue is fixed in [v6.0.0-beta3](https://github.com/99designs/aws-vault/releases/tag/v6.0.0-beta3). If it's not, can you please create a new issue?

**Comment by mtibben** [comment]
Closing this, as it's now _possible_ to use SAML via AWS SSO in #549. There are probably better ways to utilize AssumeRoleWithSAML however, so if anyone needs that support, please open a new issue or PR

**Comment by brendanheywood** [comment]
Am I missing something? AWS SSO !== a generic saml solution. From the looks of the other issue and the docs only AWS is supported. If so I think this issue should be reopened

https://github.com/99designs/aws-vault#aws-sso-integration

**Comment by mtibben** [comment]
Hey @brendanheywood AWS SSO supports [3rd party IdP](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_saml_3rd-party.html).

This issue was a very general "Support SAML-based authentication" which aws-vault can now do via AWS SSO. If you have a more specific implementation in mind, lets create a a new issue to track that

**Comment by mtibben** [comment]
Meh, I guess we can leave this issue open as the [sts.AssumeRoleWithSAML](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRoleWithSAML.html) case

**Comment by mtibben** [comment]
Anyone up for having a stab at the implementation?

It should be significantly easier than it has been in the past as the code for config, caching and credential providers are all orthogonal

**Comment by brendanheywood** [comment]
I've know saml pretty well, but not go at all. There should hopefully be some saml libs that do all the heavy lifting and this look promising:

https://github.com/crewjam/saml

**Comment by greyfairer** [comment]
My ex-colleague has implemented this in Go for SAML authentication with OneLogin: https://github.com/glnds/masl. He did a blog post on it last week.
I'm not sure if it would work with e.g. Google Apps too?

**Comment by dantrauner** [comment]
+1 for this – I love `aws-vault` for non-SAML and came from using the now unmaintained `aws-okta` for SAML, but it turns out you cannot use the AWS SSO service if your AWS account(s) are tied to a reseller. This is a known issue for the way AWS resellers are set up :(

**Comment by mtibben** [comment]
After a little more research, I'm not convinced adding direct SAML support to aws-vault is desirable given the considerable complexity involved in an implementation and that tools like https://github.com/Versent/saml2aws already exist

Seems like adding support for AssumeRoleWithSAML would only re-create what [saml2aws](https://github.com/Versent/saml2aws) does.

Maybe there's something that I'm missing. To those who have voted on this issue, what can't be accomplished with [saml2aws](https://github.com/Versent/saml2aws) that you're hoping aws-vault would be able to accomplish?

**Comment by dantrauner** [comment]
@mtibben I think `saml2aws` might not actually support encrypted backends for caching credentials, so you end up with plaintext secrets on disk. I haven't tried it in a while though, so maybe that's supported now? I know `aws-vault` has always done this.

**Comment by baztian** [comment]
@dantrauner is right. Saml2aws stores the access credentials on plain text. Personally I'm using aws accounts tied to saml idps and some not being tied to saml. Therefore it would be nice to have just one tool for the job. But honestly saml2aws is OK.

**Comment by johnkeates** [comment]
While I'd still like to have it all in aws-vault (some setups use SAML, some OID, some AWS SSO, some plain credentials), I do see the point of not making it extra complicated...

If it really is unreasonably hard to get this integrated I should probably see if the reverse can be done -- hooking a frontend up to a SAML client as well as having aws-vault as a client. It would still give the best of both worlds (somewhat).

**Comment by olfway** [comment]
It's not stale, still valid

**Comment by hannahkamundson** [comment]
+1
