### ISSUE TITLE
Long running sub-processes result in expired keys

### ISSUE THREAD

**Issue by lox** [99designs/aws-vault#24]
The maximum expiry on assume-session credentials is unfortunately 60 minutes (http://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html). What this means is that a long running process (for instance a complicated `packer` build) will end up with expired credentials.

Because `aws-vault` gets credentials to the child process as environmental variables, there aren't any mechanisms to refresh these. The various SDK's and `aws-cli` refresh these internally.  

I'm currently investigating different options, none so far which are a perfect fit.

Interested in thoughts. @joho @dgoodlad @pda @mtibben

**Comment by joho** [comment]
I think it's a really tough problem to solve :-/

I think it might be valuable for `aws-vault` to send a signal to the subprocess on credential expiry - at least by making it very obvious that your time is up with those credentials it can ease user frustration and. https://github.com/hashicorp/envconsul sends a `SIGTERM` when a consul query goes stale.

**Comment by dgoodlad** [comment]
If you ignore `AssumeRole`, and just talk about temporary session credentials, the 60 minute limit doesn't apply. You *could* request temporary session for your normal IAM user, assuming your normal user has full access rights to access "dev" type resources...

However, if that's not possible, huge :+1: for the way envconsul handles it. Make the `aws-vault` process handle session refreshes, then SIGTERM and restart

**Comment by pda** [comment]
:-1: for SIGTERM when session expires. Ending the process probably isn't going to help anybody, and auto-restarting the process is unexpected and possibly dangerous. I imagine there's cases where the credentials are only used at start-up anyway, so the program could keep running happily with an expired session.

How about having `aws-vault` emit a warning to stderr on expiry?

All of these solutions require changing the execution model from [`syscall.Exec`](https://golang.org/pkg/syscall/#Exec) (replacing the `aws-vault` process) to a subprocess model, where aws-vault remains active as the parent process.

**Comment by dgoodlad** [comment]
@lox super excited about a local metadata server for this issue. Emulating the behaviour of an EC2 instance with an Instance Profile means that any well-implemented AWS client library "just work". :star2:

**Comment by lox** [comment]
Yeah, it seems that way at present. I've actually run into more issues with older boto code and environment variables than with ec2 instance role support. My only concern is whether the complexity outweighs the value, but we'll see how it goes over the next few weeks.
