### ISSUE TITLE
aws-vault login <profile> fails on windows

### ISSUE THREAD

**Issue by HitDaCa** [99designs/aws-vault#241]
In the current 4.2.0 release (only windows) there seems to be a bug within the browser redirect functionality  triggered by `login <profile>`. When inspecting the generated url in the browser, an additional **^** is added after every url-parameter. This causes the original request to fail and display a 404 request-> page not found. Removing all additional **^** from the generated url fixes the problem.
Using `login <profile> -s` however outputs the correct url, this seems to be a valid workaround at the moment.

**Comment by ngerstle** [comment]
I have a similar issue on Linux as well.
Copy-pasting the url generated by `aws-vault login <profile> -s` works perfectly, but just using `aws-vault login <profile>` only brings up a log in page.
Haven't checked the url as received by the browser (firefox).

**Comment by rummepa** [comment]
issue still present in current version v4.4.1
bump! 👍

**Comment by juan-dambra** [comment]
This is kind of annoying, so bump! 👍 

I extended the function provided by @rummepa. Nothing too great but added support for FF as well as for Normal Mode / Incognito:

```
function aws-vault-login($profile, $browser) {

  $command = "aws-vault login $profile -s"

  Invoke-Expression $command -OutVariable $URL | Tee-Object -Variable URL

  if($browser) {
    $browser = $browser.ToLower()
  }

  switch($browser) {
    {($_ -eq "chrome") -or ($_ -eq "c")} {Start-Process "chrome.exe" -ArgumentList @( $URL ); break}
    {($_ -eq "chrome-incognito") -or ($_ -eq "ci")} {Start-Process "chrome.exe" -ArgumentList @( '-incognito', $URL ); break}
    {($_ -eq "firefox") -or ($_ -eq "f")} {Start-Process "firefox.exe" -ArgumentList @( $URL ); break}
    {($_ -eq "firefox-incognito") -or ($_ -eq "fi")} {Start-Process "firefox.exe" -ArgumentList @( '-private-window', $URL ); break}
    default {Start-Process "chrome.exe" -ArgumentList @( $URL ); break}
  }
}
```
Defaults to Chrome in Normal Mode.
