### ISSUE TITLE
--no-session does not use MFA?

### ISSUE THREAD

**Issue by gbataille** [99designs/aws-vault#245]
Hey guys,

So as discussed in a previous issue, I use `--no-session` from time to time when I need to run a part of my code that gets a FederationToken (which is not possible from a temporary session).

Now I have added an IAM policy on my account that basically disallow all access if I have no MFA setup.

It seems that if I use `--no-session` then the MFA in my config file is not used and therefore AWS rejects my actions.
I tried also to "force" the mfa by doing `aws-vault exec my_profile --no-session -m MFA_ARN` but it did not work either.

Am I right to think that `--no-session` will not use the MFA for authentication?

Is this a technical limitation or something that could be changed in aws-vault?

Thanks

**Comment by FernandoMiguel** [comment]
i dont use --no-session often so i can offer much help there
but my main profile has MFA and i tried it and it worked as expected
here's a sample of my config
https://github.com/FernandoMiguel/aws-vault-quick-guide/blob/master/README.md#aws-config

**Comment by gbataille** [comment]
@FernandoMiguel looks to have some similarities indeed. the difference though is that I have a problem only in a `--no-session` context which I think is not your case.

I can rotate my credentials fine even with the above mentioned policy forcing the MFA

**Comment by gbataille** [comment]
Hey @stale bot,

I did not remember opening this issue. I know though that I currently regularly use MFA enabled connection with the `--no-session` argument. So either something was fixed, or I was doing something wrong.

Closing
