### ISSUE TITLE
Can MaxAssumeRoleDuration be increased?

### ISSUE THREAD

**Issue by e1ven** [99designs/aws-vault#246]
My understanding is that as of [This change](https://aws.amazon.com/about-aws/whats-new/2018/03/longer-role-sessions/) we can now assume roles for up to 12h?

aws-vault still gives the error
`aws-vault: error: Maximum duration for assumed roles is 1h0m0s`

If my understanding is correct, this can be changed by increasing [this value](https://github.com/99designs/aws-vault/blob/e41f2cd89dd19c930c2c16882090f996b74b7ba8/vault/provider.go#L23)

**Comment by FernandoMiguel** [comment]
There's already a ticket and a PR for this

**Comment by lox** [comment]
Just merged https://github.com/99designs/aws-vault/pull/240.

**Comment by lox** [comment]
I don't believe this is going to work. 

https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_terms-and-concepts.html

> Role chaining limits your AWS CLI or API role session to a maximum of one hour.

**Comment by FernandoMiguel** [comment]
I'm ok with being asked for the MFA per session, if I don't have to see the session expire in an hour

**Comment by FernandoMiguel** [comment]
What is chaining in this context?
Is the process of using STS chaining? 
In my work flow, I login to an IAM account and only assume a role in another account

**Comment by lox** [comment]
`iam credentials -> assume role` basically @FernandoMiguel

**Comment by FernandoMiguel** [comment]
I see... and that breaks the total time @lox  ?

**Comment by nocode99** [comment]
Ah - I didn't realize that had to be set.  I went ahead and set it immediately and still getting same message after 15m thinking it might be eventually consistent.  The config I was using looked like:

```
[profile profile1]
region=us-east-1

[profile admin]
source_profile = profile1
role_arn = arn:aws:iam::12345:role/Admin
mfa_serial = arn:aws:iam::12345:mfa/my_user
```

and I was executing `aws-vault exec --no-session --assume-role-ttl 12h --debug admin`

Ultimately, what I'm hoping to accomplish is having users getting temporary credentials via aws-vault using MFA and then starting a tmux session.

**Comment by e1ven** [comment]
Just to check, are you compiling the code?

The most recent version from https://github.com/99designs/aws-vault/releases is 20 days ago, and @lox only merged #240 14 days ago, so this wouldn't be in v4.2.1.

**Comment by jeremygaither** [comment]
Looking forward to this making it into the next release!

**Comment by mtibben** [comment]
https://github.com/99designs/aws-vault/releases/tag/v4.3.0
