### ISSUE TITLE
Help with temp credentials

### ISSUE THREAD

**Issue by rverma-nikiai** [99designs/aws-vault#247]
We are using https://github.com/cevoaustralia/aws-google-auth to get temp token using SAML. They got stored into ~/.aws/credentials. Can we use aws-vault to read with profiles in ~/.aws/config and credentials from ~/.aws/credentials.

**Comment by FernandoMiguel** [comment]
aws-vault wont read the creds in `~/.aws/credentials`
they need to be added to the proper keychain.

**Comment by skyzyx** [comment]
Feels like this could be closed.
