### ISSUE TITLE
Provide MFA token as a command-line argument

### ISSUE THREAD

**Issue by simpsora** [99designs/aws-vault#25]
There are some workflows which use command-line tools such as [oath-toolkit](http://www.nongnu.org/oath-toolkit/oathtool.1.html) for generating MFA tokens.

It would be handy to be able to pass the MFA token value into the `aws-vault` call as a flag, which would make it easy to integrate.  Something like this:

```
$ aws-vault exec --mfa-token=123456 admin -- aws ...
```

I'm not familiar with Golang but will try to create a PR for this!

**Comment by coen-hyde** [comment]
This would be helpful for me too. I use aws-vault inside a bash script. At the moment I'm just piping the mfa token to aws-vault but having it specified as a token would make things a bit nicer.

**Comment by simpsora** [comment]
@coen-hyde I tried that and assumed it failed due to the error message, but as you say it does work!  It would be nicer to have it as a command-line argument.

**Comment by lox** [comment]
Yup, good idea. Will look into this. I'd like there to be a standard way to plug in different prompt methods to support integrating with other tools. I'm considering just using GPG's `pinentry` interface, which would open up all the existing `pinentry` methods: http://manpages.ubuntu.com/manpages/dapper/man1/pinentry-curses.1.html

**Comment by lox** [comment]
https://github.com/99designs/aws-vault/pull/37
