### ISSUE TITLE
Add support for AWS AD

### ISSUE THREAD

**Issue by myoung34** [99designs/aws-vault#251]
I dont want to give up my favorite tool for SSO =(

**Comment by FernandoMiguel** [comment]
ahahahaha

**Comment by pda** [comment]
[AWS Directory Service](https://aws.amazon.com/directoryservice/)? In what way would you want aws-vault to support it?

**Comment by myoung34** [comment]
After playing with it more I realize that AWS ad connector does not support sessions etc. What I really mean at this point is saml via https://github.com/99designs/aws-vault/issues/235
