### ISSUE TITLE
login without role

### ISSUE THREAD

**Issue by FernandoMiguel** [99designs/aws-vault#252]
silly question really but maybe there is a way and i'm missing it

I use `aws-vault login` a lot.
We have dozens of roles across dozens of accounts.
and it works perfectly

it works so well, that I want to move all users to access the IAM account , to their own profile with aws-vault, and not have a password enabled .

but as aws-vault uses STS, we cant really _login_ to an IAM account without a role, can we ?

**Comment by MrPrimate** [comment]
Disabling a users password will still allow them to log in via an assumed role and their stored credentials in the source_profile.

You will need to allow the use the ability to get a "sts:GetFederationToken". Generally though, it would be best if a user assumed a role in this source account to manage themselves. Rule of thumb: You should always assume a role.
