### ISSUE TITLE
Error: The security token included in the request is invalid

### ISSUE THREAD

**Issue by JoostSaanen** [99designs/aws-vault#260]
I have a problem and I cannot figure out why.

My AWS Account has an `admin`-user with a default Administrator policy.

My `~/.aws/config`(created with `aws-vault add admin-aim`) contains:

```
[admin-iam]
region=eu-west-2
```

When I do: 
```
aws-vault exec admin-iam -- aws iam create-user --user-name fooo
```

I've got an error:

```
An error occurred (InvalidClientTokenId) when calling the CreateUser operation: The security token included in the request is invalid
```

Any idea what could be wrong? Thx!

**Comment by JoostSaanen** [comment]
hmmm apparently fixed after running `aws-vault exec admin-iam -- aws sts get-caller-identity`?

**Comment by FernandoMiguel** [comment]
Aren't you missing fields in that config?
Where is the IAM account?
Where is the role you want to assume?

--
Fernando Miguel

**Comment by artursmet** [comment]
I've encountered the same problem. It's caused by the AWS API restrictions, that won't allow you to touch IAM related APIs using the account with MFA enabled, when you don't pass the MFA token within the request.
Work around it is to call:
```
$ aws-vault exec admin-iam --no-session -- your_command
```
It won't use temporary credentials then. I know that's not a perfect solution, but it works ;)

**Comment by errygg** [comment]
Confirmed the workaround @artursmet works. Thanks!

**Comment by JGjorgji** [comment]
This doesn't work for me and i do have `mfa_serial` specified for each profile.

```
aws-vault: error: Failed to get credentials for root (source profile for dev): InvalidClientTokenId: The security token included in the request is invalid.
```
Just calling the aws cli works fine.

```
aws-vault --version
v4.4.1
```

**Comment by robacarp** [comment]
Worth noting that if the workaround above (`aws-vault exec <profile> -- ...`) works for you, you can always spawn a shell with the profile added to the environment by just `aws-vault exec <profile>` and then carry on with whatever aws-api utilities you happen to want to use.

**Comment by hisashiyamaguchi** [comment]
I'm also struggling.

$ uname -a
Darwin tyo-mpy1d 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64
$ aws-vault --version
v6.2.0

$ aws-vault exec dev --no-session -- terraform init
Enter token for arn:aws:iam::xxxx:mfa/xxxx@xxxx.com: xxxx
aws-vault: error: exec: Failed to get credentials for dev: InvalidClientTokenId: The security token included in the request is invalid.
	status code: 403, request id: dd062af4-8bd2-4c14-8825-c6e7e0ea5fa4

"mfa_serial" is definitely set on my .aws/config. Any ideas?

**Comment by johnacliffe** [comment]
https://github.com/99designs/aws-vault/blob/master/USAGE.md#aws-single-sign-on-aws-sso

try using the AWS SSO sign on?

**Comment by juliusashu** [comment]
Please I have the error below, 
An error occurred (InvalidClientTokenId) when calling the CreateUser operation: The security token included in the request is invalid

I have changed several AWS Access Key ID and AWS Secret Access Key but still getting the same error. There is no MFA on the user account.

Please any help to resolve this error will be very grateful.

**Comment by mikethm** [comment]
use 
```
--no-session
```
ref: 
https://github.com/99designs/aws-vault/blob/master/USAGE.md#temporary-credentials-limitations-with-sts-iam
