### ISSUE TITLE
aws-vault does not support aarch64

### ISSUE THREAD

**Issue by maishsk** [99designs/aws-vault#261]
I would love to use vault on my Chromebook (running crouton) but it seems that this is not possible

I downloaded
https://github.com/99designs/aws-vault/releases/download/v4.2.1/aws-vault-linux-amd64

When trying to run `aws-vault` - I get

```
(xenial)maishsk@localhost:~/.local/bin$ ./aws-vault 
-su: ./aws-vault: cannot execute binary file: Exec format error


(xenial)maishsk@localhost:~/.local/bin$ uname -a
Linux localhost 4.4.118-13212-g6c21f415c5d1 #1 SMP PREEMPT Mon May 14 23:19:05 PDT 2018 aarch64 aarch64 aarch64 GNU/Linux 
```

Thoughts? Suggestions?

**Comment by FernandoMiguel** [comment]
That's ARM right?

**Comment by maishsk** [comment]
I think so - yes

**Comment by pda** [comment]
There's no official binaries for ARM / arm64 / aarch64. I doubt that'll change any time soon, without more community demand/support.

You can try installing the Go compiler and building aws-vault from source.

**Comment by maishsk** [comment]
@pda I understand - would you perhaps a detailed howto ?

**Comment by maishsk** [comment]
Never mind.

I managed to build it from source .

Now the question - is this something that the community would be interested in using? 

If so how?

**Comment by maishsk** [comment]
Documenting this for the future and closing

https://technodrone.blogspot.com/2018/07/aws-vault-on-chromebook.html

**Comment by fionn** [comment]
> I doubt that'll change any time soon, without more community demand/support.

How does that get measured? I'm asking because ARM is pretty popular these days. I for one would appreciate a binary distribution for this. It's also fairly trivial to cross-compile.

**Comment by nvanheuverzwijn** [comment]
@mtibben @lox @pda Considering new Macos laptop are arm, it would make sense to add arm support in my opinion.

**Comment by pda** [comment]
As far as I know, the latest stable Go 1.15 doesn't emit macOS arm64 binaries, but upcoming Go 1.16 will. It's possible to use prereleases in the mean time. But Go 1.16 release is very close, I think, so maybe we just wait?

And for linux on ARM, looks like there are already `aws-vault-linux-arm64` binaries [in the releases](https://github.com/99designs/aws-vault/releases).

**Comment by nvanheuverzwijn** [comment]
Sure, waiting for go 1.16 makes a lot of sense. It's going to take a while before macos arm gets more adoption.
