### ISSUE TITLE
Frequently prompted for password twice

### ISSUE THREAD

**Issue by kevinburkeomg** [99designs/aws-vault#267]
If I run e.g. "aws-vault exec profile -- env", I'll get prompted for the password once using the short dialog, and then immediately prompted again with a second message about how Mac can't trust the aws-vault binary.

The second dialog:

> aws-vault wants to use your confidential information stored in "aws-vault session for profile" in your keychain.
> The authenticity of "aws-vault" cannot be verified. To allow this, enter the "aws-vault" keychain password

Followed by "Always Allow", "Deny", "Allow." Clicking "Always Allow" does nothing.

Is there a way to get exactly one prompt when I start a new aws-vault session?

**Comment by kevinburkeomg** [comment]
What's even odder is I've just now realized I can click "Deny" at the second prompt and the operation still proceeds. I'm running `tip` of both Go and aws-vault.

**Comment by bracki** [comment]
I believe this to be a duplicate of #219.

**Comment by kevinburkeomg** [comment]
Ah, correct!

**Comment by lox** [comment]
@kevinburkeomg can you try signing your binary with https://github.com/99designs/aws-vault#self-signing-your-binary? I'm interested if it changes your ability to select "always trust"
