### ISSUE TITLE
aws-vault exec can not successfully run with eval

### ISSUE THREAD

**Issue by chrisLeeTW** [99designs/aws-vault#270]
`aws-vault --version` : `v4.2.1`
`OS` : `Mac High Sierra 10.13.6`
`Shell` : `zsh 5.5.1 (x86_64-apple-darwin17.5.0)`

Problem : 
execute command `aws-vault exec my_profile -- eval date`

Result :
`aws-vault: error: exec: "eval": executable file not found in $PATH`

**Comment by chrisLeeTW** [comment]
Ok, I found out that eval is shell built-in command, can not directly exec with `exec.Command` in Golang, so workaround is `aws-vault exec my_profile -- bash -c 'eval date'`, but I can execute this command successfully before, strange :)

**Comment by RoniFinTech** [comment]
installing `awscli` helped me with the same error...
