### ISSUE TITLE
Cannot find the aws-keychain in OSX Keychain Access

### ISSUE THREAD

**Issue by nitrocode** [99designs/aws-vault#276]
Hi. I'm using OSX and I cannot find the aws vault password on Keychain Access to change my password.

Instead (in case it helps anyone) I found it in this location

    ~/Library/Keychains/aws-vault.keychain-db

and change my password using this - note the prefixed space so the command is not stored in your history

     security set-keychain-password -o oldpwd -p newpwd ~/Library/Keychains/aws-vault.keychain-db

It might be good to document this in the `README.md` or similar file.

**Comment by dominics** [comment]
Better to just not specify either new or old password when changing password with that command, and you'll be prompted interactively:

```
security set-keychain-password ~/Library/Keychains/aws-vault.keychain-db
Old Password: XXXXXXX
New Password: XXXXXXX
Retype New Password: XXXXXXX
```

(A space might prevent your command being saved in your shell history, but it doesn't stop `ps` showing it.)

**Comment by nitrocode** [comment]
That's a very good point. Only reason I had to figure it out from the command line is that I couldn't find the keychain in the UI. I guess Apple doesn't search `~/Library/Keychains` directory automatically so I thought it would be easier to just add the keychain.

```
✗ security list-keychains -s `security list-keychains | xargs` ~/Library/Keychains
✗ security list-keychains
    "/Users/rbhatia/Library/Keychains/aws-vault.keychain-db"
    "/Users/rbhatia/Library/Keychains"
    "/Library/Keychains/System.keychain"
```

Source: https://apple.stackexchange.com/a/321280

**Comment by nitrocode** [comment]
That's a very good point. Only reason I had to figure it out from the command line is that I couldn't find the keychain in the UI. I guess Apple doesn't search `~/Library/Keychains` directory automatically so I thought it would be easier to just add the keychain.

```
✗ security list-keychains -s `security list-keychains | xargs` ~/Library/Keychains
✗ security list-keychains
    "/Users/user/Library/Keychains/aws-vault.keychain-db"
    "/Users/user/Library/Keychains"
    "/Library/Keychains/System.keychain"
```

Source: https://apple.stackexchange.com/a/321280
