### ISSUE TITLE
`eb-cli` credentials override aws-vault profile

### ISSUE THREAD

**Issue by emhoracek** [99designs/aws-vault#280]
Started using aws-vault today and was following some instructions that had already worked for a coworker.  `aws-vault exec profile-name -- (command to create keypair)` works fine. I am happy. I go on to to run commands to create an Elastic Beanstalk app and environment with the same profile. I look in the account -- no app! But the commands ran successfully. With a sinking feeling, I start looking through the other accounts I have access to, and finally find the app I just made in a seemingly arbitrary (client!) account. Oddly, the keypair I created before the Beanstalk app is the correct account. I used the same `aws-vault exec profile-name` prefix for all three commands. What?! 

Finally I noticed in my credentials file I have a credential for `eb-cli` which seems to be the profile that is used if you don't specify a profile with `eb` commands. After deleting that credential and rerunning the `eb` command using `aws-vault exec profile-name`, the app was created in the correct account. 

Not sure this is a bug, but you may want to note in the README that this can happen.

**Comment by FernandoMiguel** [comment]
That's your cli tool that stupidly saves the STS token to file.
I've seen other apps do that, and it's a terrible security practice.
I can't offer a solution.
You could use an hammer and touch the file with a different user preventing
it from being updated with the wrong cached creds

--
Fernando Miguel

**Comment by lox** [comment]
> So, I think as long as users specify a profile with --profile, they shouldn't run into this problem.

Do you mean `--profile` to `eb-cli`? Even if you give aws-vault a profile, the subprocess won't have one set in the environment. You'll need to specifically give `eb-cli` a profile of `default` for it to work with `aws-vault`.

**Comment by lox** [comment]
I actually kind of like the idea of making `~/.aws/credentials` unwriteable.

**Comment by FernandoMiguel** [comment]
The number of times I had to go debug devs issues and find out they had a
credentials file, is astounding

--
Fernando Miguel

**Comment by lox** [comment]
Perhaps we should show a warning in aws-vault if that file exists? There are very few scenarios where it will be intended.

**Comment by FernandoMiguel** [comment]
I never thought of that, and now I love that idea.

I would even consider a more radical approach, and ask the user if they
wish to destroy the file during aws-vault add
But I do understand that would be a dangerous move.

--
Fernando Miguel

**Comment by lox** [comment]
I've always wanted an `aws-vault import` that could import credentials, but that is another story :)

**Comment by emhoracek** [comment]
> Perhaps we should show a warning in aws-vault if that file exists? There are very few scenarios where it will be intended.

@lox I also like this idea. Basically all I wanted out of this issue personally was an assurance that other ignorant users in my position in the future will be warned. :joy:

**Comment by lox** [comment]
Noted, and this will remain a shining beacon for future `eb-cli` users. Beware ye who enter here!
