### ISSUE TITLE
Reporting age of credentials

### ISSUE THREAD

**Issue by philpennock** [99designs/aws-vault#287]
I've implemented support for reporting the age of credentials, but it's a coordinated change across three repos, two belonging to 99designs, and I want to know if there's any interest in this feature before I start trying to get the first bits upstreamed ( @keybase `go-keychain` repo).

In `aws-vault` I implement an `info` CLI command, which can report metadata about a credential without the credential itself.  For my use-case (report age of creds in shell prompt) it's critical that this happen without prompting for secrets.  It relies upon adding to `99designs/keyring` a `GetMetadata` method.

Because the `99designs/keyring` repo has a File backend, this means about the only stuff safely available is timestamps.  Folks might not appreciate us choosing to deliberately "leak" some fields into xattrs on files to store more, so I've stuck to just the modification time.  This also means I'm not trying to get real accurate data on credential age from AWS.  Since `aws-vault` doesn't validate credentials or talk to AWS on `add`, changing that would suddenly require that people be online when adding creds, which I'm hesitant to change without discussion first.  (Eg, folks might be retrieving the secrets the first time on a secured network).

Thus the "credential age" is really "rotation time, as long as `aws-vault` did the rotation, else the time the creds were given to us".  It's a sufficient proxy for me, since I rotate credentials early after adding them.  But this is another reason this feature might not be welcome.

I have so far only implemented `.GetMetadata()` for Keychain and File.  I can take a look at the Linux-only backends if the maintainers want this to move forward.

Finally, I modify `keybase/go-keychain` to be able to return the `CreationTime` and `ModificationTime` from entries in keychain.  This requires a Go 1.10 or newer compiler, which should be okay now that Go 1.11 is out.  The reason is that `CFDateRef` stuff inside CoreFoundation does Interesting Things with pointer values, prompting the `uintptr` changes in Go 1.10 referenced at https://golang.org/doc/go1.10#cgo and making it impossible to safely reference the dates in Go 1.9 or earlier.  Since `go-keychain` already has a split implementation for 1.10+ or pre1.10 I just implemented the new logic in the 1.10 code.  Thus with this change, `99designs/keyring` becomes dependent upon Go 1.10 or newer to build.

Oh, and it's my first time ever touching the CF macOS coding, but it all seems to work and was simple/formulaic; I don't think there are any new security issues there.

That's a lot of caveats, so before I start working on upstreaming, is there interest?

```
% ./aws-vault info --help
usage: aws-vault info [<flags>] <profile>

Reports information about the given profile

Flags:
      --help                  Show context-sensitive help (also try --help-long and --help-man).
      --version               Show application version.
      --debug                 Show debugging output
      --backend=BACKEND       Secret backend to use [keychain file]
      --prompt=terminal       Prompt driver to use [terminal osascript]
      --keychain="aws-vault"  Name of macOS keychain to use, if it doesn't exist it will be created
  -a, --age                   Report the age of the credentials
  -r, --rotated-time          Report when the credentials were last modified (rotated)
  -V, --values-only           Skip keys, just show values
  -s, --seconds               Report timestamps in Unix epoch seconds, durations in seconds

Args:
  <profile>  Name of the profile
```

and:

```
% ./aws-vault info pennocktech-packer
rotated-time: 2018-07-05T21:00:43Z
age: 61 days

% ./aws-vault info spodhuis
rotated-time: 2018-09-04T19:39:51Z
age: 5 hours

% ./aws-vault info -aVs pennocktech-packer
5284898
```

**Comment by mtibben** [comment]
Sure thing @philpennock, PRs are certainly welcome

**Comment by lox** [comment]
I'm pretty keen on this too @philpennock, I've wanted for ages to show a warning on exec when your credentials are too old. Let me know how I can help wrangle PR's through the other repos too.

**Comment by philpennock** [comment]
Step 1: https://github.com/keybase/go-keychain/pull/33 needs to be merged.  That's on the Keybase folks; I went ahead and filed the PR two weeks ago, they've responded in a positive light on the PR but unhappy at the Go 1.10 dependency.  But it's a hard dep, the types here are the reason for the Go 1.10 breaking changes for macOS library stuff.

Steps 2 and 3 are much more subjective and you might have better ways of handling them, but consider this a baseline proposal which works.  For both of these, there are vendored dependencies which are _not_ part of the PRs and which would need to be updated.  For `keyring`, the vendored `go-keychain` and for `aws-vault`, the vendored `keyring`.

Step 2: https://github.com/99designs/keyring/pull/26

Step 3: https://github.com/99designs/aws-vault/pull/290

<img width="631" alt="screen shot 2018-09-22 at 20 08 00" src="https://user-images.githubusercontent.com/559098/45922772-3dc3f800-bea3-11e8-9e26-337b9387e22e.png">

The green `17D` in the prompt there is the age of the AWS credentials used for my Packer setup.

The zsh logic for setting that in my prompt is over at https://github.com/philpennock/zsh-functions/blob/master/functions/prompt_pdp_setup#L320-L368

(My zsh usage predates oh-my-zsh and friends and I've never made the switch; this is a native zsh themeable prompt; instructions in that repo's README)
