### ISSUE TITLE
Ignore plugins and/or other keys in ~/.aws/config

### ISSUE THREAD

**Issue by nitrocode** [99designs/aws-vault#293]
In awscli, there is a concept of plugins where developers can add cli commands and add subcommands ([awscli-console-login](https://github.com/shiftgig/awscli-console-login), [awshelloworld](https://github.com/nitrocode/aws-cli-plugins), etc). To do this, the developer or user of the plugin has to install the plugin via pip and tell amazon to use the plugin by running the following

    aws configure set plugins.helloworld awshelloworld

Which will append the following to `~/.aws/config`

```
[plugins]
helloworld = awshelloworld
```

This will then return the `plugins` key as a profile
```
$ aws-vault list | tail -n+4 | awk '{ print $1; }'
dev
prod
plugins
```

aws-vault should ignore this particular key and / or have the flexibility to ignore a number of keys through a configuration file (similar to https://github.com/99designs/aws-vault/issues/229).

**Comment by nitrocode** [comment]
Un-stale

**Comment by nitrocode** [comment]
Un-stale

**Comment by mtibben** [comment]
This issue was resolved some time back in v5
