### ISSUE TITLE
Use vault profile aliases (not shell aliases) to reuse the same session

### ISSUE THREAD

**Issue by nitrocode** [99designs/aws-vault#294]
I do a lot of terraform and use aws-vault. Each time I terraform, I have to run a command similar to this

    aws-vault exec dev -- terraform init

which is used in an easy function

```
function avt {
  profile=$1; shift
  aws-vault exec $profile -- /usr/local/bin/terraform "$@";
}
```

to make the function easier to run

    avt dev init

My directory structure is most often like this

```
✗ tree
.
├── env1
│   └── main.tf
├── env2
│   └── main.tf
└── env3
    └── main.tf
```

Our `dev` credentials work with `env1`, `env2`, and `env3` but not for other environments. So I'd like to update our `avt` function above so we can omit the credentials

```
function avt {
  profile=$1; shift
  if [ -z "$profile" ] && profile=$(basename $(pwd));
  aws-vault exec $profile -- /usr/local/bin/terraform "$@";
}
```

now allows us to run this in each environment directory because it grabs the directory name. 

```
avt init
```

This can only work if `env1`, `env2`, and `env3` are all the same as our dev profile in aws-vault or somehow aliased.

My workaround is to add more code to the shell script. If it sees that it's in `env1` or 2 or 3 it will use the `dev` profile, if 4 or 5, it will use the `prod` profile, etc.

**Comment by pda** [comment]
If `dev` is an assumable roles you could pretty easily duplicate the `dev` profile in `~/.aws/config` a few times, naming the copies `env1`, `env2` etc.
If you're using stored IAM user credentials it'd be more awkward, you'd have to store the credentials multiple times.

I don' think there's anything `aws-vault` can/should change on this front.

**Comment by nitrocode** [comment]
@pda if I do that, I'll have to repeat my login for each environment and if I login to `env1` and then `env2`, I'll lose the `env1` credentials since each environment is for the same account. 

The only workaround I can see is to edit my bash function to use my `dev` profile when I want to use terraform for a particular list of environments.

**Comment by nitrocode** [comment]
@FernandoMiguel that's brilliant. We're slowly transitioning to this but in the interim I'm still using the above. Aliases would still be nice to have and probably won't cost too much in LoC.

**Comment by FernandoMiguel** [comment]
Glad you are heading in a direction that fixes your issue
