### ISSUE TITLE
Prompt does not ask for MFA token when is required to rotate credentials

### ISSUE THREAD

**Issue by next-victorperez** [99designs/aws-vault#298]
```
$ aws-vault --version
v4.4.1-3-g0cd0697
$ aws-vault rotate profile
Rotating credentials for profile "profile" (takes 10-20 seconds)
Enter passphrase to unlock /home/xxxxx/: 
aws-vault: error: Failed to get credentials for profile: AccessDenied: User: arn:aws:iam::xxxxxxxx:user/xxxxxxxxx is not authorized to perform: iam:CreateAccessKey on resource: user xxxxxxxxx with an explicit deny
	status code: 403, request id: xxxxxxxxxxxxxxx
```
My profile ~/.aws/config:

```
[default]
output=json
region=eu-west-1

[profile profile]
mfa_serial=arn:aws:iam::xxxxxxxxxxx:mfa/xxxxxxxxxxx
```

**Comment by frezbo** [comment]
@beeva-victorperez I wonder if it's with the backend, I use the system keyting, BTW I'm on my own fork.

**Comment by beeva-victorperez** [comment]
I'm using "file" as backend. I dont think that the backend is the problem because it works with v4.3.0

**Comment by nexeck** [comment]
Same error for me again. It works with v4.3.0 and stopped working with the current version

**Comment by nexeck** [comment]
Any updates on this?

**Comment by drsolaris** [comment]
Bump! This is a big issue for us.

**Comment by mtibben** [comment]
Does this issue still exist on v4.6.2?

**Comment by AlainODea** [comment]
This issue is fixed in v4.6.3.

**Caveat**: A `brew upgrade` didn't update it. I had to `brew cask reinstall aws-vault` to get the new version.

**Comment by rsslldnphy** [comment]
Running into this issue with 4.6.4 too unless i'm misunderstanding something? Can't rotate credentials when mfa is enforced.

**Comment by nexeck** [comment]
Works for me with 4.6.4

```aws-vault rotate XXXXX
Rotating credentials for profile "XXXXX" (takes 10-20 seconds)
Enter token for arn:aws:iam::XXXXXX:mfa/XXXXXXX: XXXXXX
Done!```

**Comment by rsslldnphy** [comment]
Ah, figured it out! I had `mfa_serial     = arn:aws:iam::xxxxxxxxxxxx:mfa/russell` in my `~/.aws/credentials`, not `~/.aws/config`. Thanks!

**Comment by FernandoMiguel** [comment]
@rsslldnphy delete your credentials file. It shouldn't exist

**Comment by rsslldnphy** [comment]
@FernandoMiguel 👍 it's a hangover from before i was using `aws-vault`. no credentials in it, but my misunderstanding was that the "direct" login configuration was kept in there, while `~/.aws/config` was just for profiles to assume. realise that's not correct now.
