### ISSUE TITLE
Automatically retrieve the account id for the mfa_serial

### ISSUE THREAD

**Issue by keymon** [99designs/aws-vault#301]
The mfa serial for an account is usually in the same account and can be retrieved from the current base user using `aws sts get-caller-identity`:

```
$ aws sts get-caller-identity
{
    "Account": "1234567890123", 
    "UserId": "AAAAAAAAAAAAAAAAA", 
    "Arn": "arn:aws:iam::1234567890123:user/jhon"
}

```

We could allow set `mfa_serial=auto` and allow automatically get the serial id

**Comment by frezbo** [comment]
@keymon This idea is cool, but it would break any other AWS sdk client that uses the `aws/config` file. This could be supported if AWS supports it. Moreover the `get-caller-identity` will not work with a session token.

**Comment by frezbo** [comment]
@keymon  No it will not work with a session token, unless authenticated via MFA (you must have `mfa_serial` set). Do we really want to move away from AWS standard?

**Comment by keymon** [comment]
> @keymon No it will not work with a session token, unless authenticated via MFA (you must have mfa_serial set).

I am confused about this, I think it is working for me:

```
$ aws-vault exec test -- env | grep AWS | sed 's/=.*/<redacted>/'
AWS_VAULT<redacted>
AWS_ACCESS_KEY_ID<redacted>
AWS_SECRET_ACCESS_KEY<redacted>
AWS_SESSION_TOKEN<redacted>
AWS_SECURITY_TOKEN<redacted>
$ aws-vault exec test -- aws sts get-caller-identity
{
    "Account": "111111111111", 
    "UserId": "AAAAAAAAAAAAAAAAAA", 
    "Arn": "arn:aws:iam::111111111111:user/jhon"
}
$ cat ~/.aws/config
[profile test]
```

> Do we really want to move away from AWS standard?

Just checking if you would consider something like that.

**Comment by frezbo** [comment]
Sorry I meant IAM operation. Try any IAM operation with MFA in a session token and that would fail.

**Comment by FernandoMiguel** [comment]
Given this is a static file, what do you expect to gain from auto guessing the mfa?

**Comment by frezbo** [comment]
I think why aws does not implement this auto detection is because sometimes we can set the mfa_serial where we assume a role using another profile as source. Eg:
```
[profile personal-ro]
region=us-east-1

[profile personal]
source_profile=personal-ro
role_arn=arn:aws:iam::<redacted>:role/admin-access
mfa_serial=arn:aws:iam::<redacted>:mfa/<redacted>```

Here if i run `sts get-caller-identity` for the `personal` profile it would return a very different set of data.

**Comment by keymon** [comment]
> but you still need the role, right?

I was talking about the MFA only, as the role is unrelated to the mfa. You can setup the mfa without having the role, you can set the role without setting the role (BTW, the documentation kinda implies that are tied)

But actually it is true in the same sense we could automate the generation of the role ARN because the same reasons.

**Comment by lox** [comment]
Going to close this one, because I want to avoid adding too many behaviours that aren't mirrored by the aws-cli.
