### ISSUE TITLE
Dashes in profile names break unexpectedly

### ISSUE THREAD

**Issue by joseph-wortmann** [99designs/aws-vault#308]
If you put a dash into your config profile name, aws-vault will fail stating `aws-vault: error: Failed to get credentials for quinovas (source profile for echostreams-dev): AccessDenied: Access denied`. Remove the dash or replace it with an underscore, and all is well.

I know it's a minor issue. I just happen to like dashes...

**Comment by FernandoMiguel** [comment]
Weird... I have several roles with dashes and haven't had this issue yet.
Then again, don't think I ever did it for the source profile, only roles

**Comment by lox** [comment]
All of my profiles have dashes, that won't be the problem I don't think! Can you show us an example of the config that breaks/unbreaks?

**Comment by joseph-wortmann** [comment]
First, thank you for a great tool. Should have said that earlier. I've already recommended it to a wider audience.

As to the break/un-break. The following works. But if you replace the `_` with a `-` then boom, you get the error above. Confirmed multiple times via trial and error.

Note - the role ARN is in a different account than the `quinovas` profile or the MFA ARN. That may be tickling something, may not...

`
[profile quinovas]
output=json
mfa_serial=arn:aws:iam::676696985827:mfa/jwortmann@quinovas.com
region=us-east-1

[profile echostreams_dev]
source_profile = quinovas
mfa_serial=arn:aws:iam::676696985827:mfa/jwortmann@quinovas.com
role_arn=arn:aws:iam::924634896298:role/administrator
region=us-east-1
`

**Comment by frezbo** [comment]
@joseph-wortmann you must be using an old version of aws-vault:

```
[profile personal-ro]
region=us-east-1

[profile personal]
source_profile=personal-ro
role_arn=arn:aws:iam::<redacted>:role/admin-access
mfa_serial=arn:aws:iam::<redactd>:mfa/<redacted>
```
I have roles that have `-` in them

**Comment by FernandoMiguel** [comment]
What I don't have is @ in my MFA.

**Comment by soerenmartius** [comment]
I am having the same issue, i am on version v4.5.1

**Comment by Developer2048** [comment]
Same issue here, on Ubuntu 18.04, installed via homebrew...
login to a profile doesn't worked, after changing dash to underscore it worked...
