### ISSUE TITLE
Using nested profiles / role assumptions

### ISSUE THREAD

**Issue by JonathanSerafini** [99designs/aws-vault#310]
I'm trying to assume a role using temporary credentials from an intermediate account and having some difficulty.

Out of the box, the CLI/SDK doesn't seem to natively support following nested `source_profile` entries and will only ever go one level down. However, `aws-vault` can be used to work around this limitation by using an intermediate step.

Specifically, I'm trying to do something like: 
~/.aws/config
```
[default]
region = us-east-1

[account1]
role_arn = arn...
source_profile = default

[account2]
credential_source = Environment
role_arn = arn...
```

This works in part, however vault will complain that "Failed to find credentials for profile "account2" in keyring".
```
aws-vault exec account1 -- aws sts assume-role --role-arn account2_role --role-session-name account2_name
# returns valid credentials
```

**Comment by PrivoAdam** [comment]
I have a similar issue with nested profiles with `aws-vault`, but have no issues with the standard CLI - `aws-cli/1.16.57 Python/2.7.15 Linux/4.18.7-200.fc28.x86_64 botocore/1.12.47`.

The only difference in my configuration is that `account2` would be:

```
[account2]
role_arn = arn..
source_profile = account1
```

While the standard CLI works, `aws-vault` outputs the following:
```
$ aws-vault --backend=secret-service --debug exec account2 -- aws s3 ls
2018/11/17 19:53:31 [keyring] Considering backends: [secret-service]
2018/11/17 19:53:31 Loading config file /home/adam/.aws/config
2018/11/17 19:53:31 Parsing config file /home/adam/.aws/config
2018/11/17 19:53:31 Looking for sessions for account2
2018/11/17 19:53:31 Looking up all keys in keyring
2018/11/17 19:53:31 Session not found in keyring for account2
2018/11/17 19:53:31 Looking up keyring for account1
2018/11/17 19:53:31 Failed to find credentials for profile "account1" in keyring
aws-vault: error: Failed to get credentials for account1 (source profile for account2): Invalid data in keyring: unexpected end of JSON input
```

I'll be keeping an eye on this as well.

**Comment by lox** [comment]
Is `credential_source` a thing? Perhaps we just need to support that?

**Comment by JonathanSerafini** [comment]
I suppose it depends on how close to the cli you want to stay...
Having aws-vault support the case where `source_profile` is a chained profile would provide the best user experience. However, this would stray from how the aws-cli works since it doesn't support chaining sources.
On the other hand if aws-vault learns to support `credentials_source` this example would work while remaining within the bounds of what the cli supports. 
As for the question, there's a bunch of different options for it in the [docs](https://docs.aws.amazon.com/cli/latest/topic/config-vars.html).
- Environment to pull source credentials from environment variables.
- Ec2InstanceMetadata to use the EC2 instance role as source credentials.
- EcsContainer to use the ECS container credentials as the source credentials.

**Comment by lox** [comment]
Either we need to support the same semantics as aws-cli or not use it's config file at all, IMO. I'd be strongly against offering differing semantics for `source_profile` with regards to chaining. My hope was that long-term tools like `aws-vault` would integrate seamlessly with aws-cli and the sdk's, which is looking more possible with things like https://github.com/99designs/aws-vault/pull/300 on the horizon.

**Comment by lox** [comment]
`credential_source` sounds like the ticket!

**Comment by lox** [comment]
@PrivoAdam I don't think your issue is related, sounds like you have corrupted credentials in your `account1` keychain? Could you find them and see and open a different issue?

**Comment by JonathanSerafini** [comment]
@lox I get that as well using the approach he presented ( i.e. via chaining ).

Based on the error message, I'd guess @PrivoAdam is running on a linux box ( the invalid JSON messages shows up when the profile wasn't found ). On Mac OSX, you get :
`The specified item could not be found in the keyring.`

Using `credential_source` would work if implemented, though it'll potentially require an middleware script to nest `aws-vault` invocations and unset AWS_VAULT in order to provide the environment variables to the second call. Totally doable, just not a great UX. 

I understand where you're coming from in regards to sticking to the CLI semantics and I think that it makes a lot of sense when integrating with the CLI. On the other hand, `aws-vault` is also extremely handy since it helps bridge the gap between up-to-date CLIs and the SDKs that are often lagging behind ( ex.: the JAVA SDK doesn't even support the named profiles in ~/.aws/config, let alone fancy schmancy things like `credential_source` or `credential_process` ).

**Comment by frezbo** [comment]
@lox +1 for supporting `credential_source` almost all never sdk's support that. We use this heavily where an application running on an ec2 assumes a rolebut using the `InstanceMetadata` as the sourc, which requires the `config` file to be set with `credential_source`. I will complete #300 one I'm back from vacation.

**Comment by PrivoAdam** [comment]
#300 will be a good fit for my day to day as well :+1:

**Comment by ldormoy** [comment]
@frezbo right now #300 is only about `credential_process`, right? Do you plan to also add support for `credential_source` in this PR?

**Comment by frezbo** [comment]
@ldormoy not in this PR, it can go in another one.

**Comment by word** [comment]
just in case someone is wondering how to do this using `credential_process` here's what works for me:

```

[profile main]
region = eu-west-1
duration_seconds = 3600
mfa_serial = arn:aws:iam::123456:mfa/user

[profile intermediate]
region = eu-west-1
role_arn = arn:aws:iam::123456789:role/MyRole
mfa_serial = arn:aws:iam::123456:mfa/user
source_profile = main
role_session_name = session
duration_seconds = 3600

[profile target]
region = eu-west-1
credential_process=aws-nested-assume-role -p intermediate -r arn:aws:iam::987654321:role/MyRole -s session
```

The credential script is here: https://gist.github.com/word/fc754fcd1773804e5222518c8c9980b9

**Comment by jeffora** [comment]
With #300 merged in, I feel like this could be handled by `aws-vault` if I could add "credentials" that included a role ARN and a source vault credential source. Then the AWS config file could simply specify the `credential_process` vault command:

```
$ aws-vault add account2 --credential-source account1 --role-arn arn:aws:iam::123456789:role/MyRole
```

```
[profile account2]
credential_process = aws-vault exec account2 --json
```

**Comment by jeffora** [comment]
I've managed to work around this for now with the following setup:

```ini
# master credentials stored in aws-vault via aws-vault add ...
[profile master]
mfa_serial = arn:aws:iam::12345678:mfa/user.name
credential_process = aws-vault exec work --json

# profile used by aws-vault
[profile master-child1]
source_profile = master
mfa_serial = arn:aws:iam::12345678:mfa/user.name
role_arn = arn:aws:iam::87654321:role/child1-role

[profile child1]
credential_process = aws-vault exec master-child1 --json
```

This means I can implicitly run `aws-vault` with one set of credentials for all roles, using `AWS_PROFILE=child1 aws s3 cp ...` etc. It will also work for non-cli processes too if the SDK supports the `credential_process`, which makes MFA via node SDK / terraform easier.
