### ISSUE TITLE
Streamlined credential import process

### ISSUE THREAD

**Issue by acdha** [99designs/aws-vault#311]
Right now, setting up a new profile requires copy-and-pasting multiple values. It'd be really nice if there was a way to do something like `aws-vault add newprofile ~/Downloads/credentials.csv` or, when migrating new users, even import all of the keys and remove them from `~/.aws/credentials`.

**Comment by bmangold** [comment]
@acdha There are two similar ways to achieve this:

1) Use the `--env` to read them:
```
AWS_ACCESS_KEY_ID=$KEY AWS_SECRET_ACCESS_KEY=$KEY2 aws-vault add --env newprofile
```

2) Use `coproc` (bash 4+)
```
#!/bin/bash
# bash 4 needed for coproc
coproc aws-vault add newprofile
sleep 2
echo >&${COPROC[1]} "AKIAJ000000000000000"
sleep 2
echo >&${COPROC[1]} "AKIAJ111111111111111"
wait $COPROC_PID
echo ""
```
(probably needs some tweaking for your use cases)

**Comment by acdha** [comment]
@bmangold The reason I was suggesting an official feature is that this is an activity almost everyone needs and a good UI would avoid common mistakes which have security impact: for example, I've seen people use something like your first form where they literally pasted in the key values without realizing that they'd be stored in the shell history or, once, even exposed them in the process command-line visible to other processes on the same system. If I was writing a wrapper I'd use the `--env` format but it'd be better to have it built-in rather than needing to distribute a separate utility.

**Comment by bmangold** [comment]
@acdha you are absolutely correct, the suggestions I provided are inadequate compared to what you have suggested, which would be much easier to work with.  I like the idea you have on adding the credentials to aws-vault , and then removing them from the .aws/credentials . That would go a long way for migrations and getting people to be more secure (tm) out of the box.
