### ISSUE TITLE
aws-vault exec intercepts long options

### ISSUE THREAD

**Issue by jottr** [99designs/aws-vault#317]
When passing a binary executed with  `aws-vault exec` long options, it seems that they are not properly passed to the executable:

```
$ aws-vault exec some_profile awless --format csv buckets                                                                                                                                                                          
aws-vault: error: unknown long flag '--format', try --help
``` 

As you can see in the above example, the `--format` flag should be passed to `awless` and not be consumed by `aws-vault`.

**Comment by frezbo** [comment]
@jottr  the execution is wrong, it should have been:

```
aws-vault exec some_profile -- awless --format csv buckets    
```

**Comment by jottr** [comment]
Maybe this should be added to `aws-vault exec --help`. 
I simply forgot that this using `--` was a requirement to separate the commands. 
I bet I'm not the first person who was stumped by this. 


For future reference, the double dash is documented in the [POSIX guidelines](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html#tag_12_02): 

> Guideline 10:
The first -- argument that is not an option-argument should be accepted as a delimiter indicating the end of options. Any following arguments should be treated as operands, even if they begin with the '-' character.

**Comment by frezbo** [comment]
Glad you got it fixed.
