### ISSUE TITLE
Brew install doesn't work with Linuxbrew because it's a cask

### ISSUE THREAD

**Issue by liamdawson** [99designs/aws-vault#324]
[Linuxbrew](https://github.com/Linuxbrew/brew) is now reaching beta support from Homebrew, so I'm attempting to build a cross-platform package suite as a test.

Unfortunately, Linuxbrew does _not_ support casks. Is there a reason this is installed as a cask (implying it's a GUI app) instead of a formula (which would work out of the box)?

**Comment by mtibben** [comment]
It's a cask because aws-vault is distributed as a code-signed binary on macOS. Code-signing is required to avoid keychain prompts
