### ISSUE TITLE
Issue listing users

### ISSUE THREAD

**Issue by ki0** [99designs/aws-vault#328]
Hi there,

> <@packer-templates>-<⎇ feature/base_box>-255-> aws --version
> aws-cli/1.16.90 Python/3.7.2 Darwin/17.7.0 botocore/1.12.80

> <@packer-templates>-<⎇ feature/base_box>-1-> aws-vault --version
> v4.4.1

Im trying to use aws cli to list users and i get this error:

`aws-vault exec frodriguez -- aws iam list-users --no-paginate`

> An error occurred (InvalidClientTokenId) when calling the ListUsers operation: The security token included in the request is invalid

It seems a bug, because if i use the credentials writing them in ~/.aws/credentials, it works.

Cheers.

**Comment by frezbo** [comment]
@ki0 This is not a bug, AWS denies any IAM operation unless authenticated by MFA when using session credentials. Below example shows this clearly:

```
$ aws-vault exec devops -- aws iam list-users

An error occurred (InvalidClientTokenId) when calling the ListUsers operation: The security token included in the request is invalid
$ aws-vault exec product -- aws iam list-users
Enter token for arn:aws:iam::<redacted>:mfa/<redacted>: 440763
{
    "Users": [
        {
```

My **~/.aws/config** file:

```
[profile product]
region=us-east-1
mfa_serial=arn:aws:iam::<redacted>:mfa/<redacted>

[profile devops]
region=us-east-1
```
