### ISSUE TITLE
Assuming multiple accounts requires a fresh TOTP code per account

### ISSUE THREAD

**Issue by danopia** [99designs/aws-vault#329]
Hey! I have dozens of AWS accounts. I noticed that each time I run a command under a new profile, I'm asked for the master account's TOTP again. 

```
~ $ aws-vault exec tenantA-preview aws s3 ls > /dev/null
Enter token for arn:aws:iam::redacted:mfa/danopia@redacted: 

~ $ aws-vault exec tenantA-staging aws s3 ls > /dev/null
Enter token for arn:aws:iam::redacted:mfa/danopia@redacted: 

~ $ aws-vault exec tenantA-prod aws s3 ls > /dev/null
Enter token for arn:aws:iam::redacted:mfa/danopia@redacted: 

~ $ aws-vault list
Profile                  Credentials              Sessions                 
=======                  ===========              ========                 
master                   master                                            
tenantA-preview          master                   1547835608               
tenantA-staging          master                   1547833543               
tenantA-prod             master                   1547834295               
tenantB-preview          master                                            
tenantB-staging          master                                            
tenantB-prod             master                                            
tenantC-preview          master                                            
tenantC-staging          master                                            
tenantC-prod             master                                            
[...]
```

Surely there's some way to cache the master account's TOTP session? The master doesn't seem to have a session created, it's like every profile starts over. When using the AWS Console site you only have to TOTP once per day and then you can freely assume whatever role you like during that 24-hour period.

Re-entering TOTP each time isn't just an annoyance, it also means that you can only assume one new role per 30-second period, as TOTP codes are not reusable.

**Comment by nielslaukens** [comment]
Technically, aws-vault should create (and cache) a session for the `master` account (the source profile), *with* MFA; and use this session to perform the AssumeRole call.

**Comment by lox** [comment]
Is it possible to assume roles with session credentials? I recall it wasn’t when I built aws-vault, which is why it’s the way it is. Agree it would be a good change if possible. I’m skeptical though!

**Comment by nielslaukens** [comment]
I'm pretty sure it is. I use it on a daily basis!

API calls to make:
1. `sts::GetSessionToken(SerialNumber, Token)` with credentials from `.aws/credentials` (or KeyChain)
2. `sts::AssumeRole(RoleArn, RoleSessionName)` with the credentials returned from the call above.

If you cache the result from step 1, you can call step 2 multiple times for different roles without re-entering an MFA code.

**Comment by lox** [comment]
Hmmm, I thought that is what we do. We cache “sessions”. Will investigate.

**Comment by nielslaukens** [comment]
Yes, you do cache sessions. The difference is to already include the MFA token in the GetSessionToken call, instead of providing it in the AssumeRole call. The latter approach requires a new OTP token on every AssumeRole; the first approach requires only one OTP per session, and allows you to AssumeRole as much as you want.
