### ISSUE TITLE
Add logging for when the server component returns a 404

### ISSUE THREAD

**Issue by williamdenton** [99designs/aws-vault#330]
There are many cases server mode does not support. Its core business is dealing with authentication after all, not the full metadata available in ec2.

However when using aws sdks, if a metadata calls fails it can cause odd behaviour (as some sdks have fall back behaviour if metadata isn't available). This can make some issues hard to debug.

It would be useful if there was a 404 handler in the server component that simply logged that the request could not be handled. This could hopefully cut down the amount of time spent debugging issues. 

`--debug` adds additional logging to successful requests, but doesn't cover 404s

**Comment by mtibben** [comment]
http logging is implemented in v6
