### ISSUE TITLE
Use aws-vault with terraform_remote_state resources in different account

### ISSUE THREAD

**Issue by mxmxx** [99designs/aws-vault#334]
I came across `aws-vault` because I was looking for a way to use MFA-enabled, cross-account roles with Terraform.

I'm using an IAM user in a "master" account that has perms to switch roles into child accounts to deploy Terraform.

`aws-vault` works great until I have a `terraform_remote_state` resource in my template. For example:

```
terraform {
  backend "s3" {
    key                = "my-state.tfstate"
    bucket             = "terraform-bucket1"
    dynamodb_table     = "terraform-state-locking"
    region             = "us-east-1"
    profile            = "my_profile"
    role_arn           = "arn:aws:iam::123456789:role/my_role"
  }
}

provider "aws" {
  profile             = "${var.my_profile}"
  region              = "us-east-1"

  assume_role {
    role_arn          = "arn:aws:iam::987654321:role/my_role"
    session_name      = "terraform"
  }
}

# Remote state

data "terraform_remote_state" "other_state" {
  backend            = "s3"
  workspace          = "${var.other_workspace}"

  config {
    bucket           = "terraform-${var.other_account_id}"
    key              = "${var.other_data_key}"
    dynamodb_table   = "terraform-state-locking"
    region           = "us-east-1"
    profile          = "${var.my_profile}"
    role_arn         = "arn:aws:iam::${var.other_account_id}:role/my_role"
  }
}
```
If I wrap my Terraform command in `aws-vault exec $my_profile --no-session -- terraform refresh`, I'm prompted for MFA. That succeeds, it begins to refresh the state, but then errors when it reaches the `terraform_remote_state` resource:

```
Error: Error refreshing state: 1 error(s) occurred:

* data.terraform_remote_state.other_state: 1 error(s) occurred:

* data.terraform_remote_state.other_state: data.terraform_remote_state.other_state: error initializing backend: The role "arn:aws:iam::*redacted*:role/my_role" cannot be assumed.

  There are a number of possible causes of this - the most common are:
    * The credentials used in order to assume the role are invalid
    * The credentials do not have appropriate permission to assume the role
    * The role ARN is not valid
```

My config, profiles, roles, etc. are set up correctly and work as expected with Terraform if the MFA condition on the roles is `false`. However, MFA condition of `true` is now required on all of my cross-account roles.

It appears the temporary creds are being used to assume the role for the `terraform_remote_state` resource? I use remote states in many of my templates; am I missing the correct way to do this or is this use case just not supported by `aws-vault`?

**Comment by FernandoMiguel** [comment]
I can look into this with more detail tomorrow, but one quick question :
Why are you running with no session?

**Comment by FernandoMiguel** [comment]
Is the role you assume with aws vault able to assume the role of the remote state "arn:aws:iam::${var.other_account_id}:role/my_role"?
Ie, if you add that role to your aws config, with your primary iam role as source, can you assume that role?

**Comment by mxmxx** [comment]
Thanks, @FernandoMiguel . I was running into permission denied issues only when assuming a role that had MFA enabled. By adding `no-session` I was prompted for my MFA token as expected..

The role that I assume with aws-vault is able to assume the role `arn:aws:iam::${var.other_account_id}:role/my_role"`. I can successfully assume the role for that account if I `exec` against it as well (rather than assuming via the `terraform_remote_state`).

Sorry for lack of output or my config, I can update tomorrow.

**Comment by mxmxx** [comment]
@FernandoMiguel, below is an example of my `~/.aws/config`:

```
Profile                  Credentials              Sessions
=======                  ===========              ========
qa                                       work                      -
dev                                     work                      -
prd                                      work                      -
staging                               work                      -
work                                   work                      -
```

My "work" or primary credentials are used to assume each of the profiles I have configured. If I execute  an `exec` against any of these, it works. In my terraform code, the two roles I'm dealing with are for staging and qa. 

So the "qa" role is the role I'm trying to assume in my `terraform_remote_state` above that fails.

If I exec against it directly, I'm successful:

```
aws-vault exec qa -- aws s3 ls  ✔  9009  09:33:40
Enter token for arn:aws:iam::************:mfa/mxmxx: 
2018-09-25 10:26:41 events
2018-09-25 10:26:50 stats
2019-01-02 13:42:16 beats-data
...
...
...
```

**Comment by FernandoMiguel** [comment]
Man, we are in terrible timezones to support each other ahha
I'm just commuting home, and mobile. 
Let me take a look at the original issue once again and see if I can decipher anything. 
Cross account can be very tricky. 

I assume your QA bucket allows the role running terraform
And that that role also has a policy that allows it to access/get a cross account bucket, right? 

Unless they are all under the same account, and in that case I'm more confused

**Comment by FernandoMiguel** [comment]
Also, not entirely sure if you are missing a provider alias here

**Comment by FernandoMiguel** [comment]
What I tend to do, is have a common account create the bucket, and then different terraform state/providers write to that bucket and set the acl to allow others to read it
I can past a snip if that helps, but would be a significant change from your current code base

**Comment by FernandoMiguel** [comment]
Yeah not entirely sure the remote data takes a provider
By having the role there, the base role, assumes that role and retrieves the data 

Maybe run 
'TF_LOG=DEBUG terraform apply'
May give you give better hints 

I know I spent a bit of time last week on a similar case, but it was an override missing. 

Don't want to sound insistant, but it sounds like a bucket permission more than anything.
And if clearly should not be an aws vault issue. 

Feel free to poke me on one of the many aws/terraform/aws-vault slacks, like hangops

**Comment by mxmxx** [comment]
Thanks @FernandoMiguel. 

I didn't have any policy in place on the QA bucket, so I've added one that I *think* should allow access to the role running terraform:

```
{
    "Version": "2012-10-17",
    "Id": "Policy1538870206203",
    "Statement": [
        {
            "Sid": "thisismysid",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::************:root"
            },
            "Action": "s3:*",
            "Resource": [
                "arn:aws:s3:::qa-bucket",
                "arn:aws:s3:::qa-bucket/*"
            ]
        }
    ]
}
```

Still no success. It errors when trying to assume the role in the `terraform_remote_state` block: 

```
Releasing state lock. This may take a few moments...

Error: Error refreshing state: 1 error(s) occurred:

* data.terraform_remote_state.other_state: 1 error(s) occurred:

* data.terraform_remote_state.other_state: data.terraform_remote_state.other_state: error initializing backend: The role "arn:aws:iam::************:role/my_role" cannot be assumed.

  There are a number of possible causes of this - the most common are:
    * The credentials used in order to assume the role are invalid
    * The credentials do not have appropriate permission to assume the role
    * The role ARN is not valid
```

Running `terraform refresh` without `aws-vault`, there is no issue refreshing the state.

**Comment by mxmxx** [comment]
Not sure if this helps at all, but here's logging from running `terraform refresh` only, which is successful:

```
# Assuming the first role

2019/01/30 13:04:55 [INFO] Attempting to AssumeRole arn:aws:iam::123456789:role/my_role (SessionName: "", ExternalId: "", Policy: "")
2019/01/30 13:04:55 [INFO] AWS Auth provider used: "SharedCredentialsProvider"
2019/01/30 13:04:55 [INFO] AWS Auth provider used: "AssumeRoleProvider"
2019/01/30 13:04:55 [INFO] Initializing DeviceFarm SDK connection
2019/01/30 13:04:58 [INFO] command: backend initialized: *s3.Backend

# Assuming the second role (in terraform_remote_state block)

2019/01/30 13:05:01 [INFO] Attempting to AssumeRole arn:aws:iam::987654321:role/my_role (SessionName: "", ExternalId: "", Policy: "")
2019/01/30 13:05:01 [INFO] AWS Auth provider used: "SharedCredentialsProvider"
2019/01/30 13:05:02 [INFO] AWS Auth provider used: "AssumeRoleProvider"
2019/01/30 13:05:02 [INFO] Initializing DeviceFarm SDK connection
```

Here's logging from when I execute `aws-vault exec $my_profile -- terraform refresh`, which fails to assume the role in the `terraform_remote_state` block:

```
## Assuming the first role

2019/01/30 13:11:55 [INFO] Attempting to AssumeRole arn:aws:iam::123456789:role/my_role (SessionName: "", ExternalId: "", Policy: "")
2019/01/30 13:11:55 [INFO] AWS Auth provider used: "EnvProvider"
2019/01/30 13:11:56 [INFO] AWS Auth provider used: "AssumeRoleProvider"
2019/01/30 13:11:56 [INFO] Initializing DeviceFarm SDK connection
2019/01/30 13:11:57 [INFO] command: backend initialized: *s3.Backend

## Assuming the second role (in terraform_remote_state_block)

2019/01/30 13:12:01 [INFO] Attempting to AssumeRole arn:aws:iam::987654321:role/my_role (SessionName: "", ExternalId: "", Policy: "")
2019/01/30 13:12:01 [INFO] AWS Auth provider used: "EnvProvider"
2019/01/30 13:12:01 [ERROR] root: eval: *terraform.EvalReadDataApply, err: data.terraform_remote_state.other_state: error initializing backend: The role "arn:aws:iam::987654321:role/my_role" cannot be assumed.

  There are a number of possible causes of this - the most common are:
    * The credentials used in order to assume the role are invalid
    * The credentials do not have appropriate permission to assume the role
    * The role ARN is not valid
2019/01/30 13:12:01 [ERROR] root: eval: *terraform.EvalSequence, err: data.terraform_remote_state.other_state: error initializing backend: The role "arn:aws:iam::987654321:role/my_role" cannot be assumed.

  There are a number of possible causes of this - the most common are:
    * The credentials used in order to assume the role are invalid
    * The credentials do not have appropriate permission to assume the role
    * The role ARN is not valid
2019/01/30 13:12:01 [TRACE] [walkRefresh] Exiting eval tree: data.terraform_remote_state.other_state
```

**Comment by FernandoMiguel** [comment]
Keep in mind the role that will access a bucket cross account, also needs a policy to allow it to access the bucket on another account. 

S3 and IAM are a bit weird given how old s3 service is.. 

Did debug help in any way?

**Comment by mxmxx** [comment]
Yep, understood. There is a policy that allows the role to access the bucket in the other account. This works fine with Terraform code in my original post if execute `terraform *` and don't use `aws-vault` to wrap it.

Debug was not so helpful unfortunately. It seems to attempt to assume the role in my `terraform_remote_state` and then just throws the same error:  `error initializing backend: The role "arn:aws:iam::987654321:role/my_role" cannot be assumed`.

Are you aware of use cases like mine where an `aws-vault exec` can be used to assume a role in `Account A` as well as `Account B`, when the role for `Account B` is defined in `terraform_remote_state`?

**Comment by FernandoMiguel** [comment]
Not sure i know something exactly like yours.
On my case, I do have cases where multiple running roles accessing a bucket 

I would like also have ec2/ecs tasks assuming roles that read states, but same account

**Comment by scalp42** [comment]
@mxmxx I'm running into the same issue. What did you end up doing on your end if you don't mind sharing?

I'm also seeing that the backend has issues in Terraform see:

- https://github.com/hashicorp/terraform/issues/20062
- https://github.com/hashicorp/terraform/issues/18402

Also related:
- https://github.com/hashicorp/terraform/issues/19482
- https://github.com/terraform-providers/terraform-provider-aws/issues/6566
- https://github.com/terraform-providers/terraform-provider-aws/issues/2420

**Comment by mxmxx** [comment]
@scalp42 Unfortunately, I'm still in the same boat with no progress made. Open to any workarounds :)

**Comment by jamroks** [comment]
@mxmxx  @scalp42 @FernandoMiguel 
Hey guys, i'm not sure at all since i haven't used aws-vault yet, as i was just poking around and reading, evaluating things as i usually do for any new cool tool that i intend to use/add to my toolchains...anyway 
i was wandering if your issue here might be related to the kmskey/dynamotable permissions : 
- Account A has a kmskey/dynamodb table for s3 backend .
- Account B (terraform_remote_state) define its own kmskey/dynamotable (i guess) 
i'm just asking myself does Account A has the right to use Account B (terraform_remote_state) kmskey/dynamotable ? isn't it necessary that it does ?

cheers

**Comment by davidcallen** [comment]
Not really wanting to re-open this ticket since is now classified as "stale" ...but can maybe help with the solution : 
I have the same workflow.  My solution is to aws-vault exec master_profile -- terraform apply
So you are "login" to the master account which you have IAM permissions to assume roles in account A and B. 
My terraform config is very similar except : 
1) no use of workspace (anywhere)
2) I dont have "profile  = "my_profile"" in backend "s3"
3) I dont have "session_name  = "terraform"" in provider "aws"

**Comment by EvanGertis** [comment]
@davidcallen  I am in the same situation.
