### ISSUE TITLE
boto3 script and profile switching

### ISSUE THREAD

**Issue by ismailyenigul** [99designs/aws-vault#337]
Hi,
I need a help to use aws-vault in boto3 codes.

when I create boto3 script I can use *.aws/credentials* file passing the profile and also I can switch from one to another profile easly:
```python session = boto3.Session(profile_name=my_aws_profile)```

If I want to use aws-vault, Should I  use env vars and call aws-vault everytime because credentials are saved in other place?

**Comment by FernandoMiguel** [comment]
just run aws-vault exec PROFILE -- python3 /PATH/YOUR_SCRIPT.py

**Comment by KursLabIgor** [comment]
no it doesnt work as mentioned above. OR need to perform another configuration of boto
```python 
botocore.exceptions.InvalidConfigError: The source_profile "terraform_dev" must specify either static credentials or an assume role configuration
```

**Comment by ryan-gerstenkorn-sp** [comment]
For anyone coming across this ticket because of the error below it seems this is caused by an old version of awscli (in my case ubuntu 18.04's default version). I believe this would apply to the SDK as well.

> The source_profile "terraform_dev" must specify either static credentials or an assume role configuration

**Comment by rossigee** [comment]
A dirty hack, in case it helps others finding this bug report to use `aws-vault` with boto...

```
  envvars = subprocess.check_output(['aws-vault', 'exec', aws_profile, '--', 'env'])
  for envline in envvars.split(b'\n'):
      line = envline.decode('utf8')
      eqpos = line.find('=')
      if eqpos < 4:
          continue
      k = line[0:eqpos]
      v = line[eqpos+1:]
      if k == 'AWS_ACCESS_KEY_ID':
        aws_access_key_id = v
      if k == 'AWS_SECRET_ACCESS_KEY':
        aws_secret_access_key = v
      if k == 'AWS_SESSION_TOKEN':
        aws_session_token = v

  session = boto3.Session(
    aws_access_key_id, aws_secret_access_key, aws_session_token
  )
```

**Comment by mjstevens777** [comment]
And in case it helps anyone else, the `export` command is a little cleaner

```python
import subprocess
import json
import boto3

def get_vault_session(aws_profile):
    aws_env_json = subprocess.check_output(['aws-vault', 'export', '--format=json', aws_profile])
    aws_env = json.loads(aws_env_json)
    return boto3.Session(
        aws_access_key_id=aws_env['AccessKeyId'],
        aws_secret_access_key=aws_env['SecretAccessKey'],
        aws_session_token=aws_env['SessionToken'],
    )
```
