### ISSUE TITLE
aws-vault server interface does not go up

### ISSUE THREAD

**Issue by codingtony** [99designs/aws-vault#338]
Sometimes when I start aws-vault exec -s profile the interface does not go up and I don't know how to debug.

```
uname -a
Linux tony-laptop 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
```
aws-vault --version
v4.5.1
```
```
aws-vault exec profile  -s --debug
2019/02/14 09:46:34 [keyring] Considering backends: [pass kwallet secret-service file]
2019/02/14 09:46:34 [keyring] Failed backend pass: The pass program is not available
2019/02/14 09:46:34 [keyring] Failed backend kwallet: The name org.kde.kwalletd was not provided by any .service files
2019/02/14 09:46:34 Loading config file /home/xxx/.aws/config
2019/02/14 09:46:34 Parsing config file /home/xxx/.aws/config
2019/02/14 09:46:34 Looking for sessions for xxxxx
2019/02/14 09:46:34 Looking up all keys in keyring
2019/02/14 09:46:34 Session "xxxxxx session (1550166412)" expires in 3h0m17.198639499s
2019/02/14 09:46:34 Using session ****************XANP, expires in 3h0m17.194314248s
2019/02/14 09:46:34 Assuming role arn:aws:iam::xxxxxxxx
2019/02/14 09:46:35 Using role ****************4Y57 (from session token), expires in 14m59.913790126s
2019/02/14 09:46:35 Starting `aws-vault server` as root in the background
2019/02/14 09:46:35 Local instance role server running on 127.0.0.1:9099
```

```
netstat -ltn | grep  169.254.169.254
# no result
```
After a little while I see : 
```
aws-vault: error: Server failed: exit status 2
```
But no other messages...

How can I debug this issue? Anything I can  I look for ?
Sometime it works...

**Comment by virgilwashere** [comment]
@codingtony I have a similar issue (#335).

I saw in the code, that `alias_linux.go` specifically tries to create a loopback interface alias on `lo:0`.  

Any chance you have a pre-existing interface configured there?

**Comment by codingtony** [comment]
I use MFA, and ithe aws-vault server crashes (probably at mfa renewal ?)
perhaps the interface still exists when I try to restart it. 

Can the code be more robust (detect that the alias is the same ip and recyle it) ?
Can the debug log be more explicit about the issue ?
Could the server run in foreground and re-ask for MFA ?
What is the best way to kill the alias on the local interface ?

**Comment by jinnko** [comment]
In the code the invocation of the server command is `sudo -b aws-vault server`.  When using `aws-vault exec --server ...` the output of the sub-command appears to be lost, so we're not seeing the following log output that we get when we run `sudo aws-vault server` directly:

```
$ sudo $(which aws-vault) server --debug
2019/08/12 13:44:33 [keyring] Considering backends: [secret-service kwallet pass file]
2019/08/12 13:46:33 [keyring] Failed backend secret-service: Failed to activate service 'org.freedesktop.secrets': timed out (service_start_timeout=120000ms)
2019/08/12 13:46:33 [keyring] Failed backend kwallet: Failed to execute program org.kde.kwalletd: No such file or directory
2019/08/12 13:46:33 [keyring] Failed backend pass: The pass program is not available
2019/08/12 13:46:33 Loading config file /home/jinn/.aws/config
2019/08/12 13:46:33 Parsing config file /home/jinn/.aws/config
aws-vault: error: Server failed: exit status 2

```

It appears the proxy process isn't starting because it's trying to find credentials and finds no backends for them, hence we get the `aws-vault: error: Server failed: exit status 2` after some time.

A workaround might be to use `pass` with the root user to make this work, but ultimately the credentials issue needs to be resolved.

**Comment by jinnko** [comment]
I believe we've narrowed this down as a problem on the master branch as installed with `go get ..`.  When we fall back to the `brew install` version the issue goes away.
