### ISSUE TITLE
github-vault

### ISSUE THREAD

**Issue by FernandoMiguel** [99designs/aws-vault#341]
Rather offtopic...
but, would anyone be interested to either implement on aws-vault of fork it to:
* manage long and short lived GitHub Personal Tokens?
* token rotation 
* multi profile support
* STS kinda tokens

**Comment by majormoses** [comment]
I don't think github has such a concept and I think to accomplish this we would be re-implementing a generic credential storage manager such as Hashicorp vault, AWS Parameter Store (SSM), etc which typically all support some kind of key rotation strategy. Also personal access tokens are specific to users so I am not sure that I would want a service managing (and exposing) a users credentials for others to be able to `(ab)use` outside of the context of the tool.
