### ISSUE TITLE
Allow multiple `exec`s to share credential server

### ISSUE THREAD

**Issue by Nuru** [99designs/aws-vault#345]
Similar to #222, I have a situation where I may want to run `aws-vault exec role --server sh` from multiple shells on the same host. This is currently not supported, but I would like it to be.

Currently, if you use the `--server` flag but the server is already running, it fails:
```
aws-vault: error: Failed to start credential server: listen tcp 127.0.0.1:9099: bind: address already in use
```
 I can sort of work around that by checking if the credential server is running and, if it is, setting up the new shell to use it, but that is not a real solution for 2 reasons:
1. I cannot be sure the credentials being served are for the same role I am trying to assume.
2. The credentials server will be stopped when the process that started it finished. 

What I would like is for the second `exec --server` to verify that the existing server is serving credentials for the same role and, if so, use that server. 

Allowing a stand-alone credential server as in #224 would solve the problem of keeping the credential server alive, but would still have the problem of `aws-vault exec role --server` failing even when the role was already active. So I see this as an important addition to #224 that would also be useful without it.

**Comment by sellers** [comment]
Since the "server" simulates the effect of an EC2 Metadata server, it would be hard to have this work in the contents of AWS commands and APIs.   They expect the credential provider to be in the standard provider chain.    (e.g. it opens up tcp4       0      0  169.254.169.254.80     *.*                    LISTEN      linked to :9090).  

I see this being akin to AWS ec2 metadata service supporting multiple profile roles on an EC2 instance.  This should be deferred until that functionality existing with AWS.

**Comment by Nuru** [comment]
@sellers I think you misunderstand my proposal. I am only proposing that a second attempt to start a credentials server _for the same credentials_ reuse the existing server.

**Comment by Nuru** [comment]
@sellers This might also help fix a current problem with`aws-vault`. Currently, when running Docker on Linux on an AWS instance, by default, the Alpine 3.9 containers I run have connectivity to the AWS meta-data server. When I then run `aws-vault --server` it fails. Apparently `aws-vault` sees the AWS meta-data server and thinks it is its own, so it does not start one, but the eventual command fails because it does not have the right credentials. Generally, "assume role" fails because the instance does not have a role. The solution to this is to simply run `aws-vault server` first, but that is undocumented now due to #208.

**Comment by lox** [comment]
I never fathomed that someone would want to run `aws-vault` on aws, would love to hear what you are using it for @Nuru

**Comment by Nuru** [comment]
@lox just because you are running in AWS doesn't mean you do not want to switch roles. See also, for example [Amazon WorkSpaces](https://aws.amazon.com/workspaces/).

**Comment by FernandoMiguel** [comment]
I thought the same @lox

@nuru wouldn't it be easier to have an instance role that allows you to STS to the other roles and deal with that at the application level?
