### ISSUE TITLE
Unable to run any command

### ISSUE THREAD

**Issue by KursLabIgor** [99designs/aws-vault#346]
I have ubuntu 18.04
aws-vault version v4.5.1
in case if i run 
`aws-vault exec dev aws s3 ls`
I got error
`aws-vault: error: Failed to get credentials for terraform (source profile for dev): Invalid data in keyring: unexpected end of JSON input`
No any extra configuration were done from my side. I just install and add user.

**Comment by FernandoMiguel** [comment]
what's in your ~/.aws/ ?
not sure if it is important, but i usually run with 
`aws-vault exec dev -- aws s3 ls`
those two dashes seem important

**Comment by KursLabIgor** [comment]
@FernandoMiguel dashes doesnt help. 
in ~./aws/config
`[profile terraform]
region=us-east-1
[profile dev]
source_profile = terraform
role_arn=arn:aws:iam::XX:role/XXX
external_id = XX`

**Comment by KursLabIgor** [comment]
Ha-ha solved it by deleting key store entirely. Add user again and now works fine. 
So seems like problem was in keystore from Ubuntu side.
