### ISSUE TITLE
Modularize vault portion so other apps can use aws-vault

### ISSUE THREAD

**Issue by nitrocode** [99designs/aws-vault#347]
I was using HashiCorp's VaultCLI today and realized that it's a pain to switch between vault authentications. There is no concept of profiles but you can run vault using `VAULT_TOKEN` prefixed to it. I was thinking if this app's vault portion of it was more modular, we could come up with many `*-vault` applications like

* vault-vault (HashiCorp vault - not the best name but w/e)
* lpass-vault (LastPass cli)
* etc

The params that would have to be configurable would be environment variable names, api endpoints, and probably a few other things but would love to have the same interface as `aws-vault`. What are some of your thoughts on this?

**Comment by lox** [comment]
That was basically the thinking behind extracting https://github.com/99designs/keyring, I suspect trying to create an abstraction at a higher level than that might end up being quite difficult, as it's very dependent on the exact semantics of the service.

**Comment by lox** [comment]
I'm going to close this one out, we don't have strong plans to make `aws-vault ` more modular beyond the `keyring` backend and possibly stronger SAML support at some point.
