### ISSUE TITLE
aws-vault generates federation tokens that are too long

### ISSUE THREAD

**Issue by chriskl** [99designs/aws-vault#350]
aws-vault uses my AWS login name as a token name, which fails:

`aws-vault: error: Failed to call GetFederationToken: ValidationError: 1 validation error detected: Value 'chris.kings-lynne@healthengine.com.au' at 'name' failed to satisfy constraint: Member must have length less than or equal to 32
	status code: 400, request id: acd94a85-4b7c-11e9-9d13-e98ee161f9e7
Login for non-assumed roles depends on permission to call sts:GetFederationToken`

Perhaps take a hash, or at least truncate the usename?

**Comment by mtibben** [comment]
Truncation seems simplest to me (assuming there are no risk of collisions). Looks like there might be [some other constraints](https://docs.aws.amazon.com/STS/latest/APIReference/API_GetFederationToken.html) too. 

PRs welcome!

**Comment by avinson** [comment]
@mtibben wdyt? https://github.com/99designs/aws-vault/pull/377

**Comment by avinson** [comment]
@mtibben thanks! if possible, I'd appreciate if you could do a new release soon to pick up this fix. cheers.
