### ISSUE TITLE
error: aws-vault sessions should be nested with care, unset $AWS_VAULT to force

### ISSUE THREAD

**Issue by jottr** [99designs/aws-vault#352]
I keep running into the following error message: 

`error: aws-vault sessions should be nested with care, unset $AWS_VAULT to force`

`aws-vault list` shows no active sessions. 
```
$ aws-vault --version
v4.5.1

$ aws-vault --keychain=login --backend=keychain --prompt=terminal exec production -- aws
aws-vault: error: aws-vault sessions should be nested with care, unset $AWS_VAULT to force

$ echo $AWS_VAULT # Returns nothing                                                                                                                 
```

**Comment by jottr** [comment]
[Found the culprit.](https://github.com/99designs/aws-vault/blob/master/USAGE.md#overriding-the-aws-cli-to-use-aws-vault)

**Comment by bitcoinbrisbane** [comment]
I fixed mine by `$ unset AWS_VAULT`

**Comment by boristyukin** [comment]
do you know why this needs to be done though? it is a workaround IMHO, not a solution. I had to do this as well, on the most recent version of aws-cli and aws-vault, using pass as a key store

**Comment by nitrocode** [comment]
The `unset $AWS_VAULT` didn't work for me.

I saw that I had a stale `aws-vault exec <profile> --server` running in the background since last week Friday. After killing using `kill -9` (which also killed my iterm), that allowed me to get around this issue. I also switched `--server` to `--ecs-server` and hoping that will auto refresh without having to kill it.

**Comment by adrian-huminiuc** [comment]
Just an FYI for google searches that land here. 
You might also get this error if you are trying to connect to a wrongly configured aws profile. (~/aws/config)
So double-check the aws profile you are trying to use and the configuration for it.

**Comment by shiva2021** [comment]
Type `exit` on your terminal and error will go away. Works for me everytime!

**Comment by tfrokt** [comment]
> Type `exit` on your terminal and error will go away. Works for me everytime!

is there any way to exit without typing `exit`? My vscode is smart enough to hide the terminal rather than exiting the vault session.
