### ISSUE TITLE
Providing config to prompt backend

### ISSUE THREAD

**Issue by viraptor** [99designs/aws-vault#354]
Hi, I'm looking at implementing an mfa prompt backend for yubikey and I've got 2 questions before digging myself in too deep.

1. Since this is the first backend where the key actually depends on the profile, I'd like to use a new entry in the config for at least one option. Unfortunately the `Profile` belongs to the vault, which means it would have to be extracted to avoid circular dependencies. This seems like a lot of rewriting all over the place - is there a better approach I could use here?

2. I could either implement a prompt specific to `ykman oath` command, or a generic `helper` prompt that takes a profile name and does whatever people want to. The generic one would require at least 2 config bits - the helper path and profile name.

3. The `prompt` seems to be only dispatched to backends for MFA and terminal is used directly for other entries. But should I really be using this for MFA only? Is this a point where prompt and mfa prompt dispatch should become explicitly different things?

(a no-refactor approach could be `ykman` specific prompt and passing just the profile name to the prompt, but that feels like bad special-casing)

Is there a preferred approach here?

**Comment by viraptor** [comment]
A trivial no-refactor implementation is available at https://github.com/viraptor/aws-vault/tree/ykman-prompt

**Comment by viraptor** [comment]
Ping @mtibben - are you interested in this getting finished?

**Comment by lox** [comment]
Sounds alright to me!

**Comment by Krenair** [comment]
On a related note, I would've quite liked the ability to configure (as a user) aws-vault to run an arbitrary program that can return the MFA code, just provided with some arguments e.g. serial. But my case is solved by the yubikey work.
