### ISSUE TITLE
Credentials mysteriously deleted

### ISSUE THREAD

**Issue by Nuru** [99designs/aws-vault#356]
My credentials were mysteriously deleted. Of course I suspect a bug in `aws-vault`.

aws-vault version: v4.4.1
OS: alpine 3.9.2

I added AWS keys for a new account:
```
aws-vault add --backend=file --add-config newprofile
```
I used the keys for a while, using the server
```
aws-vault exec --server --assume-role-ttl=1h --session-ttl=12h newprofile -- bash
```
After a while (one would guess an hour, but I'm not sure), I got this error message:
```
Error when retrieving credentials from iam-role: Credential refresh failed, response did not contain: access_key, secret_key, token, expiry_time
```
Unsurprisingly, this was followed by 
```
Unable to locate credentials. You can configure credentials by running "aws configure".
```
I then exited the `bash` shell and ran the  `aws-vault` command again. But this time:
```
aws-vault: error: Failed to get credentials for newprofile: The specified item could not be found in the keyring.
```
The credentials were gone. `~/.awsvault/keys/newprofile` was gone, and `aws-vault list` showed this (many other unrelated profiles omitted)
```
aws-vault list
Profile                     Credentials              Sessions                 
=======                     ===========              ========                 
default                     -                                                 
newprofile                  -                        1554418141   
```

This seems to happen pretty reliably. I think the trigger is `--server` plus session name == credentials name.

**Comment by jufemaiz** [comment]
Can confirm I'm seeing this happen now too :(

**Comment by mtibben** [comment]
This was fixed in v4.6.2. If you're seeing the issue in the latest release please re-open

**Comment by jufemaiz** [comment]
I think I discovered my PEBCAK issue.

I was running multiple concurrent long-running sessions in terminal (that is, the `aws-vault exec bob --` and `aws-vault exec ted --` and they seem to have clobbered each other). Thoughts?

**Comment by FernandoMiguel** [comment]
I do that and never had any trouble

--
Fernando 🐼
