### ISSUE TITLE
Redirecting output on Linux

### ISSUE THREAD

**Issue by hydrajump** [99designs/aws-vault#357]
This is an awesome project!

I'm using `aws-vault` on Debian and I've found that redirecting output from a command only outputs the prompt for the passphrase.

Example

```
$ aws-vault exec redacted -- aws ec2 describe-instances > ec2_instances.txt

$ cat ec2_instances.txt
Please enter passphrase xxxxxxx
```

I'm using an encrypted file for storing the aws credentials and the only way I've found to make redirection work is to `export AWS_VAULT_FILE_PASSPHRASE=somepassword`.

Is there some other supported way to redirect output from `awscli` or any other 3rd party tool when using `aws-vault`?

**Comment by Nuru** [comment]
@hydrajump The issue you are having is that the `> ec2_instances.tx` is being interpreted at the command line level and not being passed to `aws-vault`. What you want is something like this:
```
aws-vault exec redacted -- sh -c "aws ec2 describe-instances > ec2_instances.txt"
```
That will cause `aws-vault` to exec a shell that then parses your command line the way you want it to.

**Comment by lox** [comment]
I'll close this one out, let us know if you have any further questions @hydrajump!
