### ISSUE TITLE
Promote proxy server to first class feature

### ISSUE THREAD

**Issue by Nuru** [99designs/aws-vault#361]
There are a few open issues regarding the proxy server already, and I am opening this new one with new information/issues/use cases and will try to consolidate some of the existing issues here. 

To start with, let me define "proxy server". As [@lox explained](https://github.com/99designs/aws-vault/pull/174#issuecomment-340921440) in #174 , `aws-vault` runs 2 servers: a credentials server at 127.0.0.1:9099, which is the smart server that handles the credentials and manages refreshing them, etc., and a proxy server at 169.254.169.254:80, which simply provides the endpoint that all the AWS tools use but mainly is pretty dumb and just forwards requests to the credentials server. 

This issue is confined to issues with the proxy server.

Because the proxy server binds to privileged port 80, it needs to run (or at least be started) as root, generally either via `sudo` or by running in a `--privileged` Docker container. Because of this, and because by itself it is not a security risk, the proxy server is designed to be started once and left running, in contrast to the credentials server which should only be running while credentials are needed and is thus started and stopped on every `aws-vault exec` command. 

The command to start the proxy server, `aws-vault server` was hidden by #208 because it was confusing people. While I understand the confusing nature of it (although the command is named "server" it does not start the credentials server, which is what might be expected, as in #222 and #224), I think hiding it was a mistake, and I am opening this issue in part to make sure that the command remains available and supported, because I need it.

The reason I need it is that the current automatic starting of the proxy server does not work very well. `checkServerRunning` performs [the simplest check](https://github.com/99designs/aws-vault/blob/d3ffc27e67e886a83ccf5c723a0d2c9ec9db4f64/server/server.go#L80-L83), namely trying to open a TCP connection to 169.254.169.254:80,  to see if the proxy server is already running and if that check succeeds, `aws-vault exec --server` does not start a proxy server because it thinks one is already running.

I believe the fragility of this check, the inability to restart the proxy server described in #360, and the proxy server being hidden from the UI are contributing to the confusion about, if not completely causing, #313, #335, and #338. Promoting the proxy server to a documented, first-class role would help people understand those issues, would open the way for my feature request #345, would have caught #360 earlier, and would allow the removal of the hidden `sudo` command as [lox seems to prefer](https://github.com/99designs/aws-vault/pull/174#issuecomment-340401194) and I definitely prefer. 

I have run into 2 situations where `aws-vault exec --server` fails without providing a good explanation in its output, both due to `checkServerRunning` returning true when it should return false. 
1. The likely more common case is when anti-virus (AV) is running and snooping on web traffic. The AV will listen for attempts to connect to port 80, so it will cause `checkServerRunning` to decide a server is running and therefore does not need to be started. `aws-vault exec --server` will succeed, but the command that is exec'ed will mysteriously have no credentials.
1. The other situation I run into is when running in Docker containers in AWS. These containers have a default connection to the instance's real AWS meta-data server, so again `checkServerRunning` indicates that no server needs to be started. In this case `aws-vault exec --server` succeeds, but the command does not have the credentials of profile it was meant to have, but instead uses the instance's credentials, making `aws-vault` essentially a no-op.

In both of the above cases, my current solution is simply to start the proxy server explicitly before running `aws-vault exec --server`. 

The easiest way forward for `aws-vault` developers is just to commit to making `aws-vault server` a first-class, well documented feature. 

A more complex (but more rewarding) path forward is to replace `checkServerRunning` with an intelligent test that does the following:
1. See if a connection can be made to 169.254.169.254:80. If not, start a server and return.
1. Query the server at 169.254.169.254:80 and see if it returns credentials. 
    1.  If it does return credentials, see if they match the credentials being asked for.
        1. If the returned credentials match the desired credentials, just run the command without modifying the environment. (Implements #345)
        1. If the returned credentials are different, see if the `aws-vault` proxy server can be started to intercept traffic before getting to the existing server. (In my usage it can.) Start it if possible, otherwise print a warning and run `aws-vault exec` in non-server mode. 

What I would like to have happen is that `aws-vault server` is not hidden but is instead documented and there is a commitment to support it going forward, and manually starting and stopping the proxy server separately from the credentials server is officially supported.

**Comment by lox** [comment]
This is a really, really good summary of the state of things with `server` @Nuru. 

I've always regretted calling it `--server`, it's not intuitively obvious to folks what it is: "Automatically refresh your credentials from a local instance metadata server". I could absolutely be talked into changing it, or exposing it as a non-hidden command in the next major version. 

I'd love to find a way to allow multiple `exec` runs to share the same metadata server instance, I'd be keen to collaborate on making that a thing if you are inclined @Nuru. It would require each `exec` to register itself with the metadata server I guess? Not sure how you'd handle `profile` name clashes, but at least you could run parallel `exec`'s with different profiles. 

In terms of the improvements you suggest to `checkServerRunning`, I think they are an excellent idea. The current implementation was my first pass many years ago, but we've definitely seen some issues with it as you've pointed out. Sounds like some improvements there prior to tackling #345 would be a good place to start.

**Comment by Nuru** [comment]
@lox Thanks for considering my requests.

As a UI issue, I suggest adding `aws-vault proxy` as a command that takes further commands and options, such as `start`, `stop`, and `status` and manages the proxy server at 169.254.169.254:80. I think leaving `--server` as is is fine, meaning start a credentials server, and it's also fine if it automatically starts the proxy server, although it needs better prompting if it is going to use `sudo`. 

At the moment, small steps, I would be fine with only allowing one credentials server at a time. The key is that future execs use the running server or not as is appropriate, rather than just choking. 

I have been working on a shell script wrapper for `aws-vault` that implements a lot of this logic. You can [take a look](https://github.com/cloudposse/geodesic/blob/6f9ac53fe771d43ad8002a380111eeff59562226/rootfs/etc/profile.d/aws-vault.sh#L3-L77) and incorporate as much of that logic as you want. It basically implements #345 the way I had envisioned, although as you say, there remains future work to allow multiple profiles to be active at the same time. However, since I have that done, I'd rather you address #362 first, as that is much harder to work around.

**Comment by mindlace** [comment]
I would really like it if I could just run the proxy server as a docker container, where it's only visible on the docker network at the metadata address. Something like this https://github.com/awslabs/amazon-ecs-local-container-endpoints/blob/master/README.md but getting the credentials from aws-vault instead of directly from the user's aws creds

**Comment by FernandoMiguel** [comment]
@mindlace then start a sub shell and export the vars to the Docker
