### ISSUE TITLE
Exec should stop child process when asking for passphrase or token

### ISSUE THREAD

**Issue by Nuru** [99designs/aws-vault#362]
If `aws-vault exec --server profile -- bash` is running and the profile has MFA enabled, when the AWS credential session expires, `aws-vault` asks for a new MFA token. The problem is it does not stop the child process while doing so, leading to contention for the TTY. The usual outcome is that the token is not captured and both `aws-vault` and `bash` exit. I've seen it take out the shell that launched `aws-vault` as well. I believe this is what is happening in #222 as well. 

The solution is that when `aws-vault` needs input, it should stop its child with a SIGSTOP signal, and then when it is happy, resume the child with SIGCONT.

**Comment by lox** [comment]
Interesting 🤔 I must admit I use the modal prompt on macOS, so it pops up regardless. The biggest problem I have with it is that generally the aws-cli times out.

I actually haven't heard of `SIGSTOP` and `SIGCONT`, but they sound right and would be happy to put them in and see if they improve the issue.

**Comment by Nuru** [comment]
@lox I don't know anything about a modal prompt on macOS, please explain.

Yes, the signals are pretty straightforward: SIGSTOP stops a process, and SIGCONT starts it again. It is nicer to use SIGTSTP, and in fact `aws-vault` will receive SIGTSTP when it tries to read from the keyboard but cannot because it is in the background, but you cannot rely on it to stop your children because `bash` automatically ignores SIGTSTP and there is little you can do about it.

**Comment by Nuru** [comment]
> I actually haven't heard of `SIGSTOP` and `SIGCONT`, but they sound right and would be happy to put them in and see if they improve the issue.

@lox Have you had a chance to try out `SIGSTOP`?

**Comment by Nuru** [comment]
@lox I guess you can close this as fixed by #454 although I haven't tested it.
