### ISSUE TITLE
is it possible to use your tool inside EC2 and using instance profile?

### ISSUE THREAD

**Issue by KursLabIgor** [99designs/aws-vault#363]
I have question regarding usage aws-vault inside EC2 with attached instance role that i able perform same operation w/o storing any keys?

**Comment by FernandoMiguel** [comment]
What is the use case of aws-vault on ec2?
By having an instance role, you can perform any actions allowed by that
role and STS to others

--
Fernando Miguel

**Comment by KursLabIgor** [comment]
@FernandoMiguel ok, sorry maybe for it is not clear how will be configuration on EC2. 
I need to create in .aws/config file and just place same config as i have on my local pc, am i right ?
use case it is not store access_key and secret_keys n EC2

**Comment by FernandoMiguel** [comment]
there's is not much for a need for a config, unless for region (but that should be a ENV anyway)
certainly there isn't a need for credentials, since it pulls them from instance role

**Comment by FernandoMiguel** [comment]
i'm going back to my question:
why are you putting aws-vault INSIDE an ec2? :)

**Comment by KursLabIgor** [comment]
Ok, just want to make same approach for running terraform from automation side and human side. I wrap all things to Makefile and same file will be used in both side with some predefined logic. that is my idea. )

**Comment by KursLabIgor** [comment]
> there's is not much for a need for a config, unless for region (but that should be a ENV anyway)
> certainly there isn't a need for credentials, since it pulls them from instance role

and I guess right role for assuming in my case.

**Comment by FernandoMiguel** [comment]
we run terraform for humans and instances from different roles (we require MFA for humans).
we create a override for our CI to use another role
it is pretty straight fw
https://www.terraform.io/docs/configuration/override.html

feel free to ping me on slack, so not to make this more offtopic for aws-vault

**Comment by KursLabIgor** [comment]
yep I agree. For human I have one role with MFA required and for automation will be another role.closing

**Comment by KursLabIgor** [comment]
@FernandoMiguel sorry cant figure out how to reach you in slack )

**Comment by FernandoMiguel** [comment]
@KursLabIgor https://signup.hangops.com
