### ISSUE TITLE
WSL - Keep asking for unlock

### ISSUE THREAD

**Issue by z0ph** [99designs/aws-vault#366]
Hi,

Just trying to use `aws-vault` on my WSL, but he still ask me to unlock, how can I set a parameter for this, like a timeout?

![image](https://user-images.githubusercontent.com/20846187/56926031-07052e80-6ad1-11e9-8d8f-cdb2671d4aaa.png)

Thanks,

**Comment by dwurf** [comment]
I've heard you can set up `[pass](https://www.passwordstore.org/)`, then use it as a backend for aws-vault (`--backend pass` flag or `AWS_VAULT_BACKEND=pass`).
