### ISSUE TITLE
aws-vault not working with us-gov-east-1 govcloud region

### ISSUE THREAD

**Issue by ddimri** [99designs/aws-vault#367]
We use aws-vault to store aws credentials. we see aws-vault is not working with GovCloud region and fails with "InvalidClientTokenId" error when we are trying to assume a role with MFA condition in us-gov-east-1.  A simple command `aws-vault --debug  exec ops-admin-usgov -- terraform init` throws below error message:

`2019/05/01 14:12:50 Using region "us-gov-east-1" from AWS_REGION
2019/05/01 14:12:50 Getting new session token for profile dprasad-usgov1
aws-vault: error: Failed to get credentials for dprasad-usgov1 (source profile for ops-admin-usgov1): InvalidClientTokenId: The security token included in the request is invalid.
	status code: 403, request id: 1b5224be-6bed-11e9-9168-7574640e6034`

wanted to check if AWS GovCloud region is supported by aws-vault if so then what could be a reason for it to not work? We have the exact same profile with MFA works fine with AWS CLI command.

**Comment by frezbo** [comment]
hi @ddimri I use aws-vault with aws gov cloud and have no issues. What's the region for the profile in your `~/.aws/config` file? Are you on the latest version of aws-vault?

**Comment by ddimri** [comment]
Hi @frezbo, i have `region=us-gov-east-1` in my `~/.aws/config`.  aws-cli and terraform works fine with MFA but not aws-vault.  Is it working for you with MFA? Thanks, Deepak

**Comment by ddimri** [comment]
any word on this issue? not sure what else i can check here!

**Comment by sharmsvertafore** [comment]
Without seeing the Terraform code you are using, this typically happens because the temporary credentials do not have permissions for `IAM:::*` and I don't believe this is a `aws-vault` issue.

https://github.com/terraform-providers/terraform-provider-aws/issues/125
