### ISSUE TITLE
Working with Visual Studio Code and AWS Toolkit Pluglin

### ISSUE THREAD

**Issue by stefanorg** [99designs/aws-vault#370]
Hi, there is a way to use the aws-vault with vscode + AWS Toolkit plugin?

Thanks

**Comment by FernandoMiguel** [comment]
What's aws toolkit?

--
Fernando Miguel

**Comment by stefanorg** [comment]
Hi, this: https://aws.amazon.com/it/visualstudiocode/

**Comment by FernandoMiguel** [comment]
and what exactly are you trying to achieve?
worse case scenario, `aws-vault exec ROLE --server` will always work

**Comment by stefanorg** [comment]
I'm not able to connect the toolkit to my aws account using credentials
stored with aws-vault.
I tried --server too but maybe not in the correct way, because is not
working.

--
Stefano Corallo



Il giorno sab 18 mag 2019 alle ore 21:33 Fernando Miguel <
notifications@github.com> ha scritto:

**Comment by frezbo** [comment]
Try creating the `server` session first then opening VSCode

**Comment by stefanorg** [comment]
i tried as suggested in my terminal `aws-vault exec test --server` and then started vscode but i get the error:

```
There was an issue trying to use credentials profile test. You will be disconnected from AWS. ENOENT: no such file or directory, open '/Users/n4z4/.aws/credentials'
```

**Comment by FernandoMiguel** [comment]
Does '/Users/n4z4/.aws/credentials' exist?

**Comment by stefanorg** [comment]
Nope. Isn't that file "wrapped" by aws-vault?

--
Stefano Corallo



Il giorno lun 20 mag 2019 alle ore 20:08 Fernando Miguel <
notifications@github.com> ha scritto:

**Comment by FernandoMiguel** [comment]
Aws-vault doesn't place the file, no.
--server just creates a daemon where aws sdk apps can talk to the api 

Some apps are silly and are hardcore to look for it, so you car kinda limited. 

Maybe reach out aws support?

**Comment by virgilwashere** [comment]
I have it working. [aws-toolkit-vscode issue #566](/aws/aws-toolkit-vscode/issues/566#issuecomment-495871907)

The blocking issue for me was creating `$HOME/.config/Code/logs/aws_toolkit` on WSL, pending the extension updating.

After that, just ensure that `aws-vault` is run before the `aws_toolkit` (and `code`) starts, to setup the session env vars.  After alias expansion, the command I run (`aws whoami` which runs `sts get-caller-identity`)

```bash
aws-vault --debug exec "${AWS_DEFAULT_PROFILE:-work-profile}" --server -- aws whoami
```

Then run command `AWS: Connect to AWS` from `code` and select your `work-profile` config.
