### ISSUE TITLE
Repo Documentation is not compatible with latest distribution

### ISSUE THREAD

**Issue by rossmckelvie** [99designs/aws-vault#376]
There have been changes to README and improvements for using `aws-vault` with a multi-account AWS architecture, that are not compatible with the distributed version: @jstewmon implemented chained sessions that will allow us to configure MFA under the base iam principal, so AssumeRole requiring MFA won't work unless it is explicitly listed in the config file.

A [similar comment was made](https://github.com/99designs/aws-vault/pull/369#issuecomment-494984149) in closed PR #369, opening this issue to bring visibility to the maintainers and any new users who might be having trouble configuring a freshly installed aws-vault. I've been testing his changes locally for the last few weeks if there are any outstanding questions before publishing a new release.

**Comment by rossmckelvie** [comment]
@mtibben @lox could you provide an ETA of when you'd expect a new release to be distributed? orIf preferred I can open a PR to fix the docs in master to link to current releases's tag's version of README.

**Comment by rossmckelvie** [comment]
@mtibben any update on this? I saw you merged in another change 12hrs ago but documentation still does not match distributed release. If there's anything I can do to help please let me know, this is quite important/preventing me from rolling this out to my org.

**Comment by mtibben** [comment]
New release at https://github.com/99designs/aws-vault/releases/tag/v4.6.0

**Comment by gusztavvargadr** [comment]
@mtibben thanks, just pushed it for Chocolatey at https://chocolatey.org/packages/aws-vault/4.6.0.
