### ISSUE TITLE
removing credential leaves traces in .aws/config file

### ISSUE THREAD

**Issue by maishsk** [99designs/aws-vault#379]
When I add a new credential - it creates a new entry in `~/.aws/config`

Original state.

```
14:39  [test] $ cat ~/.aws/config 
[profile maishsk]
region=us-east-2

[profile play]
region=us-west-2
```

I then add credentials

```
14:43  [test] $ aws-vault add route53
Enter Access Key ID: 12435423
Enter Secret Access Key: 214321432
Added credentials to profile "route53" in vault


14:43  [test] $ cat ~/.aws/config 
[profile maishsk]
region=us-east-2

[profile play]
region=us-west-2

[profile route53]
```

It added a new profile to the `config` file.

Output of `aws-vault ls`:

```
14:43  [test] $ aws-vault ls
Profile                  Credentials              Sessions                 
=======                  ===========              ========                 
maishsk                  maishsk                  -                        
play                     play                     -                        
route53                  route53                  -                        
```

I then remove a credential with:

```
14:46  [test] $ aws-vault remove route53
Delete credentials for profile "route53"? (Y|n)Y
Deleted credentials.
Deleted 0 sessions.
```

It leaves traces in the `config` file

```
14:47  [test] $ cat ~/.aws/config 
[profile maishsk]
region=us-east-2

[profile play]
region=us-west-2

[profile route53]
```

And of course when I do a list of the profiles

```
14:47  [test] $ aws-vault ls
Profile                  Credentials              Sessions                 
=======                  ===========              ========                 
maishsk                  maishsk                  -                        
play                     play                     -                        
route53                  -                        -                        
```

Expected behavior:

If you add it in - then I would expect that you would remove the line that added - and remove it when I remove a credential from the vault.

Thoughts?

**Comment by FernandoMiguel** [comment]
I wasnt even aware it would modify config file :S 
i usually do mine by hand before adding new creds 🥇

**Comment by vs-jawad** [comment]
@maishsk The issue with that would be if you had added any configuration inside the profile then aws-vault would have to remove that too and you may still want that profile configuration or to set up that profile with a different set of credentials. As a result, I think the current behavior is intended and would be hesitant to change it. It's better to air on the side of safety even if that creates a little cleanup for people

**Comment by maishsk** [comment]
I can perfectly understand that.
Maybe it should be documented - that this is the default behavior?
