### ISSUE TITLE
shell variable for username

### ISSUE THREAD

**Issue by FernandoMiguel** [99designs/aws-vault#389]
is it possible to have a variable in the config file?
something like
```
[profile iam]
region=eu-west-1
mfa_serial=arn:aws:iam::123456789:mfa/${AWSIAMUSER}
```

the idea is for users to all have the same config file from a git repo, and be able to update it when new roles are added.

**Comment by bronislav** [comment]
I don't think it is supported. There are a lot of tools that reads/uses this file (mainly AWS API SDKs and similar things).

You may try to generate this file from template, so users will still be able to update it from git repo and replace placeholder with actual username.
