### ISSUE TITLE
Bind aws-vault to env vars possible?

### ISSUE THREAD

**Issue by madsem** [99designs/aws-vault#393]
Hey,

great tool! Thanks for making this open source.
Quick question, is it possible to somehow bind aws-vault to env vars directly, via a function result?

I'm asking because I don't want to have to remember to run `aws-vault ... -- aws something...` every time. If I could have the env vars automatically populated with temp credentials I could simply use the aws cli directly, at least that's what I'm thinking :)

*edit*
To better illustrate what I am asking, I'm thinking of doing something like this:
```shell
# fish shell
set -g -x AWS_ACCESS_KEY=(aws-vault exec home)
```

**Comment by FernandoMiguel** [comment]
That's what aws cli pass is for
You can config it to call an helper like aws-vault

**Comment by madsem** [comment]
@FernandoMiguel thanks! Let me read up on that, I wasn't aware :)

**Comment by madsem** [comment]
@FernandoMiguel do you maybe have a link to what you are referring? That would be amazing! I can't seem to find "aws cli pass" in this context

**Comment by FernandoMiguel** [comment]
@madsem see https://github.com/99designs/aws-vault/pull/300 for reference

**Comment by madsem** [comment]
Amazing, thanks! 

Also meanwhile found this in the docs, for anyone who might finds this later on:
https://github.com/99designs/aws-vault/blob/master/USAGE.md#overriding-the-aws-cli-to-use-aws-vault
