### ISSUE TITLE
Losing terminal history after exec

### ISSUE THREAD

**Issue by jasonkuhrt** [99designs/aws-vault#396]
Example:

```
❯ echo 1
1

❯ echo 2
2

❯ history | tail -n 2
  393  echo 1
  394  echo 2

❯ aws-vault exec --assume-role-ttl=60m --session-ttl=12h dev-ca2

❯ history | tail -n 4
  385  poetry install
  386  vim ~/.zshrc
  387  poetry run python
  388  exit
```

What's going on here?

**Comment by FernandoMiguel** [comment]
You are in a subshell... The history you see is the one before your previous shell history has been saved to disk

**Comment by jasonkuhrt** [comment]
Ah... is there any workaround? Avoid sub shell creation or inherit history from parent shell (latter being a non-aws-vault topic)

**Comment by FernandoMiguel** [comment]
```
 aws-vault exec --assume-role-ttl=1h --session-ttl=12h dev-ca2 -- /path/my/command 
```

**Comment by jasonkuhrt** [comment]
I’m aware of the but I would like to be able to change my current shell so that I can work with aws in subsequent commands.

**Comment by jasonkuhrt** [comment]
The solution to my problem is employing the solution in https://stackoverflow.com/questions/842338/how-do-i-tell-zsh-to-write-the-current-shells-history-to-my-history-fil.

Thanks @FernandoMiguel for tipping me off that there is a subshell issue at play 🙏
