### ISSUE TITLE
Environment variable to determine whether session includes MFA token

### ISSUE THREAD

**Issue by kevinburkemeter** [99designs/aws-vault#398]
I would like to enforce that some AWS account users are using MFA to access AWS. As far as I can tell I have a few options:

- IAM rules for the account, which are finicky because you have to add them after you've created the user.
- call ListDevices using the implicit credentials any time a session is created, verify at least one entry. Is this good enough? E.g. will the ListDevices call fail if a user has MFA turned on but doesn't use it to make the API call.
- Some environment variable like AWS_VAULT=true that is set by aws-vault on exec

What if we set for example `AWS_MFA_AUTHENTICATION=true` in the environment if the aws config included an mfa serial or the user included mfa-token at the command line? That would make it possible to determine whether the user used MFA without needing to authenticate with AWS.

**Comment by FernandoMiguel** [comment]
Or use aws config to guarantee that your users are enforced MFA

**Comment by FernandoMiguel** [comment]
Personally, our iam policies are set via terraform and don't change.
So once the user is created, they need to add mfa before creating an access key

**Comment by mtibben** [comment]
Yes I agree with @FernandoMiguel, if MFA is required it should be enforced on the role or via AWS Config
