### ISSUE TITLE
Allow "pass" backend config via environment variables

### ISSUE THREAD

**Issue by arnuschky** [99designs/aws-vault#399]
It would be great if one could provide the config of `aws-vault` via the environment variables or a config file (most importantly the backend config). Currently it's really cumbersome to use `aws-vault` in scripts because you'd need to either patch the script or somehow write a wrapper.

**Comment by mtibben** [comment]
Hey @arnuschky you are able to set config via environment variables - see https://github.com/99designs/aws-vault/blob/master/USAGE.md#environment-variables

**Comment by arnuschky** [comment]
Ah damn. I read the readme and help but never found the usage page. Apologies, I must have been tired. At least an issue easily resolved! Thanks.

**Comment by arnuschky** [comment]
Ah stop, just saw that I can't configure the `pass` backend using config vars. I would need vars for `--pass-dir`, `--pass-prefix`, and `--pass-cmd`

**Comment by arnuschky** [comment]
Took a look at the code and realized that those variables are there too! Brilliant!

I added a PR for documenting those vars. Thanks for your great work!
