### ISSUE TITLE
Loosing creds in keychain randomly.

### ISSUE THREAD

**Issue by zyxep** [99designs/aws-vault#407]
I've recently upgraded to v4.6.3
I'm on Mojave 10.14.6

And from time to time do I loose creds in keychain.
I did `aws-vault add test` and then my creds.

Using it with `aws-vault exec test -- terraform .....` and then it sometimes get lost.
I saw there was a bug about it earlier but should have been fixed in 4.6.2 ??

**Comment by mtibben** [comment]
Eeek yes I can reproduce this... Happened to me when using root credentials, and not using a role

**Comment by fams** [comment]
Its happening with me even using a role. The worst is, its random.

**Comment by jessebye** [comment]
This just happened to us too on v4.6.4.

**Comment by emmanuel** [comment]
I have experienced this multiple times on macOS Mojave (10.14.6), with `aws-vault` v4.6.4. I am using a session with root account credentials.

I have not yet discerned a pattern to the disappearances, but it has occurred 4 times over the last 3 days.

**Comment by FnTm** [comment]
This has happened to us as well, without a discernible pattern as of yet.
What would happen is that we would be using a base role to assume a higher privileged role with MFA enabled. This would succeed, but some time later (seems like coming back to the computer after a while), the trying to assume the higher privileged role would return this:

```
aws-vault: error: Failed to get credentials for base (source profile for higher-privileges): AccessDenied: User: arn:aws:iam::foo:user/fntm is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::foo:role/higher-privileges
    status code: 403, request id: xyz
```

For some additional context - we're using 4.6.2 on macOS Mojave, with Login set as default keychain.

What ends up helping is clearing out credentials for the base role/profile:
```
aws-vault remove base --sessions-only
```

**Comment by mtibben** [comment]
This seems to have been resolved in v5
