### ISSUE TITLE
Windows 10: aws-vault: error: Server failed: exit status 1

### ISSUE THREAD

**Issue by cholz** [99designs/aws-vault#411]
System: Windows 10, using "Git-bash" and "CMD" with Admin rights
aws-vault version: 4.6.3

procedure:
- using an AWS Account with MFA
- `aws-vault add <profile>` is working and the credentials and MFA Token is obtained
- when executing ` aws-vault exec <profile> -s` i get:
```
aws-vault: error: Server failed: exit status 1
aws-vault: error: Failed to start credential server: The credential proxy server isn't running. Run aws-vault server as Administrator in the background and then try this command again
```

The strange thing is: it worked initially. I configured everything and it worked as expected.
It does not work anymore after the first reboot.

Things i tried:
- different backend service (--backend=file)
- new AWS Access Token
- deleting wincred credentials in windows and old sessions with aws-vault
- different shells (cmd, PowerShell, git bash... all started with and without admin rigths)
- executing the `login` cmd works fine

Any help is greatly appreciated.
In my company we are using aws-vault on many different systems: mac, Win7, another win10 System. Currently i am the only one with this issue and somehow the unicorn.

Thank you.

![aws-vault](https://user-images.githubusercontent.com/6306538/63328147-ea1a9280-c32f-11e9-9cc9-cc7709a231fd.PNG)

**Comment by vrandkode** [comment]
Maybe local DNS has been screwed it up, try:
netsh interface ip set dns "Loopback Pseudo-Interface 1" dhcp
netsh interface ipv4 add address "Loopback Pseudo-Interface 1" 169.254.169.254 255.255.0.0

**Comment by mtibben** [comment]
As per the error message, you literally need to run `aws-vault server` as Administrator to start the proxy service. I'm sure this could be improved but I don't run windows. PRs welcome
