### ISSUE TITLE
"clear" alias for "--sessions-only"

### ISSUE THREAD

**Issue by nitrocode** [99designs/aws-vault#412]
It would be nice to have a `clear` alias for `--sessions-only` because running this

```
aws-vault remove work --sessions-only
```

can be dangerous if we forget the `--sessions-only`. It would be easier to do this.

```
aws-vault clear work
```
 
I store my keys in a password manager if I accidentally remove them from aws-vault.

My workaround now is to use these aliases

```
alias av="aws-vault"
alias avcw="av remove work --sessions-only"
```

**Comment by mtibben** [comment]
Yeah I've found this annoying too. For me clearing sessions is the most common reason for using the `aws-vault remove` command so probably should be easier

**Comment by nitrocode** [comment]
Friendly bump to avoid stalebot

**Comment by tomelliff** [comment]
Would it be better to flip the behaviour here and make the default just clear sessions with an extra flag such as `--remove-profile`?
