### ISSUE TITLE
Improved auto-completion for zsh

### ISSUE THREAD

**Issue by reegnz** [99designs/aws-vault#415]
I made a ZSH completion script for aws-vault, as I was frustrated that I didn't find a decent one. Here it is: https://github.com/reegnz/aws-vault-zsh-plugin

What is missing from the existing completion script is being able to complete profile names, and that was more important to me than completing flags.

Do you think it would be worth it to contribute to your repository?

**Comment by mtibben** [comment]
This works for me on zsh and completes profile names
```
eval "$(aws-vault --completion-script-zsh)"
```

**Comment by reegnz** [comment]
That's the first time I hear of that flag. Would be nice to have the completion usage be documented. :)

My script is somewhat smarter though:
1. aws-vault remove only completes to profiles that actually have credentials managed by aws-vault
2. aws-vault rotate only completes to profiles that actually have credentials managed by aws-vault

Maybe you could incorporate that behaviour into that command?

**Comment by reegnz** [comment]
So for example:
* `aws-vault remove` and `aws-vault rotate` are completed only with profiles returned by `aws-vault list --credentials`
* `aws-vault remove --sessions-only` is completed only with profiles returned by `aws-vault list --sessions`

**Comment by mtibben** [comment]
Documented at https://github.com/99designs/aws-vault/commit/e0fbe18135e2fa3107072dfb914f9ca2b4ccdab9

Feel free to PR the [contrib/completions](contrib/completions) if you think they can be improved @reegnz
