### ISSUE TITLE
Ctrl+C force-kills process executed with "aws-vault exec" on windows

### ISSUE THREAD

**Issue by vroad** [99designs/aws-vault#420]
When Ctrl+C key is pressed, aws-vault does not try to exit the running process gracefully on windows. It just forcibly kills the process without cleaning up. This is a problem when running Terraform as that may leave state file in a inconsistent state.

**Comment by mtibben** [comment]
This should be fixed by #454 in [v5.0.0-alpha2](https://github.com/99designs/aws-vault/releases/tag/v5.0.0-alpha2)
