### ISSUE TITLE
Zero-config assume-role

### ISSUE THREAD

**Issue by stribb** [99designs/aws-vault#423]
In my organisation we have O(100) accounts. In my security role, sometimes I need to jump into an account. Of course, this is what the config file is for: you get to Assume Role into other accounts, given the account ID and the role name.

However, with that many accounts, it's unlikely that the account is in  my .aws/config ahead of time.

One straw-man proposal would be to make a sort of exec on steroids command such as:

`aws-vault assume <from-profile> <to-account> <to-role>  [<cmd>] [<args>...]`

I think this is feasible given that aws-vault manipulates the session environment variables to pass to `<cmd>`.

**Comment by reegnz** [comment]
To me this sounds like you need your own wrapper around aws-vault, as the account and role structure is entirely organization-dependent. I don't think aws-vault should assume your multi-account organization structure itself, just as aws-cli doesn't make any assumptions on that either.

We shouldn't encode organisation-specific use-cases in a tool that is independent of how you use multiple aws accounts and aws organizations. A meta-tool should do that instead (and that tool could make use of aws-vault in implementing that).

Just an example on how I deal with multiple accounts with aws-vault and [direnv](https://direnv.net/):
Coommit a custom aws-configuration and .envrc files setting AWS_CONFIG_FILE the environment variable pointing to the aws-configuration alongside your infra code.
aws sdk has a lot of options governed by environment variables, so using something like aws-vault with direnv is a good marriage of tools without having to encode org. specific use-cases into either of those tools.

The whole direnv+aws-vault use-case is just my 2 cents on a possible solution, but regarding keeping organization structure use-case away from aws-vault I feel strongly about.

FYI I am just a user, not a core maintainer, so take my opinions with a grain of salt.

**Comment by mtibben** [comment]
I think this scenario should be achievable in v5 with
```terminal
$ AWS_ROLE_ARN=<to-role> aws-vault exec <from-profile> -- <cmd>
```

**Comment by mtibben** [comment]
I'll close this, assuming that `AWS_ROLE_ARN` works

**Comment by af6140** [comment]
Another way to help this is to allow dynamic include_profile where you can define role arn
