### ISSUE TITLE
Not able to create docker container

### ISSUE THREAD

**Issue by shantanuo** [99designs/aws-vault#428]
Not able to use Dockerfile mentioned in this repo. Getting error:

> 
The command '/bin/sh -c go build -a -tags netgo -ldflags '-w' -o /bin/aws-vault' returned a non-zero code: 1

**Comment by mtibben** [comment]
resolved in https://github.com/99designs/aws-vault/commit/091d2dc54aeb5d57e855c4df229f2057f5902a66
