### ISSUE TITLE
aws-vault with WSL

### ISSUE THREAD

**Issue by rchazelle** [99designs/aws-vault#432]
Hello!

I have installed aws-vault through WSL and the brew install according to the docs. I created a profile, I can login, I can create a session, I can execute commands like `aws s3 ls`. 

My problem comes with `env | grep AWS`. From one session to the next, from one profile to the next, my keys/tokens are not changing. 

I don't know what other info would be helpful to debug this, please let me know

**Comment by ZoidBB** [comment]
How long are you waiting between sessions? The sessions get cached

**Comment by mtibben** [comment]
You can see what STS calls are getting made by using `--debug`
