### ISSUE TITLE
New dmg-style mac release won't work with current homebrew cask script

### ISSUE THREAD

**Issue by reegnz** [99designs/aws-vault#439]
Saw the new beta release, awesome! 👍 

I was wondering though that now that for Mac it's now a dmg file and that might not work with the current homebrew cask script, and it seems like it's incompatible currently:

https://github.com/Homebrew/homebrew-cask/blob/master/Casks/aws-vault.rb#L5

It would be best to prepare a PR for the cask so that the release gets to homebrew users without problems.

**Comment by mtibben** [comment]
I've created a PR https://github.com/Homebrew/homebrew-cask/pull/71644

**Comment by reegnz** [comment]
They merged the PR, install with homebrew works! 👍
