### ISSUE TITLE
Instance Metadata server complicates process model

### ISSUE THREAD

**Issue by pda** [99designs/aws-vault#44]
Introducing the Instance Metadata server in https://github.com/99designs/aws-vault/pull/26 meant replacing `syscall.Exec` with `exec.Command().Run()`; the former replaces the current aws-vault process with the command being executed, the latter runs it as a child process. This introduces lots of complexity and downside;

- The pid of the command being executed is different to the PID that the shell saw launched.
- Signal handling needs to be managed.
- Exit status needs to be captured and passed through.
- The proctitle remains `aws-vault` rather than that of the command being executed.
    - Go doesn't support reading/writing proctitle without using barely maintained third-party libs.

This isn't a call-to-action issue, just highlighting some of the downsides alongside discussion in https://github.com/99designs/aws-vault/pull/43 etc.

**Comment by lox** [comment]
Yeah, I'd prefer to go back to Exec if possible. One catch would be that Windows doesn't support Exec, but that could be special cased I guess when that problem becomes a thing. 

The only complexity I forsee is that with Exec there is no way to cleanup the generated AWS_CONFIG_FILE. Perhaps there is no point in generating it and we should point it at `/dev/null` or equiv.

**Comment by lox** [comment]
Btw, the other major annoyance with Exec is that it swallows `go test` runs :)

**Comment by lox** [comment]
It seems like `proctitle` would be reasonably easy to address in that list. Do you have any example of where the different pid causes issues?

**Comment by pda** [comment]
Nope, it's mostly proctitle that bothers me, but also the awareness of additional complexity. But that awareness goes away when it all Just Works for a while ;)
