### ISSUE TITLE
Viewing stored credentials in the MacOS keychain

### ISSUE THREAD

**Issue by ggeldenhuis** [99designs/aws-vault#444]
This might be my lack of complete understanding of how the tool works, but I assumed that I would see a aws-vault named keychain within the MacOS keychains app. I am however not seeing a separate keychain. So should I see a seperate keychain and if not how would I verify/check items stored in my OS keychain other than using aws-vault command to check it?

**Comment by FernandoMiguel** [comment]
@ggeldenhuis if i'm not mistaken, it's called aws-vault

**Comment by jffry** [comment]
1. Open _Keychain Access.app_
2. _File > Add Keychain_, or Option+Click in the list of keychains and pick _Add Keychain_
3. Navigate to `~/Library/Keychains/` and pick `aws-vault.keychain-db`
4. You should be able to see it in the list of keychains on the left now

**Comment by ggeldenhuis** [comment]
@jffry many thanks! That was exactly what I was looking for. My mistake was that I assumed that new keychains would appear automatically in the keychain app.
