### ISSUE TITLE
Proposed namespace change for providing mfa serial via environment variable

### ISSUE THREAD

**Issue by rossmckelvie** [99designs/aws-vault#446]
In PR #443 the opening sentence states:
> Rotate didn’t respect the AWS_MFA_SERIAL environment variable that is used by the AWS SDK 

I'm not sure which SDK respects environment variable `AWS_MFA_SERIAL`, but the [AWS CLI documentation on environment variables](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html) don't honor this env var.

I worry that we are overloading the AWS namespace for an environment variable that only works in the context of aws-vault. Looking at the changes from 443 this has already been somewhat supported by aws-vault for some time, so I don't have high hopes for this, but there are aws-vault specific configurations that can be set in the environment using `AWS_VAULT_` as a prefix, rather than `AWS_`.

is there any objection to namespacing this environment variable and renaming it to `AWS_VAULT_MFA_SERIAL`? Happy to make the changes and open a PR, just wanted to get initial thoughts as it's been in place for some time

**Comment by jstewmon** [comment]
Apparently, none of the official AWS SDKs support that environment variable. Searching the AWS org for [AWS_MFA_SERIAL](https://github.com/search?q=AWS_MFA_SERIAL+org%3Aaws&type=Code) returns no results.

**Comment by reegnz** [comment]
Agreed, I was also under the impression that AWS_MFA_SERIAL is an AWS SDK variable when I did that PR.

I second the renaming AWS_MFA_SERIAL -> AWS_VAULT_MFA_SERIAL to highlight that this is indeed parameterizing an AWS_VAULT feature.
But please think about a deprecation period so that people already using it have time to migrate away from it. :)

Sidenote: the 'doesn't respect' explanation in that PR still holds: aws-vault itself didn't take into account the env var being set in the rotate command while it used the env-var in other commands, breaking uniformity of it's interface.

**Comment by FernandoMiguel** [comment]
+1 from me on the var rename

**Comment by rossmckelvie** [comment]
if I can add in a error if any env variables are detected that are no longer supported, that too much of a breaking change? I could try to bake in support for both env variables during this period, which begs the question how long do we wait to drop support? I'd hate to add support for 2 env variables, only to have to maintain both for eternity.

I was also thinking about properly namespacing `AWS_ASSUME_ROLE_TTL` and some of the others that are non-standard, however when I google for `AWS_ASSUME_ROLE_TTL` the first result is aws-vault and the second is aws-okta, so seems other projects may be using the same env var.

**Comment by mtibben** [comment]
I'm not sure this is necessary. It _is_ an AWS MFA device, it's not an aws-vault mfa device. The `AWS_VAULT_*` env vars currently refer to the vaulting options, not aws config. As `AWS_MFA_SERIAL` is a modifier to AWS config, I think it's OK to leave it as is
