### ISSUE TITLE
Question: can aws-vault be used in a pass-through/no-op mode with EC2 Instance Credentials?

### ISSUE THREAD

**Issue by FnTm** [99designs/aws-vault#451]
_Preface: We might be using aws-vault in a way not intended, and if so - please let me know_

So our scenario is this:
We're a fairly small team, working on a single product, and we're using aws-vault mainly to streamline the process of requiring MFA with AWS.
Our deployment process is currently a bunch of bash scripts. Using them locally works great, because we've just sprinkled in aws-vault calls in as necessary.
But we'd also like to use the same bash scripts in Jenkins to do the CI based deployments. Jenkins currently gets it's credentials from the EC2 Instance Role. This means that we have to either have 2 different deployment bash scripts or have to do a lot of `if/else` in our deploy scripts to differentiate between cases where we need to use `aws-vault` vs CI.

So my questions is:
Is there some way to configure `aws-vault` to use the EC2 Instance Role as a _backend_?
My ideal scenario here would bet that we could configure `aws-vault` on Jenkins to use the exact same `aws-vault` incantation as on our local machines, and the same bash scripts would just continue working, with the source of credentials abstracted away.

**Comment by FernandoMiguel** [comment]
If you already have instance roles, would be preferred to use that instead.
What I've done in the past was have aws-vault wrapped outside the script, so it would also work in jenkins

**Comment by mtibben** [comment]
Yes best practice would be to use aws-vault outside of scripts... e.g. execute with `aws-vault exec prod -- ./bin/deploy.sh` locally, and simply `./bin/deploy.sh` in EC2

**Comment by FnTm** [comment]
Got it, thanks for the help! Closing this as Resolved.
