### ISSUE TITLE
Passing through signals

### ISSUE THREAD

**Issue by zerkms** [99designs/aws-vault#453]
I have noticed that sometimes the ctrl-c is not passed to the executed command:

```
ivan      6551  0.0  0.0 117836  4724 pts/2    Tl   Nov15   0:00  |   |   \_ aws-vault exec <redacted> -- ansible-playbook deploy-kubernetes.yml -i demo-dev.aws_ec2.yml
ivan      6564  0.0  0.6 355852 102288 pts/2   Tl   Nov15   0:02  |   |       \_ /usr/bin/python2 /usr/bin/ansible-playbook deploy-kubernetes.yml -i demo-dev.aws_ec2.yml
```

I ctrl-c'ed it, then give it few minutes - nothing happened, then detached the terminal (using ctrl+z) and since then it's in that state for 3 days now.

The same has happened with `terraform` the other day, so it's not ansible-specific.

I'm currently running `aws-vault v4.6.4` and am not sure if I can provide anything helpful to narrow the problem scope.

**Comment by mtibben** [comment]
This has also bothered me for a while, I have a fix in #454

**Comment by mtibben** [comment]
Fix is in https://github.com/99designs/aws-vault/releases/tag/v5.0.0-alpha2

**Comment by zerkms** [comment]
Switched to 5.0.0-a2, thanks!

**Comment by mtibben** [comment]
Great, let me know how it goes
