### ISSUE TITLE
Credentials not good enough for IAM operations

### ISSUE THREAD

**Issue by mamash** [99designs/aws-vault#455]
I'm opening a new issue based on [this comment](https://github.com/99designs/aws-vault/issues/339#issuecomment-555425342). All AWS operations seem to work fine *except* for anything IAM related. This is 100% reproducible for me, see below.

Exporting the original credentials or using an awscli profile works fine. Exporting the aws-vault temporary credentials manually fails on IAM too.

```
$ aws-vault --version
v4.7.1


$ aws-vault exec purple -- aws configure list
      Name                    Value             Type    Location
      ----                    -----             ----    --------
   profile                <not set>             None    None
access_key     ****************MCFS              env
secret_key     ****************lGCl              env
    region             eu-central-1              env    AWS_DEFAULT_REGION


$ aws-vault exec purple -- aws ec2 describe-instances --query 'Reservations[*].Instances[*].{Instance:InstanceId}' --output text | wc -l
      44


$ aws-vault exec purple -- aws iam get-account-summary

An error occurred (InvalidClientTokenId) when calling the GetAccountSummary operation: The security token included in the request is invalid
```

**Comment by frezbo** [comment]
@mamash in-order for sessiuon token to work with any AWS IAM operation the session needs to be created with MFA token passed. This is not an aws-vault issue. Please remove the existion session using `aws-vault remove -s <profile_name>` and then add `mfa_serial` for the corresponding profile and do a new exec, the IAM would just work fine.

**Comment by mamash** [comment]
I'm not sure I understand. This account doesn't use/enforce MFA at all. I can't find any docs that would mention that sessions require MFA to be used.

**Comment by frezbo** [comment]
@mamash you need to setup MFA for the iam user you are using in order to use an IAM API calls with sessiontokens. Ref: https://docs.aws.amazon.com/STS/latest/APIReference/API_GetSessionToken.html

**You cannot call any IAM API operations unless MFA authentication information is included in the request. **

The relevant part of the doc is highligthed above,

**Comment by frezbo** [comment]
@mtibben doesn't the README alreadt mention this, i did not find this when I skimmed. Many users have reported this issue due to lack of knowlege of how AWS `GetSessionToken` API works. Better we add a section under readme if not already present.

**Comment by mamash** [comment]
Thanks, this should definitely be mentioned in the README for sure, because it's impossible to find without looking at the API reference.

**Comment by mtibben** [comment]
This is in the docs at https://github.com/99designs/aws-vault/blob/master/USAGE.md#limitations-with-sts, feel free to improve them
