### ISSUE TITLE
Help / man-page does not describe the -- separator

### ISSUE THREAD

**Issue by elofu17** [99designs/aws-vault#456]
You should update the help, usage and man-page to show

`usage: aws-vault [<flags>] [--] <command> [<args> ...]`

Notice the added [--] in the middle.

...and describe it in the help textbody...

I was trying to run 'aws-vault exec foo terraform destroy -target=foo-policy' but only got "aws-vault.exe: error: time: invalid duration, try --help". 

Argument -target for terraform was treated as -t by aws-vault.

Looked for an argument separator in the help, but there was none.
I tried escaping the dash, quoting the arguments after the command terraform... Nothing worked.
Then I found an example command in USAGE.md that contained a -- separator. So apparently there is one!

Remember to update all help pages for each sub-command, not just the main page. :-)

**Comment by mtibben** [comment]
Hey @elofu17, `--` is a bash-ism, and so would not be true of other shells. See https://unix.stackexchange.com/a/187548

A PR to USAGE.md to explain this would be welcomed

**Comment by elofu17** [comment]
Thanks, @mtibben . Had no idea this was interpreted by the shell.
