### ISSUE TITLE
InfoSec questions

### ISSUE THREAD

**Issue by eupestov** [99designs/aws-vault#457]
Hi!

I love AWS Vault and I would like it to get approved by our InfoSec team. In general they are positive, but have got few questions about how the community:

- ensure code contributions are trusted, e.g. how many people have write access to the repo, what the peer-review principles are
- ensure that there are no vulnerable dependencies, e.g. scanning through Snyk or similar tool

Thanks!

**Comment by mtibben** [comment]
Hey @eupestov, aws-vault is open source software and comes with no guarantees. Feel free to audit the tool yourself
