### ISSUE TITLE
Retrieving via "go get" or import statement

### ISSUE THREAD

**Issue by jsclarridge** [99designs/aws-vault#458]
Fetching the go module by either:

* Compiling with `go get github.com/99designs/aws-vault` or
* Adding an import statement in a go application

Retrieves v4.5.1 of the module, not the most recent stable version (v4.7.1). We can use the workaround of specifying the commit hash in the `go get` command, but it would be helpful if there were import paths to pull the latest release of a major version. Are there any plans on the roadmap to address this?

**Comment by mtibben** [comment]
Hey @jsclarridge this behaviour is related to the go toolchain. v4.5.1 was the last release before go modules were introduced. I should note that aws-vault is a cli tool, and is not designed to be imported by other applications

**Comment by chrisgilmerproj** [comment]
@mtibben - I work with @jsclarridge but I'm on a different project. I have an example of how I use the vault code directly in my CLI tools if it helps to have an example: https://github.com/transcom/mymove/blob/master/pkg/cli/vault.go

So it would be nice if we could keep our tools updated with your code.

**Comment by mtibben** [comment]
Hey @chrisgilmerproj and @jsclarridge, why don't you use the AWS SDK directly for this use-case? What capability is aws-vault giving you that couldn't be expressed more directly with the SDK? 

Also, why aren't you using aws-vault as a wrapper in the way it is intended to be used - what are you trying to achieve by using it as a library?

It would be helpful to understand this, as I was planning to put all the aws-vault code inside an `internal/` directory for the v5 release

**Comment by jsclarridge** [comment]
@mtibben We use the aws-vault script-wrapper for most use cases of interacting with AWS on the command line (terraform, packer, AWS CLI, etc.), but we also have a use case for configuring new user accounts (create aws-vault profile, set up MFA for AWS, rotate access keys). Historically, we've used shell scripts for this, which call out to the aws-vault CLI, but we're looking to migrate those scripts to a Go tool that would use the aws-vault library directly.

**Comment by chrisgilmerproj** [comment]
> Hey @chrisgilmerproj and @jsclarridge, why don't you use the AWS SDK directly for this use-case? What capability is aws-vault giving you that couldn't be expressed more directly with the SDK?
> 
> Also, why aren't you using aws-vault as a script-wrapper in the way it is intended to be used - what are you trying to achieve by using it as a library?
> 
> It would be helpful to understand this, as I was planning to put all the aws-vault code inside an `internal/` directory for the v5 release

@mtibben - I think its probably fine to migrate to the AWS SDK. When I wrote that code originally I was trying to keep my surface area of things I was working on pretty small and the aws-vault code provided a nice entry point for me. But I'd much rather fall back on the code you wrote than write and maintain a near perfect copy on my end. Just something to think about. I don't have time to modify my code yet, which probably means I'm stuck with your older code for a while.
