### ISSUE TITLE
Support aws-cli version 2

### ISSUE THREAD

**Issue by mbacchi** [99designs/aws-vault#459]
Version 2 of the [aws-cli](https://github.com/awsdocs/aws-sam-developer-guide/blob/master/doc_source/serverless-sam-cli-install-linux.md) is in "preview" mode, but aws-vault doesn't work unless the command `aws` is in the user's path. aws-cli v2 is called `aws2`, so I had to make a symlink from `/usr/local/bin/aws2` -> `/usr/local/bin/aws` to make `aws-vault` work.

**Comment by mtibben** [comment]
Hey @mbacchi, aws-vault has no dependency on the aws cli command. Can you explain more what issue you're encountering with examples?

**Comment by mbacchi** [comment]
Ya this was my fault, I was using aws2 instead of aws on the command line after aws-vault. For reference the error was:

```
aws-vault: error: exec: "aws": executable file not found in $PATH
```

Adding a link from aws2 -> aws was the solution. Sorry for the confusion.
