### ISSUE TITLE
Log out after 15 min v4.7.1

### ISSUE THREAD

**Issue by marty331** [99designs/aws-vault#463]
After getting a new work computer I installed the latest version of aws-vault and started experiencing an issue where I would be logged out every 15 min, no matter what flags I provided. I typically log in with the following flag `--federation-token-ttl=12h` but it did not help.

Yesterday I downgraded to version 4.5.1 (what I had on my previous computer) and this issue is no longer happening.

**Comment by mtibben** [comment]
I suspect you're using the AssumeRole token rather than the ferderation token. I've tried to address this usability issue in #464

**Comment by mtibben** [comment]
This should be addressed in https://github.com/99designs/aws-vault/releases/tag/v5.0.0-beta3. Can you confirm @marty331 ?

**Comment by mtibben** [comment]
This has been resolved in v5

**Comment by marty331** [comment]
Sorry, meant to confirm this works in v5.
