### ISSUE TITLE
Force create new session if old session is close to expiring

### ISSUE THREAD

**Issue by kevinburkemeter** [99designs/aws-vault#469]
Occasionally I'll have the following sequence of events occur:

```
t0: Start a session with a 4 hour expiration
t3h,55m: Invoke `aws-vault exec` with some long running operation (creating new ASG's)
t4h: Session expires, Terraform starts timing out commands
```

It would be nice to have some way to specify, say, `minimum-session-duration` or similar to ensure that a new session will be created and used if the existing one has less time on it than the minimum amount.

**Comment by kevinburkemeter** [comment]
I could try to work on this if we can agree on an API and if there's a place where we store the date and time of existing session expiration.

**Comment by mtibben** [comment]
Yep been thinking about this too as I've been refactoring the session duration stuff this week. I'm thinking if a `--duration` is specified as a flag, we should make sure the session lasts at least that long

**Comment by ZoidBB** [comment]
On a related note, I just submitted a PR to optionally force a new session

**Comment by M1ke** [comment]
Came here to post a similar request; would this be a complex implementation?

**Comment by mtibben** [comment]
This was actually fixed in v5. The expiration window is [5 minutes](https://github.com/99designs/aws-vault/blob/master/vault/vault.go#L19) i.e. if a credential is 5 minutes away from expiring a new one will be generated.

If you find this is not the case can you provide a full bug report?
