### ISSUE TITLE
aws-vault should clean up empty profiles after removing them from the creds db

### ISSUE THREAD

**Issue by ZoidBB** [99designs/aws-vault#477]
Currently if I "aws-vault foobar" and don't have a foobar profile in my aws config file, a profile section will be added and written to the file. However, if I then /remove/ the credentials, the profile section remains despite being empty. The expected behavior from me would be that if the profile were still empty (that is, never filled with extra data by the user), then it would be removed.

**Comment by mtibben** [comment]
An empty profile could exist for other reasons too... perhaps a placeholder, or maybe the profile is referenced by source_profile in other profiles

**Comment by MrT3313** [comment]
👀 anything on this?
