### ISSUE TITLE
aws-vault exec does not allow use of --query parameter for awscli commands

### ISSUE THREAD

**Issue by gw-bcharboneau** [99designs/aws-vault#479]
aws-vault exec does not allow use of --query parameter for awscli commands in windows, not sure about linux/mac.

such as aws-vault exec profile_name -- aws profile_name list-distributions --query "DistributionList.Items[*].{DLID:Id,DomainName:AliasICPRecordals[*].CNAME,WebACLId:WebACLId}"

results in "aws-vault.exe: error: unknown long flag '--query', try --help"

**Comment by gw-bcharboneau** [comment]
nevermind i had a typo which was difficult to catch. but i found it

**Comment by 1pavanb** [comment]
I'm getting the same error

anything with --parameters will break the functionality

seems like the -- separator for aws-vault won't work when there is another one in the command to be executed.

Simple Reproducible Eg: aws-vault exec blah -- aws --help

I'm not using it for --help but faced when trying to run a serverless secrets command.

**Comment by sonatypejuanfe** [comment]
@1pavanb the issue you are reporting is solved by this explanation https://github.com/99designs/aws-vault/issues/317 by adding a -- separator between `aws-vault` parameters and the actual command everything works fine.
