### ISSUE TITLE
brew cask installs with permissions of 777

### ISSUE THREAD

**Issue by zfasel** [99designs/aws-vault#482]
Given the package seems to be maintained by @mtibben figured the best place to track the issue would be here.

### Issue

Upon installing aws-vault by way of `brew cask install aws-vault` on macos 10.15.2, the permissions on the source binary (located at /usr/local/Caskroom/aws-vault/<version>/aws-vault) are set for 777, making it world writeable. This is a security risk for local privilege escalation.

### Steps to reproduce

```
brew cask install aws-vault
ls -altr /usr/local/Caskroom/aws-vault/5.0.1
```

**Comment by mtibben** [comment]
Hey @zfasel this seems to be in issue in homebrew-cask itself. Can you open an issue there?
