### ISSUE TITLE
Add Ability to Pass in Variables to AWS-Vault

### ISSUE THREAD

**Issue by mtoconno** [99designs/aws-vault#483]
Is there any way to pass environment variables into AWS-Vault commands?  Right now, I have multiple scripts that I run using aws-vault that requires an environment variable to run correctly.  I can change the scripts, but it would be great to be able pass in variables nonetheless.

**Comment by frezbo** [comment]
There are two  options I guess:
* I use `direnv` personally which sets environment variables per folders
* or use something like `aws-vault exec <profile> -- FOO=BAR <command>`

**Comment by mtoconno** [comment]
I've tried `aws-vault exec <profile> -- FOO=BAR <command>`, and it didn't work for me.  I'll try using `direnv` and report back.

**Comment by mtoconno** [comment]
I've tried using direnv, but it seems that aws-vault doesn't import direnv variables either when running a terraform plan.

**Comment by mtibben** [comment]
`AWS_PROFILE` is specifically unset by aws-vault. If it's set, the aws cli or SDK tries to use the aws config rather than the env vars set by aws-vault

**Comment by mtibben** [comment]
What are you trying to achieve by using `AWS_PROFILE` @mtoconno ?

**Comment by mtoconno** [comment]
We currently use the `AWS_PROFILE` in several of our scripts as an environment variable, since we use multiple AWS regions.

I'll just modify our scripts to use another variable, as I didn't know that it's specifically unset.  Thanks for the response. I'll close this out.
