### ISSUE TITLE
Question : terragrunt / terraform

### ISSUE THREAD

**Issue by ahmedfourti** [99designs/aws-vault#484]
Hello,

I am using Terragrunt/Terraform as many people I guess.
When I run terragrunt/terraform command, it will look for a variable AWS_PROFILE to handle the infrastructure.

How does that work with aws-vault ?

Thanks

**Comment by FernandoMiguel** [comment]
the better pattern to use aws-vault and terraform is to assume a role that is able to perform your tasks.
if you have multiple provider alias, your role should be able to STS into those roles.

**Comment by ahmedfourti** [comment]
Yes but how do we export that AWS_PROFILE ?

**Comment by FernandoMiguel** [comment]
you really dont.. you dont use it.

**Comment by ahmedfourti** [comment]
I am maybe missing something but without that variable terraform/terragrunt won't work.
Here is the error :
Error finding AWS credentials (did you set the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables?): InvalidClientTokenId: The security token included in the request is invalid

**Comment by FernandoMiguel** [comment]
can you post a sanitised version of your terraform provider block?
and the command you are running to execute aws-vault and terragrunt.

**Comment by ahmedfourti** [comment]
Sorry my bad I figured it out.
I just noticed that I have to use aws-vault for every command I need to run. 
It is working now.

**Comment by FernandoMiguel** [comment]
or as a subshell or as `-server`

feel free to close this ticket if fixed
