### ISSUE TITLE
How to NOT be prompted for passphrase on "aws-vault exec"?

### ISSUE THREAD

**Issue by samkbit** [99designs/aws-vault#486]
I was able to successfully __add__ profile as follows.
 ```bash
aws-vault add my-profile
```
Got prompted to provide
* Access Key ID
* Secret Access Key
* passphrase

No issue there - for passphrase, I entered ```Go Pats 2051```

I was also able to successfully __execute__ as follows
```bash
aws-vault exec my-profile -- aws s3 ls
```
Got prompted to provide __passphrase__, I entered ```Go Pats 2051``` and voila the AWS command to list s3 executed perfectly fine.

Question is __how do I execute `aws-vault exec my-profile -- aws s3 ls`  in a non-interactive/unattended way without being prompted for passphrase__? The reason is I would like to be able to include this command in a __script__ that runs on a server completely unattended even if that means the script will contain the passphrase.

What I have tried so far 

(1) I created an executable file __aws-vault-exec-my-profile.sh__ as follows.
```bash
#!/usr/bin/expect -f
spawn aws-vault exec my-profile
expect "Enter passphrase to unlock /home/sam/.awsvault/keys/:"
send "Go Pats 2051\n";
interact
```
Then I ran ```aws-vault-exec-my-profile.sh -- aws s3 ls``` at which point I got this error

Output
```bash
spawn aws-vault exec my-profile
aws-vault: error: aws-vault sessions should be nested with care, unset $AWS_VAULT to force
send: spawn id exp4 not open
    while executing
"send "Go Pats 2051\n""
    (file "/home/sam/bin/aws-vault-exec-my-profile.sh" line 4)
```
(2) Echoed passphrase and piped to aws-vault exec as follows.
```bash
echo "Go Pats 2051\n" | aws-vault exec my-profile -- aws s3 ls
```
Essentially got the same error.

Output
```
aws-vault: error: aws-vault sessions should be nested with care, unset $AWS_VAULT to force
```

Any suggestions?

**Comment by FernandoMiguel** [comment]
Look at `--server` instead, which should run outside your script.
Passing passwords like that isn't safe, maybe if you use a store, or a vault.

But you really don't want to have a password, then avoid aws-vault at all and just use aws api keys (stored in a vault)
#inception

**Comment by samkbit** [comment]
Why not make __passphrase prompt__ _optional_ when __adding__ profile using ```aws-vault add <profile>``` command?

In fact, __On Windows__,  even if you wanted  to, __aws-vault__ does not give you __passphrase prompt__  when __adding__ profile. So scripting out is easy on Windows. Unfortunately, our CICD server is Linux and having passphrase prompt as _optional_ would be very helpful with scripting.

Security wise, even without the passphrase, credentials are encrypted-at-rest anyways and would still be better than the plaintext option offered by __aws cli__, no?

**Comment by mtibben** [comment]
What backend are you using @samkbit ?

**Comment by samkbit** [comment]
@mtibben, I'm not using anything special for the __backend__ on our CICD __Ubuntu 18.04__ server so I believe __aws-vault__ defaults to using the keystore natively supported by the Ubuntu OS I believe.

**Comment by mtibben** [comment]
What does `--debug` tell you? Depending on your backend you can set a passphrase using env vars https://github.com/99designs/aws-vault/blob/master/USAGE.md#environment-variables

**Comment by samkbit** [comment]
oh thanks lemme try

**Comment by samkbit** [comment]
@mtibben thank you very much, that worked 👍

**Comment by magzim21** [comment]
I solved that with `expect` tool.
Put this executable file in PATH, name it `aws-vault-custom`.
```
#!/usr/bin/expect

# We use this workaround because aws-vault does not recognize AWS_VAULT_PASSPHRASE and the passphrase prompt cannot be avoided easily.
set passphrase $env(AWS_VAULT_PASSPHRASE)

# Disable logging before running the spawn command
log_user 0


spawn aws-vault exec my-profile --duration=12h --backend=file --json


# Wait for either the MFA code prompt or the passphrase prompt
expect {
  "Enter MFA code for" {
    send_user "Enter MFA: \n" 
    # Allow user to input MFA code and regain control when the user presses Enter
    interact -o -nobuffer -re ".*\n" return

    # Wait for passphrase prompt and send the passphrase
    expect "Enter passphrase to unlock"
    send "$passphrase\r"
  }
  "Enter passphrase to unlock" {
    # If MFA prompt does not appear, directly send the passphrase
    send "$passphrase\r"
  }
}

# Capture the output of the spawn command
expect -re "{.*}"
set spawn_output $expect_out(0,string)

expect eof

# Print the output of the spawn command
puts $spawn_output 
```

And was config snippet:
```
[profile my-profile]
credential_process=aws-vault-custom
region=us-east-1
aws_account_id=es-identity
```
