### ISSUE TITLE
No credentials in profile after restart

### ISSUE THREAD

**Issue by coen-hyde** [99designs/aws-vault#49]
It appears my access credentials got lost from the key chain after a restart. My profile appears in aws-vault but I get the message "No credentials found for profile "development"" when trying to use it. Any idea what has happened?

**Comment by lox** [comment]
Hrm, that's very odd. What do you get for `aws-vault --debug ls`?

**Comment by coen-hyde** [comment]
weird indeed. It's working now and i didn't do anything. Still have my bash history from when it wasn't working. Here is the output of ```aws-vault --debug ls```

```
DEBUG 2015/10/16 15:50:39 Opening keychain /Users/coen-hyde/Library/Keychains/aws-vault.keychain
development
default session
development session
```

I also verified the existence of the aws-vault keychain file when it wasn't working.

**Comment by coen-hyde** [comment]
hmm, it's doing it again

```
$ aws-vault exec development --write-env -- env | grep AWS
No credentials found for profile "development"
```

```
$ aws-vault --debug ls
DEBUG 2015/10/19 16:26:41 Opening keychain /Users/coen-hyde/Library/Keychains/aws-vault.keychain
development
default session
development session
```

**Comment by pda** [comment]
Are you accidentally landing in an aws-vault subshell by running `aws-vault exec <profile>` without a command?

```sh
$ ./aws-vault-2.4.1 exec fooprofile -- env | grep AWS
AWS_CONFIG_FILE=/var/folders/ck/tx_xkpf54x30fbh9__ycyn340000gn/T/aws-vault064985698
AWS_DEFAULT_PROFILE=fooprofile
AWS_PROFILE=fooprofile
AWS_DEFAULT_REGION=us-east-1
AWS_REGION=us-east-1

$ ./aws-vault-2.4.1 exec fooprofile    # seems to do nothing, actually launches subshell

$ ./aws-vault-2.4.1 exec fooprofile -- env | grep AWS
No credentials found for profile "fooprofile"

$ exit

$ ./aws-vault-2.4.1 exec fooprofile -- env | grep AWS
AWS_CONFIG_FILE=/var/folders/ck/tx_xkpg54x30dbh9__ycyn320000dn/T/aws-vault115037450
AWS_DEFAULT_PROFILE=fooprofile
AWS_PROFILE=fooprofile
AWS_DEFAULT_REGION=us-east-1
AWS_REGION=us-east-1
```

I think this only happens for profiles that use `source_profile`? And it's fixed in 7d63d81120e515e84e35103e3bc2d21cfc3b89af on master.

**Comment by lox** [comment]
@coen-hyde could you give 3.0.0 a try?

The other troubleshooting tips are to restart your shell and repair disk permissions (it works).

**Comment by coen-hyde** [comment]
@pda, @lox Sorry I wasn't able to reply sooner. Traveling atm. 3.0.0 is working fine for the moment. I must be entering into aws-vault subshell some how on occasions.

**Comment by lox** [comment]
Let us know if it happens again!

**Comment by TimMoore** [comment]
I've started having a similar problem since updating to v3.1 today. Yesterday it was working fine with v3.0.

```
Last login: Wed Oct 28 16:06:18 on ttys008
[16:08:43] tim@Tim-Culture-Amp:~ $ env |grep AWS
[16:08:52] tim@Tim-Culture-Amp:~ $ aws-vault ls --debug
DEBUG 2015/10/28 16:08:59 Opening keychain /Users/tim/Library/Keychains/aws-vault.keychain
default
[16:08:59] tim@Tim-Culture-Amp:~ $ aws-vault ls --debug
DEBUG 2015/10/28 16:09:23 Opening keychain /Users/tim/Library/Keychains/aws-vault.keychain
default
[16:09:23] tim@Tim-Culture-Amp:~ $ aws-vault exec default -- env |grep AWS
No credentials found for profile "default"
[16:09:41] tim@Tim-Culture-Amp:~ $ aws-vault --version
v3.1.0

[16:11:51] tim@Tim-Culture-Amp:~ $ aws-vault exec --debug default -- env |grep AWS
DEBUG 2015/10/28 16:12:02 Parsing config file /Users/tim/.aws/config
DEBUG 2015/10/28 16:12:02 Looking up keyring for default
DEBUG 2015/10/28 16:12:02 Opening keychain /Users/tim/Library/Keychains/aws-vault.keychain
DEBUG 2015/10/28 16:12:02 Error from keyring The user name or passphrase you entered is not correct.
No credentials found for profile "default"
```

That's a fresh terminal window, so no sub-shell involved. I'm not sure about that error message, but I'm pretty sure I typed the keychain password correctly (tried several times... usually it doesn't re-prompt for the password however).

**Comment by TimMoore** [comment]
I tried it again and it's working for me now. Is it possible that I did typo the keychain passphrase and it was cached and reused?

**Comment by lox** [comment]
It turns out that `The user name or passphrase you entered is not correct.` is a catch-all error for a variety of Keychain permissions issues. The fix is generally using Disk Utility to repair your disk permissions, or the Keychain Access utility to repair the keychain. The actual cause is frustratingly opaque. I'm going to re-open this issue and investigate adding some detection of when this issue occurs.

**Comment by lox** [comment]
If anyone notices this happening, I'd be fascinated to see what their permissions were like on their various keychains.

**Comment by coen-hyde** [comment]
I've just experienced the issue again, seemingly random. Calling aws-vault is wrapped in a script that hasn't changed for a while, so unlikely that i've entered into a subshell. Debug output:

```
DEBUG 2015/11/18 16:31:48 Parsing config file /Users/coen-hyde/.aws/config
DEBUG 2015/11/18 16:31:48 Looking up keyring for development
DEBUG 2015/11/18 16:31:48 Opening keychain /Users/coen-hyde/Library/Keychains/aws-vault.keychain
DEBUG 2015/11/18 16:31:48 Error from keyring In dark wake, no UI possible
No credentials found for profile "development"
```

**Comment by lox** [comment]
Wow. That is truly a bizarre error. Is it working now @coen-hyde?

**Comment by lox** [comment]
I'm pretty tempted to link to a wiki page of Keychain troubleshooting errors if Keychain returns weird errors.

**Comment by coen-hyde** [comment]
It's working now, but only after a restart.

**Comment by coen-hyde** [comment]
An update: I'm still getting this error occasionally but have noticed it happens after switching from or to an external screen. Is doesn't happen every time, just sometimes .. an OSX bug for sure.

**Comment by coen-hyde** [comment]
An update: I'm still getting this error occasionally but have noticed it happens after switching from or to an external screen. Is doesn't happen every time, just sometimes .. an OSX bug for sure.

**Comment by lox** [comment]
What version of macOS are you on these days?

**Comment by netors** [comment]
Same issue here on OS X Yosemite 10.10.5 very annoying, have not found any way to fix it other than rebooting

**Comment by lox** [comment]
@netors and it's happening repeatedly?

**Comment by calvis** [comment]
I encountered this 'dreaded' issue this morning while using aws-vault v0.3.4 (at first).  I am using 10.10.4 Yosemite.  Here's an account of what happened if this is at all useful:

First encountered this error from `aws-vault exec spark` in a fresh shell: 
```
2016/11/03 10:25:37 Parsing config file /Users/calvis/.aws/config
2016/11/03 10:25:37 Looking up keyring for spark
2016/11/03 10:25:37 Opening keychain /Users/calvis/Library/Keychains/aws-vault.keychain
2016/11/03 10:25:37 Error from keyring The user name or passphrase you entered is not correct.
No credentials found for profile "spark"
````
I rebooted, nothing changed.

I futzed around a bit then asked a colleague, he suggested I upgrade to v0.3.5 and I did.  Nothing changed.  I rebooted a few more times.  I repaired the keychain above using Keychain Access, and during the repair it reported it fixed a problem with that keychain.  However, `aws-vault exec spark` still errored in the same way as above.  I rebooted a few more times, still nothing.

Then I downgraded to v0.3.4.  Works perfectly, able to exec that profile.  Upgraded to v0.3.5, broken again.  Downgraded, works perfectly.

**Comment by coen-hyde** [comment]
I upgraded to OSX Sierria from El Capitan a week ago and haven't seen this bug since. This isn't conclusive evidence that it is fixed but it is looking good.

**Comment by shivangipatwardhan2018** [comment]
I am having the same issue with v3.7.1 using Version 10.9.5. Any pointers?

**Comment by coen-hyde** [comment]
@shivangipatwardhan2018 Upgrade OSX. I haven't had this issues since I upgraded to El Capitan. I'm on Sierra now and it's been fine too.

**Comment by phantomwhale** [comment]
Got this error myself after a full rebuild - solution is this doesn't work for anything other that Sierra now, so upgrade your MacOS

**Comment by johnlinvc** [comment]
I've face the same issue, got following message
```
aws-vault: error: Failed to get credentials for full (source profile for readonly): The specified item could not be found in the keyring.
```

Not sure if it related but I've changed the aws-vault keychain's lock after * minutes of inactivity setting to 720 mins.

The problem goes ways after I lock the keychain in keychain access and unlock it in aws-vault's prompt.

**Comment by stevenjw0228001** [comment]
running version 5.4.4 and getting this error when trying to execute "aws-vault exec terraform -- terraform plan"

swilliams@Stevens-MacBook-Pro Project_02_Master_Templates % aws-vault exec terraform -- terraform plan
aws-vault: error: exec: Error getting temporary credentials: profile terraform: credentials missing
swilliams@Stevens-MacBook-Pro Project_02_Master_Templates % aws-vault list
Profile                  Credentials              Sessions                 
=======                  ===========              ========                 
-                        Terraform                -                        
swilliams@Stevens-MacBook-Pro Project_02_Master_Templates % aws-vault --debug ls
2020/06/09 15:31:23 aws-vault v5.4.4
2020/06/09 15:31:23 [keyring] Considering backends: [keychain pass file]
2020/06/09 15:31:23 Loading config file /Users/swilliams/.aws/config
2020/06/09 15:31:23 Parsing config file /Users/swilliams/.aws/config
2020/06/09 15:31:23 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/06/09 15:31:23 [keyring] Found 1 results
2020/06/09 15:31:23 Looking up all keys in keyring
2020/06/09 15:31:23 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/06/09 15:31:23 [keyring] Found 1 results
Profile                  Credentials              Sessions                 
=======                  ===========              ========                 
-                        Terraform                -                        
swilliams@Stevens-MacBook-Pro Project_02_Master_Templates % aws-vault remove terraform
Delete credentials for profile "terraform"? (Y|n)y
aws-vault: error: The specified item could not be found in the keychain. (-25300)
swilliams@Stevens-MacBook-Pro Project_02_Master_Templates %

**Comment by jhonjairoveem** [comment]
I got the same error:

$ aws-vault exec veem -- env | grep AWS
aws-vault: error: exec: Error getting temporary credentials: profile ops: credentials missing

**Comment by ab-hackitnow** [comment]
can someone help pleas, I am getting                             
aws-vault: error: exec: Error getting temporary credentials: profile Undfederatedadministrator: credentials missing

aws-vault --debug ls 
2024/06/02 16:21:04 aws-vault v6.2.0
2024/06/02 16:21:04 [keyring] Considering backends: [secret-service]
2024/06/02 16:21:04 Loading config file /home/v/.aws/config
2024/06/02 16:21:04 Parsing config file /home/v/.aws/config
2024/06/02 16:21:04 Unrecognised ini file section: DEFAULT
2024/06/02 16:21:04 Unrecognised ini file section: profle Unfederatedadministrator
Profile                  Credentials              Sessions                    
=======                  ===========              ========                    
default                  -                        -                           
noble              noble              sts.GetSessionToken:33m11s
