### ISSUE TITLE
Unable to set --duration flag to exceed 1h

### ISSUE THREAD

**Issue by zbenamram** [99designs/aws-vault#493]
In versions below 4.7.1 and below I am able to execute the below command to chain roles and extend the duration of impersonation:
aws-vault exec sample_role --assume-role-ttl=12h --no-session 

In verions 5.0.0 and above, the above flags have been deprecated and advised to use:
aws-vault exec sample_role --duration=1h

the duration flag is limited to a maximum of 1 h. For backwards compat, this needs to be extended.

**Comment by hunttom** [comment]
Can you run `aws-vault exec sample_role --duration 8h --debug` (-d=8h, -d 8h, --duration 8h, --duration=8h) are fine.

I just ran it with 5.1.0 and it worked fine. It should give you a line with the expiration based on the hours: Example: Session "session,dG9taHVudGUrYg,,1578916267" expires in 7h59m26.003835s`

**Comment by mtibben** [comment]
Hey @zbenamram this is working for me - can you provide more details about your config and the `--debug` output`?

**Comment by zakswindow** [comment]
@mtibben same issue here.

**Comment by mtibben** [comment]
Fixed in #498

**Comment by zakswindow** [comment]
it's working now.
i used this command:
`aws-vault --debug exec sample-profile --duration 8h --no-session
