### ISSUE TITLE
Basic usage question - dealing with AWS_PROFILE?

### ISSUE THREAD

**Issue by chrismanderson** [99designs/aws-vault#494]
Hello! Trying out the tool for the first time and hit a stumbling block. I'm unable to tell `aws-cli` to use a profile different than `default` - when I'm trying to use a different profile.

My app uses the aws ruby sdk. Part of the SDK has a class for setting up credentials (https://docs.aws.amazon.com/sdkforruby/api/Aws/SharedCredentials.html) that references the `AWS_PROFILE` env variable. If it's not set, it assumes the profile will be 'default'.

So, I've tried to set that env variable both in my .zshrc file and the shell directly. I've also tried executing the was-vault command with something like 

`AWS_PROFILE=desired-profile aws-vault --debug exec desired-profile -- bundle exec rake pg:import`

But, in my app when it comes time to create that `Aws::SharedCredentials` class, `AWS_PROFILE` remains unset, the shared credentials attempt to load the `default` profile (which has no credentials) and my command fails. I tried setting `AWS_DEFAULT_PROFILE` as well, just in case, but that also did not work. I saw some various issues in this repo saying that the `AWS_PROFILE` gets unset when you use `aws-vault`, but I don't see a way to prevent that from happening when I need it to be set.

I saw the section in the usage document about overriding `aws-cli` to use `aws-vault` (https://github.com/99designs/aws-vault/blob/master/USAGE.md#overriding-the-aws-cli-to-use-aws-vault) that seemed somewhat related,

but when I tried pasting that command into my `.zshrc`, my terminal would immediately quit when I opened it, so that did not work.

I can log in and execute commands using `aws-vault` perfectly fine when the AWS_PROFILE is not needed for the command. My `~/.aws/config` is quite simple and is just 

```
[default]
region = us-east-1

[profile dev]

[profile prod]
mfa_serial = arn:aws:iam::000000000000:mfa/token
```

Feel like I must be missing something obvious here - any help is appreciated!

**Comment by mtibben** [comment]
By default aws-vault exposes credentials via env vars, which negates the need for aws config. However if you want aws cli or sdk to use credentials from aws-vault, you can use the `credentials_process` to achieve this - see https://github.com/99designs/aws-vault/blob/master/USAGE.md#using-credential-helper. Let us know how you go, and feel free to update docs to make this clearer

**Comment by mtibben** [comment]
Assuming this answer helped, feel free to update the docs!

**Comment by vishvish** [comment]
The credential helper docs have vanished from the USAGE and we too have this problem in which it appears that aws-vault overwrites the AWS_PROFILE in the env.

**Comment by mtibben** [comment]
ok fixed the link now @vishvish
