### ISSUE TITLE
Should AWS_SECURITY_TOKEN be removed or have a flag for it ?

### ISSUE THREAD

**Issue by mateimicu** [99designs/aws-vault#495]
The`AWS_SECURITY_TOKEN` is set and also `AWS_SESSION_TOKEN` but looking at this [article](https://aws.amazon.com/blogs/security/a-new-and-standardized-way-to-manage-credentials-in-the-aws-sdks/) it seems like `AWS_SESSION_TOKEN` is the standard.

Having both variables can cause weird problems like https://github.com/gruntwork-io/terragrunt/issues/998, I was wondering if it makes sense to add a flag for this variable or to remove it completely.

**Comment by mtibben** [comment]
Yes it probably makes sense to put these legacy env vars behind some flag

**Comment by mateimicu** [comment]
I'm new to golang but I'll try to propose a PR.

**Comment by mateimicu** [comment]
Created https://github.com/99designs/aws-vault/pull/516

**Comment by mtibben** [comment]
Closing for now, haven't heard of anyone else with issues and it's easy to unset in the shell if required
