### ISSUE TITLE
FEATURE REQUEST: Output URL rather than invoking local browser

### ISSUE THREAD

**Issue by QuinnyPig** [99designs/aws-vault#502]
On aws-vault login, having a flag to return the generated URL to STDOUT would be handy for a couple of use cases:
* Manipulating the generated login URL on remote systems without it opening a browser on that end
* Copying and pasting the URL into a Firefox container

**Comment by mtibben** [comment]
Hey @QuinnyPig, this already exists - see `aws-vault login --stdout`

**Comment by FernandoMiguel** [comment]
@QuinnyPig
Shell support for Firefox containers 
 https://github.com/FernandoMiguel/aws-vault-quick-guide/blob/master/browsers.md#firefox

**Comment by philcruz** [comment]
This doesn't work for AWS SSO profiles. That's a feature request under https://github.com/99designs/aws-vault/issues/678
