### ISSUE TITLE
Bash autocompletion broke in most recent release?

### ISSUE THREAD

**Issue by e1ven** [99designs/aws-vault#506]
I am running Ubuntu 19.10 amd64.
I upgraded from v4.71 to v5.2.0

Previous, after running `eval "$(aws-vault --completion-script-bash)"`, I could type "aws-vault exec [tab]" and it would display a list of profiles. (It wouldn't autocomplete them in the prompt, but it would list them..)

After upgrading, starting a new shell, and running the `eval`, it looks like there may be a bug.

The initial command works as it did previously.
```
Sawbones:tmp$ aws-vault  [tab]
add     exec    help    list    login   remove  rotate
```
`aws-vault exec [tab]` crashes `aws-vault`.
```
$ aws-vault exec [tab]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x9a458a]

goroutine 1 [running]:
github.com/99designs/aws-vault/vault.(*ConfigFile).ProfileSections(0x0, 0x0, 0xc000202800, 0x1)
	github.com/99designs/aws-vault@/vault/config.go:150 +0x3a
github.com/99designs/aws-vault/vault.(*ConfigFile).ProfileNames(0x0, 0xf0, 0xc00024c4b0, 0x0)
```

Perhaps there is a config file change I need to make?

**Comment by mtibben** [comment]
Fixed in v5.2.1
