### ISSUE TITLE
Infinite recursion checking macOS keychain

### ISSUE THREAD

**Issue by jameshiew** [99designs/aws-vault#507]
Version: v5.2.0
on macOS 10.15.2

Running `aws-vault --debug login default` results in infinite logs like

```
2020/01/22 22:57:17 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/01/22 22:57:17 [keyring] Found 0 results
```

Without the `--debug` flag the program appears to be hanging.

I have a `default` profile in my `.aws/config` file, but the same issue can occur if a non-existent profile string is used.

**Comment by jameshiew** [comment]
Adding an error if empty string for the `keyring.CredentialKeyring.Has(string)` method prevents the infinite loop.

```go
func (ck *CredentialKeyring) Has(credentialsName string) (bool, error) {
	if credentialsName == "" {
		return false, fmt.Errorf("empty credential name")
	}
```

`vault.MasterCredentialsFor` can end up calling that func over and over with an empty string. I don't have enough context though to know if handling it with an error like above is appropriate though.

**Comment by mtibben** [comment]
dupe #545
