### ISSUE TITLE
add a way to make --no-session forks usable in scripts

### ISSUE THREAD

**Issue by bleachbyte** [99designs/aws-vault#509]
From all that I can tell, from experimenting and reading online, running `aws vault exec $PROFILE --no-session` can be used to do an API AssumeRole call directly (and avoid the restriction on role chaining). However, both this command, and using the `--server` flag, `fork` the current shell whenever they are invoked.

This is confusing on its own (I don't think there's any documentation for this?), but frustrating as it appears there is no way to do the following sequence of commands, together, in a function/script:

1. run `aws vault exec $PROFILE --no-session --duration 4h` to do the API call and keep the role in place for 4 hours
2. run a "long" process, i.e. `terraform apply`, using the role invoked by `--no-session` above

The point of using `--no-session` is to allow a command like `terraform apply` to run continuously without its session having expired (which has lead to extremely broken `tfstate` files in the past). The use case here is to be able to create a script, or even a small function, which will run the AssumeRole call _and then_ immediately proceed to whatever command follows it.

The closest I can get is passing a command to it in quotes, but despite its `env` being the same as that of the parent shell, `aws-vault` is still reticent to work:

```
vault-test () {
    aws-vault exec dev-admin --no-session 'echo $$'
}

$ vault-test
aws-vault: error: exec: "echo $$": executable file not found in $PATH
```

This behavior is exhibited no matter what command one throws at it:

```
vault-test () {
    aws-vault exec dev-admin --no-session 'terraform --version'
}

$ vault-test
aws-vault: error: exec: "terraform --version": executable file not found in $PATH
```

I might be missing something due to the way Bash/`zsh`/`golang` is doing forks/subshells here -- and, if so, please let me know what I should do instead! -- but if not, I feel like this is behavior that should be possible to do.

**Comment by jimbocoder** [comment]
@bleachbyte I use this pattern for long terraform runs: `aws-vault exec --no-session $PROFILE -- terraform apply`  If I understand correctly, that should be all you need to get up to 12 hours with an assumed role. Hope that's helpful.

**Comment by FnTm** [comment]
Just to add a bit to what @jimbocoder said above - the `--` between the exec and the command you're trying to exec is the important part which will actually tell aws-vault that this is the end of flags, and what follows is the actual command to be invoked with the new environment variables.

**Comment by mtibben** [comment]
As of v5.2.0, you don't even need the `--no-session`. If you specify a role duration over an hour, aws-vault will skip the session. So it's simply `aws-vault exec --duration=12h -- cmd-to-exec`

**Comment by mtibben** [comment]
Closing, assuming v5.2.0 has solved this issue
