### ISSUE TITLE
MFA Session not being reused

### ISSUE THREAD

**Issue by yarinb** [99designs/aws-vault#511]
My config worked well before the latest upgrade to v5.1.2

Now even though I have a session duration set to 1 hour, aws-vault starts a new session (and new MFA request).

Here's the output for two consecutive runs... (about a 30 seconds apart)

```
➜  repo git:(master) ✗ aws-vault exec --debug production -- aws s3 ls
2020/01/28 16:20:53 [keyring] Considering backends: [keychain pass file]
2020/01/28 16:20:53 Loading config file /Users/userxx/.aws/config
2020/01/28 16:20:53 Parsing config file /Users/userxx/.aws/config
2020/01/28 16:20:53 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/01/28 16:20:53 [keyring] Found 2 results
2020/01/28 16:20:53 profile production: using stored credentials
2020/01/28 16:20:53 profile production: using AssumeRole (using MFA)
Enter token for arn:aws:iam::400000000000:mfa/userxx: 123456
2020/01/28 16:21:05 Looking up keyring for 'production'
2020/01/28 16:21:05 [keyring] Querying keychain for service="aws-vault", account="production", keychain="aws-vault.keychain"
2020/01/28 16:21:05 [keyring] Found item "aws-vault (production)"
2020/01/28 16:21:06 Generated credentials ****************SVWL using AssumeRole, expires in 59m59.238157s
2020/01/28 16:21:06 Setting subprocess env: AWS_DEFAULT_REGION=us-west-2, AWS_REGION=us-west-2
2020/01/28 16:21:06 Setting subprocess env: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
2020/01/28 16:21:06 Setting subprocess env: AWS_SESSION_TOKEN, AWS_SECURITY_TOKEN
2020/01/28 16:21:06 Setting subprocess env: AWS_SESSION_EXPIRATION
2019-08-07 16:26:35 cf-templates-oahsdljhaksudhasd-west-2
2019-02-28 14:39:14 io.9a8hsdajlshdkjahsd.assets


➜  repo git:(master) ✗ aws-vault exec --debug production -- aws s3 ls
2020/01/28 16:21:26 [keyring] Considering backends: [keychain pass file]
2020/01/28 16:21:26 Loading config file /Users/userxx/.aws/config
2020/01/28 16:21:26 Parsing config file /Users/userxx/.aws/config
2020/01/28 16:21:26 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/01/28 16:21:26 [keyring] Found 2 results
2020/01/28 16:21:26 profile production: using stored credentials
2020/01/28 16:21:26 profile production: using AssumeRole (using MFA)
Enter token for arn:aws:iam::400000000000:mfa/userxx: 234567
2020/01/28 16:21:34 Looking up keyring for 'production'
2020/01/28 16:21:34 [keyring] Querying keychain for service="aws-vault", account="production", keychain="aws-vault.keychain"
2020/01/28 16:21:34 [keyring] Found item "aws-vault (production)"
2020/01/28 16:21:35 Generated credentials ****************3ZAC using AssumeRole, expires in 59m59.819175s
2020/01/28 16:21:35 Setting subprocess env: AWS_DEFAULT_REGION=us-west-2, AWS_REGION=us-west-2
2020/01/28 16:21:35 Setting subprocess env: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
2020/01/28 16:21:35 Setting subprocess env: AWS_SESSION_TOKEN, AWS_SECURITY_TOKEN
2020/01/28 16:21:35 Setting subprocess env: AWS_SESSION_EXPIRATION
2019-08-07 16:26:35 cf-templates-oahsdljhaksudhasd-west-2
2019-02-28 14:39:14 io.9a8hsdajlshdkjahsd.assets
➜  repo git:(master) ✗
```

**Comment by mtibben** [comment]
Please run on the latest aws-version, and provide config and `--debug` output

**Comment by TheNamesJF** [comment]
Same here.
Cant assume role using a base (source) profile.  
running latest version of everything:
aws-vault-linux-amd64 --version
v5.2.0
aws --version
aws-cli/1.17.9 Python/2.7.16 Linux/4.14.154-128.181.amzn2.x86_64 botocore/1.14.9

> aws-vault-linux-amd64 exec --debug tick-prod
> 2020/01/31 14:29:36 [keyring] Considering backends: [pass file]
> 2020/01/31 14:29:36 [keyring] Failed backend pass: The pass program is not available
> 2020/01/31 14:29:36 Loading config file /home/ec2-user/.aws/config
> 2020/01/31 14:29:36 Parsing config file /home/ec2-user/.aws/config
> 2020/01/31 14:29:36 [keyring] Expanded file dir to /home/ec2-user/.awsvault/keys/
> 2020/01/31 14:29:36 [keyring] Expanded file dir to /home/ec2-user/.awsvault/keys/
> 2020/01/31 14:29:36 profile jf: using stored credentials
> **2020/01/31 14:29:36 profile jf: skipping GetSessionToken because profile 'tick-prod' has no MFA serial defined**
> 2020/01/31 14:29:36 profile tick-prod: using AssumeRole
> 2020/01/31 14:29:36 Looking up keyring for 'jf'
> 2020/01/31 14:29:36 [keyring] Expanded file dir to /home/ec2-user/.awsvault/keys/
> 2020/01/31 14:29:36 [keyring] Expanded file dir to /home/ec2-user/.awsvault/keys/
> Enter passphrase to unlock /home/ec2-user/.awsvault/keys/:
> aws-vault: error: exec: Failed to get credentials for tick-prod: AccessDenied: User: arn:aws:iam::111111111111:user/jf@isp.net is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::222222222222:role/OrganizationAccountAccessRole
>         status code: 403, request id: 15ffdbfd-4460-11ea-bbd7-23fffffffff7df


Works using aws-vault v4.6.3:

> aws-vault-linux-v463 exec --debug tick-prod
> 2020/01/31 14:33:58 [keyring] Considering backends: [pass file]
> 2020/01/31 14:33:58 [keyring] Failed backend pass: The pass program is not available
> 2020/01/31 14:33:58 Loading config file /home/ec2-user/.aws/config
> 2020/01/31 14:33:58 Parsing config file /home/ec2-user/.aws/config
> 2020/01/31 14:33:58 Looking for sessions for tick-prod
> 2020/01/31 14:33:58 Looking up all keys in keyring
> 2020/01/31 14:33:58 [keyring] Expanded file dir to /home/ec2-user/.awsvault/keys/
> 2020/01/31 14:33:58 Session "jf session (1580513309)" expires in 3h54m30.939601113s
> 2020/01/31 14:33:58 Session not found in keyring for tick-prod
> 2020/01/31 14:33:58 Looking for sessions for jf
> 2020/01/31 14:33:58 Looking up all keys in keyring
> 2020/01/31 14:33:58 [keyring] Expanded file dir to /home/ec2-user/.awsvault/keys/
> 2020/01/31 14:33:58 Session "jf session (1580513309)" expires in 3h54m30.939231962s
> 2020/01/31 14:33:58 [keyring] Expanded file dir to /home/ec2-user/.awsvault/keys/
> 2020/01/31 14:33:58 [keyring] Expanded file dir to /home/ec2-user/.awsvault/keys/
> Enter passphrase to unlock /home/ec2-user/.awsvault/keys/:
> 2020/01/31 14:34:00 Using session ****************SDRS, expires in 3h54m28.213558308s
> 2020/01/31 14:34:00 Using session ****************SDRS, expires in 3h54m28.213482271s
> 2020/01/31 14:34:00 Using region "us-east-1" from profile
> 2020/01/31 14:34:00 Assuming role arn:aws:iam::222222222222:role/OrganizationAccountAccessRole from session token
> 2020/01/31 14:34:00 Using role ****************VT4B (from session token), expires in 14m59.141632994s
> 2020/01/31 14:34:00 Setting subprocess env: AWS_DEFAULT_REGION=us-east-1, AWS_REGION=us-east-1
> 2020/01/31 14:34:00 Setting subprocess env: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
> 2020/01/31 14:34:00 Setting subprocess env: AWS_SESSION_TOKEN, AWS_SECURITY_TOKEN

**Comment by TheNamesJF** [comment]
Config used:
[profile jf]
region=us-east-1
output=json
mfa_serial=arn:aws:iam::111111111111:mfa/jf@isp.net

[profile tick-prod]
source_profile=jf
region=us-east-1
role_arn=arn:aws:iam::222222222222:role/OrganizationAccountAccessRole

**Comment by mtibben** [comment]
Yes this is expected behaviour, the chaining implementation between v4 and v5 changed substantially. You'll need to add mfa_serial to tick-prod as the --debug output indicates

**Comment by mtibben** [comment]
Closing, assuming specifying mfa_serial in the profile solves this issue
