### ISSUE TITLE
Hong Kong and Bahrain: AWS was not able to validate the provided access credentials

### ISSUE THREAD

**Issue by nshenry03** [99designs/aws-vault#512]
I was unable to use aws-vault with Hong Kong (ap-east-1) and Bahrain (me-south-1):

```NOFORMAT
$ aws-vault exec production -- aws ec2 describe-instances --region ap-east-1
An error occurred (AuthFailure) when calling the DescribeInstances operation: AWS was not able to validate the provided access credentials
```

It worked in all other regions, just not those two (even though Bahrain and Hong Kong regions were enabled)...

After lots of digging, I found [this](https://docs.amazonaws.cn/en_us/IAM/latest/APIReference/API_SetSecurityTokenServicePreferences.html):

> If you make an STS call to the global endpoint, the resulting session tokens might be valid in some Regions but not others. It depends on the version that is set in this operation. Version 1 tokens are valid only in AWS Regions that are available by default. These tokens do not work in manually enabled Regions, such as Asia Pacific (Hong Kong). Version 2 tokens are valid in all Regions. However, version 2 tokens are longer and might affect systems where you temporarily store tokens. For information, see Activating and Deactivating STS in an AWS Region in the IAM User Guide.

I was able to fix the issue with this:

```NOFORMAT
# Get current endpoint token version
$ aws-vault exec production -- aws iam get-account-summary | jq .SummaryMap.GlobalEndpointTokenVersion
1

# Set endpoint token version to v2 (and make sure command was a success)
$ aws-vault exec production -- aws iam set-security-token-service-preferences --global-endpoint-token-version v2Token
$ echo $?
0

# Double check to be sure that endpoint token version is now v2
$ aws-vault exec production -- aws iam get-account-summary | jq .SummaryMap.GlobalEndpointTokenVersion
2

# Test to be sure it works!
$ aws-vault exec production -- aws ec2 describe-instances --region ap-east-1
```

**Comment by StevePavlin** [comment]
For anyone else getting this and using an SDK, make sure sessionToken (set by AWS vault as AWS_SESSION_TOKEN) is being provided in the credentials alongside the access key id and secret access key. 😅
