### ISSUE TITLE
MFA vs Password Prompt order

### ISSUE THREAD

**Issue by TheNamesJF** [99designs/aws-vault#515]
Is it just me or... 
Asking for the MFA before the keyring password is confusing. (changed behavior)
Because of old habits, I'm now entering the password in clear in the MFA prompt too often.... >_<

> aws-vault exec jf
> Enter token for arn:aws:iam::111111111111:mfa/jf@isp.net: Super_Secret_password_in_clear_here_for_'everyone'_to_see
> Enter passphrase to unlock /home/ec2-user/.awsvault/keys/:
> aws-vault: error: exec: Failed to get credentials for jf: aes.KeyUnwrap(): integrity check failed.

*fcuk*

v5.2.0
using config like so:
[profile jf]
region=us-east-1
output=json
mfa_serial=arn:aws:iam::111111111111:mfa/jf@isp.net

**Comment by mtibben** [comment]
Ha yes muscle memory is hard one to overcome. In v5 the prompts come on-demand, only when aws-vault requires them. This was to fix a bunch of bugs around multiple prompts to unlock, but yes things might get prompted in a different order now
