### ISSUE TITLE
aws-vault rotate (CLI cmd) interprets slashes in SecretAccessKey literally

### ISSUE THREAD

**Issue by KyleJGreen** [99designs/aws-vault#517]
If someone's SecretAccessKey contains a slash in its String, the aws-vault rotate command for the cli interprets that slash literally when it builds the call to aws sts, which leads to an IncompleteSignature error, because it expects a slash delineated signature with exactly five fields in a particular order.

**Comment by mtibben** [comment]
Can you provide an example with full `--debug` output?
