### ISSUE TITLE
Rename `parent_profile`

### ISSUE THREAD

**Issue by mtibben** [99designs/aws-vault#520]
On reflection this name isn't great. It's not so much a parent-child relationship, it's a horizontal import of config.

Some potentials:
 - `template_profile`
 - `mixin_profile`
 - `include_profile`
 - `import_profile`

Any thoughts @j0hnsmith or anyone else using this feature?

**Comment by j0hnsmith** [comment]
I like `include_profile` or even `extend_profile`. 

I have `source_profile` and `parent_profile` on nearly every entry in my `~/.aws/config`, I'm guessing it's not possible but would be nice to simply add the behaviour to wherever `source_profile` is specified.

```
[profile root]
mfa_serial=arn:aws:iam::123456789:mfa/johnsmith
region=eu-west-1

[profile order-dev]
source_profile = root
parent_profile = root
role_arn=arn:aws:iam::123456789:role/developers

[profile order-staging-admin]
source_profile = root
parent_profile = root
role_arn=arn:aws:iam::123456789:role/administrators

...
```

**Comment by mtibben** [comment]
Could you use this?

```ini
[profile default]
mfa_serial=arn:aws:iam::123456789:mfa/johnsmith
region=eu-west-1

[profile order-dev]
source_profile = default
role_arn=arn:aws:iam::123456789:role/developers

[profile order-staging-admin]
source_profile = default
role_arn=arn:aws:iam::123456789:role/administrators
```

**Comment by j0hnsmith** [comment]
Doesn't work... unless I change `ParentProfile` to `SourceProfile` on these lines.

https://github.com/99designs/aws-vault/blob/31055701a599ca34e4f95fac0bb9478daf1c3ff2/vault/config.go#L300-L301

Not sure if that's valid or not, [this](https://aws.amazon.com/blogs/security/how-to-use-a-single-iam-user-to-easily-access-all-your-accounts-by-using-the-aws-cli/) seems to indicate it is.

**Comment by mtibben** [comment]
Oh my bad, it's `default` not `profile default`. Fixed above. Try again

**Comment by j0hnsmith** [comment]
I use multiple `mfa_serial`s so it's not practical for one to be specified in `[default]`.

The changes in https://github.com/99designs/aws-vault/commit/f26b718f741a3f5c51809982539e6d7a1b6f4280 (and possibly also https://github.com/99designs/aws-vault/commit/1ce365597489943c2894d3265280933af28de102) have broken my setup but rather than talk about my config can we confirm what _should_ be a valid config then compare the current behaviour to the desired behaviour?

```
[profile root]
mfa_serial=arn:aws:iam::123456789:mfa/johnsmith
region=eu-west-1

[profile order-dev]
source_profile = root
role_arn=arn:aws:iam::123456789:role/developers

[profile order-staging-admin]
source_profile = root
role_arn=arn:aws:iam::123456789:role/administrators
...
```

With this config only `root` should need to be added via `aws-vault add root` (and only `root` get a cached session in keychain), when using the `order-dev` and `order-staging-admin` the auth is done via `root` then creds generated as necessary? Do you agree?

**Comment by j0hnsmith** [comment]
I've just realised by reading another issue and doing some research that `[default]` is simply the profile that's used unless another named one is specified. I had thought that it was where default keys were set and inherited by other profiles.

**Comment by j0hnsmith** [comment]
> Could you use this?
>
>```
>[default]
>mfa_serial=arn:aws:iam::123456789:mfa/johnsmith
>region=eu-west-1
>source_profile = root
>
>[profile root]
>```

Since `root` is empty I don't understand what `source_profile = root` is supposed to do in `[default]`.

Sorry to have polluted this issue with my misunderstanding however given the config in https://github.com/99designs/aws-vault/pull/526 does everything I want (with the PR) I'm not sure what `parent_profile` offers. If there are few users/uses can it be deprecated then removed at some point in the future?

**Comment by mtibben** [comment]
Hey @j0hnsmith yes it seems you have quite a complex config.

> I use multiple mfa_serials so it's not practical for one to be specified in [default].

OK so it would be best to keep that in it's own profile fragment then

> With this config only `root` should need to be added via `aws-vault add root` (and only `root` get a cached session in keychain), when using the `order-dev` and `order-staging-admin` the auth is done via `root` then creds generated as necessary? Do you agree?

Yes, with the caveat that no config can be "inherited" by `order-dev` and `order-staging-admin`. Those profiles are simply nominating where to find the master (or role-chained) credentials. `mfa_serial` in your config has no effect unless `root` is used directly, or it is used in the context of role-chaining.

So then you could have a config like:
```ini
[profile root-common]
region=eu-west-1
mfa_serial=arn:aws:iam::123456789:mfa/johnsmith

[profile root]
parent_profile = root-common

[profile order-dev]
source_profile = root
parent_profile = root-common
role_arn=arn:aws:iam::123456789:role/developers

[profile order-staging-admin]
source_profile = root
parent_profile = root-common
role_arn=arn:aws:iam::123456789:role/administrators
```


> I've just realised by reading another issue and doing some research that `[default]` is simply the profile that's used unless another named one is specified

`[default]` contains config that gets included by every profile


> Since `root` is empty I don't understand what `source_profile = root` is supposed to do in `[default]`.

`[default]` contains config that gets included by every profile, so putting `source_profile` there means every profile would get `source_profile = root`

**Comment by mtibben** [comment]
I'm leaning towards `include_profile`. In the above example it would be much clearer to be seeing `include_profile` rather than `parent_profile`. I'm still partial to `mixin_profile` though as it describes exactly what is going on. 

For example, using the config from the above config

```ini
[profile root-common]
region=eu-west-1
mfa_serial=arn:aws:iam::123456789:mfa/johnsmith
source_profile = root

[profile root]
include_profile = root-common

[profile order-dev]
include_profile = root-common
role_arn=arn:aws:iam::123456789:role/developers

[profile order-staging-admin]
include_profile = root-common
role_arn=arn:aws:iam::123456789:role/administrators
```

**Comment by j0hnsmith** [comment]
> So then you could have a config like:
> 
>```
>[profile root-common]
>region=eu-west-1
>mfa_serial=arn:aws:iam::123456789:mfa/johnsmith
>source_profile = root
>
>[profile root]
>parent_profile = root-common
>
>[profile order-dev]
>parent_profile = root-common
>role_arn=arn:aws:iam::123456789:role/developers
>
>[profile order-staging-admin]
>parent_profile = root-common
>role_arn=arn:aws:iam::123456789:role/administrators
>```

I like it, I hate it, I like it, I hate it.... 

That `root` and `root-common` essentially point at each other (in different ways) is the bit I don't like and it's not intuitive however it's necessary. I do like that it will simplify my config.

`mixin_profile` does indeed make sense as that exactly describes what's happening and good naming places less importance on documentation 👍

**Comment by mtibben** [comment]
> That root and root-common essentially point at each other (in different ways) is the bit I don't like, it's not intuitive however it's necessary. I do like that it will simplify my config.

You could also also make the config more terse with
```ini
[profile root]
region=eu-west-1
mfa_serial=arn:aws:iam::123456789:mfa/johnsmith
source_profile = root

[profile order-dev]
parent_profile = root
role_arn=arn:aws:iam::123456789:role/developers

[profile order-staging-admin]
parent_profile = root
role_arn=arn:aws:iam::123456789:role/administrators
```

It's just non intuitive to have `source_profile = root` in the root profile, so I didn't want to confuse things initially

**Comment by j0hnsmith** [comment]
Lol. Good luck documenting that.

**Comment by j0hnsmith** [comment]
It does make sense though, however much it makes you want to scream.

**Comment by mtibben** [comment]
> Lol. Good luck documenting that.

Exactly..

Three paths we can take here I think

**1. Use a different keyword for profile fragments.** This makes the config quite explicit. There are no mixing of terms. You won't be able to store credentials against a mixin

```ini
[mixin root-common]
region=eu-west-1
mfa_serial=arn:aws:iam::123456789:mfa/johnsmith
source_profile = root

[profile root]
include_mixin = root-common

[profile order-dev]
include_mixin = root-common
role_arn=arn:aws:iam::123456789:role/developers

[profile order-staging-admin]
include_mixin = root-common
role_arn=arn:aws:iam::123456789:role/administrators
```

**2. Revert back to implicit behaviour using parent_profile**. The original behaviour of v5.0.0 was to use the parent_profile credentials as the source_profile *implicitly*. I backed away from this in v5.1.0 because I found it confusing explaining the hierarchy when issues started coming in. The config is not explicit about what profile is being used for credentials. I believe this is the path you've been asking for @j0hnsmith. The question is whether implicit behaviour is desirable and able to be documented satisfactorily

```ini
[profile root]
region=eu-west-1
mfa_serial=arn:aws:iam::123456789:mfa/johnsmith

[profile order-dev]
parent_profile = root
role_arn=arn:aws:iam::123456789:role/developers

[profile order-staging-admin]
parent_profile = root
role_arn=arn:aws:iam::123456789:role/administrators
```

**3. Keep the current behaviour, but change the keyword to `include_profile`**. The original proposal of this PR. The upside is flexibility, there are quite a few ways you can compose your config using this construct. It's also explicit config, there should be no surprises. The downside is flexibility. Because profiles can be used as will as imported, there are more ways to break your config, or store credentials against a fragment.

```ini
[profile root-common]
region=eu-west-1
mfa_serial=arn:aws:iam::123456789:mfa/johnsmith
source_profile = root

[profile root]
include_profile = root-common

[profile order-dev]
include_profile = root-common
role_arn=arn:aws:iam::123456789:role/developers

[profile order-staging-admin]
include_profile = root-common
role_arn=arn:aws:iam::123456789:role/administrators
```

**Comment by j0hnsmith** [comment]
I've written then deleted a few different comments that had differing views. All of the paths have pros & cons. I think the answer is to go with what you are most comfortable explaining/documenting but also that would have the cleanest implementation. Do the simplest thing.
