### ISSUE TITLE
session-timeout not working correctly

### ISSUE THREAD

**Issue by stevecookms** [99designs/aws-vault#524]
My logins last about 15 minutes.

The Maximum CLI/API session duration on the role I am assuming is: 4 hours.

Am I doing something wrong?

- [x] I am using the latest release of AWS Vault

Yes

- [x] I have provided my `.aws/config` (redacted if necessary)

steve@STEVE-9560:~$ cat ~/.aws/config
[profile steve]
mfa_serial = arn:aws:iam::xxxx:mfa/steve
duration_seconds = 7200

[profile ms-main-admin]
region = us-east-1
role_arn = arn:aws:iam::xxxxxx:role/AdministratorUserRole
source_profile = steve
duration_seconds = 7200

- [x] I have provided the debug output using `aws-vault --debug` (redacted if necessary)
steve@STEVE-9560:~$ aws-vault login ms-main-admin --debug
2020/02/14 13:50:22 [keyring] Considering backends: [pass file]
2020/02/14 13:50:22 [keyring] Failed backend pass: The pass program is not available
2020/02/14 13:50:22 Loading config file /home/steve/.aws/config
2020/02/14 13:50:22 Parsing config file /home/steve/.aws/config
2020/02/14 13:50:22 Looking for sessions for ms-main-admin
2020/02/14 13:50:22 Looking up all keys in keyring
2020/02/14 13:50:22 [keyring] Expanded file dir to /home/steve/.awsvault/keys/
2020/02/14 13:50:22 Session "session,xxxxxx" expires in 1h12m33.5135687s
2020/02/14 13:50:22 Session not found in keyring for ms-main-admin
2020/02/14 13:50:22 Looking for sessions for steve
2020/02/14 13:50:22 Looking up all keys in keyring
2020/02/14 13:50:22 [keyring] Expanded file dir to /home/steve/.awsvault/keys/
2020/02/14 13:50:22 Session "session,xxxxxx" expires in 1h12m33.5134269s
2020/02/14 13:50:22 [keyring] Expanded file dir to /home/steve/.awsvault/keys/
2020/02/14 13:50:22 [keyring] Expanded file dir to /home/steve/.awsvault/keys/
Enter passphrase to unlock /home/steve/.awsvault/keys/:
2020/02/14 13:50:28 Using session ****************, expires in 1h12m27.6470629s
2020/02/14 13:50:28 Using session ****************, expires in 1h12m27.6470077s
2020/02/14 13:50:28 Using region "us-east-1" from profile
2020/02/14 13:50:28 Assuming role arn:aws:iam::xxxxxxx:role/AdministratorUserRole from session token
2020/02/14 13:50:28 Using role **************** (from session token), expires in 14m59.4659432s
2020/02/14 13:50:28 Creating login token, expires in 12h0m0s
2020/02/14 13:50:28 exec: "xdg-open": executable file not found in $PATH

**Comment by mtibben** [comment]
The output doesn't look like it's from the latest release... what does `aws-vault --version` give you?

**Comment by stevecookms** [comment]
I updated to the latest version, and now I cannot get a session.

steve@STEVE-9560:~$ aws-vault --version
v5.3.0

steve@STEVE-9560:~$ aws-vault login ms-main-admin
Enter passphrase to unlock /home/steve/.awsvault/keys/:
aws-vault: error: Login failed: Failed to get credentials for ms-main-admin: AccessDenied: User: arn:aws:iam::xxxx:user/steve is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::xxxx:role/AdministratorUserRole
        status code: 403, request id: xxxxx

Here is my IAM policy:

"Effect": "Allow",
            "Action": "sts:AssumeRole",
            "Resource": "arn:aws:iam::xxxx:role/AdministratorUserRole"

**Comment by stevecookms** [comment]
Looks like I had a config issue.

I needed to add my mfa token to the individual profiles and it started working
