### ISSUE TITLE
Mixed-case profile names are valid, but unrecognized

### ISSUE THREAD

**Issue by jimbocoder** [99designs/aws-vault#528]
- [x] I am using the latest release of AWS Vault
- [ ] I have provided my `.aws/config` (redacted if necessary)
- [ ] I have provided the debug output using `aws-vault --debug` (redacted if necessary)

This was a result of merging [PR#461](https://github.com/99designs/aws-vault/pull/461) which in my opinion was ill-advised.

The whole motivation for the change was to make it possible for a specific class of typographical error accepted by `aws-vault`. Considering this change breaks existing configurations for teams like mine, that doesn't seem like a strong enough justification.

Profile names are case-sensitive in AWS SDKs. It only ini *keys* which should be case-insensitive.

Thus, it would be fine to lowercase the keys, I guess. But not the ini section names (which are the profile names). Unfortunately [PR#461](https://github.com/99designs/aws-vault/pull/461) was a little too broad in that sense. I would propose either:

1. Don't do any insensitivity. People should expect that invalid keys won't work.
1. Or, improve this changeset by only treating keys insensitively. It's going to be more code, but more correct.

**Comment by mtibben** [comment]
Yes this is unfortunate, and seems like a bigger problem than the issue fixed in #461... are we able to resolve this @jonhadfield or should we revert #461?

**Comment by jonhadfield** [comment]
The ini parsing library only has a boolean option 'insensitive' covering both:
`// Insensitive indicates whether the parser forces all section and key names to lowercase.  `
I was sure I tested the AWS CLI and it's python code to prove case insensitivity. I'll have another look.

**Comment by jonhadfield** [comment]
After checking behaviour I can confirm @jimbocoder is correct that section names are treated as case sensitive whilst key names are case insensitive.
Whilst the ini parsing library doesn't provide the option to apply case (in)sensitivity for section and key name independently, I'd suggest reverting the change.

I'll look for alternate options and raise a PR if I can find something that supports the AWS behaviour.

**Comment by jimbocoder** [comment]
Thanks for your consideration and looking into this, both of you! Looking forward to your findings and/or a resolution.

I don't know much about the internal workings/philosophies/standards of this project (nor golang), but I feel like it might be solved quickly with a regex that matches ini keys, but doesn't match ini sections, and lowercase the matches. (Although parsing a structured document like that [might summon objectors](https://stackoverflow.com/a/1732454)) :wink:

**Comment by nbrys** [comment]
Also, if you do `aws-vault add Operations`, the profile in ~/.aws/config is called [operations]. When using this profile as source_profile, aws-vault is unable to find the credentials.
