### ISSUE TITLE
Add --region to login

### ISSUE THREAD

**Issue by iconara** [99designs/aws-vault#531]
Being able to specify which region to end up in when using `aws-vault login` would be a great complement to the `--path` flag.

I noticed that setting `AWS_REGION` achieves this. However I don't have this variable set in my shell, and I don't have a region specified in my `~/.aws/config` profiles, because I often work with multiple regions and want to be explicit to avoid mistakes.

When I use `aws-vault login` I end up in us-east-2 and usually have to change regions.

I would love to be able to do `aws-vault login my-profile --region=eu-north-1 --path=lambda` for example.

**Comment by mtibben** [comment]
Does this work for you? `AWS_REGION=eu-north-1 aws-vault login my-profile --path=lambda`

**Comment by iconara** [comment]
@mtibben I didn't mention it specifically, but that is a (slightly unergonomic) workaround in bash and zsh, but unfortunately not as well in for example fish. To avoid having to type all of `aws-vault login`, I have, as I suspect many others, an alias (function in fish) called `avl`. In fish you can't set per-command environment variables like in bash, you have to use `env`, and that means the command is no longer interpreted by fish, and aliases can't be used. E.g. `env AWS_REGION=eu-north avl my-profile -s --path=lambda | pbcopy` does not work.
