### ISSUE TITLE
AWS Vault ignores prompt terminal on OSX

### ISSUE THREAD

**Issue by javatarz** [99designs/aws-vault#535]
## Command executed
`aws-vault --prompt=terminal login dev`
or
`aws-vault login dev --prompt=terminal`
(this is not a command-specific issue, I've seen this pop up when any `aws-vault` command is used)

## Expected result
Prompt for password is on the terminal instead of the OS dialogue box

## Actual result
OS dialogue box pops up

## Debug output
```
2020/02/28 13:01:04 aws-vault v5.3.2
2020/02/28 13:01:04 [keyring] Considering backends: [keychain pass file]
2020/02/28 13:01:04 Loading config file /Users/karun/.aws/config
2020/02/28 13:01:04 Parsing config file /Users/karun/.aws/config
2020/02/28 13:01:04 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/02/28 13:01:04 [keyring] Found 6 results
2020/02/28 13:01:04 Looking up keyring for 'dev'
2020/02/28 13:01:04 [keyring] Querying keychain for service="aws-vault", account="dev", keychain="aws-vault.keychain"
2020/02/28 13:01:19 [keyring] No results found
aws-vault: error: Login failed: The specified item could not be found in the keyring
```

## AWS Config
```
[profile production]
region=eu-west-1

[profile dev]
region=eu-west-1

[default]
region=eu-west-1
s3=
  max_concurrent_requests = 50
```

## System Details
1. Mac OSX 10.15.3
2. iTerm 3.3.9
3. zsh 5.8 (x86_64-apple-darwin19.3.0)
4. v5.3.2

**Comment by mtibben** [comment]
Hey @javatarz you're seeing the Keychain dialog, not an aws-vault dialog. See the docs at https://github.com/99designs/aws-vault/blob/master/USAGE.md#keychain
