### ISSUE TITLE
Add support for aws-vault config file

### ISSUE THREAD

**Issue by olfway** [99designs/aws-vault#537]
Now you have to specify aws-vault parameters as args or environment variables

It would be convenient to be able to load parameters from config file

For example, my ~/.aws/config
```
[profile A]
region = eu-central-1
mfa_serial = arn:aws:iam::111111111111:mfa/user
credential_process = aws-vault --backend=pass --pass-prefix=aws-vault --prompt=osascript exec A --json
```
I would like to have `--backend=pass --pass-prefix=aws-vault --prompt=osascript` stored in some config file as defaults

**Comment by mtibben** [comment]
Perhaps something like this?
```ini
[default]
region = eu-central-1
aws_vault_backend = pass
aws_vault_pass_prefix = aws-vault
aws_vault_prompt = osascript

[profile A]
...
```

PRs welcome
