### ISSUE TITLE
Show account alias in mfa prompt

### ISSUE THREAD

**Issue by olfway** [99designs/aws-vault#538]
Right now aws-vault prints mfa arn:
```
Enter token for arn:aws:iam::1111111111111:mfa/username: 
```
but if you have several accounts, it's difficult to find what mfa do you need

I think it will be better to print account name here, or maybe make this configurable

```
[profile root]
region = eu-central-1
mfa_serial = arn:aws:iam::11111111111:mfa/username
```

```
Enter token for root:
```
оr
```
Enter token for username@root
```

**Comment by mtibben** [comment]
Thanks for the suggestion @olfway. As profiles can use different MFA devices, this would add indirection and may cause confusion. Best to be explicit
