### ISSUE TITLE
Storing arbitrary secret data with profiles

### ISSUE THREAD

**Issue by coen-hyde** [99designs/aws-vault#54]
This is probably outside the scope of aws-vault but I would like to store other data along side the aws profile. In my use case this would be an auth token to another service related to the aws profile. I only want this token exposed once credentials have been successfully created. What are your thoughts?

**Comment by lox** [comment]
Store it in s3?

**Comment by coen-hyde** [comment]
That's not a bad idea. With the appropriate policies and acl it should be safe. But it doesn't feel right, let me think about this :). Cheers.

**Comment by lox** [comment]
Alternately, KMS + S3: https://github.com/codahale/sneaker

**Comment by lox** [comment]
https://github.com/fugue/credstash is another alternative that uses DynamoDB. It looks like the best fit for what you are looking for.

**Comment by coen-hyde** [comment]
I'm just going to pgp encrypt the data. Thanks for the links
