### ISSUE TITLE
--server on linux runs whole aws-vault as root

### ISSUE THREAD

**Issue by gdamjan** [99designs/aws-vault#541]
I have aws-vault setup on linux, KDE, using Kwallet (which is additionally supported by GPG). 
`aws-vault exec profile -- aws …` commands work just fine. But there's an issue when trying to use it with the `--server` flag.

`aws-vault exec --server profile -- k9s` asks for a sudo password, and then it seems to start aws-vault fully as root, and then tries to use a root kwallet (which doesn't exist).

I believe the `--server` option should just start a helper as `root` to setup the needed redirections of `169.254.169.254:80`and then continue as the normal user.

```
aws-vault --version
v5.3.2
```

**Comment by gdamjan** [comment]
for ex. on Linux I could setup iptables like this[1], to redirect all local traffic for  169.254.169.254:80 to 127.0.0.1:8080. I'm even fine with doing this manually, if aws-vault would just start it's faux metadata server on any port on localhost.

[1]
```
sudo iptables -t nat -I OUTPUT 1 -p tcp -d 169.254.169.254 --dport 80 -j DNAT --to 127.0.0.1:8080
```

ps.
Now that I think of it, I might need another iptables rule (PREROUTING) if I want to redirect traffic from docker containers or VMs, so perhaps the best way would be if I can explicitly start the server, with something like `aws-vault server --port 9876`.

**Comment by mtibben** [comment]
> I believe the --server option should just start a helper as root to setup the needed redirections of 169.254.169.254:80and then continue as the normal user.

Yes this is exactly how it should be working. If it's not feel free to submit a PR

**Comment by mtibben** [comment]
FYI the latest version of aws-vault supports `--ecs-server` which does not require root

**Comment by gdamjan** [comment]
thanks, I think that will work for me just fine!

**Comment by gdamjan-loka** [comment]
Update:
nowdays --server is alias for ecs-server

`-s, --[no-]server              Alias for --ecs-server`
