### ISSUE TITLE
duration_seconds not honored

### ISSUE THREAD

**Issue by kennedy** [99designs/aws-vault#544]
- [x] I am using the latest release of AWS Vault
- [x] I have provided my `.aws/config` (redacted if necessary)
- [x] I have provided the debug output using `aws-vault --debug` (redacted if necessary)

I have set `duration_seconds` to be 43200 seconds (12 hours) in my configuration, but mfa/sts sessions are only 1 hour. 

I have currently tested this on:
- windows10 powershell.core 7
- windows10 powershell.core 6
- macOS 10.15.3 zsh

According to the USAGE.md page, I can override the `exec` command's sts session request by modifying the env variables, but that didnt work either. I even set all four possible `*_TTL` variable and it still gives me 1 hour. 

config (redacted):
```
[default]
duration_seconds = 43200

[profile testaccount]
mfa_serial = arn:aws:iam::xxxxx:mfa/kennedy
region = us-east-1
duration_seconds = 43200
```

debug (redacted):
```
PS C:\Users\kennedy\Documents\projects\test\terraform> echo $env:AWS_ASSUME_ROLE_TTL
43200
PS C:\Users\kennedy\Documents\projects\test\terraform> echo $env:AWS_CHAINED_SESSION_TOKEN_TTL
43200
PS C:\Users\kennedy\Documents\projects\test\terraform> echo $env:AWS_FEDERATION_TOKEN_TTL
43200
PS C:\Users\kennedy\Documents\projects\test\terraform> echo $env:AWS_SESSION_TOKEN_TTL
43200
PS C:\Users\kennedy\Documents\projects\test\terraform> aws-vault --debug exec testaccount -- terraform
2020/03/24 16:17:50 aws-vault v5.3.2
2020/03/24 16:17:50 [keyring] Considering backends: [wincred pass file]
2020/03/24 16:17:50 Loading config file C:\Users\kennedy\.aws\config
2020/03/24 16:17:50 Parsing config file C:\Users\kennedy\.aws\config
2020/03/24 16:17:50 profile testaccount: using stored credentials
2020/03/24 16:17:50 profile testaccount: using GetSessionToken (with MFA)
2020/03/24 16:17:50 Looking for sessions for testaccount
2020/03/24 16:17:50 Looking up all keys in keyring
Enter token for arn:aws:iam::XXXXX:mfa/kennedy: XXXXX
2020/03/24 16:17:59 Looking up keyring for 'testaccount'
2020/03/24 16:17:59 Generated credentials **************** using GetSessionToken, expires in 59m59.6140725s
2020/03/24 16:17:59 Writing session for testaccount to keyring: "session,xxxx,xxxxxx,158xx"
2020/03/24 16:17:59 Setting subprocess env: AWS_DEFAULT_REGION=us-east-1, AWS_REGION=us-east-1
2020/03/24 16:17:59 Setting subprocess env: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
2020/03/24 16:17:59 Setting subprocess env: AWS_SESSION_TOKEN, AWS_SECURITY_TOKEN
2020/03/24 16:17:59 Setting subprocess env: AWS_SESSION_EXPIRATION
Usage: terraform [-version] [-help] <command> [args]
...
```

**Comment by kennedy** [comment]
Just attempted with `aws-vault --debug exec testaccount --duration=12h -- terraform` and it does not work either

**Comment by irgeek** [comment]
It took me a while to work out -- and it required digging into the code -- but `duration_seconds` is only used when your profile is assuming a role. For standard `GetSessionToken` profiles like you are using, it's ignored. I'm guessing there's a reason, but I haven't found anywhere it was discussed / decided / documented.

As for the environment variables, the one you need for `GetSessionToken` profiles is `AWS_SESSION_TOKEN_TTL`. The value, though, is parsed with [time.ParseDuration](https://golang.org/pkg/time/#ParseDuration) which expects units after the numbers. Instead of

```AWS_SESSION_TOKEN_TTL= 43200```

use

```AWS_SESSION_TOKEN_TTL= 43200s```

or 

```AWS_SESSION_TOKEN_TTL= 12h```

Also, make sure your environment variables are exported. All of this is a bit challenging to debug because `aws-vault` silently ignores values in environment variables that can't be parsed.

**Comment by mtibben** [comment]
Feel free to help improve the docs

**Comment by azisi** [comment]
I confirm that `duration_seconds` in `.aws/config` is ignored, but the `--duration` flag works as expected, see below. I am using macOS 10.15.3 ssh. 

```
$ aws-vault exec testaccount --debug --duration=8h

2020/04/06 02:38:53 aws-vault v5.3.2
2020/04/06 02:38:53 [keyring] Considering backends: [keychain pass file]
2020/04/06 02:38:53 Loading config file /Users/test/.aws/config
2020/04/06 02:38:53 Parsing config file /Users/test/.aws/config
2020/04/06 02:38:53 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/04/06 02:38:53 [keyring] Found 1 results
2020/04/06 02:38:53 profile testaccount: using stored credentials
2020/04/06 02:38:53 profile testaccount: using GetSessionToken (with MFA)
2020/04/06 02:38:53 Looking for sessions for testaccount
2020/04/06 02:38:53 Looking up all keys in keyring
2020/04/06 02:38:53 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/04/06 02:38:53 [keyring] Found 1 results
Enter token for arn:aws:iam::XXXXXXXXX:mfa/test: 123456
2020/04/06 02:39:00 Looking up keyring for 'testaccount'
2020/04/06 02:39:00 [keyring] Querying keychain for service="aws-vault", account="testaccount", keychain="aws-vault.keychain"
2020/04/06 02:39:00 [keyring] Found item "aws-vault (testaccount)"
2020/04/06 02:39:00 Generated credentials ****************MZVT using GetSessionToken, expires in 8h0m1.00004s
2020/04/06 02:39:01 Writing session for testaccount to keyring: "session,xxxx,xxxxxx,xxxxx"
2020/04/06 02:39:01 [keyring] Checking keychain status
2020/04/06 02:39:01 [keyring] Keychain status returned nil, keychain exists
2020/04/06 02:39:01 [keyring] Keychain item trusts keyring
2020/04/06 02:39:01 [keyring] Adding service="aws-vault", label="aws-vault session for testaccount", account="session,xxxx,xxxxxx,xxxxx", trusted=true to osx keychain "aws-vault.keychain"
2020/04/06 02:39:01 Setting subprocess env: AWS_DEFAULT_REGION=eu-west-1, AWS_REGION=eu-west-1
2020/04/06 02:39:01 Setting subprocess env: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
2020/04/06 02:39:01 Setting subprocess env: AWS_SESSION_TOKEN, AWS_SECURITY_TOKEN
2020/04/06 02:39:01 Setting subprocess env: AWS_SESSION_EXPIRATION

```
config (redacted):

```
[default]
region=eu-west-1
output=json

[profile testaccount]
mfa_serial = arn:aws:iam::XXXXXXXXX:mfa/test

```

**Comment by mtibben** [comment]
>  I'm guessing there's a reason, but I haven't found anywhere it was discussed / decided / documented.

`duration_seconds` is the AWS CLI documented config for assuming roles. As aws-vault typically uses both a 12h session token that gets cached in the keystore as well as an assumed role, it would be confusing and clunky to reuse this config for both session tokens and roles.

`--duration` should indeed work as the "simple" config for this, as well as `AWS_SESSION_TOKEN_TTL` as the specific config for session tokens
