### ISSUE TITLE
Print prompts to stderr

### ISSUE THREAD

**Issue by TimMoore** [99designs/aws-vault#56]
I just tried to run a command with `aws-vault exec` and pipe the output, like:

```
aws-vault exec profile -- ./ec2.py --refresh-cache |less
```

My profile required MFA, and the prompt was printed to stdout, so this didn't work the way I hoped.

It might be better to print prompts to stderr instead of stdout to avoid problems with stdout redirection.

**Comment by lox** [comment]
I've been wondering about this myself. I'm sure there is some tty magic to make this work reliably. The usecase that always bites me is when I'm running exec with `--server` and a subshell and the mfa prompt breaks in a similar manner to yourself.

**Comment by lox** [comment]
I've implemented this as part of #57.

**Comment by TimMoore** [comment]
:+1:

**Comment by lox** [comment]
I released this as part of https://github.com/99designs/aws-vault/releases/tag/v3.2.0. Let me know how you go @TimMoore!
