### ISSUE TITLE
aws-vault --server should kill the root processes when it exits

### ISSUE THREAD

**Issue by philsnow** [99designs/aws-vault#581]
While verifying @mtibben 's fix on https://github.com/99designs/aws-vault/issues/578 , I was briefly thrown for a loop when I noticed that the root proxy process that I started on Monday was still running, even though I had long since killed the `aws-vault exec --server` process (and the PTY that the process had been running in):

```
% ps -ef | grep aws-va
    0 68217     1   0 Mon02PM ??         0:00.00 sudo -b aws-vault server
    0 68218 68217   0 Mon02PM ??         0:00.17 aws-vault server
  501 68626 75486   0 12:45PM ttys046    0:00.05 ./aws-vault exec --server work
```

So this means that all that time, there was a process silently proxying traffic from localhost:80 to localhost:9099.  Some other process could listen on port 9099 and effectively get access to listening on a low-numbered port without sudo.

The `sudo` and the `aws-vault server` process should die when my user's `aws-vault exec --server` process dies.

**Comment by mtibben** [comment]
v5 is more restrictive here, it only proxies one URL path. v6 is currently proxying everything

**Comment by mtibben** [comment]
dupe of #548 ?
