### ISSUE TITLE
aws-vault get << profile >>

### ISSUE THREAD

**Issue by danielcrisap** [99designs/aws-vault#589]
Hi,
What do you think about implementing a `get` function for aws-vault, where it only export environments as `exec` and we can continue switching from one profile to another without problems.

I understand that `exec` would be for on-time executions and `get` would be to keep the shell working with the necessary environments and to easily switch to another profile. Today I need to run the `unset $AWS_VAULT` before switching to another profile. What do you think?

**Comment by mtibben** [comment]
The default behaviour of exec is to launch a subshell, so I'm not sure I understand what you're proposing or wanting to do. Can you provide a step by step example of the undesired behaviour you're seeing in aws-vault?

**Comment by danielcrisap** [comment]
> The default behaviour of exec is to launch a subshell (which you can `exit` from), so I'm not sure I understand what you're proposing or trying to achieve. Can you provide a step by step example of the desired behaviour you're wanting?

I was using it that way 👇 
```bash
[] ~ ⌚ 9:27:14
$ aws-vault exec foo-bar
[foo-bar] ~ ⌚ 9:27:22
$ aws-vault exec bar-foo
aws-vault: error: exec: aws-vault sessions should be nested with care, unset $AWS_VAULT to force
[foo-bar] ~ ⌚ 9:27:25
$
```

but reading your comment I understood that I should open a sub shell to do the things I need with that AWS session.

```bash
[] ~ ⌚ 9:33:03
$ aws-vault exec foo-bar --
[foo-bar] ~ ⌚ 9:33:11
$ aws sts get-caller-identity | jq -r .Account
111111111111
[foo-bar] ~ ⌚ 9:33:15
$ exit
[] ~ ⌚ 9:33:17
$ aws-vault exec bar-foo --
[bar-foo] ~ ⌚ 9:33:22
$ aws sts get-caller-identity | jq -r .Account
22222222222
[bar-foo] ~ ⌚ 9:33:25
$ exit
[]~ ⌚ 9:33:29
$
```

using `--` after my profile works the way I was thinking about the get function.

**Comment by mtibben** [comment]
No need to even use the trailing `--`.  Just `aws-vault exec foo-bar` will work just as well :)
