### ISSUE TITLE
Assume role session expires in 15 mins

### ISSUE THREAD

**Issue by ptolemy428** [99designs/aws-vault#59]
Hi @lox,  

Currently, when running aws-vault with exec, it creates a session (for assuming role), which times out after 15 mins. AWS assume role API allows up to 1 hour as the duration of the session.

Is there a way to configure this setting with aws-vault (i.e. env vars, config files, etc)?

~/development/ca/data$ aws-vault --debug exec dev-admin
DEBUG 2016/02/16 14:26:38 Parsing config file /Users/dev/.aws/config
DEBUG 2016/02/16 14:26:38 Looking up keyring for default
DEBUG 2016/02/16 14:26:38 Opening keychain /Users/dev/Library/Keychains/aws-vault.keychain
DEBUG 2016/02/16 14:26:40 Opening keychain /Users/dev/Library/Keychains/aws-vault.keychain
DEBUG 2016/02/16 14:26:43 Using session ****************LVXQ, expires in 3h41m40.575404173s
DEBUG 2016/02/16 14:26:43 Assuming role arn:aws:iam::xxxxxxxxxxxxxx:role/xxxxxxxxxxxx
DEBUG 2016/02/16 14:26:45 Using role ****************XSZA, **expires in 14m59.24446076s**
DEBUG 2016/02/16 14:26:45 Parsing config file /Users/dev/.aws/config
DEBUG 2016/02/16 14:26:45 Writing temporary credentials to ENV
cmd has been run. exit

Some background information, we use aws-vault to create sessions on local machine to run aws command. some of the commands take more than 15 mins to complete. (i.e. such as baking AMIs). The session timed out after 15 mins, which leavings everything hanging.

**Comment by lox** [comment]
Interesting, I wonder why I did that. The best way to solve this problem is to use the `--server` parameter to `aws-vault exec` which will run an ec2 metadata service so that your credentials can be refreshed. I'll look into why the role is using the minimum expiry time.

**Comment by lox** [comment]
I believe I just never got around to adding a flag for setting the `assume-role-ttl`, there is on for the `session-ttl`. I'd happily accept a PR, or I can look into this when I've got a moment.

**Comment by mtibben** [comment]
Fixed in #64

**Comment by warrenseen** [comment]
@lox the default lifetime for STS role tokens is the maximum, 1 hour (ref: http://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html). 

> The temporary security credentials are valid for the duration that you specified when calling AssumeRole, which can be from 900 seconds (15 minutes) to a maximum of 3600 seconds (1 hour). The default is 1 hour.

I'd suggest if you're changing it, to align it with their default, rather than 30 minutes?
