### ISSUE TITLE
aws-vault -server is exposed to minikube containers

### ISSUE THREAD

**Issue by etuttle** [99designs/aws-vault#595]
aws-vault: v5.4.4
hyperkit: 0.20200224
minikube: v1.10.1
macOS: 10.14.6

I ran `aws-vault -server`.  Out of curiosity, I tried an aws-cli command in a container running on a local minikube.  Sure enough, `aws s3 ls` was able to connect to  aws-vault at `169.254.169.254:80`.  It transparently requested my credentials and used them.

I think this is kind of a neat feature but it may not be "expected behavior".  Actually I would prefer that the connection was blocked by default, but it could be allowed with a flag.

I just saw #205 so, looks like some thought has gone into this already.  There must be some DNAT going on to make the connection appear to come from localhost.  That is strange.  Maybe I'll dig into it some more.

If a complete fix is a ways away (usng firewall rules, or whatever) it would be an improvement if the docs warned: "Beware that local virtual machines or containers may be able to reach the server endpoint".

**Comment by mtibben** [comment]
PR welcome @etuttle, also see [these issues](https://github.com/99designs/aws-vault/issues?q=is%3Aissue+is%3Aopen+label%3Aserver)
