### ISSUE TITLE
Ubuntu 20 --server not working

### ISSUE THREAD

**Issue by hunttom** [99designs/aws-vault#596]
When running the following:
 user@blacknovember  ~  aws-vault exec default -s --debug                                                                                      
2020/05/29 14:22:47 aws-vault 5.4.4
2020/05/29 14:22:47 [keyring] Considering backends: [file]
2020/05/29 14:22:47 Loading config file /home/user/.aws/config
2020/05/29 14:22:47 Parsing config file /home/user/.aws/config
2020/05/29 14:22:47 [keyring] Expanded file dir to /home/user/.awsvault/keys/
2020/05/29 14:22:47 profile default: using stored credentials
2020/05/29 14:22:47 profile default: using GetSessionToken 
2020/05/29 14:22:47 Looking for sessions for default
2020/05/29 14:22:47 Looking up all keys in keyring
2020/05/29 14:22:47 [keyring] Expanded file dir to /home/user/.awsvault/keys/
2020/05/29 14:22:47 Looking up keyring for 'default'
2020/05/29 14:22:47 [keyring] Expanded file dir to /home/user/.awsvault/keys/
2020/05/29 14:22:47 [keyring] Expanded file dir to /home/user/.awsvault/keys/
Enter passphrase to unlock /home/user/.awsvault/keys/: 
2020/05/29 14:22:49 Generated credentials ****************NWWX using GetSessionToken, expires in 59m59.231543939s
2020/05/29 14:22:49 Writing session for default to keyring: "session,ZGVmYXVsdA,,12345678980"
2020/05/29 14:22:49 [keyring] Expanded file dir to /home/user/.awsvault/keys
2020/05/29 14:22:49 [keyring] Expanded file dir to /home/user/.awsvault/keys/
2020/05/29 14:22:49 Starting `aws-vault server` as root in the background
[sudo] password for user: 
sudo: aws-vault: command not found
aws-vault: error: exec: Failed to start credential server: exit status 1
```
Uname -a: Linux computer 5.4.0-31-generic #35-Ubuntu SMP Thu May 7 20:20:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Note: ID data has been changed to user, SessionID,

**Comment by abbottdev** [comment]
> When running the following:
> user@blacknovember  ~  aws-vault exec default -s --debug
> 2020/05/29 14:22:47 aws-vault 5.4.4
> 2020/05/29 14:22:47 [keyring] Considering backends: [file]
> 2020/05/29 14:22:47 Loading config file /home/user/.aws/config
> 2020/05/29 14:22:47 Parsing config file /home/user/.aws/config
> 2020/05/29 14:22:47 [keyring] Expanded file dir to /home/user/.awsvault/keys/
> 2020/05/29 14:22:47 profile default: using stored credentials
> 2020/05/29 14:22:47 profile default: using GetSessionToken
> 2020/05/29 14:22:47 Looking for sessions for default
> 2020/05/29 14:22:47 Looking up all keys in keyring
> 2020/05/29 14:22:47 [keyring] Expanded file dir to /home/user/.awsvault/keys/
> 2020/05/29 14:22:47 Looking up keyring for 'default'
> 2020/05/29 14:22:47 [keyring] Expanded file dir to /home/user/.awsvault/keys/
> 2020/05/29 14:22:47 [keyring] Expanded file dir to /home/user/.awsvault/keys/
> Enter passphrase to unlock /home/user/.awsvault/keys/:
> 2020/05/29 14:22:49 Generated credentials ****************NWWX using GetSessionToken, expires in 59m59.231543939s
> 2020/05/29 14:22:49 Writing session for default to keyring: "session,ZGVmYXVsdA,,12345678980"
> 2020/05/29 14:22:49 [keyring] Expanded file dir to /home/user/.awsvault/keys
> 2020/05/29 14:22:49 [keyring] Expanded file dir to /home/user/.awsvault/keys/
> 2020/05/29 14:22:49 Starting `aws-vault server` as root in the background
> [sudo] password for user:
> sudo: aws-vault: command not found
> aws-vault: error: exec: Failed to start credential server: exit status 1
> 
> ```
> Uname -a: Linux computer 5.4.0-31-generic #35-Ubuntu SMP Thu May 7 20:20:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
> 
> Note: ID data has been changed to user, SessionID,
> ```

@hunttom I was having this same problem - I think it's a general linux thing (I must admit I'm a nix noob but).. If instead of running `aws-vault <args> --server` - as this shorthand has been added to your path - because the cmd needs to run as root - and root doesnt have the same path as your user - I think you need to run the resolved path instead.

I.e. instead of `aws-vault exec <profile> --server` - I ran - `which aws-vault` which returns the path to use instead (in my case this ended up being) `sudo /home/linuxbrew/.linuxbrew/bin/aws-vault <profile> --server`

The code appears to be doing this intentionally as it's using args[0] to determine the process name to execute, rather than a hard-coded `aws-vault` string.
