### ISSUE TITLE
Windows Defender virus alert for multiple versions

### ISSUE THREAD

**Issue by gusztavvargadr** [99designs/aws-vault#599]
Hi there,

After #566 Windows Defender still reports virus alerts for multiple versions, including the latest 5.4.4.

This is being reported by several users of the Chocolatey package I maintain at https://github.com/gusztavvargadr/aws-vault-chocolatey/issues/31.

It seems to be a recurring issue, some Windows Defender definitions are not reporting issues, then with the next definition updates the next day the problem occurs again.

I have double checked the hashes of the original binaries and the ones packages for Chocolatey for the most recent versions and it is correct, so the issue is not with the packaging.

Please advise.

**Comment by mtibben** [comment]
> Please advise.

I have no idea @gusztavvargadr. I don't use Windows, Windows Defender or Chocolatey. 

What would you suggest?

**Comment by gusztavvargadr** [comment]
@mtibben sorry for the late response, it seems it was indeed a false positive and was solved by a custom submission.

https://github.com/99designs/aws-vault/issues/566#issuecomment-639268939
