### ISSUE TITLE
aws-vault list output changes and feature request (v6 Beta)

### ISSUE THREAD

**Issue by enly1** [99designs/aws-vault#602]
**aws-vault list format changes breaking automation**

I note that between 5.x and 6.x, the session output from aws-vault list has changed.

On the previous output, it was possible to determine which profiles had active MFA sessions, but this capability is lost in the new format.  I am unable to find any way to determine which profiles in use have MFA sessions based on the new output.

**v5.x (v5.1.0-rc1**
```
aws-vault list

Profile                   Credentials              Sessions                 
=======                   ===========              ========                 
aws-api                   aws-api                  1591626681 (mfa)         

```
**Dev build**
```
aws-vault list

Profile                   Credentials              Sessions                 
=======                   ===========              ========                 
aws-api                   aws-api                  session:3h0m32s          

```
I previously used the (mfa) marker in automation to allow me to flush all MFA sessions based on the presence of (mfa) in the v5 output..

Would it be possible to re-include (mfa) in the aws-vault list output, or could you offer any way to find active profiles with  mfa sessoins .

Alternatively, could I request two new possible feature variants:

1. Clear all sessions ( aws-vault remove --all-sessions )
2. Clear all MFA sessions (aws-vault remove --all-mfa-sessions )

The desire to do this comes from MFA session caching and the desire to be able to invalidate all cached sessions, thus forcing the need for new MFA challenge.

**Comment by mtibben** [comment]
It might make sense to add `aws-vault list --json` which could provide this data in a machine-readable way
