### ISSUE TITLE
aws-vault one credential broke

### ISSUE THREAD

**Issue by deiga** [99designs/aws-vault#604]
- [x] I am using the latest release of AWS Vault
- [x] I have provided my `.aws/config` (redacted if necessary)
- [x] I have provided the debug output using `aws-vault --debug` (redacted if necessary)

[AWS Config](https://gist.github.com/deiga/99e0b7d0be904445a726c61fe83344a4)
Debug output:
```2020/06/18 15:18:41 aws-vault v5.4.4
2020/06/18 15:18:41 [keyring] Considering backends: [keychain pass file]
2020/06/18 15:18:41 Loading config file /Users/tsd/.aws/config
2020/06/18 15:18:41 Parsing config file /Users/tsd/.aws/config
2020/06/18 15:18:41 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/06/18 15:18:41 [keyring] Found 3 results
2020/06/18 15:18:41 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/06/18 15:18:41 [keyring] Found 3 results
aws-vault: error: exec: Error getting temporary credentials: profile bar-staging: credentials missing
```

Hey,

Since yesterday one of my credentials broke and will not function again. It happened after I either Ctrl+C'd during a OTP prompt or a OS password prompt window.

I know that I can probably just remove and re-add the credential, but I would like to help to figure out if this bug can be averted in the future.

All other credentials still work.

**Comment by ronkorving** [comment]
I just had exactly the same happen to me. I don't know what triggered it, but it's quite plausible to think that it was CTRL-C mid-prompt.

This has never happened before.

```
2020/06/26 09:35:16 aws-vault v5.4.4
2020/06/26 09:35:16 [keyring] Considering backends: [keychain pass file]
2020/06/26 09:35:16 Loading config file /Users/rkorving/.aws/config
2020/06/26 09:35:16 Parsing config file /Users/rkorving/.aws/config
2020/06/26 09:35:16 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/06/26 09:35:16 [keyring] Found 1 results
aws-vault: error: exec: Error getting temporary credentials: profile development: credentials missing
```
