### ISSUE TITLE
Stdout delayed with awscli v2

### ISSUE THREAD

**Issue by pikeas** [99designs/aws-vault#605]
- [x] I am using the latest release of AWS Vault
- [x] I have provided my `.aws/config` (redacted if necessary)
- [x] I have provided the debug output using `aws-vault --debug` (redacted if necessary)

```
$ cat ~/.aws/config
[profile foo]
credential_process=aws-vault --debug exec foo --json
mfa_serial=arn:aws:iam::1234:mfa/me

$ aws-vault --version
v5.4.4
$ aws --version
aws-cli/2.0.25 Python/3.8.3 Darwin/19.3.0 botocore/2.0.0dev29
$ aws-vault exec foo -- ls # works as expected
Enter token for arn:aws:iam::1234:mfa/me: ^C
$❯ aws s3 ls


Error when retrieving credentials from custom-process: 2020/06/25 12:14:51 aws-vault v5.4.4
2020/06/25 12:14:51 [keyring] Considering backends: [keychain pass file]
2020/06/25 12:14:51 Loading config file /Users/me/.aws/config
2020/06/25 12:14:51 Parsing config file /Users/me/.aws/config
2020/06/25 12:14:51 [keyring] Querying keychain for service="aws-vault", keychain="login.keychain"
2020/06/25 12:14:51 [keyring] Found 1 results
2020/06/25 12:14:51 profile foo: using stored credentials
2020/06/25 12:14:51 profile foo: using GetSessionToken (with MFA)
2020/06/25 12:14:51 Looking for sessions for foo
2020/06/25 12:14:51 Looking up all keys in keyring
2020/06/25 12:14:51 [keyring] Querying keychain for service="aws-vault", keychain="login.keychain"
2020/06/25 12:14:51 [keyring] Found 1 results
Enter token for arn:aws:iam::1234:mfa/me:
```

The "enter token" text isn't displayed when using credential_process. The token itself can still be entered. Adding `python -u` to `/usr/local/Cellar/awscli/2.0.25/bin/aws` didn't make a difference.

I'm not sure if this an issue with aws-vault or with the aws cli.

**Comment by cornickj** [comment]
Try setting the AWS_PAGER environment variable to "" instead of the default less that the installer configures.

**Comment by pikeas** [comment]
> Try setting the AWS_PAGER environment variable to "" instead of the default less that the installer configures.

Thanks for the suggestion. No change, alas:

```
$ AWS_PAGER="" aws s3 ls

# No output, can still enter MFA
```

**Comment by pikeas** [comment]
```
credential_process=aws-vault exec --json --prompt=osascript <my profile>
```

This seems to work! Note that `--prompt=terminal` will not.

**Comment by mtibben** [comment]
Yes I believe this is intended, `credential_process` isn't expecting an interactive TTY.

Also my understanding is that `credential_process` is designed for the storage/retrieval of master credentials, while the command you have given above will be outputing STS credentials. I'm not sure how using those STS credentials will interact with the aws cli/sdk behaviour. 

I'd be expecting a config something more like

```ini
[profile master]

[profile foo]
credential_process=aws-vault exec --no-session master --json
mfa_serial=arn:aws:iam::1234:mfa/me
```

**Comment by pikeas** [comment]
@mtibben `credential_process` supports expiry (https://docs.aws.amazon.com/cli/latest/topic/config-vars.html), and I haven't been able to find any docs about only using it for "master" credentials, or why you're suggesting `--no-session`. I don't fully understand why this is incorrect usage:

```
[profile foo]
credential_process=aws-vault exec --json --prompt=osascript flow
mfa_serial=arn:aws:iam::1234:mfa/me
```

**Comment by mtibben** [comment]
> The Expiration key is an ISO8601 formatted timestamp. If the Expiration key is not returned in stdout, the credentials are long term credentials that do not refresh. Otherwise the credentials are considered refreshable credentials and will be refreshed automatically. NOTE: Unlike with assume role credentials, the AWS CLI will NOT cache process credentials. If caching is needed, it must be implemented in the external process.

My understanding is that `credential_process` is analogous to `source_profile`. Generally you're using these configs to provide long-term (or "master") creds. Sure you can get aws-vault to provide short-term creds. But then what happens if you have a role configured. Does it get a double role? I'm not sure tbh, but if you can provide further clarity to the docs that would be great

**Comment by pikeas** [comment]
I'm happy to send a docs PR, but I don't feel that I understand the moving parts well enough to do so at this time. My goal state is: a) MFA for securing access, b) aws-vault so that my master credentials are encrypted rather than stored plaintext in ~/.aws/credentials, and c) "hiding" the usage of aws-vault with credential_helper, so that setting `AWS_PROFILE` (potentially with `AWS_SD_LOAD_CONFIG=1` as well for certain apps) is the only thing needed after initial setup.

**Comment by frezbo** [comment]
@pikeas if you have `terminal` as prompt for a `credential_process`, it will not work. The SDK's are designed not to prompt. 
When using `osascript` the process actually waits until the prompt is complete and hence that works. So as per the SDK's there's no way to get prompt working with terminal when using credential process. I think we can close this issue since it's not aws-vault issue.
