### ISSUE TITLE
ykman not accepted as --prompt option

### ISSUE THREAD

**Issue by dvdtoth** [99designs/aws-vault#606]
- [x] I am using the latest release of AWS Vault
- [x] I have provided my `.aws/config` (redacted if necessary)
- [x] I have provided the debug output using `aws-vault --debug` (redacted if necessary)

The `--prompt` flag does not accept `ykman` as option.

Following instructions from [USAGE.md](https://github.com/99designs/aws-vault/blob/master/USAGE.md#usage-1) to set up MFA with yubikey, I get the following error:

```
aws-vault exec --debug --prompt ykman foo -- aws s3 ls
2020/06/26 17:00:25 aws-vault v5.4.4
2020/06/26 17:00:25 [keyring] Considering backends: [keychain pass file]
2020/06/26 17:00:25 Loading config file /Users/foo/.aws/config
2020/06/26 17:00:25 Parsing config file /Users/foo/.aws/config
aws-vault: error: enum value must be one of terminal,kdialog,osascript,zenity, got 'ykman', try --help
```

.aws/config
```
[default]

[profile foo]
```

**Comment by avegao** [comment]
I had the same "problem". You're showing the new v6 documentation but this version isn't released. In v5, the current version, this option is unavailable.

**Comment by dvdtoth** [comment]
Thanks @avegao, well spotted
Closing this
