### ISSUE TITLE
Only appears to output to stderr

### ISSUE THREAD

**Issue by createdbypete** [99designs/aws-vault#61]
Happened to notice this when playing around. 

I'm not that familiar with Go yet so I'm not sure where the problem is exactly to put in a PR but incase someone else can in the meantime it can be tested simply with the terminal:

```
$ aws-vault --version > /dev/null
v3.2.0

$ aws-vault --version 2> /dev/null
```

Also noticed `aws-vault --help` has an exit status of `1`.

**Comment by lox** [comment]
This seems to be an upstream decision in the argument parsing lib we use.

**Comment by lox** [comment]
https://github.com/alecthomas/kingpin/issues/136

**Comment by lox** [comment]
https://github.com/alecthomas/kingpin/issues/137

**Comment by lox** [comment]
These should both be fixed upstream now and also in HEAD. Thanks for the report.
