### ISSUE TITLE
Getting unknown long flag when trying to setup parameters in AWS SES

### ISSUE THREAD

**Issue by Zeth0** [99designs/aws-vault#611]

**Comment by Zeth0** [comment]
PS C:\Windows\system32> aws-vault exec ldcprofile aws ses create-configuration-set --configuration-set "Name=AcctX"
aws-vault.exe: error: unknown long flag '--configuration-set', try --help

Other SES short commands work with no issue like below.
PS C:\Windows\system32> aws-vault exec ldcprofile aws ses get-send-quota
Enter token for arn:aws:iam::22934160XXX:mfa/mxykx: 084053
{
    "Max24HourSend": 1000000.0,
    "MaxSendRate": 80.0,
    "SentLast24Hours": 3224.0
}
Any help will be appreciated.
Thanks

**Comment by 1pavanb** [comment]
I'm getting the same error

anything with --parameters will break the functionality

seems like the -- separator for aws-vault won't work when there is another one in the command to be executed.

Simple Reproducible Eg: aws-vault exec blah -- aws --help

I'm not using it for --help but faced when trying to run a serverless secrets command.

why is this issue closed?

**Comment by 1pavanb** [comment]
looks like a duplicate of https://github.com/99designs/aws-vault/issues/479
