### ISSUE TITLE
aws-vault add [profile] prints secret key when entered

### ISSUE THREAD

**Issue by quodlibetor** [99designs/aws-vault#616]
It seems like [this prompt](https://github.com/99designs/aws-vault/blob/e94c19cfd040ba9aba590feca47256e11f778855/cli/add.go#L73) should use [`terminal.ReadPassWord`](https://godoc.org/golang.org/x/crypto/ssh/terminal#Terminal.ReadPassword) instead, to prevent echo or it existing in terminal window history.

**Comment by mtibben** [comment]
Can you explain why this is desirable, and any specific use-cases? Can you demonstrate how it exists in the terminal history? 
```
$ aws-vault add foo
Enter Access Key ID: foo
Enter Secret Access Key: lkdgasdfkkj
Added credentials to profile "foo" in vault
$ history | grep lkdgasdfkkj
   40  history | grep lkdgasdfkkj
```

**Comment by quodlibetor** [comment]
It's not in the history file, just in the scrollback buffer (e.g. e.g. konsole/iterm2) so if you are screen sharing/pair programming and you add a key it will be visible, including if you scroll up to look at something unrelated. It is generally just considered best practice to not show password text by default -- this is why almost all cli programs hide input by default, the official golang organization provides the functionality, web browsers and all other GUI toolkits provide specific password input fields that obfuscate the password.
