### ISSUE TITLE
aws-vault and --duration for roles

### ISSUE THREAD

**Issue by kiwimato** [99designs/aws-vault#617]
Hello,

So I noticed this in the docs: 
> For that reason, AWS Vault will not use GetSessionToken if --duration or the role's duration_seconds is longer than 1h.

Even though I modified `Maximum CLI/API session duration` in AWS for the specific role, it doesn't work? Shouldn't it work if the duration was modified?

Note: I have `"aws:MultiFactorAuthPresent": "true"` in the target role policy, so I noticed that removing that works, but I would prefer to keep the MFA enforcement enabled.

logs:
```
[mihai@rivendell ~]$ aws-vault exec development-mihai-test 
Enter token for arn:aws:iam::XXXXXX:mfa/mihai-test: XXXXXX
[mihai@rivendell ~]$ aws s3 ls s3://some-bucket/
                           PRE <redacted>
2020-07-16 10:55:18          0 test
[mihai@rivendell ~]$ exit
[mihai@rivendell ~]$ aws-vault exec --duration=9h development-mihai-test
Enter token for arn:aws:iam::XXXXXX:mfa/mihai-test: XXXXXX
[mihai@rivendell ~]$ aws s3 ls s3://some-bucket/
An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied
[mihai@rivendell ~]$ 
```

**Comment by kiwimato** [comment]
After a bit some digging I think it's actually an AWS policy limitation, and moving the MFA enforcement up in the main AWS account, from where I assume the target role, it actually works.

**Comment by mtibben** [comment]
OK assuming this was an aws config issue
