### ISSUE TITLE
aws-vault add does not say how to provide credentials

### ISSUE THREAD

**Issue by gitcos** [99designs/aws-vault#619]
% aws-vault add --help
usage: aws-vault add [<flags>] <profile>

Adds credentials, prompts if none provided
[...]

I'm looking for a way to add credentials without being prompted interactively.  "if not provided" in the --help output implies there is a way to provide credentials, without being prompted... but doesn't say how to do it.  None of the rest of the help output does.  Nor can I find it in your README or USAGE files.

Please fix the --help output to clarify how to provide credentials.
It would also be helpful to put this information in USAGE.md.

**Comment by jimbrowne** [comment]
What version are you running?  `master` includes:

```  --env                      Read the credentials from the environment```

which is how we add credentials non-interactively.  Python code:

```    
    env = os.environ.copy()
    env['AWS_ACCESS_KEY_ID'] = access_key_id
    env['AWS_SECRET_ACCESS_KEY'] = secret_access_key

    cmd = [AWS_VAULT_BINARY, 'add', '--debug', '--backend=keychain', '--env']
```

**Comment by gitcos** [comment]
My version does actually ouput that line, but that's VERY obfuscated, so I didn't even realize it was relevant.

**Comment by gitcos** [comment]
If the environment is the only way to provide credentials aside from interactive prompting, then I suggest:

A: Change "Adds credentials, prompts if none provided" to "Adds credentials, prompts if none provided as environment variables".

B: After (or before) "Args:" add an "Environment Variables:" section in the --help output, that lists what environment variables it takes as *input* and what each one does.  Maybe it's just those two, maybe there are some more.

C: Update USAGE.md, add a section on "adding credentials" under "managing credentials", where you show by example how to run aws-vault add with and without environment variables.  One example would show the user being prompted, and the other would show the user setting env vars and then not being prompted.

**Comment by mtibben** [comment]
Hey @gitcos a PR with your suggestions would be 💯

**Comment by mtibben** [comment]
This was addressed in the latest v6 beta
