### ISSUE TITLE
Can't vendor this repo

### ISSUE THREAD

**Issue by kevinburke** [99designs/aws-vault#621]
I am trying to vendor the aws-vault command. As I understand it it's impossible to vendor the v5.x line of Git tags.

If I add 

```
	github.com/99designs/aws-vault v5.4.4
```

to my go.mod file and then run `go mod vendor`, I get this error:

```
require github.com/99designs/aws-vault: version "v5.4.4" invalid: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v5
```

This error message is rather unhelpfully explained here: https://github.com/golang/go/issues/35732

> The error message is correct. See https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning.
> 
> The v1.9.1-0.[…] version string is a pseudo-version generated from the requested commit.
>
> From the perspective of the go command, this is working as designed.

So it seems like you're supposed to put the source code in a folder labeled "v5", I think? I don't really know how this is supposed  to work, but I'd like to be able to vendor the project at the latest version...

**Comment by kevinburke** [comment]
Never mind, got it sorted... needed this

```
	github.com/99designs/aws-vault/v6 v6.0.0-beta5
```

and then also update code references to "aws-vault/v6".

**Comment by mtibben** [comment]
Note that the API is not stable, it's there to serve the aws-vault CLI only
