### ISSUE TITLE
Export STS creds to credentials file

### ISSUE THREAD

**Issue by RyanJarv** [99designs/aws-vault#623]
Opening this mostly to see if there is any interest this and if I submitted a PR for it if it would be considered here.

This would be another form of running aws-vault, like aws-vault exec or, --server, but would instead either merge or update temporary credentials in ~/.aws/credentials (taking care to avoid updating non-sts creds). I suspect there would also be functionality to control when key's are updated, i.e. only if they expire in x hours. One difference from other modes might be it may make sense to control which profiles are exported via ~/.aws/config so that aws-vault can operate on all of them.

For me this solves my use case for originally wanting https://github.com/99designs/aws-vault/pull/400 merged, but should be somewhat simpler and doesn't require running in the background. The problem is that many tools don't support all of the options in ~/.aws/config that are needed with aws-vault, this end's up costing a lot of time in figuring out what's going on. Exporting to the credentials file ensure's compatibility with those tools and is useful for sharing multiple profiles to a single docker container in a way that most setup's already support. Having the temporary key's in the credentials file rather than the environment also gives you more access control's compared to the environment or tcp socket. One trade off might be the batch export mode if used would expose all key's it's enabled for at any given time rather then the specific one that was needed, so that would have to be up to the user whether or not to export specific or any enabled creds (which I'm imagining would be most useful in a cronjob).

Really this could be done in a shell script but have been finding myself needing to do this for more projects lately and imagine other people are running into the same thing and it would be nice if this could be done in aws-vault directly.

Let me know if you have any thoughts or suggestions here as well.

Thanks!

**Comment by FernandoMiguel** [comment]
I entirely disagree with this proposal.
aws-vault was built exactly to avoid having (long lived) creds in clear text saved on disk.

any tools interacting with AWS should support AWS SDKs, which means env var creds and metadata (--server/--ecs) would work out of the box

**Comment by ryan-gerstenkorn-sp** [comment]
@FernandoMiguel
> aws-vault was built exactly to avoid having (long lived) creds in clear text saved on disk.
I agree with this for long lived credentials, this would specifically be for temporary sts credentials.

> any tools interacting with AWS should support AWS SDKs, which means env var creds and metadata (--server/--ecs) would work out of the box
This get's more complicated when you need to support multiple profiles without assuming roles. There's also many cases where custom credential resolving doesn't behave exactly like the default lookup, or the config file doesn't load by default. I can start making a list of these cases if it's helpful here.

**Comment by mtibben** [comment]
Yes it would be good to understand your use-case a little clearer

> The problem is that many tools don't support all of the options in ~/.aws/config that are needed with aws-vault, this end's up costing a lot of time in figuring out what's going on. Exporting to the credentials file ensure's compatibility with those tools and is useful for sharing multiple profiles to a single docker container in a way that most setup's already support

Can you be more specific? I really am not any clearer about the problem you're facing

> Really this could be done in a shell script

Yes, a shell script is always a good place to start and we have a `contrib` directory for that kind of thing

**Comment by irgeek** [comment]
If editing credentials into an existing `~/.aws/credentials` file isn't a requirement and using [jq](https://stedolan.github.io/jq/) is OK, a shell script to accomplish this is pretty trivial:

```bash
#!/bin/bash -e

JQ_TEMPLATE='
"[\($profile)]
aws_access_key_id=\(.AccessKeyId)
aws_secret_access_key=\(.SecretAccessKey)
aws_session_token=\(.SessionToken)
"'

_credentials() {
    local PROFILE="${1}";
    aws-vault exec -j "${PROFILE}" | jq --arg profile "${PROFILE}" -r "${JQ_TEMPLATE}"
}

for profile in "$@"; do
    _credentials "${profile}"
done
```

If you put that into a file named `credentials.sh` and make it executable, you can call it with a list of `aws-vault` profiles and it'll dump them in (what should be) the format used for `~/.aws/credentials`.

Running this:
```
credentials.sh profile-1 profile-2 profile-3
```

Will produce this:

```
[profile-1]
aws_access_key_id=< ... snip ... >
aws_secret_access_key=< ... snip ... >
aws_session_token=< ... snip ... >

[profile-2]
aws_access_key_id=< ... snip ... >
aws_secret_access_key=< ... snip ... >
aws_session_token=< ... snip ... >

[profile-3]
aws_access_key_id=< ... snip ... >
aws_secret_access_key=< ... snip ... >
aws_session_token=< ... snip ... >

```

I don't see any advantage to including the behaviour in `aws-vault` itself.

**Comment by RyanJarv** [comment]
@irgeek 

I did this originally with a shell script but in the end it ended up getting a bit more complex then I would have liked.

These are the things I'd like for this feature to accomplish:
1. Minimum possible password and MFA prompts
2. Standard method for refreshing credentials

**Comment by RyanJarv** [comment]
@mtibben 

> Yes, a shell script is always a good place to start and we have a contrib directory for that kind of thing

Ok thanks, let me take a stab at that again as a PR there.

**Comment by so0k** [comment]
we also have a similar set up where multiple AWS_PROFILE are used by our terraform providers to manage resources across AWS accounts (without having to bootstrap those accounts with certain roles)

**Comment by thattommyhall** [comment]
Can you use credential_process in the profiles terraform references?

**Comment by RyanJarv** [comment]
Second the credential process option. IIRC it get's a bit funky if you're trying to use MFA as well, that said TF has made a lot of improvements to how AWS creds are handled recently afik so you may have better luck then I did at the time.

**Comment by danieljamesscott** [comment]
Would `credential_source = Environment` work?

https://docs.aws.amazon.com/credref/latest/refdocs/setting-global-credential_source.html

Or is this where you need to use multiple different AWS users?

**Comment by so0k** [comment]
multiple different AWS users in my case

**Comment by RyanJarv** [comment]
If someone want's to assign this issue to me I'll likely work on a script for this use case when I get some time.

**Comment by irgeek** [comment]
I just found out that the `aws-cli` `configure` command can already edit `~/.aws/configure` in-place.

```
#!/bin/bash -e

aws configure --profile "${AWS_VAULT}" set aws_access_key_id "${AWS_ACCESS_KEY_ID}"
aws configure --profile "${AWS_VAULT}" set aws_secret_access_key "${AWS_SECRET_ACCESS_KEY}"
aws configure --profile "${AWS_VAULT}" set aws_session_token "${AWS_SESSION_TOKEN}"
```

If you put that into a file called `credentials.sh` and make it executable, you can use it like this:

```aws-vault exec profile-1 -- credentials.sh```

That will update the `profile-1` credentials in `~/.aws/configure` for you without touching credentials for any other profiles.

**Comment by RyanJarv** [comment]
Opened a PR for this in #785 if anyone is interested in taking a look at that.
