### ISSUE TITLE
aws-vault exec works sporadically

### ISSUE THREAD

**Issue by tony-garcia** [99designs/aws-vault#624]
Thanks for the very useful product.
I'm running into an issue, though, in which issuing `aws cli` commands via `aws-vault exec` is only working sporadically.
My OS is MacOS Mojave
AWS-Vault version: 5.4.4

**Config file**:
[default]
region=us-east-1
output=json
credential_process=aws-vault exec -j default

[profile computation]
region=us-east-1
output=json

[profile secrets]
region=us-east-1
source_profile = computation
role_arn = arn:aws:iam::xxxxxxxxxxxx:role/secrets-role

I have set up a role to enable my 'computation' user to be able to access secrets in the Secrets Manager. I was testing getting a secret (not using MFA) and it would work the first time, but then I would execute the command again a couple of seconds later and it would give me a `permission denied` message.

**command:**
aws-vault exec secrets --debug -- aws secretsmanager get-secret-value --secret-id mysecret

here is the debug trace when it succeeds:

2020/08/07 13:36:14 aws-vault v5.4.4
2020/08/07 13:36:14 [keyring] Considering backends: [keychain pass file]
2020/08/07 13:36:14 Loading config file /Users/agarcia/.aws/config
2020/08/07 13:36:14 Parsing config file /Users/agarcia/.aws/config
2020/08/07 13:36:14 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/08/07 13:36:14 [keyring] Found 3 results
2020/08/07 13:36:14 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/08/07 13:36:14 [keyring] Found 3 results
2020/08/07 13:36:14 profile computation: using stored credentials
2020/08/07 13:36:14 profile computation: skipping GetSessionToken because profile 'secrets' has no MFA serial defined
2020/08/07 13:36:14 profile secrets: using AssumeRole
2020/08/07 13:36:14 Looking up keyring for 'computation'
2020/08/07 13:36:14 [keyring] Querying keychain for service="aws-vault", account="computation", keychain="aws-vault.keychain"
2020/08/07 13:36:14 [keyring] Found item "aws-vault (computation)"
2020/08/07 13:36:14 Generated credentials ****************IBMB using AssumeRole, expires in 59m59.099361s
2020/08/07 13:36:14 Setting subprocess env: AWS_DEFAULT_REGION=us-east-1, AWS_REGION=us-east-1
2020/08/07 13:36:14 Setting subprocess env: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
2020/08/07 13:36:14 Setting subprocess env: AWS_SESSION_TOKEN, AWS_SECURITY_TOKEN
2020/08/07 13:36:14 Setting subprocess env: AWS_SESSION_EXPIRATION
[output of secret follows]

here it is when it fails:

2020/08/07 13:36:50 aws-vault v5.4.4
2020/08/07 13:36:50 [keyring] Considering backends: [keychain pass file]
2020/08/07 13:36:50 Loading config file /Users/agarcia/.aws/config
2020/08/07 13:36:50 Parsing config file /Users/agarcia/.aws/config
2020/08/07 13:36:50 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/08/07 13:36:50 [keyring] Found 3 results
2020/08/07 13:36:50 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/08/07 13:36:50 [keyring] Found 3 results
2020/08/07 13:36:50 profile computation: using stored credentials
2020/08/07 13:36:50 profile computation: skipping GetSessionToken because profile 'secrets' has no MFA serial defined
2020/08/07 13:36:50 profile secrets: using AssumeRole
2020/08/07 13:36:50 Looking up keyring for 'computation'
2020/08/07 13:36:50 [keyring] Querying keychain for service="aws-vault", account="computation", keychain="aws-vault.keychain"
2020/08/07 13:36:50 [keyring] Found item "aws-vault (computation)"
2020/08/07 13:36:50 Generated credentials ****************VR43 using AssumeRole, expires in 59m59.062745s
2020/08/07 13:36:50 Setting subprocess env: AWS_DEFAULT_REGION=us-east-1, AWS_REGION=us-east-1
2020/08/07 13:36:50 Setting subprocess env: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
2020/08/07 13:36:50 Setting subprocess env: AWS_SESSION_TOKEN, AWS_SECURITY_TOKEN
2020/08/07 13:36:50 Setting subprocess env: AWS_SESSION_EXPIRATION
aws-vault: error: exec: Error execing process: permission denied

I noticed that the last four of the "Generated credentials" is different. Should that be the same, since it says "expires in 59m..."?

I found that this not only happens with getting secrets, but other aws cli commands, such as `aws s3 ls` without even using assumerole (e.g. `aws exec default -- aws s3 ls`). It will work sometimes but other times I get `permission denied`.

Any assistance would be much appreciated.

**Comment by tony-garcia** [comment]
Here's an example of a straight `exec` call without assumerole executed within seconds of each other. The first gave me a `permission denied` and the second was successful (this time I see it's re-using cached credentials):

(base) agarcia-mbp00:.aws agarcia$ aws-vault exec default --debug -- aws s3 ls
2020/08/07 14:06:23 aws-vault v5.4.4
2020/08/07 14:06:23 [keyring] Considering backends: [keychain pass file]
2020/08/07 14:06:23 Loading config file /Users/agarcia/.aws/config
2020/08/07 14:06:23 Parsing config file /Users/agarcia/.aws/config
2020/08/07 14:06:23 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/08/07 14:06:23 [keyring] Found 3 results
2020/08/07 14:06:23 profile default: using stored credentials
2020/08/07 14:06:23 profile default: using GetSessionToken
2020/08/07 14:06:23 Looking for sessions for default
2020/08/07 14:06:23 Looking up all keys in keyring
2020/08/07 14:06:23 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/08/07 14:06:23 [keyring] Found 3 results
2020/08/07 14:06:23 Session "session,ZGVmYXVsdA,,1596825024" expires in 24m0.036739s
2020/08/07 14:06:23 [keyring] Querying keychain for service="aws-vault", account="session,ZGVxxxxxxx,,xxxxxxx024", keychain="aws-vault.keychain"
2020/08/07 14:06:23 [keyring] Found item "aws-vault session for default"
2020/08/07 14:06:23 Re-using cached credentials ****************B4SF generated from GetSessionToken, expires in 24m0.024071s
2020/08/07 14:06:23 Setting subprocess env: AWS_DEFAULT_REGION=us-east-1, AWS_REGION=us-east-1
2020/08/07 14:06:23 Setting subprocess env: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
2020/08/07 14:06:23 Setting subprocess env: AWS_SESSION_TOKEN, AWS_SECURITY_TOKEN
2020/08/07 14:06:23 Setting subprocess env: AWS_SESSION_EXPIRATION
aws-vault: error: exec: Error execing process: permission denied


(base) agarcia-mbp00:.aws agarcia$ aws-vault exec default --debug -- aws s3 ls
2020/08/07 14:06:38 aws-vault v5.4.4
2020/08/07 14:06:38 [keyring] Considering backends: [keychain pass file]
2020/08/07 14:06:38 Loading config file /Users/agarcia/.aws/config
2020/08/07 14:06:38 Parsing config file /Users/agarcia/.aws/config
2020/08/07 14:06:38 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/08/07 14:06:38 [keyring] Found 3 results
2020/08/07 14:06:38 profile default: using stored credentials
2020/08/07 14:06:38 profile default: using GetSessionToken
2020/08/07 14:06:38 Looking for sessions for default
2020/08/07 14:06:38 Looking up all keys in keyring
2020/08/07 14:06:38 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/08/07 14:06:38 [keyring] Found 3 results
2020/08/07 14:06:38 Session "session,ZGVmYXVsdA,,1596825024" expires in 23m45.210137s
2020/08/07 14:06:38 [keyring] Querying keychain for service="aws-vault", account="session,ZGVxxxxxxx,,xxxxxxx024", keychain="aws-vault.keychain"
2020/08/07 14:06:38 [keyring] Found item "aws-vault session for default"
2020/08/07 14:06:38 Re-using cached credentials ****************B4SF generated from GetSessionToken, expires in 23m45.197345s
2020/08/07 14:06:38 Setting subprocess env: AWS_DEFAULT_REGION=us-east-1, AWS_REGION=us-east-1
2020/08/07 14:06:38 Setting subprocess env: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
2020/08/07 14:06:38 Setting subprocess env: AWS_SESSION_TOKEN, AWS_SECURITY_TOKEN
2020/08/07 14:06:38 Setting subprocess env: AWS_SESSION_EXPIRATION
[output of s3 buckets]

**Comment by mtibben** [comment]
@tony-garcia can you reproduce the problem with the v6 beta ?

**Comment by tony-garcia** [comment]
Hi @mtibben 
I just tried it with v6.0.0-beta6 and it seems to happen less. But I do occasionally still get 'permission denied'. Not sure how to quantify how much less it happens. Using 'sudo' is a workaround. Also, taking advantage of the `credentials_process` setting in my default config, I can use the aws cli with no issues directly. The issue is only when I use the `aws-vault exec` command so I have to resort to using sudo if I'm not using the default config (and the credentials_process). This isn't a huge problem but it's weird that I get the permissions issue only sporadically (when I don't use sudo).

**Comment by mtibben** [comment]
Can you provide an example of where it fails with the full command and logs from v6?

**Comment by tony-garcia** [comment]
Sure. Here you go.

(base) agarcia-mbp00:~ agarcia$ aws-vault exec --debug default -- aws s3 ls
2020/08/17 07:41:02 aws-vault v6.0.0-beta6
2020/08/17 07:41:02 Loading config file /Users/agarcia/.aws/config
2020/08/17 07:41:02 Parsing config file /Users/agarcia/.aws/config
2020/08/17 07:41:02 [keyring] Considering backends: [keychain pass file]
2020/08/17 07:41:02 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/08/17 07:41:02 [keyring] Found 3 results
2020/08/17 07:41:02 profile default: using stored credentials
2020/08/17 07:41:02 profile default: using GetSessionToken
2020/08/17 07:41:02 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/08/17 07:41:02 [keyring] Found 3 results
2020/08/17 07:41:02 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/08/17 07:41:02 [keyring] Found 3 results
2020/08/17 07:41:02 [keyring] Querying keychain for service="aws-vault", account="sts.GetSessionToken,ZGVmYXVsdA,,1597668187", keychain="aws-vault.keychain"
2020/08/17 07:41:02 [keyring] Found item "aws-vault session for default (expires 2020-08-17T12:43:07Z)"
2020/08/17 07:41:02 Re-using cached credentials ****************C6CN from sts.GetSessionToken, expires in 1h2m4.341435s
2020/08/17 07:41:02 Setting subprocess env: AWS_DEFAULT_REGION=us-east-1, AWS_REGION=us-east-1
2020/08/17 07:41:02 Setting subprocess env: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
2020/08/17 07:41:02 Setting subprocess env: AWS_SESSION_TOKEN, AWS_SECURITY_TOKEN
2020/08/17 07:41:02 Setting subprocess env: AWS_SESSION_EXPIRATION
2020/08/17 07:41:02 Exec command aws s3 ls
aws-vault: error: exec: permission denied

**Comment by mtibben** [comment]
It's failing while trying an exec syscall. To eliminate variables can you try removing `credential_process` from your config first?

**Comment by tony-garcia** [comment]
I'm still getting 'permission denied' after removing `credential_process`

(base) agarcia-mbp00:~ agarcia$ aws-vault exec default --debug -- aws s3 ls
2020/08/17 11:45:19 aws-vault v6.0.0-beta6
2020/08/17 11:45:19 Loading config file /Users/agarcia/.aws/config
2020/08/17 11:45:19 Parsing config file /Users/agarcia/.aws/config
2020/08/17 11:45:19 [keyring] Considering backends: [keychain pass file]
2020/08/17 11:45:19 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/08/17 11:45:19 [keyring] Found 3 results
2020/08/17 11:45:19 profile default: using stored credentials
2020/08/17 11:45:19 profile default: using GetSessionToken
2020/08/17 11:45:19 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/08/17 11:45:19 [keyring] Found 3 results
2020/08/17 11:45:19 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/08/17 11:45:19 [keyring] Found 3 results
2020/08/17 11:45:19 [keyring] Querying keychain for service="aws-vault", account="sts.GetSessionToken,ZGVmYXVsdA,,1597682824", keychain="aws-vault.keychain"
2020/08/17 11:45:19 [keyring] Found item "aws-vault session for default (expires 2020-08-17T16:47:04Z)"
2020/08/17 11:45:19 Re-using cached credentials ****************XBKO from sts.GetSessionToken, expires in 1h1m44.96575s
2020/08/17 11:45:19 Setting subprocess env: AWS_DEFAULT_REGION=us-east-1, AWS_REGION=us-east-1
2020/08/17 11:45:19 Setting subprocess env: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
2020/08/17 11:45:19 Setting subprocess env: AWS_SESSION_TOKEN, AWS_SECURITY_TOKEN
2020/08/17 11:45:19 Setting subprocess env: AWS_SESSION_EXPIRATION
2020/08/17 11:45:19 Exec command aws s3 ls
aws-vault: error: exec: permission denied

**Comment by mtibben** [comment]
1. Can you try using the [v6.0.0-beta8](https://github.com/99designs/aws-vault/releases/tag/v6.0.0-beta8), and post logs?
2. What does `which aws` output?
3. Is it possible you have the setuid bit set on the binary being executed?
4. Can you give us more information about the binary you're executing with `ls -l /full/path/to/aws`, including details of any symlinks?

**Comment by tony-garcia** [comment]
I have the aws CLI installed as a python package in my base [conda](https://docs.conda.io/en/latest/) environment. Here is the debug output with v6.00-beta9:

```
(base) agarcia-mbp00:~ agarcia$ aws-vault exec default --debug -- aws s3 ls
2020/08/18 14:13:04 aws-vault v6.0.0-beta9
2020/08/18 14:13:04 Loading config file /Users/agarcia/.aws/config
2020/08/18 14:13:04 Parsing config file /Users/agarcia/.aws/config
2020/08/18 14:13:04 [keyring] Considering backends: [keychain]
2020/08/18 14:13:04 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/08/18 14:13:04 [keyring] Found 3 results
2020/08/18 14:13:04 profile default: using stored credentials
2020/08/18 14:13:04 profile default: using GetSessionToken
2020/08/18 14:13:04 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/08/18 14:13:04 [keyring] Found 3 results
2020/08/18 14:13:04 [keyring] Removing keychain item service="aws-vault", account="sts.GetSessionToken,ZGVmYXVsdA,,1597768890", keychain "aws-vault.keychain"
2020/08/18 14:13:04 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/08/18 14:13:04 [keyring] Found 2 results
2020/08/18 14:13:04 [keyring] Querying keychain for service="aws-vault", account="sts.GetSessionToken,ZGVmYXVsdA,,-62135596800", keychain="aws-vault.keychain"
2020/08/18 14:13:04 [keyring] No results found
2020/08/18 14:13:04 Looking up keyring for 'default'
2020/08/18 14:13:04 [keyring] Querying keychain for service="aws-vault", account="default", keychain="aws-vault.keychain"
2020/08/18 14:13:04 [keyring] Found item "aws-vault (default)"
2020/08/18 14:13:14 Generated credentials ****************CGMI using GetSessionToken, expires in 59m59.385711s
2020/08/18 14:13:14 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/08/18 14:13:14 [keyring] Found 2 results
2020/08/18 14:13:14 [keyring] Checking keychain status
2020/08/18 14:13:14 [keyring] Keychain status returned nil, keychain exists
2020/08/18 14:13:14 [keyring] Keychain item trusts keyring
2020/08/18 14:13:14 [keyring] Adding service="aws-vault", label="aws-vault session for default (expires 2020-08-18T19:13:14Z)", account="sts.GetSessionToken,ZGVmYXVsdA,,1597777994", trusted=true to osx keychain "aws-vault.keychain"
2020/08/18 14:13:14 Setting subprocess env: AWS_DEFAULT_REGION=us-east-1, AWS_REGION=us-east-1
2020/08/18 14:13:14 Setting subprocess env: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
2020/08/18 14:13:14 Setting subprocess env: AWS_SESSION_TOKEN, AWS_SECURITY_TOKEN
2020/08/18 14:13:14 Setting subprocess env: AWS_SESSION_EXPIRATION
2020/08/18 14:13:14 Exec command aws s3 ls
2020/08/18 14:13:14 Found executable /anaconda3/bin/aws
aws-vault: error: exec: permission denied
```

here is the output of `which aws`

```
/anaconda3/bin/aws
```

**Comment by tony-garcia** [comment]
Also output of `ls -l $(which aws)`

```
-rwxr-xr-x  1 agarcia  wheel  820 Oct  8  2019 /anaconda3/bin/aws
```

**Comment by tony-garcia** [comment]
OK -- uninstalling the python package and installing the aws cli as described here seems to have solved the issue. 
https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-mac.html

Maybe the docs should  be updated so that people don't try to use it with the python version.

**Comment by mtibben** [comment]
OK so is this an issue with conda then? I would still like to understand why aws-vault can't execute `/anaconda3/bin/aws`

**Comment by tony-garcia** [comment]
I'm not sure. Might have to do with the file permissions. As noted above, the python `aws` package installed in conda has user permissions:

```
-rwxr-xr-x  1 agarcia  wheel  820 Oct  8  2019 /anaconda3/bin/aws
```

But now when I installed the aws binary (version 2, which isn't a python package). It has root permissions:

```
lrwxr-xr-x  1 root  admin  22 Aug 18 14:25 /usr/local/bin/aws -> /usr/local/aws-cli/aws
```

I'm assuming it has something to do with that.

**Comment by tony-garcia** [comment]
So `aws-vault` can execute `aws` installed as a conda package, but the `permission denied` errors make me think it was trying to get it to do things it didn't have enough permissions to do. It's still weird that sometimes it worked and sometimes it didn't.

**Comment by mtibben** [comment]
The aws script uses the python interpreter, so may have something to do with the permissions of conda python?

**Comment by mtibben** [comment]
assuming this is fixed
