### ISSUE TITLE
Pass Backend for Linux not working in 5.4.4

### ISSUE THREAD

**Issue by rjackson-dev-ops** [99designs/aws-vault#626]
Are you dropping support for "pass" backend?

I got this error after trying to use 5.4.4. Pass works fine in 4.7.2.

aws-vault: error: enum value must be one of kwallet,secret-service,file, got 'pass', try --help

**Comment by mtibben** [comment]
Hey @rjackson-dev-ops, aws-vault will make pass available if the pass binary is available... see https://github.com/99designs/keyring/blob/master/pass.go#L27-L31

`which pass` should let you know where the pass binary exists
