### ISSUE TITLE
Running in --server mode fails: "Failed to wait for command termination: exit status 255"

### ISSUE THREAD

**Issue by tony-garcia** [99designs/aws-vault#629]
- [x] I am using the latest release of AWS Vault
- [x] I have provided my `.aws/config` (redacted if necessary)
- [x] I have provided the debug output using `aws-vault --debug` (redacted if necessary)

OS: MacOS 10.14.16
AWS-Vault versions: 5.4.4 and 6.0.0-beta6

Config file:
[default]
region=us-east-1
output=json
credential_process=aws-vault exec -j default

[profile computation]
region=us-east-1
output=json

[profile secrets]
region=us-east-1
source_profile = computation
role_arn = arn:aws:iam::xxxxxxxxxxxx:role/secrets-role

I always get the error in the title when I try to run `aws-vault exec` with the `--server` flag.

Here is the debug output on **version 5.4.4**:

(base) agarcia-mbp00:~ agarcia$ sudo aws-vault exec --server default --debug -- aws s3 ls
2020/08/17 07:37:55 aws-vault v5.4.4
2020/08/17 07:37:55 [keyring] Considering backends: [keychain pass file]
2020/08/17 07:37:55 Loading config file /Users/agarcia/.aws/config
2020/08/17 07:37:55 Parsing config file /Users/agarcia/.aws/config
2020/08/17 07:37:55 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/08/17 07:37:55 [keyring] Found 3 results
2020/08/17 07:37:55 profile default: using stored credentials
2020/08/17 07:37:55 profile default: using GetSessionToken
2020/08/17 07:37:55 Looking for sessions for default
2020/08/17 07:37:55 Looking up all keys in keyring
2020/08/17 07:37:55 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/08/17 07:37:55 [keyring] Found 3 results
2020/08/17 07:37:55 Session "session,ZGVmYXVsdA,,1597667747" expires in 57m51.690839s
2020/08/17 07:37:55 [keyring] Querying keychain for service="aws-vault", account="session,ZGVmYXVsdA,,1597667747", keychain="aws-vault.keychain"
2020/08/17 07:37:55 [keyring] Found item "aws-vault session for default"
2020/08/17 07:37:55 Re-using cached credentials ****************ADF2 generated from GetSessionToken, expires in 57m51.683038s
2020/08/17 07:37:55 Starting local instance role server on 127.0.0.1:9099
2020/08/17 07:37:55 Setting subprocess env: AWS_DEFAULT_REGION=us-east-1, AWS_REGION=us-east-1

Error when retrieving credentials from custom-process:
aws-vault: error: exec: Error execing process: Failed to wait for command termination: exit status 255

Here is the debug output on **version 6.0.0-beta6** (after clearing sessions)

(base) agarcia-mbp00:~ agarcia$ aws-vault exec --server default --debug -- aws s3 ls
2020/08/17 07:30:13 aws-vault v6.0.0-beta6
2020/08/17 07:30:13 Loading config file /Users/agarcia/.aws/config
2020/08/17 07:30:13 Parsing config file /Users/agarcia/.aws/config
2020/08/17 07:30:13 [keyring] Considering backends: [keychain pass file]
2020/08/17 07:30:13 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/08/17 07:30:13 [keyring] Found 2 results
2020/08/17 07:30:13 profile default: using stored credentials
2020/08/17 07:30:13 profile default: using GetSessionToken
2020/08/17 07:30:13 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/08/17 07:30:13 [keyring] Found 2 results
2020/08/17 07:30:13 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/08/17 07:30:13 [keyring] Found 2 results
2020/08/17 07:30:13 [keyring] Querying keychain for service="aws-vault", account="sts.GetSessionToken,ZGVmYXVsdA,,-62135596800", keychain="aws-vault.keychain"
2020/08/17 07:30:13 [keyring] No results found
2020/08/17 07:30:13 Looking up keyring for 'default'
2020/08/17 07:30:13 [keyring] Querying keychain for service="aws-vault", account="default", keychain="aws-vault.keychain"
2020/08/17 07:30:13 [keyring] Found item "aws-vault (default)"
2020/08/17 07:30:13 Generated credentials ****************LNVE using GetSessionToken, expires in 1h2m9.025142s
2020/08/17 07:30:13 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/08/17 07:30:13 [keyring] Found 2 results
2020/08/17 07:30:13 [keyring] Checking keychain status
2020/08/17 07:30:13 [keyring] Keychain status returned nil, keychain exists
2020/08/17 07:30:13 [keyring] Keychain item trusts keyring
2020/08/17 07:30:13 [keyring] Adding service="aws-vault", label="aws-vault session for default (expires 2020-08-17T12:32:23Z)", account="sts.GetSessionToken,ZGVmYXVsdA,,1597667543", trusted=true to osx keychain "aws-vault.keychain"
2020/08/17 07:30:13 Starting EC2 Instance Metadata server on 127.0.0.1:9099
2020/08/17 07:30:13 Setting subprocess env: AWS_DEFAULT_REGION=us-east-1, AWS_REGION=us-east-1
2020/08/17 07:30:13 Starting child process: aws s3 ls

Error when retrieving credentials from custom-process: aws-vault: error: exec: aws-vault sessions should be nested with care, unset $AWS_VAULT to force

aws-vault: error: exec: Failed to wait for command termination: exit status 255

Not sure if this may be related to https://github.com/99designs/aws-vault/issues/624

**Comment by mtibben** [comment]
Could you try without using `sudo` and without `credential_process` in the config (see the note about master credentials [here](https://github.com/99designs/aws-vault/blob/master/USAGE.md#using-credential-helper))?

And ensure you use a fresh shell - if `AWS_VAULT` is already set you're already in an aws-vault spawned shell

**Comment by tony-garcia** [comment]
If I remove `credential_process` and use `sudo`, I get "Unable to locate credentials" when using the --server flag (v 6.0.0-beta6):

(base) agarcia-mbp00:~ agarcia$ sudo aws-vault exec --server default --debug -- aws s3 ls
2020/08/17 11:50:18 aws-vault v6.0.0-beta6
2020/08/17 11:50:18 Loading config file /Users/agarcia/.aws/config
2020/08/17 11:50:18 Parsing config file /Users/agarcia/.aws/config
2020/08/17 11:50:18 [keyring] Considering backends: [keychain pass file]
2020/08/17 11:50:18 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/08/17 11:50:18 [keyring] Found 3 results
2020/08/17 11:50:18 profile default: using stored credentials
2020/08/17 11:50:18 profile default: using GetSessionToken
2020/08/17 11:50:18 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/08/17 11:50:18 [keyring] Found 3 results
2020/08/17 11:50:18 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/08/17 11:50:18 [keyring] Found 3 results
2020/08/17 11:50:18 [keyring] Querying keychain for service="aws-vault", account="sts.GetSessionToken,ZGVmYXVsdA,,1597682824", keychain="aws-vault.keychain"
2020/08/17 11:50:18 [keyring] Found item "aws-vault session for default (expires 2020-08-17T16:47:04Z)"
2020/08/17 11:50:18 Re-using cached credentials ****************XBKO from sts.GetSessionToken, expires in 56m45.397767s
2020/08/17 11:50:18 Setting subprocess env: AWS_DEFAULT_REGION=us-east-1, AWS_REGION=us-east-1
2020/08/17 11:50:18 Starting child process: aws s3 ls
2020/08/17 11:50:18 Starting EC2 Instance Metadata server on 127.0.0.1:9099
Unable to locate credentials. You can configure credentials by running "aws configure".
aws-vault: error: exec: Failed to wait for command termination: exit status 255

And yes -- I can use the aws CLI without aws-vault when I use `credential_process`. So that's fine when I'm using the default profile. The issue is when I want to use a different profile than `default`. I actually wanted to get --server mode to work because my co-worker told me that was how he was able to get around the `permission denied` issue that I reported in https://github.com/99designs/aws-vault/issues/624

**Comment by tony-garcia** [comment]
...also, I never see AWS_VAULT set. Any time I do `echo $AWS_VAULT` I get nothing.

**Comment by mtibben** [comment]
> If I remove `credential_process` and use `sudo`

No I'm saying don't use sudo.

Don't use sudo, don't use `credential_process` , and try the latest v6 beta

**Comment by tony-garcia** [comment]
Ah ok. I did that and now it works. So using `credential_process` I get

```
Error when retrieving credentials from custom-process: aws-vault: error: exec: aws-vault sessions should be nested with care, unset $AWS_VAULT to force

aws-vault: error: exec: Failed to wait for command termination: exit status 255
```

When when I remove `credential_process`,  `aws-vault` executes fine with the --server flag.

So is this a bug? Should I be able to use the --server flag when `credential_process` is set?

**Comment by mtibben** [comment]
Not a bug. When using credentials_process you shouldn't use aws-vault directly to run commands. See the usage docs

**Comment by tony-garcia** [comment]
OK gotcha. I guess this can be closed then.
