### ISSUE TITLE
Allow specifying RoleSessionName at runtime

### ISSUE THREAD

**Issue by christophetd** [99designs/aws-vault#634]
When assuming a role, aws-vault currently uses the role_session_name parameter defined in ~/.aws/config: https://github.com/99designs/aws-vault/blob/master/vault/config.go#L136

It would be useful to be able to specify (and override) this at runtime, e.g.

```
aws-vault exec dev --role-session-name "christophe-test"
```

Thoughts? Is that something you would consider implementing? 

Thanks!

**Comment by mtibben** [comment]
You can actually set `AWS_ROLE_SESSION_NAME` env var for this purpose
