### ISSUE TITLE
transparent usage of awscli

### ISSUE THREAD

**Issue by stevenolen** [99designs/aws-vault#641]
Apologies if this has been asked before (I did some searching of the issue list and didn't see an obviously similar question). I'll start by saying: aws-vault is great and I'd love to push adoption at my org. 

While taking a look and getting comfortable with it I stumbled into an odd situation that I'd love some input on from the community. I'd like to be able to set up my `~/.aws/config` such that I can use vault for credentials, but not modify my other aws usage -- this seems like a great case for `credential_process` since it allows me to have awscli fetch credentials from aws-vault, but because they share a config file I have ended up with what appears to me as a very odd profile inheritance situation:

```
[profile foo]
# my standard profile that has permanent credentials added to vault
region = us-east-1
credential_process = aws-vault exec foo --json --prompt=osascript

[profile bar]
# a placeholder profile that gets used with `aws` commands
region = us-east-1
credential_process = aws-vault exec bar-devops --json --prompt=osascript

[profile assume-role-common]
# some common profile items that can't be applied to the `foo` profile
source_profile = foo
mfa_serial = arn:aws:iam::000000000000:mfa/my-mfa
duration_seconds = 43200

[profile bar-devops]
# a devops role in the 'bar' subaccount, which uses `foo` permanent credentials to obtain temporary credentials
# notably, this profile only functions via `aws-vault` and cannot be used directly by awscli
include_profile = assume-role-common
role_arn = arn:aws:iam::000000000001:role/devops
```

This situation, however, is really great: I can execute `aws --profile bar s3 ls` and I'm prompted for my mfa if needed, or if vault has temporary credentials for `bar`, the command will simply finish executing. It feels odd though, requiring two separate profiles for the same role (one that aws-vault will use, and the other which can be used by an aws library that supports `credential_process`. It also feels like a decent example of why joining the configuration of `aws-vault` into awscli's config file leads to some confusion with regards to which tool can process which lines.

Am I doing this wrong? Is there a better configuration to achieve the same result? I like both the `exec` and `server` features of `aws-vault` but they seem to require an "all-in" approach that I'd like to avoid by ensuring that the standard profile selection of awscli continues to function transparently.

**Comment by FernandoMiguel** [comment]
@stevenolen 
let me put the question the other way around:
why/when would you want to use aws cli **without** aws-vault?

**Comment by stevenolen** [comment]
Hi @FernandoMiguel!

My last sentence was trying to get at that, but I can certainly be more clear with my intent: backwards compatibility with a pre-aws-vault world. It offers a lower barrier to entry if users can continue to run their tooling as they always have, but integrate aws-vault to hold credentials. 

A more concrete example may be a simple script/tool that makes use of the aws cli and the `--profile` opt to make a handful of aws calls, each to different profiles using the `--profile` opt to coordinate between subaccounts. This would require writing to prepend each call with `aws-vault exec` and remove the profile opt, but your support of `credential_process` actually allows this to happen seamlessly!

To be clear I think it's totally reasonable if the `aws-vault` project has no interest in supporting this path or making the path cleaner, but the ability to use it as a `credential_process` makes me feel like things are _almost_ there.

**Comment by FernandoMiguel** [comment]
Having creds in clear text is what we are trying to address here.
So keeping using old methods should be discourage

**Comment by stevenolen** [comment]
The suggestion I mentioned doesn't store credentials in clear text any more than it `aws-vault exec --` does though? In fact, it would be relying entirely on `aws-vault` for credentials, it's just that the use of profiles by awscli is a pretty decent standard for making calls between different profiles, which wont work any longer with aws-vault.

**Comment by mtibben** [comment]
There does seem to be some confusion with new users to aws-vault who jump straight to using `credential_process`. Using `credentials_process` isn't the way I use aws-vault, it was a contributed addition, so feels like we should emphasise this is not the recommended path.

Setting a profile env var isn't required with aws-vault because you specify it on the command line. e.g. `aws-vault exec PROFILE -- aws ....`

> it's just that the use of profiles by awscli is a pretty decent standard for making calls between different profiles, which wont work any longer with aws-vault

In fact this is how aws-vault v1 did actually work. It turned out the ergonomics of using aws-vault were awkward however, and v2 switched to the current approach. Perhaps with `credentials_process` the original approach could be improved, I'm not sure

So as a new user, I would recommend learning aws-vault without `credentials_process`. And if you want to use `credential_process` I would recommend using it as analogous to `source_profile` and use the `--no-session` flag.

**Comment by stevenolen** [comment]
Hi @mtibben! 

> There does seem to be some confusion with new users to aws-vault who jump straight to using credential_process. Using credentials_process isn't the way I use aws-vault, it was a contributed addition, so feels like we should emphasise this is not the recommended path.

I agree and totally understand your point when viewed from that standpoint. For what it's worth, I actually think that making a local environment where the transparent use of aws tooling via vault credentials would be superb, and would definitely drive adoption of `aws-vault` but perhaps that's actually a completely different tool than the one you're offering! 

 I'll close this since it doesn't seem like it jives with the current direction of the project, and I don't want to contribute to clutter! Thanks to both of you for the better understanding of that current direction!

**Comment by olfway** [comment]
I use it this way:

~/.aws/config
```
[profile root]
mfa_serial = arn:aws:iam::XXX:mfa/olfway
credential_process = env AWS_SDK_LOAD_CONFIG=0 aws-vault --backend=pass --pass-prefix=aws-vault --prompt=osascript exec --region eu-west-1 --duration=1h root --json

[profile core-admin]
source_profile = root
parent_profile = root
role_arn = arn:aws:iam::YYY:role/CoreAdmin
```

some-project/.envrc
```
export AWS_PROFILE="core-admin"
export AWS_DEFAULT_REGION="eu-west-1"

export AWS_VAULT_BACKEND=pass
export AWS_VAULT_PASS_PREFIX=aws-vault
```

This ".envrc" file auto–loads with direnv when I cd in "some-project" catalog

So I'm able to use aws / terraform / packer / etc with aws-vault
```
aws sts get-caller-identity
```
