### ISSUE TITLE
Profile named "default" not working when using AWS SSO in 6.0 beta 10

### ISSUE THREAD

**Issue by andreausu** [99designs/aws-vault#642]
Hello,

I'm running into an issue while using aws-vault 6.0.0 beta 10 with AWS SSO.
I'm trying to use `aws-vault exec` with a profile named `default` that is configured to login using AWS SSO, however I'm getting the following error: `aws-vault: error: exec: Error getting temporary credentials: profile default: credentials missing`
What is really strange is that if I simply rename the profile from `default` to anything else it works as expected.
It should be possible to just use a profile named default in conjunction with AWS SSO, since doing so from AWS CLI v2 works as expected.

Thanks!

- [x] I am using the latest release of AWS Vault
`v6.0.0-beta10`

- [x] I have provided my `.aws/config` (redacted if necessary)
```
[profile default]
sso_start_url = http://aaa.awsapps.com/start
sso_region = eu-west-1
sso_account_id = xxx
sso_role_name = AdministratorAccess
region = eu-west-1

[profile secrets]
role_arn = arn:aws:iam::xxx:role/SomeRoleName
source_profile = default

[profile uk-admin]
sso_start_url = http://aaa.awsapps.com/start
sso_region = eu-west-1
sso_account_id = yyy
sso_role_name = AdministratorAccess
region = eu-west-1
```

- [x] I have provided the debug output using `aws-vault --debug` (redacted if necessary)

```
aws-vault --debug exec default -- aws sts get-caller-identity 
2020/08/25 17:49:09 aws-vault v6.0.0-beta10
2020/08/25 17:49:09 Loading config file /Users/andrea/.aws/config
2020/08/25 17:49:09 Parsing config file /Users/andrea/.aws/config
2020/08/25 17:49:09 [keyring] Considering backends: [keychain]
2020/08/25 17:49:09 Profile 'default' missing in config file
2020/08/25 17:49:09 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/08/25 17:49:09 [keyring] Found 3 results
aws-vault: error: exec: Error getting temporary credentials: profile default: credentials missing
```

**Comment by mtibben** [comment]
Using a profile named `default` is a little unusual, as there is a `[default]` section in the AWS config also. How does aws-cli handle having both `[default]` and `[profile default]` sections?

**Comment by tgardiner** [comment]
I mistakenly had `[profile default]` set instead of `[default]` and hit this issue.  The awscli seems to just treat it as default as I hadn't noticed any odd behaviour and wasn't specifying a profile.
