### ISSUE TITLE
Feedback on `clear` command

### ISSUE THREAD

**Issue by mtibben** [99designs/aws-vault#645]
I've just merged the addition of a `clear` command in the latest v6 beta - see #644 #591 #412

I initially wanted to use the existing `rm --sessions-only` to achieve this, but found too many inconsistencies between add vs rm, specifying a profile vs no profile and sessions vs oidc token, so fell back to the original proposal of a `clear` command which had none of the inconsistencies.

Please feel free to test `clear` (clears sessions/tokens), the changes to `list` with sessions and oidc tokens displayed in the Sessions column, and `rm` now being used for long-term credentials (but still supporting the old flag for full backwards compatibility).

Any feedback welcome those who have commented so far @pda @olfway @rossmckelvie @nitrocode @FernandoMiguel @scalp42 @tomelliff and anyone else with an interest.

If this works out for everyone I think we're ready for a v6 release finally 😅

**Comment by FernandoMiguel** [comment]
Uhhh a full release.. Such a long time coming

**Comment by mtibben** [comment]
Yeah the v5 release was a little rushed, didn't want to make the same mistake twice but it's taken a little while getting here

**Comment by FernandoMiguel** [comment]
Since I use aws sso been on v6 since it was made available and got rid of the sportradar docker.
I missed aws-vault ease and multi role so much

Thank you and the other contributors so much

**Comment by FernandoMiguel** [comment]
https://github.com/99designs/aws-vault/blob/master/USAGE.md#removing-credentials
Should this bit of the docs be updated to use `clear` instead?

**Comment by FernandoMiguel** [comment]
Never mind.. It's below

**Comment by mtibben** [comment]
ok fixed

**Comment by ajkerrigan** [comment]
Thanks everyone for all the work on this - the new `clear` command is helpful, and the tweaks to `list` are welcome. Things feel really solid at this point, and equally smooth with or without SSO. 👏

**Comment by olfway** [comment]
Works for me, thanks @mtibben !

noticed a small inconsistency with expired sessions:
```
❯ aws-vault list
root                      root                            sts.GetSessionToken:-31m50s
```
Shows there is one (expired) session

```
❯ aws-vault clear
Cleared 0 sessions.
```
Says zero sessions was cleared

But actually session was cleared
```
❯ aws-vault list
root                       root                           -
```

**Comment by mtibben** [comment]
v6 released 🎉
