### ISSUE TITLE
Unsetting AWS_CONFIG_FILE breaks `aws cloudfront`

### ISSUE THREAD

**Issue by dgoodlad** [99designs/aws-vault#65]
The `cloudfront` command of the aws CLI requires that you explicitly enable it by setting this in your aws config file:

```ini
[preview]
cloudfront = true
```

In the forked environment of `aws-vault exec`, `AWS_CONFIG_FILE` gets set to `/dev/null` by https://github.com/99designs/aws-vault/blob/master/exec.go#L89 (this behavior was introduced in cb5710de405503c2dea35d6bf3046fb50ebae367). With that, the `aws` tool can't see the configuration enabling the cloudfront preview.

The hack workaround was to spawn a shell and reset that env var, but that's not exactly ideal 😄 

What's the reason for :skull: `AWS_CONFIG_FILE`, anyway? What kinds of values in there were you trying to avoid, @lox ?

**Comment by lox** [comment]
Hmmmm, I seem to recall the issue is that subshells would try and read the aws config file, rather than use the injected credentials and this lead to strange combinations of credentials and failures. Initially I was generating a version of the config file per sub-shell to work around the issue, perhaps this needs to be done again.

**Comment by dgoodlad** [comment]
I can imagine a situation where someone's got credentials hardcoded in their config and that would cause conflicts. That seems like a misconfiguration to me, though, and could possibly be something that `aws-vault` looks for and warns about?

**Comment by lox** [comment]
Sounds like it might need some testing. If you wanted to submit a PR that drops that unset, I'd put out a RC release with it in it and we can run it for a while?

**Comment by dgoodlad** [comment]
:ok_hand:





On Mon, Jun 20, 2016 at 10:38 PM +1000, "Lachlan Donald" <notifications@github.com> wrote:












Sounds like it might need some testing. If you wanted to submit a PR that drops that unset, I'd put out a RC release with it in it and we can run it for a while?

**Comment by lox** [comment]
I'm going to re-open this until we confirm it fixes the issue and doesn't cause any others.

**Comment by lox** [comment]
https://github.com/99designs/aws-vault/releases/tag/v3.3.0-experimental

**Comment by lox** [comment]
I'm not doing a lot of `aws-vault`-ing whilst on holidays, so certainly would appreciate feedback from others.

**Comment by dgoodlad** [comment]
Thanks @lox - tested 3.3.0-experimental and `aws cloudfront` works as expected now. In very limited testing I didn't run into any issues because of this change, but my `~/.aws/config` definitely doesn't cover every possible configuration!
