### ISSUE TITLE
Ship ppc64le binary for every new release

### ISSUE THREAD

**Issue by runlevel5** [99designs/aws-vault#650]
I've been using aws-vault on the Raptor Blackbird workstation (which runs Linux PowerPC 64 LE) as the main driver for awhile and really enjoying it. As the platform has grown in popularity, wondering if the team could ship ppc64le binary for every new release?

FYI TravisCI does support ppc6le Linux.

**Comment by mtibben** [comment]
Done in https://github.com/99designs/aws-vault/commit/ddd3e5fe2049fe6c9f1c75c2f7cf671aa65767bc

**Comment by runlevel5** [comment]
@mtibben Let's hope the binary would be out for 6.0.2

**Comment by runlevel5** [comment]
Nice 6.1.0 has shipped the binary! YAYH!
