### ISSUE TITLE
GenericRXLS-ZZ!0256F7FB2E5B malware alert on latest version on Windows

### ISSUE THREAD

**Issue by codethatrocks** [99designs/aws-vault#652]
- [x ] I am using the latest release of AWS Vault
- [x] I have provided my `.aws/config` (redacted if necessary)
- [x] I have provided the debug output using `aws-vault --debug` (redacted if necessary)
Just downloaded latest version for windows and McAffee hooked in:
McAfee reports GenericRXLS-ZZ!0256F7FB2E5B Malware on aws-vault.exe

VirusTotal:
https://www.virustotal.com/gui/file/5185bb5130dafb5c939f408781d7640e953134ae94ae0ccb52229969b47f0c80/detection

![shasum-OK](https://user-images.githubusercontent.com/27976182/92398620-38602680-f129-11ea-9ffe-1b61a27d8604.PNG)

**Comment by mtibben** [comment]
Similar to previous reports of false positives. Unless you know of a way to prevent this (code-signing?), not sure there's anything we can do here.
