### ISSUE TITLE
Release for v6.0.1 is missing SHA256SUMS

### ISSUE THREAD

**Issue by douglaswth** [99designs/aws-vault#658]
The [v6.0.1](https://github.com/99designs/aws-vault/releases/tag/v6.0.1) release does not have the `SHA256SUMS` file like previous releases.

- [x] I am using the latest release of AWS Vault
- [ ] I have provided my `.aws/config` (redacted if necessary)
- [ ] I have provided the debug output using `aws-vault --debug` (redacted if necessary)

**Comment by mtibben** [comment]
fixed, thanks
