### ISSUE TITLE
Windows Security on Work Laptop identifying AWS Vault as Trojan:Win32/Zpevdo.B

### ISSUE THREAD

**Issue by darrenkidd** [99designs/aws-vault#661]
- [ ] ~I am using the latest release of AWS Vault~
- [ ] ~I have provided my `.aws/config` (redacted if necessary)~
- [ ] ~I have provided the debug output using `aws-vault --debug` (redacted if necessary)~

I went to run `aws-vault` for the first time in a little while on my work laptop, and got a mysterious "command not found" error. Looks like Windows Security thinks this is **Trojan:Win32/Zpevdo.B** and therefore automatically deleted the binary.

![image](https://user-images.githubusercontent.com/14284827/93550648-f56f4000-f9bf-11ea-8aa8-886f6539d6f5.png)

I tried to download the latest version (6.1.0) but the download was picked up as a trojan too.

![image](https://user-images.githubusercontent.com/14284827/93550721-1cc60d00-f9c0-11ea-860b-a26abfd56c02.png)

HTH.

**Comment by darrenkidd** [comment]
Linking to a previous issue: #566.

**Comment by mtibben** [comment]
What do suggest @darrenkidd ?

**Comment by darrenkidd** [comment]
Sorry, @mtibben, I only skimmed the previous issue and assumed that submitting it as a false positive was something only repo owners could do. Apologies.

I've submitted this to Microsoft ([link](https://www.microsoft.com/en-us/wdsi/submission/b7eb5a6d-61b5-4feb-ae53-50a52e72145e)) now. Figured that it wouldn't be very good if all the Window 10 PCs in the world refused to download or run AWS Vault.

Nothing left to do but wait, I guess.

**Comment by mtibben** [comment]
Great thanks @darrenkidd

**Comment by darrenkidd** [comment]
FYI: Microsoft has analysed the binary and has marked it as safe.

![image](https://user-images.githubusercontent.com/14284827/93689484-01274780-fb23-11ea-851d-da8786e36be6.png)

My machine still thinks it's malware, but I suspect that the corporate security policies are probably overruling my latest definition update on my laptop. Hopefully it comes good in a day or so; at least it will stop the issue for many future downloaders/users.

**Comment by mtibben** [comment]
Hey @darrenkidd if you or your employer wants to fund a [code signing cert](https://www.digicert.com/code-signing/) for signing windows builds, this would go a long way towards addressing the issue
