### ISSUE TITLE
aws-vault fails on MacOS Catalina, "can't be opened because Apple cannot check it for malicious software"

### ISSUE THREAD

**Issue by gitcos** [99designs/aws-vault#665]
Currently on OS X Catalina 10.15.6.
I originally installed aws-vault on this macbook back in April or May, using HomeBrew.  At the time I was already on Catalina, but an older version of course.
Today, I ran 'brew upgrade aws-vault' which brought me up to aws-vault 6.2.0:
| ==> Upgrading 1 outdated package:
| aws-vault 5.4.1 -> 6.2.0

Immediately after that upgrade, I could no longer run aws-vault, I got "aws-vault can't be opened because Apple cannot check it for malicious software".

I found this older bug from 2019, now closed: #430 
@mtibben closed it on October 28, 2019, after commenting "it seem to execute fine on the command line, which is where it will be used".  However, I *am* running it from the command line.

After running this to remove the quarantine attribute, I can use aws-vault again:
`xattr -d com.apple.quarantine /usr/local/Caskroom/aws-vault/6.2.0/aws-vault`

I'm not sure what changed with this upgrade.  Based on issue #430 , I get the impression that aws-vault was not notarized for Catalina in April/May, and is still not notarized now.  It is possible that security settings on my Mac have changed.  It's also possible that Homebrew changed whether or not they add the quarantine attribute - https://github.com/Homebrew/homebrew-cask/issues/70798 - the timeline there is not clear to me.

However, what is clear to me is that lack of notarization does seem to interfere with command-line invocation of aws-vault.

**Comment by mtibben** [comment]
> I get the impression that aws-vault was not notarized for Catalina in April/May, and is still not notarized now

@gitcos aws-vault macOS release binaries are signed, and the dmg is signed and notorized, and have been since [v4.7.0](https://github.com/99designs/aws-vault/releases/tag/v4.7.0)

Binaries themselves can't be notorized at this time, however when copying binaries from a notorized dmg macOS will not quarantine them. As you note, brew cask also has some issues around notorization and quarantining

Perhaps your aws-vault install has made it through a macOS update where the quarantine flag wasn't removed? Can you reproduce this behaviour if you uninstall aws-vault completely then re-install?

**Comment by gitcos** [comment]
I'm having a hard time understanding your comment.  However, just to be clear, as I described above, the problem began not with a MacOS update, but with an aws-vault update.  I ran 'brew upgrade aws-vault'.  aws-vault worked just before the upgrade, and failed with the guardian error immediately after the upgrade.

I think you are saying that the aws-vault binary I get from homebrew should have quarantine disabled, and that homebrew is responsible for doing that, so what happened here is that it failed to do that?  Do you know of a homebrew bug about this, or do you think a new one should be opened?  Or, am I misunderstanding you?

**Comment by ronkorving** [comment]
Same problem here on Catalina 10.15.7. Just want to make it clear that this is not just @gitcos with a problem. I freshly installed aws-vault 6.2.0 (not an upgrade) today on a freshly installed Catalina.

<img width="532" alt="image" src="https://user-images.githubusercontent.com/631240/94681835-0f653700-035f-11eb-9d18-11d2cb583e63.png">

However, @gitcost, when I ran `brew cask reinstall aws-vault`, the problem disappeared. Please give that a shot.

**Comment by mtibben** [comment]
@gitcos does `brew cask reinstall aws-vault` solve the issue for you?

**Comment by gitcos** [comment]
As I noted in my initial comment, I got rid of the issue with xattr.  Are you suggesting that I should try using xattr to turn quarantine back on on this file, then verify that I can't run it, and then try brew cask reinstall to see if that re-fixes it?  Just want to be clear that I'm understanding you and you're not misunderstanding me.

**Comment by mtibben** [comment]
Ah I'm suggesting
 1. Uninstall aws-vault completely `brew cask uninstall aws-vault` + purge or whatever else you need to do to completely get rid of the binaries
 2. Install aws-vault - `brew cask install aws-vault`
 3. Question: Do you still have the problem that you initially had? If not, this was a brew issue during the upgrade

**Comment by mtibben** [comment]
Assuming this is resolved for you

**Comment by gitcos** [comment]
Wait what?  What reason is there to think this is resolved?

I worked around it with xattr but that doesn't mean the problem is gone.  Did you figure out the cause, or change something to fix it?

**Comment by mtibben** [comment]
> What reason is there to think this is resolved?

There was no reply to https://github.com/99designs/aws-vault/issues/665#issuecomment-708827133

**Comment by skyzyx** [comment]
A weird Homebrew nuance I've observed is that if you _overwrite_ a quarantined binary with a new binary, the quarantine persists. However, if you _delete_ the quarantined binary and replace it with a new binary, the quarantine is lifted.

(Specifically talking about _notarized_ binaries, and in particular, ones written in Go.)

**Comment by mcpherson** [comment]
For others looking, I had the same problem on 10.15.7 and @mtibben suggestion to uninstall/reinstall fixed the issue.

**Comment by simonmulser** [comment]
I had to remove the attribute as suggested by OP

`xattr -d com.apple.quarantine path-to-the-binary`

Then I uninstalled and reinstalled.

**Comment by honey-malviya** [comment]
@simonmulser reinstallation is not needed. Or at least not for me. maybe its the newer version. 

As of this date, you can use:

` xattr -d com.apple.quarantine /opt/homebrew/Caskroom/aws-vault/7.2.0/aws-vault` or path to your vault file.

**Comment by mercadoalex** [comment]
brew reinstall --cask aws-vault works for me
