### ISSUE TITLE
Docs: How does AWS_VAULT_PROMPT work?

### ISSUE THREAD

**Issue by davidvasandani** [99designs/aws-vault#666]
To retrieve my TOTP I use 1Password CLI `op get totp NameIn1Password`.

Is it possible to pass the TOTP via `AWS_VAULT_PROMPT=terminal` or is there another method?

**Comment by shockey** [comment]
There's a flag you can use — here's how I do it:

```
aws-vault exec --mfa-token $(op get totp my_aws_1password_entry_name) my_aws_role_name
```
