### ISSUE TITLE
Instructors on how to run aws-vault inside Docker

### ISSUE THREAD

**Issue by Dzhuneyt** [99designs/aws-vault#671]
I am a big fan of aws-vault, already advertising it to my colleagues.

However, since we all use different OSes (Mac, Ubuntu, Ubuntu as WSL2 image) we had some recent issues with the installation and keychain detection.

Since we feel pretty comfortable using Dockerfiles and docker-compose.yml based projects, I was curious to understand if you plan on showcasing some basic instructions on how to get aws-vault running in a cross-platform way using mounted volumes, etc?

I am available to help.

**Comment by vroad** [comment]
I don't recommend running aws-vault inside a container.

I also run tools that need aws credentials inside docker, but I'm currently using aws-vault installed on the host. I have a small wrapper script which executes aws-vault, gets credentials in env vars, and passes them to docker run. This way I could still use OS specific keyring such as wincred, macOS/OSX keychain.

**Comment by Dzhuneyt** [comment]
The keyring is exactly one of the reasons I brought up this topic. I've had nothing but bad experience running aws-vault inside Ubuntu inside Windows WSL2, which is a bit more "lightweight" version of Ubuntu excluding built-in keyrings software.

If aws-vault was running inside a container that had, e.g, Ubuntu + AWS CLI + Keyring software, that would be a much pleasant developer user experience - running a simple `docker run --` command instead of tackling Homebrew, Keyring, AWS CLI, etc as the prerequisites that are currently required on a clean OS.

**Comment by vroad** [comment]
One way that could work is using pass backend and share unix socket that gpg-agent will use for communication, but I haven't tried that by myself. 

I'm using Terraform container as an alias to a shell script that runs `docker run`, which means container gets recreated every time I run it. Unless I switch to docker run + docker exec, I can't run gpg-agent inside in the same container as Terraform.

I'd prefer running gpg-agent inside separate container to make docker image minimal, if running aws-vault inside container is a requirement.

**Comment by Dzhuneyt** [comment]
I've started working on this: https://github.com/Dzhuneyt/aws-vault-docker

**Comment by Nuru** [comment]
Cloud Posse's [Geodesic](https://github.com/cloudposse/geodesic) solves this issue by using `export AWS_VAULT_BACKEND=file` to use the file-based keyring stored on the host, and then mounts the directory containing the keyring file into the Docker container.

**Comment by mtibben** [comment]
@Dzhuneyt aws-vault will work fine inside a docker container if that's what you want to do. And you can pass in env vars and mounts the same way you would any docker container. Feel free to contribute extra docs if you think they would be useful

**Comment by danwashusen** [comment]
Here is my take on it: https://gist.github.com/danwashusen/d3b942e4fa013c27bd5fd421403617d8

**Comment by DaazKu** [comment]
If you came from a search engine here's the "proper way" to do it:

https://github.com/99designs/aws-vault/blob/master/USAGE.md#docker

Alternative way of doing it that is much simpler:

- Define this in `environment` section of the service:
    ```
    environment:
      - AWS_REGION
      - AWS_DEFAULT_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
    ```
- Start `docker-compose.yml` like so:
    ```
    aws-vault exec {PROFILE} -- docker compose up ...
    ```

The downside is that the creds won't be automatically renewed.

---

As for the previous post. Do not mount your `.ssh` folder in containers. Use the agent. See https://stackoverflow.com/a/72384972
