### ISSUE TITLE
Assume Role - MFA Issue - MultiFactorAuthentication failed, unable to validate MFA code

### ISSUE THREAD

**Issue by gw-bcharboneau** [99designs/aws-vault#676]
I am getting the following error in Windows version 6.2.0

aws-vault: error: exec: Failed to get credentials for account2: AccessDenied: MultiFactorAuthentication failed, unable to validate MFA code.  Please verify your MFA serial number is valid and associated with this user.
        status code: 403, request id: d5dd2148-ff06-4ec9-859f-9a245e318712

I know it is valid because I am able to login to the account the mfa is setup on with it just fine. just not able to login to other accounts using the same roles as other users in my organization

what else am I missing?

My Config - obviously I changed certain parts for security

```
[default]
cli_pager=
mfa_serial=arn:aws:iam::XXXXXXXX1:mfa/my.user
region=us-east-1
output=json

[profile account1]
region=us-east-1
mfa_serial=arn:aws:iam::XXXXXXXX1:mfa/my.user
role_arn=arn:aws:iam::XXXXXXXX2:role/mfarole

[profile account2]
region=us-east-1
output=json
mfa_serial=arn:aws:iam::XXXXXXXX1:mfa/my.user
role_arn=arn:aws:iam::XXXXXXXX3:role/mfarole
```
debug output
```
2020/10/15 15:17:48 aws-vault v6.2.0
2020/10/15 15:17:48 Loading config file D:\Users\my.user\.aws\config
2020/10/15 15:17:48 Parsing config file D:\Users\my.user\.aws\config
2020/10/15 15:17:48 [keyring] Considering backends: [wincred]
2020/10/15 15:17:48 profile account2: using stored credentials
2020/10/15 15:17:48 profile account2: using GetSessionToken (with MFA)
2020/10/15 15:17:48 profile account2: using AssumeRole (chained MFA)
2020/10/15 15:17:48 Using STS endpoint https://sts.amazonaws.com
Enter token for arn:aws:iam::151396376837:mfa/my.user: 823130
2020/10/15 15:18:11 Using STS endpoint https://sts.amazonaws.com
2020/10/15 15:18:11 Looking up keyring for 'account2'
aws-vault: error: exec: Failed to get credentials for account2: AccessDenied: MultiFactorAuthentication failed, unable to validate MFA code.  Please verify your MFA serial number is valid and associated with this user.
        status code: 403, request id: 6a399238-6ce3-452b-a801-1cd812fd0889
```

**Comment by gw-bcharboneau** [comment]
Any Idea what my issue might be? works without MFA, but I would prefer to use a single MFA Token rather than having 1 for each AWS Account.

Any help is greatly appreciated. If it is something I missed, please let me know.

**Comment by mtibben** [comment]
Something up with the way MFA set up on your account? aws-vault is trying to use GetSessionToken with MFA - is that something your IAM is allowing?

**Comment by HRUAS** [comment]
Hi, I am also getting the same issue, any idea how is was resolved?
