### ISSUE TITLE
Feature: AWS SSO "--no-browser" option

### ISSUE THREAD

**Issue by lsowen** [99designs/aws-vault#678]
For various reasons such as not wanting to use the  system default browser, wanting to open the SSO link in a specific Firefox Containers container, etc, it would be useful to be able to optionally only print the `VerificationUriComplete` instead of only showing it if `open.Run()` fails.  My suggestion would be to add a new `--no-browser` or similar option that could be used to trigger this behaviour (with the default being the current widely useful "auto-open" method).

Once the link is opened once, it cannot be re-used, so currently there is no way to grab the link before it has been used the first time (unless the default URL handling browser fails to open or is missing)

https://github.com/99designs/aws-vault/blob/8a679cf21c5f74b7d9e967aa6ada2f9b543ba8cd/vault/ssorolecredentialsprovider.go#L129-L132

**Comment by olfway** [comment]
It's not stale

**Comment by lsowen** [comment]
Not stale

**Comment by turiandras** [comment]
did anyone find a good workaround?
for the 'aws' cli,  setting BROWSER to /usr/bin/echo is supposedly a good solution ( https://github.com/aws/aws-cli/issues/5301  ),  doesnt seem to work for 'aws-vault'

**Comment by turiandras** [comment]
Ok apparently the "--stdout" flag now does exactly this
