### ISSUE TITLE
Docs example for include_profile not working

### ISSUE THREAD

**Issue by pikeas** [99designs/aws-vault#679]
- [x] I am using the latest release of AWS Vault
- [x] I have provided my `.aws/config` (redacted if necessary)

From https://github.com/99designs/aws-vault/blob/master/USAGE.md
```
; The "root" profile here operates as a profile, a config fragment as well as a source_profile
[profile root]
region=eu-west-1
mfa_serial=arn:aws:iam::123456789:mfa/johnsmith
source_profile = root
```

```
$ aws-vault add root
aws-vault: error: add: Your profile has a source_profile of root, adding credentials to root won't have any effect
```

I can remove `source_profile`, add credentials, and then restore it. If this is working as intended and the usage is recommended, please update the docs accordingly.

**Comment by pikeas** [comment]
Tinkering with this a bit more, it doesn't seem to be working the way I expect. I know this was reworked in v6, so perhaps that has something to do with it.

```
[profile dev]
include_profile = root
```

With a separate dev profile (planning to add a role_arn, building the config up step-by-step):

```
$ aws-vault exec dev -- aws s3 ls
Enter token for arn:aws:iam::1234:mfa/me: ...
Enter token for arn:aws:iam::1234:mfa/me: ...
aws-vault: error: exec: Failed to get credentials for dev: AccessDenied: Cannot call GetSessionToken with session credentials
```

It looks like the aws-vault generates temporary credentials for the root profile, which it then attempts to use to generate temporary dev credentials, which fails.

There are other way to wire this up that work, so this is likely an issue of documentation drift.

**Comment by pikeas** [comment]
Also:

```
[profile root]
region=us-west-2
mfa_serial=arn:aws:iam::1234:mfa/aris
source_profile = root
credential_process = aws-vault exec --no-session --json --prompt=osascript root

[profile dev]
include_profile = root
role_arn = arn:aws:iam::1234:role/dev

$ aws-vault exec dev -- aws sts get-caller-identity
{
    "UserId": "...",
    "Account": "...",
    "Arn": "arn:aws:sts::1234:assumed-role/dev/1234"
}
$ AWS_PROFILE=dev aws sts get-caller-identity

Partial credentials found in assume-role, missing: source_profile or credential_source
```

`include_profile` is an aws-vault value, which the aws CLI doesn't parse. This is mentioned early in the docs but could be reiterated in the [Using credential_process](https://github.com/99designs/aws-vault/blob/master/USAGE.md#using-credential_process) section.

**Comment by hslavchev** [comment]
> av add root
> aws-vault: error: add: Your profile has a source_profile of root, adding credentials to root won't have any effect

I'm seeing the same behavior...

> I can remove `source_profile`, add credentials, and then restore it. If this is working as intended and the usage is recommended, please update the docs accordingly.

I've been using the same workaround because everything works great following the "parent" style config (as seen in the documentation) once credentials are added. The trouble is adding the credentials while having "parent" style config in the first place.

**Comment by vspinu** [comment]
Hey greedy bot, this one should not be closed. It's a real issue.

Each time our access token expires we have to comment `source_profile=` line, do `aws-add xyz` then uncomment. Not a very big deal, but would be great to have a cleaner solution.

**Comment by danwashusen** [comment]
+1 the example provided in the docs does not seem to be working...

**Comment by gshel** [comment]
+1 at the very least, can this workaround be included in the documentation?

**Comment by codyrobbins** [comment]
Following the documentation and just ran into this too—it’s still not working.

**Comment by wesquiveljc** [comment]
This is still broken :(
