### ISSUE TITLE
AWS Vault and WSL - crazy slow

### ISSUE THREAD

**Issue by murbanowicz** [99designs/aws-vault#681]
- [x] I am using the latest release of AWS Vault
- [x] I have provided the debug output using `aws-vault --debug` (redacted if necessary)
```
➜  System32 date
Thu Oct 29 16:03:32 CET 2020
➜  System32 aws-vault --debug
2020/10/29 16:05:47 aws-vault 6.2.0
```
I have just installed the AWS Vault in my WSL instance (Ubuntu 20.04).
For each command, it takes more than 2 minutes to get any output.
I have run these commands one after the previous one. As you can see it took 2m15s to get any output.
It is exactly the same even for `--version`.

Any idea why it is like that?

**Comment by Majsvaffla** [comment]
That sounds strange. Are you on WSL1 or WSL2? I’ve been using aws-vault with WSL2 for some time and have not experienced such problems at all. I haven’t used it with WSL1 at all.

**Comment by murbanowicz** [comment]
WSL2
I know it is strange...

**Comment by bateleurX** [comment]
@murbanowicz 
My environment also affected this issue. I tried strace of aws-vault and it suggested that aws-vault is waiting to start dbus-launch process, but it failed to start.
dbus is not necessary in my workload, so I did `apt remove dbus` and it worked.

**Comment by murbanowicz** [comment]
Wow! Great job! Works perfect now! No idea why `dbus` does not want to start, but it will be probably not important when they release WSLG
