### ISSUE TITLE
Can malcious apps read credentials stored in wincred backend?

### ISSUE THREAD

**Issue by vroad** [99designs/aws-vault#682]
Looks like wincred backend does not restrict which program can read the credentials, or encrypt credentials. Any programs running inside the same account could read credentials.

Ideally, I don't want to remember additional password to protect credentials, but is there a technique other than encryption to prevent other programs from reading credentials?

**Comment by sandstrom** [comment]
Sounds like that's outside the scope of AWS vault? Maybe this issue can be closed?

**Comment by mtibben** [comment]
Different backends do have different security profiles - this is not well explained in the USAGE docs.

99designs uses keychain on macOS which prompts every time the AWS creds are accessed. The other backends have been contributed by others, and may not have that same level of transparency.

You could try the pass or file backends, to improve this? And any docs you could contribute on this topic would be useful
