### ISSUE TITLE
aws-vault using pass doesn't find gpg key

### ISSUE THREAD

**Issue by prelegalwonder** [99designs/aws-vault#686]
Version: `v6.2.0`
Platform: WSL Ubuntu 18.04

Issue: When using the pass backend / cmd, aws-vault is unable to find the correct gpg key. The line in the debug output that is particularly suspect to me is `2020/11/04 12:07:14 Looking up keyring for 'root'` as this seems to indicate that its trying to find an ID in gpg that is my aws profile name instead of the ID specified when I did `pass init`. I don't understand how this could be aws-vault specific, but I know if I run pass manually it works just fine. 

If I run pass manually and authenticate gpg, then aws-vault works fine until my gpg agent session times out.

aws config:
```
[profile root]
region=us-east-1
output=json
credential_process = aws-vault --debug exec root --json --prompt=pass
```

Env Vars:
```
AWS_VAULT_BACKEND=pass
AWS_VAULT_PASS_CMD=pass
AWS_VAULT_PASS_PASSWORD_STORE_DIR=/home/myuser/.password-store
AWS_VAULT_PROMPT=pass
AWS_VAULT_PASS_PREFIX=aws-vault
AWS_PROFILE=root
```
Example:
```
$> aws s3 ls
Error when retrieving credentials from custom-process: 2020/11/04 12:07:14 aws-vault v6.2.0
2020/11/04 12:07:14 Loading config file /home/myuser/.aws/config
2020/11/04 12:07:14 Parsing config file /home/myuser/.aws/config
2020/11/04 12:07:14 [keyring] Considering backends: [pass]
2020/11/04 12:07:14 Profile 'default' missing in config file
2020/11/04 12:07:14 profile root: using stored credentials
2020/11/04 12:07:14 profile root: using GetSessionToken
gpg: decryption failed: No secret key
2020/11/04 12:07:14 Using STS endpoint https://sts.amazonaws.com
2020/11/04 12:07:14 Looking up keyring for 'root'
gpg: decryption failed: No secret key
aws-vault: error: exec: Failed to get credentials for root: exit status 2
```

When executing pass manually:
```
$> pass aws-vault/root

<.. screen refreshes and prompts for gpg pass ..>

                                                                                                          ┌────────────────────────────────────────────────────────────────────┐
                                                                                                          │ Please enter the passphrase to unlock the OpenPGP secret key:      │
                                                                                                          │ "Andrew Replogle (Pass Vault ID) <andrew.replogle@mydomain.tld>"  │
                                                                                                          │ 3072-bit RSA key, ID C6B0665E7ED16D98,                             │
                                                                                                          │ created 2020-11-04 (main key ID F9B90A6EE9EED2DC).                 │
                                                                                                          │                                                                    │
                                                                                                          │                                                                    │
                                                                                                          │ Passphrase: ______________________________________________________ │
                                                                                                          │                                                                    │
                                                                                                          │          <OK>                                      <Cancel>        │
                                                                                                          └────────────────────────────────────────────────────────────────────┘

<.. I enter the password and hit ok ..>
{"Key":"root","Data":"eyJBY2XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXI6IiJ9","Label":"aws-vault (root)","Description":"","KeychainNotTrustApplication":true,"KeychainNotSynchronizable":false}
```

**Comment by prelegalwonder** [comment]
Found a post that suggested the following:

`export GPG_TTY=$(tty)`

I don't know why but this resolved my issue. Will submit a PR for USAGE.md to add a note to PASS related usage.

**Comment by boristyukin** [comment]
> Found a post that suggested the following:
> 
> `export GPG_TTY=$(tty)`
> 
> I don't know why but this resolved my issue. Will submit a PR for USAGE.md to add a note to PASS related usage.

had the same issue exactly

**Comment by gclair** [comment]
> export GPG_TTY=$(tty)

With ZSH , I found a post that said to use `export GPG_TTY=$TTY` instead. So far its working out well for me.

**Comment by prelegalwonder** [comment]
FYI - I tried to submit a PR for updates to the documentation for a workaround but the maintainers aren't interested and I guess would rather just have people struggle with the issue on their own. 

https://github.com/99designs/aws-vault/pull/687

**Comment by CevG33ko** [comment]
> 
> 
> Found a post that suggested the following:
> 
> `export GPG_TTY=$(tty)`
> 
> I don't know why but this resolved my issue. Will submit a PR for USAGE.md to add a note to PASS related usage.

Had the same Issue, its still there. Thank for the solution post.

**Comment by doolio** [comment]
@prelegalwonder 
> The line in the debug output that is particularly suspect to me is 2020/11/04 12:07:14 Looking up keyring for 'root' 

 Is this not because you specified 'root' as the profile name in your config file:

![image](https://github.com/99designs/aws-vault/assets/13859009/5ffc7d61-95c6-4c12-a590-2892fcc8e533)

> Found a post that suggested the following:
> export GPG_TTY=$(tty)

This is a requirement of `gpg` (which `pass` uses) as it expects you to be connected to a real tty device (see [here](https://www.gnupg.org/documentation/manuals/gnupg/Common-Problems.html)). On some systems this is only the case if your session starts a login shell. Setting `GPG_TTY` and exporting it ensures `gpg` works when your session does not start a login shell and that it is also set for any interactive non-login shell you might launch say when you open a terminal window.

@gclair 
> With ZSH , I found a post that said to use `export GPG_TTY=$TTY` instead. So far its working out well for me.

`$(tty)` is a command that requires that stdin is attached to a terminal and so may not work if stdin has been redirected. If you had used it and moved it to the very top of your `~/.zshrc` it likely would have worked. `TTY` is a special parameter set by zsh very early during initialization. It gives you access to the terminal even when stdin might be redirected and so should always work. See [here](https://unix.stackexchange.com/a/608921).

cc: @mtibben
