### ISSUE TITLE
fatal: no submodule mapping found

### ISSUE THREAD

**Issue by mpictor** [99designs/aws-vault#69]
I'm trying to use your keyring module; I'm importing `"github.com/99designs/aws-vault/keyring"`. However, I get an error when I attempt to install my code's dependencies (which include aws-vault).

$ `go get .`
```
# cd /home/mark/go/src/github.com/99designs/aws-vault; git submodule update --init --recursive
fatal: no submodule mapping found in .gitmodules for path 'vendor/github.com/alecthomas/units'
package github.com/99designs/aws-vault/keyring: exit status 128
```

I noticed that the most recent commit, [09f0ba74](https://github.com/99designs/aws-vault/commit/09f0ba74945d2f5bb0e825c350b7585ae27a02c7), was "Update Vendors". Thinking this might be the issue, I tried checking out the previous commit and re-running the submodule update command. This resulted in the same error.

**Comment by lox** [comment]
Let me know if this resolves the issue for you, also how you go with the keyring library. I was in the process of moving over the good parts of it to https://github.com/keybase/go-keychain/pull/4#issuecomment-184969521

If you can, I'd suggest using https://github.com/keybase/go-keychain instead. See  #58.

**Comment by mpictor** [comment]
Thanks, that fixes the git error.

I'm using keyring because it supports kwallet; it looks like go-keychain doesn't yet support any linux mechanism.

Assuming you add kwallet support to go-keychain, the following may be helpful to you:

* support kde5 (I'm sure this will break kde4, so a complete solution would require additional logic)
```diff
--- a/keyring/kwallet.go
+++ b/keyring/kwallet.go
 const (
-       DBUS_SERVICE_NAME = "org.kde.kwalletd"
-       DBUS_PATH = "/modules/kwalletd"
+       DBUS_SERVICE_NAME = "org.kde.kwalletd5"
+       DBUS_PATH         = "/modules/kwalletd5"
        APPID = "aws-vault"
        FOLDER = "aws-vault"
 )
```

* allow overriding the appid/folder
```diff
--- a/keyring/kwallet.go
+++ b/keyring/kwallet.go
 const (
        DBUS_SERVICE_NAME = "org.kde.kwalletd5"
        DBUS_PATH         = "/modules/kwalletd5"
-       APPID = "aws-vault"
-       FOLDER = "aws-vault"
 )
+
+var APPID = "aws-vault"
+var FOLDER = "aws-vault"
```

**Comment by lox** [comment]
Thanks @mpictor, `go-keychain` is purely OSX Keychain bindings, it's not meant to be an abstraction layer.

**Comment by lox** [comment]
I've added your feedback to https://github.com/99designs/aws-vault/issues/23 too.
