### ISSUE TITLE
SSO login does not work under Windnows

### ISSUE THREAD

**Issue by obones** [99designs/aws-vault#691]
Hello,

I'm using AWS Vault 6.2.0 with AWS-CLI 2.0.62 under Windows 10 1909 and am having issues on all but one machine with the following configuration:

```
[profile MyProfile]
sso_start_url=https://MyCompany.awsapps.com/start
sso_region=eu-west-1
sso_account_id=00000000000000
sso_role_name=MyRole
region=eu-west-1
output=json
```

On the only machine where it works, I get this from `aws-vault login MyProfile --debug`

```
2020/11/09 11:40:34 aws-vault v6.2.0
2020/11/09 11:40:34 [keyring] Considering backends: [wincred]
2020/11/09 11:40:34 Loading config file C:\Users\Me\.aws\config
2020/11/09 11:40:34 Parsing config file C:\Users\Me\.aws\config
2020/11/09 11:40:35 Created new OIDC client (expires at: 2021-02-07 11:40:37 +0100 CET)
2020/11/09 11:40:35 Created OIDC device code for https://MyCompany.awsapps.com/start (expires in: 600s)
2020/11/09 11:40:35 Opening SSO authorization page in browser
Opening the SSO authorization page in your default browser (use Ctrl-C to abort)
https://device.sso.eu-west-1.amazonaws.com/?user_code=SOMECODE
2020/11/09 11:40:46 Created new OIDC access token for https://MyCompany.awsapps.com/start (expires in: 28800s)
2020/11/09 11:40:47 Got credentials ****************XMWR for SSO role MyRole (account: 00000000000), expires in 11h59m59.9766451s
```

But on all other machines with the same configuration, all I get is this:

```
2020/11/09 11:43:51 aws-vault v6.2.0
2020/11/09 11:43:51 [keyring] Considering backends: [wincred]
2020/11/09 11:43:51 Loading config file C:\Users\Me\.aws\config
2020/11/09 11:43:51 Parsing config file C:\Users\Me\.aws\config
2020/11/09 11:43:51 Profile 'default' missing in config file
aws-vault: error: login: Failed to get credentials for MyProfile: Élément introuvable.
```

The error message is localized by Windows and says "Item not found"
Experimenting a bit, I tried issuing `aws-vault add MyProfile` and this leads to a different log for `aws-vault login MyProfile`:

```
2020/11/09 11:16:49 aws-vault v6.2.0
2020/11/09 11:16:49 [keyring] Considering backends: [wincred]
2020/11/09 11:16:49 Loading config file C:\Users\Me\.aws\config
2020/11/09 11:16:49 Parsing config file C:\Users\Me\.aws\config
2020/11/09 11:16:49 Profile 'default' missing in config file
2020/11/09 11:16:49 profile MyProfile: using stored credentials
2020/11/09 11:16:49 profile MyProfile: using GetSessionToken
2020/11/09 11:16:49 Using STS endpoint https://sts.amazonaws.com
2020/11/09 11:16:49 Looking up keyring for 'MyProfile'
aws-vault: error: login: Failed to get credentials for MyProfile: InvalidClientTokenId: The security token included in the request is invalid.
        status code: 403, request id: a06ab900-2e96-4189-9a08-124f211041f6
```

I believe this expected because it looks up the credentials in `wincred` but they are meant for SSO, not regular login.

All in all, it's as if `aws-vault` totally ignores the `sso` items in the config file but I can't figure out what's wrong on 4 machines and right on just one of them.
What have I missed? What can I try?

**Comment by alexreynoso** [comment]
Clearing all the files under .password-store did the trick

**Comment by obones** [comment]
> 
> 
> Clearing all the files under .password-store did the trick

Hello,

I went looking for that folder in the affected computers, but I could not find it in those locations:

c:\Users\AccountName\
c:\Users\AccountName\.aws
c:\Users\AccountName\AppData\Local
c:\Users\AccountName\AppData\LocalLow
c:\Users\AccountName\AppData\Roaming
C:\ProgramData

Would you have a suggestion for another location to look for?

**Comment by cofrey** [comment]
Hi @obones,

were you able to resolve it?

I have got the same issue with aws-vault 6.2.0 and AWS CLI 2.1.29

**Comment by obones** [comment]
Hello,

Alas, no, it was never solved, we have stopped using aws-vault since then
