### ISSUE TITLE
InvalidClientTokenId: The security token included in the request is invalid.

### ISSUE THREAD

**Issue by fields** [99designs/aws-vault#694]
I am able to make calls using the awscli directly, using both an iam credential profile and a role profile. I can assume the role with no problems. If I try to make this same call using aws-vault, I get an InvalidClientTokenId error.

Am I missing some configuration here?

Output:
```
$ aws --profile=credential_account sts get-caller-identity
{
    "Account": "XXXXXXXXXXXX",
    "UserId": "YYYYYYYYYYYY",
    "Arn": "arn:aws:iam::XXXXXXXXXXXX:user/credential_account"
}

$ aws --profile=role_provisioner sts get-caller-identity
{
    "Account": "WWWWWWWWWWWWW",
    "UserId": "ZZZZZZZZZZZZ:botocore-session-ZZZZZZZZ",
    "Arn": "arn:aws:sts::WWWWWWWWWWWWW:assumed-role/user_access_role/botocore-session-ZZZZZZZZ"
}
$ aws-vault --debug --backend=file exec role_provisioner -- aws sts get-caller-identity
2020/11/24 19:26:03 aws-vault v6.2.0
2020/11/24 19:26:03 Loading config file /home/user/.aws/config
2020/11/24 19:26:03 Parsing config file /home/user/.aws/config
2020/11/24 19:26:03 [keyring] Considering backends: [file]
2020/11/24 19:26:03 Profile 'default' missing in config file
2020/11/24 19:26:03 Profile 'default' missing in config file
2020/11/24 19:26:03 [keyring] Expanded file dir to /home/user/.awsvault/keys/
2020/11/24 19:26:03 [keyring] Expanded file dir to /home/user/.awsvault/keys/
2020/11/24 19:26:03 profile credential_account: using stored credentials
2020/11/24 19:26:03 profile credential_account: using GetSessionToken (with MFA)
2020/11/24 19:26:03 profile role_provisioner: using AssumeRole (chained MFA)
2020/11/24 19:26:03 Using STS endpoint https://sts.amazonaws.com
2020/11/24 19:26:03 [keyring] Expanded file dir to /home/user/.awsvault/keys/
2020/11/24 19:26:03 [keyring] Expanded file dir to /home/user/.awsvault/keys/
2020/11/24 19:26:03 [keyring] Expanded file dir to /home/user/.awsvault/keys/
Enter token for arn:aws:iam::XXXXXXXXXXXX:mfa/credential_account: ######
2020/11/24 19:26:08 Using STS endpoint https://sts.amazonaws.com
2020/11/24 19:26:08 Looking up keyring for 'credential_account'
2020/11/24 19:26:08 [keyring] Expanded file dir to /home/user/.awsvault/keys/
2020/11/24 19:26:08 [keyring] Expanded file dir to /home/user/.awsvault/keys/
Enter passphrase to unlock /home/user/.awsvault/keys/:
aws-vault: error: exec: Failed to get credentials for role_provisioner: InvalidClientTokenId: The security token included in the request is invalid.
	status code: 403, request id: ################
```

.aws/config:
```
[profile role_provisioner]
region=us-east-1
role_arn=arn:aws:iam::YYYYYYYYYYYY:role/user_access_role
source_profile=credential_account
mfa_serial=arn:aws:iam::XXXXXXXXX:mfa/credential_account

[profile credential_account]
region=us-east-1
mfa_serial=arn:aws:iam::XXXXXXXXX:mfa/credential_account
```

**Comment by mtibben** [comment]
Does it work with `--no-session`? Or is this an issue with your MFA token? The example using `aws --profile=role_provisioner sts get-caller-identity` doesn't appear to use MFA

**Comment by dmitry-mightydevops** [comment]
I got into the same issue.

long-live AWS credentials worked, but short-term credentials received by running 
```bash
aws-vault add client/aws/master-admin 
aws-vault exec client/aws/master-admin --debug -- zsh --login
terraform apply
```

Some of the resources were created, but lambdas, eks clusters, vpc flow logs failed to be created.

I then just exported AWS creds into shell manually and everything worked.

**Comment by ezeql** [comment]
+1 creating iam roles

**Comment by sindhu-shree-1** [comment]
Same. Just had to run `aws-vault add <profile-name>`

**Comment by gabrielhesposito** [comment]
same `--no-session` w/ iam role creation wondering if this is more a documentation/configuration issue since it's cropped up twice for me in two different orgs

**Comment by tekumara** [comment]
A restart and adding a new access key solved this for me.

**Comment by george-richardson** [comment]
> The temporary security credentials created by GetSessionToken can be used to make API calls to any AWS service with the following exceptions:
> * You cannot call any IAM API operations unless MFA authentication information is included in the request.
> * You cannot call any AWS STS API except AssumeRole or GetCallerIdentity.

[GetSessionToken](https://docs.aws.amazon.com/STS/latest/APIReference/API_GetSessionToken.html)

If you are getting the `InvalidClientTokenId` error when using IAM you either need to use `aws-vault exec <profile> --no-session` or configure MFA on your IAM user and profile.

**Comment by DavidPesticcio** [comment]
Just to clarify the entry above, from the AWS docs link linked above...

> **Permissions**
>
> The temporary security credentials created by GetSessionToken can be used to make API calls to any AWS service with the following exceptions:
> 
> - You cannot call any IAM API operations unless MFA authentication information is included in the request.
> 
> - You cannot call any AWS STS API except AssumeRole or GetCallerIdentity.

**Comment by nidgetgod** [comment]
Try delte password in keyring, in Ubuntu it should see in seahorse(awsvault)

After delete it and re-create using `aws-vault add <profile>`
