### ISSUE TITLE
Add support of Apple Silicon chips.

### ISSUE THREAD

**Issue by mkryva** [99designs/aws-vault#695]
Hi. It would be fine, if You add darwin arm64 packages to releases. Thanks!

**Comment by mtibben** [comment]
This can be done when Go 1.16 is released

**Comment by roma4u** [comment]
I also subscribe to the request.

**Comment by roma4u** [comment]
> This can be done when Go 1.16 is released

https://golang.org/dl/#go1.16beta1

**Comment by mtibben** [comment]
Fixed in a previous release
