### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by orjanno** [99designs/aws-vault#696]
**Issue:**
C:\Users\Me>aws-vault exec myprofile -- aws iam list-users --debug
Enter token for arn:aws:iam::xxxxxxxxxxxx:mfa/my-user: 275837
aws-vault: error: exec: Failed to get credentials for myprofile : RequestError: send request failed
caused by: Post "https://sts.amazonaws.com/": x509: certificate signed by unknown authority

What is causing this?

- [x] I am using the latest release of AWS Vault
- [ ] I have provided my `.aws/config` (redacted if necessary)
- [x] I have provided the debug output using `aws-vault --debug` (redacted if necessary)

aws-vault --version: v6.2.0
Windows 10

**Comment by mtibben** [comment]
> What is causing this?

The HTTPS POST request to sts.amazonaws.com is failing because the cert isn't recognised. Either there is something up with root certs on your system or the request is being intercepted by software or firewall
