### ISSUE TITLE
aws-vault: command not found

### ISSUE THREAD

**Issue by bnocular** [99designs/aws-vault#697]
Hi,

I was following aws-vault installation instructions using brew install aws-vault on Ubuntu 18.04. When it finished and all seems fine, _aws-vault: command not found_ error occurred when trying to run it. It is weird, seems like the aws-vault is not been installed. Any idea what I missed?

**Comment by DFenwick-CAT** [comment]
I am having a similar issue, running aws-vault.exe however seems to do something?

**Comment by mtibben** [comment]
Perhaps check the brew linux docs?

**Comment by monikasulik** [comment]
I'm having the same issue on debian. I would have thought this is an issue with how aws-vault is packaged on homebrew, not an issue with homebrew itself? Setting `alias aws-vault='/home/linuxbrew/.linuxbrew/bin/aws-vault'` seems to fix it, but I would have thought the installation script should do this or at least print out something to prompt the user to do something similar?
