### ISSUE TITLE
Enter Secret Access Key not possible

### ISSUE THREAD

**Issue by cnadolny2s** [99designs/aws-vault#699]
As stupid as it sounds, but I can not type my AWS Secret Access Key when using `aws-vault add home` in my Windows console. I already tried different terminals on Windows like Git Bash, bash (linux sub system), Windows PowerShell and I even installed aws-vault via chocalatery and tried that but with no success.

The problem must be with the aws-vault executable itself, as I already googled for whether that is a Windows console problem in general and nobody seems to have this problem but me.

Typing `aws-vault add home` prompts for my credentials. I can enter my access key Id but when it comes to enter my secret access key, typing does not show any characters. Even pasting did not help.

`aws-vault --debug login home` says `Profile 'default' missing in config file`. Does it have anything to do with that?

- [x ] I am using the latest release of AWS Vault (v6.2.0)

**Comment by cnadolny2s** [comment]
I somehow solved this issue for me. Although typing the key is still not visible under Windows, the typed value got accepted and I was able to login successfully with that. I assume I had some invisible characters in my clipboard when copy and pasting my access key. Anyways, it works now.

**Comment by gottscraham** [comment]
I am having this same issue and I have tried typing it and copying it in to my terminal
