### ISSUE TITLE
bash completion of exec command

### ISSUE THREAD

**Issue by jedi4ever** [99designs/aws-vault#70]
we use `make` a lot at work. It has nice bashcompletion for it's tasks.

Execing it with `aws-vault exec <profile> make` sure works great! thanks for the plugin!
But it breaks the completion.

I researched and came across `_command_offset`in bash_completion.
It is used by `sudo` to achieve something similar.

Maybe it can inspire you :)

**Comment by lox** [comment]
Yup, I've wanted to do this for a while. Unfortunately I'm a zsh user, but I think it can be done such that it's portable.

**Comment by lox** [comment]
Apparently this is somewhat helped by the cli library we use: https://github.com/alecthomas/kingpin#bashzsh-shell-completion

**Comment by jedi4ever** [comment]
@lox this build in completion will only help for the aws-vault options
afaik this will not pass commandcompletion to the execed command
for that the command offset is needed , but I guess it's a good start to hack on

**Comment by jedi4ever** [comment]
I tried the build in `eval "$(aws-vault --completion-script-bash)"`
but it says --completion-script-bash option is not found.

I've made some progress on the completion of the exec command.

`aws-vault exec profile1 -- make <TAB>` now expands correctly the make tasks

I'll continue to enhance it with the aws-vault options.

```
# bash completion for aws-vault                             -*- shell-script -*-

_aws_vault()
{
    local cur prev words cword

    local i

    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    for (( i=1; i <= COMP_CWORD; i++ )); do
        if [[ ${COMP_WORDS[i]} == -- ]]; then
            local root_command=${COMP_WORDS[i]}
            _command_offset $i+1
            return
        fi
    done

} && complete -F _aws_vault aws-vault
```

**Comment by lox** [comment]
Nice! I've been working on getting the latest cli stuff into aws-vault so that we can at least use kingpin to output the above script when `--completion-script-bash` is passed.
