### ISSUE TITLE
Code-sign Windows binaries

### ISSUE THREAD

**Issue by sveinungre** [99designs/aws-vault#701]
Can you please start signing the files using a digital signature so its not blocked by Edge SmartScreen, and also make it possible to use digital signature when doing application control in an enterprise environment. Application control meaning AppLocker, WDAP, any EPM solution to control applications that users can execute etc. I cannot stress how important this is.

It's year 2020 (soon 2021) , signing executables is a proven standard. Thanks.

**Comment by mtibben** [comment]
Hey @sveinungre, the macOS builds are code-signed. I'm assuming you're asking for Windows code signing?

We don't use Windows desktops at 99designs, but if you want this feature and is willing to [fund the cert](https://www.digicert.com/code-signing/) that would not be difficult to implement.

**Comment by sveinungre** [comment]
Yes, the Windows version. So that would require signing aws-vault-windows-386.exe.

Personally I do not use it myself, but my customer does. Let me convince them to fund the cert and get back to you shortly! Then maybe next time another company can fund the cert, there must be many companies out there using aws-vault.

**Comment by sveinungre** [comment]
Hello
The customer is willing to sponsor the certificate. Who is the contact person to arrange the practical matters, requirements and payment?

**Comment by mtibben** [comment]
Hey @sveinungre you can DM me at https://twitter.com/MichaelTibben
