### ISSUE TITLE
Won't assume role

### ISSUE THREAD

**Issue by djmills64** [99designs/aws-vault#706]
I am running:
`aws-vault login --path=iam --debug new-acc-admin`
on Ubuntu 20.0.4 using seahorse as the key manager.  I get the response
`2021/01/04 13:33:47 aws-vault v6.2.0
2021/01/04 13:33:47 [keyring] Considering backends: [secret-service]
2021/01/04 13:33:47 Loading config file /home/djm/.aws/config
2021/01/04 13:33:47 Parsing config file /home/djm/.aws/config
2021/01/04 13:33:47 Using "regional" from AWS_STS_REGIONAL_ENDPOINTS
2021/01/04 13:33:47 Using duration_seconds "1h0m0s" from AWS_ASSUME_ROLE_TTL
2021/01/04 13:33:47 Using "regional" from AWS_STS_REGIONAL_ENDPOINTS
2021/01/04 13:33:47 Using duration_seconds "1h0m0s" from AWS_ASSUME_ROLE_TTL
2021/01/04 13:33:47 profile temp-user: using stored credentials
2021/01/04 13:33:47 profile temp-user: skipping GetSessionToken because profile 'new-acc-admin' has no MFA serial defined
2021/01/04 13:33:47 profile new-acc-admin: using AssumeRole 
2021/01/04 13:33:47 Using STS endpoint https://sts.ap-southeast-2.amazonaws.com
2021/01/04 13:33:47 Looking up keyring for 'temp-user'
aws-vault: error: login: Failed to get credentials for new-acc-admin: AccessDenied: User: arn:aws:iam::<master-account>:user/AwsAccountProvisioner2 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::<client-account>:role/OrganizationAccountAccessRole
	status code: 403, request id: <id>
`
Is the issue that seahorse is failing to provide the access keys or that they are provided but AWS is returning the error?
It's probably some issue with our configuration, but I'm failing to diagnose what.  Any help would be greatly appreciated.

**Comment by djmills64** [comment]
I got a colleague to try the same (but using v5.4.4) - the result wasa the same.  Which means that the issue must be at the AWS end.

**Comment by djmills64** [comment]
The AWS documentation says to add a trust relationship on the target account's role with
`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::<acc id>:root"
            },
            "Action": "sts:AssumeRole"
        }
    ]
}`
I have found that changing "root" to the name of the master account user attempting to assume the role then it works.  "root' used to work so why has it stopped?

**Comment by djmills64** [comment]
I have discovered that the issue relates to region choice.  The assume role works when the profile is set to specific regions, but not for other regions.  Which regions work or don't work seems to vary from one account to another.  What region specific config allows/denies this?
The region that fails for most users (but not all) is af-south-1.  I know this is a region that is not enabled by default.  But I have enabled in both our master account and the client account, and I have changed the sts token version to 2.  As I said, one user is able to assume a role in the client account for the af-south-1 region.  Whereas other users can only assume the same role in the client account, but for regions enabled by default.  
What am I missing?

**Comment by mtibben** [comment]
I believe IAM and STS needs to be enabled in certain regions - see
 - https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html
 - https://github.com/99designs/aws-vault/issues/543
 - https://github.com/99designs/aws-vault/pull/662

**Comment by mtibben** [comment]
> the issue occurs when the source profile's account does not have the region enabled even if the profile you're authenticating to does have the region enabled

(from https://github.com/99designs/aws-vault/issues/543#issuecomment-695839865)

**Comment by djmills64** [comment]
I discovered why.  The other users were based in a 3rd account (not the master account).  I enabled the region and the STS version there and it worked.  Thanks for the advice.
