### ISSUE TITLE
Using $XDG_CONFIG_HOME For File Backend Keys

### ISSUE THREAD

**Issue by viliampucik** [99designs/aws-vault#707]
In case of using encrypted file backend (`AWS_VAULT_BACKEND=file`), aws-vault stores keys in `$HOME/.awsvault`.

To prevent filling user home directory with hidden files, can the application follow [XDG Base Directory specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) and store the keys in `$XDG_CONFIG_HOME/awsvault` (`$HOME/.config/awsvault`)?

Or is there a way to adjust the default encrypted file backend location?

**Comment by ardrigh** [comment]
I already have my AWS config stored under the `$XDG_CONFIG_HOME` directory on Fedora install - `~/.config/aws`

I would like to convert to using this tool, but I am happy to wait until XDG support is added.
