### ISSUE TITLE
Validation for URLs

### ISSUE THREAD

**Issue by hlascelles** [99designs/aws-vault#709]
We were recently seeing quite esoteric failures like this:

```
aws-vault: error: exec: Failed to get credentials for foo: InvalidRequestException:
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "4a328325-4fd6-4710-a3ca-12345671234567"
  },
  Error_: "invalid_request",
  Error_description: "Invalid request"
}
```

It turned out our dev wiki markdown editor had mangled the example AWS config SSO url like this:

```
sso_start_url=<https://d-1234567890.awsapps.com/start>
```

The `<>` are not right.

Would it be worth having validation for the URL? Actually, is this a question for aws-vault or the aws-cli?

**Comment by hlascelles** [comment]
Still a possible improvement.

**Comment by hlascelles** [comment]
Still nice to have.

**Comment by hlascelles** [comment]
Still nice please.

**Comment by mtibben** [comment]
Hey @hlascelles  if you wish to implement this, feel free to open a PR. As I don't intend to implement at this time I will close for now.
