### ISSUE TITLE
Question - is it possible to show AWS_ACCESS_KEY_ID for a profile

### ISSUE THREAD

**Issue by eskp** [99designs/aws-vault#715]
I'd like to rotate a key but don't know which profile it belongs to. Doing the following shows temporary keys:

`aws-vault exec test -- env | grep KEY_ID`

and

`aws-vault exec test -- aws sts get-caller-identity`

Is it possible to show the stored key ID for a profile?

**Comment by vroad** [comment]
You can find which profile has master "credentials" by running `aws-vault list`.

```
Profile                  Credentials              Sessions
=======                  ===========              ========
common                   -                        -
home                     home                     -
foobar                   -                        sts.AssumeRole:21m38s
```

In this case `home` is the name of profile you set credentials to.
You can then `aws-vault rotate home` to rotate the key.

Or, you can do something like this to get access key ID, if you already know the profile name. `--no-session` (or `-n`) is required to get long-lived credentials.

```
aws-vault exec home --no-session -- env | grep ^AWS_ACCESS_KEY_ID
```

**Comment by eskp** [comment]
Perfect, thanks @vroad, `--no-session` did it!
