### ISSUE TITLE
have to manually run pass command in new terminal session

### ISSUE THREAD

**Issue by boristyukin** [99designs/aws-vault#719]
aws-vault is awesome but I have an issue with `pass` backend. It only works for me if I run `pass myprofile` command manually first and then type `pass store` password. I have to do it in every new terminal session. Is there a way around this?

```
$ aws-vault exec myprod --duration=12h --debug
2021/02/05 09:31:35 aws-vault v6.2.0
2021/02/05 09:31:35 Loading config file /home/xxx/.aws/config
2021/02/05 09:31:35 Parsing config file /home/xxx/.aws/config
2021/02/05 09:31:35 [keyring] Considering backends: [pass]
2021/02/05 09:31:35 Profile 'default' missing in config file
2021/02/05 09:31:35 profile myprod: using stored credentials
2021/02/05 09:31:35 profile myprod: using GetSessionToken (with MFA)
Enter token for arn:aws:iam::xxxx: 1111111
2021/02/05 09:31:56 Using STS endpoint https://sts.amazonaws.com
2021/02/05 09:31:56 Looking up keyring for 'myprod'
gpg: decryption failed: No secret key
aws-vault: error: exec: Failed to get credentials for myprod: exit status 2
```

but if I run `pass myprod` and then type pass password manually, the same command as in example above works fine.

**Comment by aswadsun** [comment]
Hi, I also got the same issue:
```
% aws-vault exec test -n --debug
2021/10/06 19:32:58 aws-vault 6.3.1-Homebrew
2021/10/06 19:32:58 Loading config file /Users/xxx/.aws/config
2021/10/06 19:32:58 Parsing config file /Users/xxx/.aws/config
2021/10/06 19:32:58 [keyring] Considering backends: [pass]
2021/10/06 19:32:58 Using region "xxxx" from AWS_DEFAULT_REGION
2021/10/06 19:32:58 profile test: using stored credentials
2021/10/06 19:32:58 profile test: skipping GetSessionToken because disabled
2021/10/06 19:32:58 Looking up keyring for 'test'
gpg: public key decryption failed: No such file or directory
gpg: decryption failed: No such file or directory
aws-vault: error: exec: Failed to get credentials for test: exit status 2
```
The same with __boristyukin__, I have to run `pass test` and enter the gpg key password before it could work on every new terminal. Why `aws-vault` does not prompt for gpg password as it does when adding new profile? Does some body have any work around for this? Thank you.

**Comment by aswadsun** [comment]
Hi @boristyukin, 

I accidentally solved this problem when solving `gpg` issue. So the problem is on the `gpg` side rather than `aws-vault` or `pass`. I just add following line to `.zshrc` ( or `.bashrc` ), so in new terminal I just need to directly run `aws-vault` and it will ask for `gpg` password the first time. No need to run `pass xx` first. The password will be cached by `gpg-agent` until it get cleared.

```
export GPG_TTY=$(tty)
```

I hope this help your issue.
