### ISSUE TITLE
aws-vault: error: login: Failed to get credentials for REDACTED: : Session token not found or invalid         status code: 401, request id: 

### ISSUE THREAD

**Issue by yuklia** [99designs/aws-vault#722]
OS: MacOS Big Sur, Version 11.1 
- [+] I am using the latest release of AWS Vault
v6.2.0
- [+] I have provided my `.aws/config` (redacted if necessary)
```
[profile REDACTED]
sso_start_url = https://REDACTED
sso_region = eu-west-1
sso_account_id = REDACTED
sso_role_name = AWSAdministratorAccess
region = eu-central-1
output = json
[profile REDACTED]
sso_start_url = https://REDACTED
sso_region = eu-west-1
sso_account_id = REDACTED
sso_role_name = AdministratorAccess
region = eu-central-1
output = json
```
- [+] I have provided the debug output using `aws-vault --debug` (redacted if necessary)

```
$ aws-vault --debug login REDACTED
2021/02/11 17:18:55 aws-vault v6.2.0
2021/02/11 17:18:55 [keyring] Considering backends: [keychain]
2021/02/11 17:18:55 Loading config file /Users/yulia/.aws/config
2021/02/11 17:18:55 Parsing config file /Users/yulia/.aws/config
2021/02/11 17:18:55 Profile 'default' missing in config file
2021/02/11 17:18:55 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2021/02/11 17:18:55 [keyring] Found 2 results
2021/02/11 17:18:55 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2021/02/11 17:18:55 [keyring] Found 2 results
2021/02/11 17:18:55 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2021/02/11 17:18:55 [keyring] Found 2 results
2021/02/11 17:18:55 [keyring] Querying keychain for service="aws-vault", account="sso.GetRoleCredentials,R2xvYnVzLVN0YWdpbmc,aHR0cHM6Ly9kLTkzNjcwM2Q2NjIuYXdzYXBwcy5jb20vc3RhcnQv,-62135596800", keychain="aws-vault.keychain"
2021/02/11 17:18:55 [keyring] No results found
2021/02/11 17:18:55 [keyring] Querying keychain for service="aws-vault", account="oidc:https://REDACTED", keychain="aws-vault.keychain"
2021/02/11 17:18:55 [keyring] Found item "aws-vault oidc token for https://REDACTED/ (expires 2021-02-11T23:21:21+02:00)"
aws-vault: error: login: Failed to get credentials for REDACTED: : Session token not found or invalid
        status code: 401, request id: 
```

**Comment by mcooper-apptio** [comment]
I had the same issue today. Running 'aws-vault clear' fixed the issue for me.

**Comment by c-ameron** [comment]
I think this is an issue where the aws-vault doesn't automatically clear/re-login after the token expiration in the keychain

**Comment by skyzyx** [comment]
Thanks for the pointers. Using this post, I logged into _Keychain Access.app_ (macOS), searched for `aws-vault`, and found the entry with "oidc" in the name.

Deleted it, re-ran, re-authed with AWS SSO, and all is well.

**Comment by mbevc1** [comment]
Same here for couple of days using AWS SSO; `aws-vault clear` removed invalid sessions and works now.

**Comment by edouardlp** [comment]
I had the same happen to me after a few weeks of using AWS SSO with aws-vault without any issues.

**Comment by gwynnarth** [comment]
Recently `aws-valut` started to misbehave for me as described in this ticket. It was working for months without any problems but something must have changed that now when the AWS SSO login expires, I see this:
```
Error when retrieving credentials from custom-process: aws-vault: error: exec: Failed to get credentials for REDACTED: : Session token not found or invalid
	status code: 401, request id:
```

Of course `aws-vault clear` works, but in the past it was not necessary - if the SSO credentials have expired, then the login window popped up automatically. Now I need to explicitly remove them beforehand, which is annoying.

**Comment by himanshu-agarwl** [comment]
Our team also has started to see this a lot now a days. Any help would be appreciated. 
`aws-vault clear` clears the invalid token but it doesn't seem ideal.

**Comment by momchilvangelov** [comment]
We are also having the same problem now! The whole team!

**Comment by majormoses** [comment]
We have in some cases needed to delete the keychain/ring altogether after attempting lighter touches.

**Comment by alienth** [comment]
Also getting this in Linux, starting very recently. So, I don't think this is limited to OSX or its keyring.

**Comment by filipvh-sentia** [comment]
Had a similar issue today. Response was also

```
Session token not found or invalid
        status code: 401, request id: 
```

`aws-vault clear` also fixed it for me. But this hasn't happened before today ( monday 7th of feb ).
Been using SSO for ~2-3 weeks.

**Comment by endzyme** [comment]
I was trying to track this down the other day and noticed that the create token response from AWS was giving us a 7 day expiration for the access token. I was able to modify the expiration date, which produced the normal behavior of reinitializing the SSO flow with the browser. Has anyone else noticed a change in their access token responses from AWS which might be causing this issue?

**Comment by mchineboy** [comment]
Clearing this with aws-vault clear is not working for me this morning. There must've been a change on the AWS side?

**Comment by henkka** [comment]
We're facing the same issue for two days in a row, `aws-vault clear` solves it for the day.

Thanks @endzyme for digging into the issue more thoroughly. I can see from [here](https://medium.com/@lex.berger/anatomy-of-aws-sso-device-authorization-grant-2839008c367a) that at least 2 years ago AWS was returning OIDC access tokens with TTL of 8 hours. I can confirm that as of now, AWS returns OIDC access tokens that are valid for 7 days. I'm however unsure whether this is the root cause of the issue we're facing.

https://docs.aws.amazon.com/singlesignon/latest/OIDCAPIReference/API_CreateToken.html

**Comment by endzyme** [comment]
Just to cross post from https://github.com/99designs/aws-vault/issues/854. 

Our AWS support has confirmed they see an issue internally and our TAM is working with the SSO team at AWS to identify the issue and hopefully resolve it.

**Comment by henkka** [comment]
AWS support just responded to let us know that the change has been reverted, and I can confirm that `CreateToken` is again returning `expiresIn: 28800` 

> From the feedback I received from the internal team, there was an an update that was pushed but this has now been reverted.

**Comment by Xe** [comment]
I ran into this issue today as well

**Comment by brian-skafte** [comment]
Not sure if it is related or another issue, but I had the same error message when trying to use a newly added credential set in aws-vault. I tried with aws-vault clear, but that didn't help. Then I remembered the secret contained a couple of slashes "/", and I thought maybe those were the problems, why I removed the aws-vault entry and added a new one with a new credential set, which doesnt contain slash - then it worked without any other changes. 

I haven't tried to generate new credentials to get one with a slash or more to prove that was the cause, but I did try to add the problematic credentials multiple times to aws-vault without luck.

**Comment by mhnajumudeen** [comment]
I have got the same issue today and I have followed aws-vault clear not helped.

I have reset AWS console password. you the following command to add new access key and secret key into vault.
aws-vault add PROFILE_NAME

If the above steps looks good. then you will get the confirmation like Added credentials  to profile "PROFILE_NAME" in vault

Next, you run another command.

aws-vault exec PROFILE_NAME

if you account is MFA enabled then it's asking for type Token in the command prompt.

If you want switch the profile you have mentioned in ~/.aws/config file. change the profile name accordingly.

**Comment by toby-griffiths** [comment]
In case it's of use to anyone, I was having this issue.  For me it was caused by the fact that I have a Yubikey setup for 2fa, and I didn't have it plugged in to my laptop.

**Comment by mtibben** [comment]
I'm assuming this issue was caused by erroneous AWS responses as mentioned on https://github.com/99designs/aws-vault/issues/722#issuecomment-1032653101 and is now resolved. If anyone continues to experience problems, please open a new issue

**Comment by franklinmoraisti** [comment]
aws-vault v5.4.4
Estava com erro semelhante, fiz o seguinte:

aws-vault remove default
aws-vault add default

Resolvido meu problema, acredito que estava com uma credencial antiga salva e quando precisei mudar o token tive esse problema.

**Comment by john-boxcar** [comment]
In case it helps anyone: Make sure your computer's clock is set correctly. I ran into this issue today but the problem was entirely my fault because I had been changing my system clock to troubleshoot a time sensitive bug. Once I ran a network time update everything started working again.
