### ISSUE TITLE
AWS_DEFAULT_REGION overrides config region

### ISSUE THREAD

**Issue by laurichj** [99designs/aws-vault#726]
Since https://github.com/99designs/aws-vault/blob/4a3b14548dca1c7af57bc4d434769bdff751363d/vault/config.go#L439 is being called before cl.populateFromConfigFile, the region set by the env variable overrides those set by the config. https://github.com/99designs/aws-vault/blob/b599e184bad2fd5d9a3754f9b7a98b15e80b70e6/vault/config.go#L296 is where the psection.Region gets ignored.

This had me chasing my tail for a while. I think it'd probably be fine to load the env vars after the configs, but not my codebase :)

**Comment by mtibben** [comment]
Yes that's the intended behaviour - an env var has higher precedence than config - see https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#precedence
