### ISSUE TITLE
Exporting credentials

### ISSUE THREAD

**Issue by johnlane** [99designs/aws-vault#734]
Is there a way to export a credential from aws-vault? Something like `aws-vault get PROFILE` as the opposite of `aws-vault add` ?

I found a little [external tool](https://bke.ro/extracting-secrets-from-aws-vault) that does this but I wondered whether this is something that aws-vault can do somehow already despite not having a `get` command?

My reason for asking is so I don't have to keep a separate copy of credentials around in case I need them - I could treat the files in `~/.awsvault/keys` as masters and avoid duplicating keys.

I'm using version 6.2.0.

**Comment by Jno21** [comment]
Technically those key are available in the vaulting backend that you are using. 
So you could retrieve those key from there.

Or you could aslo call:
`aws-vault exec PROFILE --json --no-session`

I don't know if that answer the topic ?
