### ISSUE TITLE
Start metadata server without subshell (non-daemonized)

### ISSUE THREAD

**Issue by nitrocode** [99designs/aws-vault#735]
- [x] I am using the latest release of AWS Vault

```
$ aws-vault --version
```

- [x] I have provided my `.aws/config` (redacted if necessary)

```ini
[profile sso_engineer]
sso_role_name = snip_engineer
sso_start_url = https://snip.awsapps.com/start
sso_region = us-west-2
sso_account_id = snip
region = us-west-2
cli_pager=
```

- [x] I have provided the debug output using `aws-vault --debug` (redacted if necessary)

## Context

When I run `--server` to launch the metadata service, it runs successfully and seems to launch a new shell. If i run `exit`, it will end my metadata service. The subshell level of `2` can be seen by echoing the `$SHLVL` after running `--server`.

```bash
$ aws-vault exec sso_engineer --server
$ ps ax | grep aws-vault | grep -v aws-vault
35091   ??  Ss     0:00.34 /usr/local/bin/aws-vault proxy
38100 s029  Ss     0:00.75 aws-vault exec sso_engineer --server
$ echo $SHLVL
2
$ exit
$ echo $SHLVL
1
$ ps ax | grep aws-vault | grep -v aws-vault
(nothing)
```

For some reason the normal `nohup <command> 2>&1 > /dev/null &` doesn't work to daemonize the app.

The workaround is to use either `screen` or `tmux`.

```bash
$ screen -dmS metadata aws-vault exec sso_engineer --server
$ ps ax | grep aws-vault | grep -v aws-vault
35091   ??  Ss     0:00.34 /usr/local/bin/aws-vault proxy
38097   ??  Ss     0:00.00 SCREEN -dmS metadata aws-vault exec sso_engineer --server
38100 s029  Ss     0:00.75 aws-vault exec sso_engineer --server
$ exit
$ ps ax | grep aws-vault | grep -v aws-vault
35091   ??  Ss     0:00.34 /usr/local/bin/aws-vault proxy
38097   ??  Ss     0:00.00 SCREEN -dmS metadata aws-vault exec sso_engineer --server
38100 s029  Ss     0:00.75 aws-vault exec sso_engineer --server
```

## Code change

https://github.com/99designs/aws-vault/pull/740 If we remove the `go` prefixed in this line

https://github.com/99designs/aws-vault/blob/4a3b14548dca1c7af57bc4d434769bdff751363d/server/ec2server.go#L29

We can run the app non-daemonized via `nohup` and I can curl the metadata endpoint without any issues.

```bash
$ make clean
$ make aws-vault-darwin-amd64
$ nohup ./aws-vault-darwin-amd64 \
  exec sso_engineer \
  --server \
  --debug > /var/log/aws_vault/server.log 2>/var/log/aws_vault/server.errors.log &
```

And the working plists: https://gist.github.com/nitrocode/cd864db74a29ea52c7b36977573d01cb

**Comment by mtibben** [comment]
Hey @nitrocode, thanks for the effort here put in for this PR. However I don't think this is the direction we want to go in for aws-vault.

`aws-vault` is designed to be a simple, secure tool, without footguns. The whole point of aws-vault is to allow developers to access AWS without having to worry that keys may be leaking, even to rouge processes on the same computer - this was written in the time when npm installs could run code willy nilly with full access to the system.

The server option is already pushing the boundaries of this goal. However we do our best to ensure that the server can only run as long as the executed command is running. Ideally we move to the --ecs-server model permanently when SDKs support it properly.

Adding a feature like this enables aws-vault to run in the background permanently - and this seems to me to be in opposition to that central goal of what aws-vault is trying to accomplish.

**Comment by nitrocode** [comment]
Devs are already using aws-vault as a permanent server option by daemonizing it with screen.

I'm still getting password prompts to access the keychain and my aws sso still requires me to manually sign in using the browser if I use screen or use the --no-daemonize option.

This change simply removes the screen dependency and allows us to use launchd itself. It also prevents my server from dying if I exit the terminal where I initially ran the server.

There are too many sdks that do not support the --ecs-server option so it's still not completely viable for our devs.

We're in the process of using aws-vault as an alternative to hologram which is what most devs use hlat our company but this issue has been our biggest blocker since hologram can be put into a plist but aws-vault cannot.

**Comment by mtibben** [comment]
> The original inspiration for this ticket and the subsequent PR was your comment #548 (comment) last year on a previous issue and you suggested to put the server in launchd which is not possible until the merge of #740.

Ah so that relates to the proxy service - there is a long lived process that aws-vault fires up to proxy requests to the actual aws-vault server. (If aws-vault was itself to become long-lived, that proxy service would not be necessary)

**Comment by nitrocode** [comment]
The irony here is that currently both --server and --ecs-server attempt to daemonize using the `go` function which seems opposite to the goal you mentioned above.

The proposed pr puts in logic so the tool does not daemonize the server and thereby removes the footgun of inadvertently killing the server by exiting the terminal. By not daemonizing either server in the app itself, the PR seems more in line with the project's goal when supplying the --no-daemonize switch.

In fact, i believe if you want aws-vault's server 1:1 with that goal, it makes the most sense to me to not even provide the --no-daemonize switch but to actually default the removal of the `go` function so devs can cmd+c to kill the server.

**Comment by mtibben** [comment]
Sorry, I'm not sure I'm following your argument.

> removes the footgun of inadvertently killing the server by exiting the terminal

That's a feature. When the process requiring credentials exits, so does the credential server. Essentially it's trying to be a daemon only for the target process.

> In fact, I believe if you want aws-vault's server and ecs-server 1:1 with that goal

I mean ideally in my mind we remove `--ec2-server` and only have `--ecs-server`, the latter option is superior in a number of ways

**Comment by nitrocode** [comment]
If the both the proxy and the metadata server ran infinitely but the role used by the metadata server expired after X time and a password prompt came up, wouldn't that be the best option ?

Workflow

1. User runs the proxy service
1. User attempts to runs the metadata service to use role `sre` which has a session expiration of 1h
1. aws-vault prompts for password
    * If role is an AWS SSO role, then don't prompt for password as AWS SSO forces the user to approve via a website
1. Once the password or AWS SSO is approved, the metadata service is started
1. After the session expiration, repeat from step 3

Wouldn't that be a better workflow than the current undocumented feature (which I've been calling a footgun)?

I'm following the SSO path so this workflow has been working for me brilliantly. Our `sre` session expiration is 1h because it's admin and our other roles have a longer session expiration of `4h` and `2h` depending on how many permissions are given to them.

**Comment by nitrocode** [comment]
> > removes the footgun of inadvertently killing the server by exiting the terminal
> 
> That's a feature. When the process requiring credentials exits, so does the credential server. Essentially it's trying to be a daemon only for the target process.
> 
> > In fact, I believe if you want aws-vault's server and ecs-server 1:1 with that goal
> 
> I mean ideally in my mind we remove `--ec2-server` and only have `--ecs-server`, the latter option is superior in a number of ways

Even if you used the `--ecs-server` flag instead of the `--ec2-server` flag, you'd still be bitten by this issue where it drops a subshell which is the root issue here.

**Comment by mtibben** [comment]
Thanks again for your efforts here. I've again recently reviewed the direction of using aws-vault as standalone server in #876. After trying a few directions, I haven't yet found a compelling use-case that fits the original goal of aws-vault - a simple tool to securely access AWS credentials. Adding a standalone server allows aws-vault to run in a way that can compromise those goals, and for that reason I'll close this issue.
