### ISSUE TITLE
Update the docs to make WSL usage more clear

### ISSUE THREAD

**Issue by epicserve** [99designs/aws-vault#736]
- [ ] I am using the latest release of AWS Vault
- [ ] I have provided my `.aws/config` (redacted if necessary)
- [ ] I have provided the debug output using `aws-vault --debug` (redacted if necessary)

```
$ aws-vault --debug
2021/03/01 16:56:08 aws-vault v6.2.0
```

```
$ cat ~/.aws/config
[default]
region=us-east-1

[profile admin]
source_profile=work
parent_profile=work
role_arn=arn:aws:iam::<redacted>:role/OEIEAdmin

[profile dev]
region=us-east-1
source_profile=work
parent_profile=work
role_arn=arn:aws:iam::<redacted>:role/Developer

[profile work]
mfa_serial=<redacted>
```

When reading through the [README](https://github.com/99designs/aws-vault/blob/master/README.md) it's not clear which backend you're supposed to use with Ubuntu under Windows WSL 2. I was able to get the file backend to work, however, it doesn't seem like the file backend can remember your password for a given period of time like I was used to under macOS.

**Comment by paulmchenry** [comment]
I've also been having problems with this and was wondering if I'm supposed to be prompted to enter credentials with every `aws-vault exec` command I use; this is what I am currently seeing and it seems incorrect.

**Comment by ibuseyo** [comment]
Yes. Could we have some support of backend for wsl2. I am getting 
`Specified keyring backend not available, try --help`

**Comment by mtibben** [comment]
PRs welcome

**Comment by epicserve** [comment]
@mtibben,

Is the file backend what is recommended when using WSL 2/ubuntu or is it something else? I would need to know that before creating a PR.

**Comment by mtibben** [comment]
I don't use windows, I have no recommendation

**Comment by ibuseyo** [comment]
I got it running setting pass as the backend password manager. 

`export AWS_VAULT_BACKEND="pass"`

**Comment by warwickgrigg** [comment]
The instructions in #683 for pass and gpg work for me when combined with:

export AWS_VAULT_BACKEND=pass
export GPG_TTY="$( tty )"

**Comment by dannysauer** [comment]
I've been using X410 as an X server and have installed gnome-keyring in my WSL image, and that backend works ok with both this and saml2aws.  I haven't yet figured out how to make a single keyring instance live under the command line, however; it wants dbus in order to work.  Same is true of the KDE keyring program.  That Open Desktop keyring standard is available, though... So if someone wants to look around for a console-friendly keyring option, or maybe figure out how o get a DBUS session working without a traditional Linux desktop environment, that might give a start.

**Comment by dannysauer** [comment]
Docs have not been updated. Issue is not stale.

**Comment by MikeKroell** [comment]
I am interested in this as well. We use gimme-aws-creds for AWS authentication and the keyring is not working for us either. I;m not a developer, but interested in having a solution.

**Comment by SimonLafrikh** [comment]
If you are on windows 11 and on the supported build you can install gnome keyring on wsl and use aws-vault like normal.
https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps

Make sure to update your GPU drivers to the latest version that includes this feature.
