### ISSUE TITLE
Replace deprecated ykman commands with newer unaliased versions

### ISSUE THREAD

**Issue by tomelliff** [99designs/aws-vault#741]
Yubikey-manager v4.0.0 [deprecated the use of `ykman oath code`, replacing it with `ykman oath accounts code`](https://github.com/Yubico/yubikey-manager/commit/f1bbfc3a13ee0f6cef2656c365fbdc579da2d56f). It has [aliased the old command for now](https://github.com/Yubico/yubikey-manager/blob/068bb0d8717f86607dd66deb8a50cec9e30be298/ykman/cli/aliases.py#L102) but I suspect it will be removed in v5.

AWS-Vault could either detect the version of `ykman` and use the appropriate command or, and I think this is my preference for simplicity, just update to use the new command and release that change as a breaking change for AWS-Vault, requiring v4.0.0+ Yubikey-manager to be installed.

**Comment by rantoniuk** [comment]
@mtibben any chance for getting this released 🥺 🙏🏻

**Comment by nvdbleek** [comment]
The fix is in v6.4.0-beta1 is there an ETA for the official release of v6.4.0?
