### ISSUE TITLE
zsh completions are not working correctly

### ISSUE THREAD

**Issue by moltar** [99designs/aws-vault#744]
- [x] I am using the latest release of AWS Vault
- [ ] I have provided my `.aws/config` (redacted if necessary)
- [ ] I have provided the debug output using `aws-vault --debug` (redacted if necessary)

---

I've setup completions the following way (as per docs):

```sh
# in ~/.zshrc

eval "$(aws-vault --completion-script-zsh)"
```

The completions work to suggest the sub-command, but then they do not work further, and keep suggesting the sub command over and over:

![screenshot-20210310T110522-W9DRZO1b](https://user-images.githubusercontent.com/491247/110574933-9a5d1f80-8190-11eb-9de9-6940aea8b6a2.gif)

---

Also, it appears that the completion script provided, is not up to date with the `contrib/completions` dir. But maybe it is not supposed to be, I am not sure.

```
❯ aws-vault --completion-script-zsh
#compdef aws-vault

_aws-vault() {
    local matches=($(${words[1]} --completion-bash "${(@)words[1,$CURRENT]}"))
    compadd -a matches

    if [[ $compstate[nmatches] -eq 0 && $words[$CURRENT] != -* ]]; then
        _files
    fi
}

if [[ "$(basename -- ${(%):-%x})" != "_aws-vault" ]]; then
    compdef _aws-vault aws-vault
fi
```

VS

https://github.com/99designs/aws-vault/blob/2e2c157726ce607a29699b14eac90dc1875f28b4/contrib/completions/zsh/aws-vault.zsh#L1-L24

**Comment by moltar** [comment]
Stale not. Bot bad.

**Comment by moltar** [comment]
[GitHub stale bot considered harmful](https://drewdevault.com/2021/10/26/stalebot.html)

**Comment by tomgilligan** [comment]
I get the same problem when using
> eval "$(aws-vault --completion-script-zsh)"
The completions included in contrib work.
Perhaps the instructions in USAGE.md need to be updated.

**Comment by mtibben** [comment]
Fixed in https://github.com/99designs/aws-vault/commit/106991e626c6938caf66289198ceb2a2142ca82d
