### ISSUE TITLE
Help: Reduce Number of Keychain Password Prompts?

### ISSUE THREAD

**Issue by callum-tait-pbx** [99designs/aws-vault#745]
What controls how often you get prompted for keychain access? I'm trying to get Lens setup to work with aws-vault however I get a prompt for my keychains password roughly every 15 minutes at the moment.

<img width="438" alt="image" src="https://user-images.githubusercontent.com/52924845/110700366-c6f05600-81e7-11eb-8f07-01303a1be4fd.png">

**Comment by Pluies** [comment]
Hey @callum-tait-pbx , I was wondering the same and thought I'd keen an eye on this issue – did you close it because you found a way around this? :)

**Comment by brewingcode** [comment]
I was also wondering this, and found the `security` utility in OSX to manage keychain settings. I ran `set-keychain-settings` without any options to remove the settings from the keychain created by `aws-vault` (the 3rd command below):

```
$ security show-keychain-info ~/Library/Keychains/aws-vault.keychain-db
Keychain "$HOME/Library/Keychains/aws-vault.keychain-db" lock-on-sleep timeout=300s

$ security set-keychain-settings --help
set-keychain-settings: illegal option -- -
Usage: set-keychain-settings [-lu] [-t timeout] [keychain]
    -l  Lock keychain when the system sleeps
    -u  Lock keychain after timeout interval
    -t  Timeout in seconds (omitting this option specifies "no timeout")

        Set settings for a keychain.

$ security set-keychain-settings ~/Library/Keychains/aws-vault.keychain-db

$ security show-keychain-info ~/Library/Keychains/aws-vault.keychain-db
Keychain "$HOME/Library/Keychains/aws-vault.keychain-db" no-timeout

**Comment by kristian-nst** [comment]
> I was also wondering this, and found the `security` utility in OSX to manage keychain settings. I ran `set-keychain-settings` without any options to remove the settings from the keychain created by `aws-vault` (the 3rd command below):
> 
> ```
> $ security show-keychain-info ~/Library/Keychains/aws-vault.keychain-db
> Keychain "$HOME/Library/Keychains/aws-vault.keychain-db" lock-on-sleep timeout=300s
> 
> $ security set-keychain-settings --help
> set-keychain-settings: illegal option -- -
> Usage: set-keychain-settings [-lu] [-t timeout] [keychain]
>     -l  Lock keychain when the system sleeps
>     -u  Lock keychain after timeout interval
>     -t  Timeout in seconds (omitting this option specifies "no timeout")
> 
>         Set settings for a keychain.
> 
> $ security set-keychain-settings ~/Library/Keychains/aws-vault.keychain-db
> 
> $ security show-keychain-info ~/Library/Keychains/aws-vault.keychain-db
> Keychain "$HOME/Library/Keychains/aws-vault.keychain-db" no-timeout
> ```

omg thx! why isn't this the default?!

ive never in 20 years seen a cli that keeps prompting shit :|
