### ISSUE TITLE
When using 'aws-vault exec', 'echo $AWS_VAULT' yields no return

### ISSUE THREAD

**Issue by kd-nguyen** [99designs/aws-vault#746]
- [X] I am using the latest release of AWS Vault
- [ ] I have provided my `.aws/config` (redacted if necessary)
- [ ] I have provided the debug output using `aws-vault --debug` (redacted if necessary)

Hi,

These last several weeks, I have noticed a behaviour I believe was not there before.
When I use `aws-vault exec` inline like so
```
aws-vault exec <profile> -- echo $AWS_VAULT
```
I get no return, while running
```
aws-vault exec <profile> -- env | grep AWS_VAULT
```
yields my profile back

I noticed that when starting a nodeJS application: `process.env.AWS_VAULT` is now empty, while it wasn't some weeks ago

Would you happen to have an idea why?

**Comment by mknapik** [comment]
When you run `aws-vault exec <profile> -- echo $AWS_VAULT` the env var is evaluated before running the command.
Try `aws-vault exec <profile> -- $SHELL -c 'echo $AWS_VAULT'`
