### ISSUE TITLE
aws-vault doesn't source user's ~/.bash_profile on MacOS

### ISSUE THREAD

**Issue by ivan-balandzin** [99designs/aws-vault#752]
- [X] I am using the latest release of AWS Vault
- [ ] I have provided my `.aws/config` (redacted if necessary)
- [ ] I have provided the debug output using `aws-vault --debug` (redacted if necessary)

OS: MacOS Big Sur 11.2.2
AWS Vault v6.2.0

AFAIK when I'm executing `aws-vault exec ***` tool performs something like switching to new session for current user with exporting AWS-specific extra vars. But for some reason it completely miss local user's ~/.bash_profile
For me personally and for many other users I believe local bash profile contains customisations, commands and other things making our life easier and console more handy.
 
```
ivan @ HOSTNAME ~
└─ $ ▶ aws-vault exec *****
Enter token for arn:aws:iam::*************:mfa/ivan-balandzin: ********
bash: __git_ps1: command not found
ivan @ HOSTNAME ~
└─ $ ▶ whoami
ivan
bash: __git_ps1: command not found
```

So you see console throws this error each time I'm passing any command.
Error caused by mechanism of branch autodiscovery in console if I'm in local git repo at the moment.

```
ivan @ HOSTNAME ~
└─ $ ▶ cd /some/local/git/repository
ivan @ HOSTNAME /some/local/git/repository (some_branch)
└─ $ ▶
```

So I have to source my bash profile manually to get rid of this error.

```
ivan @ HOSTNAME ~
└─ $ ▶ source ~/.bash_profile
ivan @ HOSTNAME ~
└─ $ ▶ whoami
ivan
ivan @ HOSTNAME ~
└─ $ ▶
```
Could you please check and fix behaviour of application?
Thank you in advance

**Comment by mtibben** [comment]
aws-vault executes whatever is specified in `SHELL`. If it's bash, it means bash gets executed as a subshell. There are some notes on this at https://gist.github.com/korya/bd0de47f36dbb5c29a90 but the tldr is that `.bashrc` is the place where you want to put this config
