### ISSUE TITLE
Releasing can be reasier with goreleaser

### ISSUE THREAD

**Issue by nitrocode** [99designs/aws-vault#754]
When I put in the PR https://github.com/99designs/aws-vault/pull/751, I didn't realize there is an easier way to do this. I figured it would be best done by a separate ticket and PR.

In the future, instead of piecemea-ing different binaries and having to maintain a `Makefile`, it would be better to use [goreleaser](https://github.com/goreleaser/goreleaser). A good example is their [quick start](https://goreleaser.com/quick-start/). Basically, you can tag the code, run the command, and the release has all the binaries available.

**Comment by mtibben** [comment]
looks like a good tool, however I'm quite comfortable with a Makefile
