### ISSUE TITLE
Feature: Make usage of Firefox containers

### ISSUE THREAD

**Issue by T00mm** [99designs/aws-vault#755]
Currently I am using a custom script that lacks 99% of the functionality that aws-vault provides but what it does is, it uses the profile name in combination with [Firefox containers](https://addons.mozilla.org/en-GB/firefox/addon/multi-account-containers/?utm_content=addons-manager-reviews-link&utm_medium=firefox-browser&utm_source=firefox-browser) and [Open url in container](https://addons.mozilla.org/en-GB/firefox/addon/open-url-in-container/?utm_content=addons-manager-reviews-link&utm_medium=firefox-browser&utm_source=firefox-browser) to seperate each login from eachother.  Making it easy to access multiple consoles in the same browser and with colored tabs.

**Comment by Kessir** [comment]
The `-s` flag on `aws-vault login` will "Print login URL to stdout instead of opening in default browser"

You can then open this URL however you want. 
In this example, I open the AWS console in a specific Microsoft Edge profile:

```open -na "Microsoft Edge" --args --profile-directory="Profile 2" $(aws-vault login -s staging)```

**Comment by mtibben** [comment]
Use `-s` for custom behaviour like this
