### ISSUE TITLE
SSO Authorization stuck

### ISSUE THREAD

**Issue by imartin-MT** [99designs/aws-vault#757]
- [X] I am using the latest release of AWS Vault (using 6.2.0 which is the one accesible on brew)
- [X] I have provided my `.aws/config` (redacted if necessary)
- [X] I have provided the debug output using `aws-vault --debug` (redacted if necessary)

Config
![image](https://user-images.githubusercontent.com/57625850/112304728-bafb9e00-8c95-11eb-9c8c-1b2a1c5df17a.png)

When trying to start the server it will get stuck trying to do the SSO login, it won't open my default browser, if I open the link manually and login it will still not advance, stays like that forever...

![image](https://user-images.githubusercontent.com/57625850/112305117-3b220380-8c96-11eb-983c-6bb0ef657e61.png)

**Comment by sapg** [comment]
I have this same problem on WSL2.

**Comment by turiandras** [comment]
I have the same problem currently on WSL2.
