### ISSUE TITLE
AWS_VAULT_PROMPT not taken from environment

### ISSUE THREAD

**Issue by warden** [99designs/aws-vault#774]
In the [ykman usage](https://github.com/99designs/aws-vault/blob/master/USAGE.md#usage-1) it's mentioned that I can use AWS_VAULT_PROMPT variable. 
It works fine if I use it in the zsh shell like this:

```AWS_VAULT_PROMPT=ykman YKMAN_OATH_CREDENTIAL_NAME=myMfaId aws-vault exec MY-PROFILE -- aws s3 ls```

But when I have the `AWS_VAULT_PROMPT=ykman` in my `~/.zshrc`, then it has no effect (even though i see it's value via echo $AWS_VAULT_PROMPT=ykman in the shell).

Am I missing something obvious? Additionally, is it possible to set `YKMAN_OATH_CREDENTIAL_NAME` in the `~/.aws/config` per profile, so that I don't need to include it in the lengthy `aws-vault` command?

**Comment by mtibben** [comment]
Are you using `export AWS_VAULT_PROMPT=ykman`?

See https://superuser.com/questions/18988/difference-between-a-b-and-export-a-b-in-bash

**Comment by warden** [comment]
@mtibben indeed, that was the issue, thanks a lot.
Do you have any idea for the `YKMAN_OATH_CREDENTIAL_NAME` per profile? I tried using this in the ROOT profile:
```
credential_process = env YKMAN_OATH_CREDENTIAL_NAME=XXX AWS_SDK_LOAD_CONFIG=0 aws-vault --backend=pass --pass-prefix=aws-vault --prompt=osascript exec --region eu-west-1 --duration=1h root --json
```
but apparently this doesn't work.

I need this because using the ykman credentials in `arn:aws:iam::${ACCOUNT_ID}:mfa/${IAM_USERNAME}` form is not human-friendly - and since AWS Console does not support YubiKey by default, to have both, _aws-vault_ working on the CLI and _AWS console_ in the browser, I need to use `ykman oath accounts code -s <projectname>` to easily differentiate between projects and get a token to log in to the AWS console using Virtual MFA. 
Unless you have some method for having them both working together?

**Comment by rantoniuk** [comment]
@mtibben should I open a new issue for the above to be possible?
