### ISSUE TITLE
How to just cache STS credentials without an `exec`? 

### ISSUE THREAD

**Issue by vspinu** [99designs/aws-vault#781]
I a probably missing something obvious. Sorry if it's the case. 

How can one ensure that STS is cached and MFA asked for (if needed) without invoking an AWS command?  What I do right now is

```
aws-vault exec finanzcheck --json > /dev/null
```
Is this the standard way to achieve session login?

**Comment by irgeek** [comment]
You can just invoke a command that does nothing like:

```
aws-vault exec finanzcheck echo
```

or 

```
aws-vault exec finanzcheck true
```

**Comment by vspinu** [comment]
Ha ha. Cool. No idea how this didn't occur to me. Thanks!
