### ISSUE TITLE
Lost Credentials 

### ISSUE THREAD

**Issue by powerserg19** [99designs/aws-vault#786]
i installed aws-vault yesterday on ubuntu 20. I was able to run aws-vault commands
Today I cannot  run any aws-vault command because I do not know what my password is
How do I reset the password or start over again?

**Comment by powerserg19** [comment]
The keyring file is located here. I removed it and started over again
~/.local/share/keyrings/awsvault.keyring

**Comment by powerserg19** [comment]
~/.local/share/keyrings/awsvault.keyring

**Comment by exchgr** [comment]
for those coming here on macOS, it's at `~/Library/Keychains/aws-vault.keychain-db`
