### ISSUE TITLE
Warn when failing to bind to port 80 when creating the metadata server

### ISSUE THREAD

**Issue by williamdenton** [99designs/aws-vault#788]
- [ ] I am using the latest release of AWS Vault
- [ ] I have provided my `.aws/config` (redacted if necessary)
- [ ] I have provided the debug output using `aws-vault --debug` (redacted if necessary)

On windows, IIS is by default configured to bind to `*:80`, this means that when aws vault adds a new interface/ip  (169.254.169.254) for the metadata server, iis immediately binds to it before aws-vault can, this means that aws-vault server mode does not work for clients as IIS returns 404 for everything.

The fix for this is to
* disable/stop IIS
or
* configure IIS to bind to 127.0.0.1 rather than all local ip addresses

aws-vault could handle this better by warning that it was unable to bind to port 80 when starting the metadata server

**Comment by williamdenton** [comment]
i still think this is a good idea, and maybe ill have time to have a crack in future, so just adding a comment to make it not stale

**Comment by mtibben** [comment]
> aws-vault could handle this better by warning that it was unable to bind to port 80 when starting the metadata server

Does it not do this already?
