### ISSUE TITLE
Yubikey with multiple accounts

### ISSUE THREAD

**Issue by zfLQ2qx2** [99designs/aws-vault#797]
If I am using aws-vault with yubikey can I use the same hey for multiple accounts? Or do I need one key per account? Multi-organization situation, AWS accounts are completely separate businesses, I know that 99designs is a proponent of using a management account to assume roles in different accounts within the same organization.

**Comment by zfLQ2qx2** [comment]
I can answer my own question - I got ahold of a Yubikey 5C over the weekend and I was able to add 32 different TOTP accounts to the device which is very respectable IMO though not documented anywhere.

**Comment by mtibben** [comment]
> though not documented anywhere

Feel free to document it - PRs welcome
