### ISSUE TITLE
ykman MFA gui prompt

### ISSUE THREAD

**Issue by antonstamenov** [99designs/aws-vault#801]
- [x] I am using the latest release of AWS Vault
- [ ] I have provided my `.aws/config` (redacted if necessary)
- [ ] I have provided the debug output using `aws-vault --debug` (redacted if necessary)

I'm using aws-vault with yubikey. It works just fine. The only inconvenience I see is that ykman prompt is text only. It will be really nice if there is ykman-gui prompt that indicates when I have to touch the yubikey when asked from a GUI app, like PyCharm.

**Comment by meeuw** [comment]
That's an interesting idea but as far as I can see ykman-gui isn't able to prompt to touch the YubiKey. 

What made you think this is possible?

**Comment by jasiek** [comment]
I've been thinking about this - perhaps it'd be possible to delegate the OTP code generation to an external process, such as ykman. When running aws-vault this would then require the user to touch their key to generate a code and the code would be fed into aws-vault.

A poor man's version of this would be to just run `ykman oath accounts code <account>` before aws-vault to display the code.

**Comment by mtibben** [comment]
@jasiek isn't this exactly what `--prompt=ykman` does?

**Comment by dantman** [comment]
I often run aws-vault with local dev servers and for GUIs to manage EKS clusters that need credentials from aws-vault. It would be lovely to have more than just the yubikey's green light blinking to let me know when a MFA is required.

A Windows notification like what KeePass Agent sends when an SSH key is sent would be enough for me.
