### ISSUE TITLE
Versions later than 4 don't wait for MFA prompt on Ubuntu on WSL2

### ISSUE THREAD

**Issue by tomdeblende** [99designs/aws-vault#805]
- [ V] I am using the latest release of AWS Vault
- [ X] I have provided my `.aws/config` (redacted if necessary)
- [ V] I have provided the debug output using `aws-vault --debug` (redacted if necessary)

When running aws-vault with MFA, it does not wait for MFA input:

`tom@tom-work:~$ ./aws-vault-linux-amd64.1 exec profile --debug
2021/09/12 14:48:00 aws-vault v6.3.1
2021/09/12 14:48:00 Loading config file /home/tom/.aws/config
2021/09/12 14:48:00 Parsing config file /home/tom/.aws/config
2021/09/12 14:48:00 [keyring] Considering backends: [file]
2021/09/12 14:48:00 Profile 'default' missing in config file
2021/09/12 14:48:00 Profile 'default' missing in config file
2021/09/12 14:48:00 [keyring] Expanded file dir to /home/tom/.awsvault/keys/
2021/09/12 14:48:00 [keyring] Expanded file dir to /home/tom/.awsvault/keys/
2021/09/12 14:48:00 profile root: using stored credentials
2021/09/12 14:48:00 profile root: using GetSessionToken (with MFA)
2021/09/12 14:48:00 profile profile: using AssumeRole (chained MFA)
2021/09/12 14:48:00 Using STS endpoint https://sts.amazonaws.com
2021/09/12 14:48:00 [keyring] Expanded file dir to /home/tom/.awsvault/keys/
2021/09/12 14:48:00 [keyring] Expanded file dir to /home/tom/.awsvault/keys/
2021/09/12 14:48:00 [keyring] Expanded file dir to /home/tom/.awsvault/keys/
Enter token for arn:aws:iam::ID:mfa/user:
2021/09/12 14:48:02 Using STS endpoint https://sts.amazonaws.com
aws-vault: error: exec: Failed to get credentials for profile: InvalidParameter: 1 validation error(s) found.
- minimum field size of 6, GetSessionTokenInput.TokenCode.`

Similar issues: https://github.com/99designs/aws-vault/issues/126

Works fine on last version 4 (4.7.2), does not work on latest versions 5 (5.4.4) and 6 (6.3.1).

**Comment by prmarino1m** [comment]
I cant confirm this issue in the latest development branch assuming the profile is configured correctly in the AWS SDK config file
I have seen something similar when aws-vault is called via the credential_process directive in the profile it gives a blank prompt for the MFA and you get that error if you don't enter a code at the blank prompt. That could be what you are running into. Does it hang until you hit enter then return the error?

**Comment by tomdeblende** [comment]
It does not hang waiting for an enter. It just quits.

How can I test the latest development branch?
