### ISSUE TITLE
Dave isn't a committer

### ISSUE THREAD

**Issue by joho** [99designs/aws-vault#82]
@dgoodlad can't commit.

**Comment by dgoodlad** [comment]
![aws-vault a vault for securely storing and accessing aws credentials in development environments 2016-08-17 12-48-26](https://cloud.githubusercontent.com/assets/399/17722879/e79daf88-6478-11e6-846e-c7a8fcf9e7e8.png)

COMMIT BIT: GET!

**Comment by joho** [comment]
![](https://media.giphy.com/media/l0MYC0LajbaPoEADu/giphy.gif)
