### ISSUE TITLE
Question: Is the AWS_ACCESS_KEY_ID supposed to match what I entered?

### ISSUE THREAD

**Issue by jessecodescode** [99designs/aws-vault#824]
I ran these commands in succession. Should I expect the Access Key ID that I entered to be the same or different from the AWS_ACCESS_KEY_ID output the env command produces?

```
 aws-vault add bfn.jesXXXXXXXXX
 aws-vault exec bfn.jesXXXXXXXXX
 echo $SHLVL
 env | grep AWS
```

The access key id I entered is not the same value as what I got from the env command inside the subshell. Is that intentional?

I am using the latest release of AWS Vault
I am running Ubuntu 20.04.3

**Comment by phaalonso** [comment]
I have the same problem
