### ISSUE TITLE
Minor feature request: seeing the role ARN in `aws-vault list`

### ISSUE THREAD

**Issue by ronkorving** [99designs/aws-vault#830]
I often have to look up role names or account IDs based on a profile name. So I often find myself `cat`ing `~/.aws/config`, which, I guess works. With many profiles (definitely the case for me), that output can be a bit big, and I have to scroll and search...

If the output from `aws-vault list` would have one extra column with the role ARN in it, I could easily clipboard-copy the role name and account ID from it.

It's just a minor request, not something to prioritize, I guess. But a welcome quality-of-life improvement nonetheless.

Thanks!

**Comment by mtibben** [comment]
Hey @ronkorving  if you wish to implement this, feel free to open a PR. As I don't intend to implement at this time I will close for now.
