### ISSUE TITLE
Please document how supply chain is taken care of

### ISSUE THREAD

**Issue by arkadijs** [99designs/aws-vault#838]
I, as a decision maker in a particular enterprise or a security cautious person, would like to know how authors of AWS Vault take care of preventing malicious code getting into its source code base. I may need to answer a question: what is the basis of my trust in 99designs engineering process?

Spotlight is on the tools that "provides" security. A paragraph in Readme explaining the process would be enough.

-- 
Happy `aws-vault` user.

**Comment by mtibben** [comment]
@arkadijs This is open source software with no guarantees, responsibility for security lies with the user

**Comment by arkadijs** [comment]
Hey, you're fully entitled to your right to hangup on your end of the channel. Please state what you wrote above on the front page of the project then?

For your consideration:

https://wiki.debian.org/Teams/Security
https://www.debian.org/social_contract

https://1passwordstatic.com/files/security/1password-white-paper.pdf (page 66)
https://blog.1password.com/how-the-1password-security-team-evaluates-new-tools/
https://support.1password.com/security-assessments/

https://github.com/opengovsg/engineering-practices/blob/develop/developer-environment/passwords.md

If me / my company have proper engineering practices, then it's beneficial to promote them - for the product (open-source or proprietary), for the company - stating explicitly what they are. Not a huge work required nor any additional "responsibility" assigned.

I suppose, one of the reasons to open-source aws-vault was to improve the ecosystem by having more users install it. This - publishing how work on aws-vault is organized - will get you more users (or not).

> We were more concerned about malware stealing credentials from disk.
> It’s a binary and very easy to install and incorporate in your day-to-day usage. Give it a try and let us know how we can improve it.

@lox
