### ISSUE TITLE
duration_seconds is ignored if set in ~/.aws/config

### ISSUE THREAD

**Issue by 1oglop1** [99designs/aws-vault#851]
Hi, it looks like that duration_seconds setting is ignored by aws-vault unless I misunderstood anything.

- [x] I am using the latest release of AWS Vault: *6.4.0-Homebrew*
- [X] I have provided my `.aws/config` (redacted if necessary)
```
[profile my-profile]
duration_seconds=28800
mfa_serial=arn:aws:iam::<redacted>:mfa/username
region=eu-central-1
output=text
```
- [x] I have provided the debug output using `aws-vault --debug` (redacted if necessary)

without duration argument - I expected 8 hours not 1.
```
aws-vault --debug login my-profile
2022/01/24 12:54:29 aws-vault 6.4.0-Homebrew
2022/01/24 12:54:29 [keyring] Considering backends: [secret-service]
2022/01/24 12:54:29 Loading config file /home/jan/.aws/config
2022/01/24 12:54:29 Parsing config file /home/jan/.aws/config
2022/01/24 12:54:29 Looking up keyring for 'stx'
2022/01/24 12:54:29 Using GetFederationToken for credentials
2022/01/24 12:54:29 Looking up keyring for 'stx'
2022/01/24 12:54:29 Generated credentials **************** using GetFederationToken, expires in 1h0m0.35678599s
2022/01/24 12:54:29 Creating login token, expires in 1h0m0.356666614s
```

with
```
aws-vault login my-profile --debug --duration=2h
2022/01/24 12:59:51 aws-vault 6.4.0-Homebrew
2022/01/24 12:59:51 [keyring] Considering backends: [secret-service]
2022/01/24 12:59:51 Loading config file /home/jan/.aws/config
2022/01/24 12:59:51 Parsing config file /home/jan/.aws/config
2022/01/24 12:59:51 Looking up keyring for 'my-profile'
2022/01/24 12:59:52 Using GetFederationToken for credentials
2022/01/24 12:59:52 Looking up keyring for 'my-profile'
2022/01/24 12:59:52 Generated credentials ****************CR2J using GetFederationToken, expires in 1h59m59.772701458s
2022/01/24 12:59:52 Creating login token, expires in 1h59m59.772600874s
```

**Comment by mtibben** [comment]
`duration_seconds` is for roles, not federation

**Comment by 1oglop1** [comment]
@mtibben Could you please elaborate on your comment?
I'm not too familiar with these things in IAM and my question was based on this https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html#cli-configure-files-settings 

Does that mean that `duration_secconds` in config is honored by `aws sts assume-role` but not `aws sts get-federation-token`? 
They both have a duration argument though. 
https://awscli.amazonaws.com/v2/documentation/api/2.1.30/reference/sts/assume-role.html
https://awscli.amazonaws.com/v2/documentation/api/2.1.30/reference/sts/get-federation-token.html

**Comment by mtibben** [comment]
> Does that mean that duration_secconds in config is honored by aws sts assume-role but not aws sts get-federation-token?

Correct. See the USAGE docs for configuring TTLs https://github.com/99designs/aws-vault/blob/master/USAGE.md#environment-variables
