### ISSUE TITLE
`aws-vault` suddenly started to report "UnauthorizedException: Session token not found or invalid" every morning

### ISSUE THREAD

**Issue by foxylion** [99designs/aws-vault#854]
Since a few days I receive every morning a message from `aws-vault` that looks like the following:
```
aws-vault: error: exec: Failed to get credentials for xyz-sso: operation error SSO: GetRoleCredentials,
https response error StatusCode: 401, RequestID: , UnauthorizedException: Session token not found or invalid
```

I frequently use the command `aws-vault exec xyz-sso --json` to generate some new temporary credentials.
Previously this worked flawlessly and opened the SSO page, if my session had expired, but now I only receive the above mentioned error.

To fix it I need to run `aws-vault clear` manually.

---

My `aws-vault` configuration:
```
AWS_VAULT_BACKEND=file
AWS_VAULT_FILE_PASSPHRASE=*some-secret-string*
```

I am using the latest release of AWS Vault
```
aws-vault --debug
2022/02/01 09:12:01 aws-vault 6.4.0
```
I have provided my `.aws/config` (redacted if necessary)
```
[profile xyz-sso]
sso_start_url = https://xyz.awsapps.com/start
sso_region = eu-central-1
sso_account_id = 1234567890
sso_role_name = AdministratorAccess
region = eu-central-1
```
I have provided the debug output using `aws-vault --debug` (redacted if necessary)
```
➜ aws-vault exec xyz-sso --json --debug
2022/02/01 09:13:05 aws-vault 6.4.0
2022/02/01 09:13:05 Loading config file /home/xyz/.aws/config
2022/02/01 09:13:05 Parsing config file /home/xyz/.aws/config
2022/02/01 09:13:05 [keyring] Considering backends: [file]
2022/02/01 09:13:05 Profile 'default' missing in config file
2022/02/01 09:13:05 [keyring] Expanded file dir to /home/xyz/.awsvault/keys/
2022/02/01 09:13:05 [keyring] Expanded file dir to /home/xyz/.awsvault/keys/
2022/02/01 09:13:05 [keyring] Expanded file dir to /home/xyz/.awsvault/keys/
2022/02/01 09:13:05 [keyring] Expanded file dir to /home/xyz/.awsvault/keys/
2022/02/01 09:13:05 [keyring] Expanded file dir to /home/xyz/.awsvault/keys/
2022/02/01 09:13:05 [keyring] Expanded file dir to /home/xyz/.awsvault/keys/
aws-vault: error: exec: Failed to get credentials for xyz-sso: operation error SSO: GetRoleCredentials, https response error StatusCode: 401, RequestID: , UnauthorizedException: Session token not found or invalid
```

**Comment by gwynnarth** [comment]
Looks like a duplicate of https://github.com/99designs/aws-vault/issues/722

I am having the same issues, BTW.

**Comment by momchilvangelov** [comment]
We are also having the same problem now! The whole team!

**Comment by philcruz** [comment]
I just upgraded to 6.4.0 and ran into this issue. Running `aws-vault clear` helped me work around it.

**Comment by endzyme** [comment]
https://github.com/99designs/aws-vault/issues/722 - is this a duplicate of this?

**Comment by endzyme** [comment]
To duplicate my note here, can anyone confirm their `Token.ExpiresIn` value from their keystore? Mine currently says `604800` (7 days). My hunch is that the actual expiration of the token is < 7 days, and so `aws-vault` doesn't engage the SSO flow because it believes the token to still be valid. If you look at your keystore, you should see an OIDC token (depending on your configuration). In the keystore payload there is a `.Data` key, which has your base64 encoded `Token` response from the `CreateToken` API which AWS uses for SSO. To inspect this, copy the content of the keystore key into a file and run `jq -r '.Data|@base64d` keystore-contents.json | jq .`

Anyone else have other values other than 604800 in the `ExpiresIn` key?

**Comment by endzyme** [comment]
Quick update here - Our AWS support case has confirmed that our `ExpiresIn` _was_ returning `28800` (8 hours)  and is now returning `604800` (7 days). This apparently is an internal configuration in the AWS service itself, which cannot be edited by customers. They're investigating the issue, but I would recommend reaching out to AWS support about this issue.

**Comment by ajkerrigan** [comment]
> Quick update here - Our AWS support case has confirmed that our `ExpiresIn` _was_ returning `28800` (8 hours) and is now returning `604800` (7 days). This apparently is an internal configuration in the AWS service itself, which cannot be edited by customers. They're investigating the issue, but I would recommend reaching out to AWS support about this issue.

Hey thanks for digging into this. I started seeing this issue recently, and had only started to poke around to see what might have changed. I had the same suspicion as you - glancing at the token details they all _claimed_ to expire in 7 days but were throwing errors sooner.

This morning I generated fresh SSO creds with aws-vault, but separately went through a manual `aws sso-oidc create-token` dance to get a test outside the aws-vault world. I'm curious to see if one or both tokens are still valid later tonight or tomorrow.

**Comment by ajkerrigan** [comment]
> > Quick update here - Our AWS support case has confirmed that our `ExpiresIn` _was_ returning `28800` (8 hours) and is now returning `604800` (7 days). This apparently is an internal configuration in the AWS service itself, which cannot be edited by customers. They're investigating the issue, but I would recommend reaching out to AWS support about this issue.
> 
> Hey thanks for digging into this. I started seeing this issue recently, and had only started to poke around to see what might have changed. I had the same suspicion as you - glancing at the token details they all _claimed_ to expire in 7 days but were throwing errors sooner.
> 
> This morning I generated fresh SSO creds with aws-vault, but separately went through a manual `aws sso-oidc create-token` dance to get a test outside the aws-vault world. I'm curious to see if one or both tokens are still valid later tonight or tomorrow.

To follow up on this, the response from my manual `aws sso-oidc create-token` with the AWS CLI this morning had the `604800` expiration:
```json
{
    "accessToken": "eyJ...",
    "tokenType": "Bearer",
    "expiresIn": 604800
}
``` 
I was able to use that token successfully in a `aws sso list-accounts` call ~8 hours ago, and it's failing now. Both tests were _not_ using aws-vault. This is mostly a big +1 to what @endzyme said with it seeming like a backend issue on the AWS side. I was wondering if this is event something aws-vault could gracefully handle, but I don't think it is since the API error response is vague and would often suggest a non-retryable problem with the credentials.

**Comment by FernandoMiguel** [comment]
Thanks for digging this up....
I had upgraded to macos 12 and thought it was related upgrade.
I'll reach out to our TAM so that they can keep us informed.

**Comment by endzyme** [comment]
Quick update from our AWS support case. They told us that the token TTL is definitely supposed to be 8 hours and referenced this doc (https://aws.amazon.com/premiumsupport/knowledge-center/sso-temporary-credentials/#:~:text=is%20valid%20for-,8%20hours,-as%20noted%20in).

I would suggest everyone open a case with their AWS support to get more attention on the issue.

**Comment by momchilvangelov** [comment]
@endzyme 
Do you mean the SSO session duration, because that's actually editable, and you can set any values from 1h to 12h.
![image](https://user-images.githubusercontent.com/73303702/153009051-f07a36a0-1223-43ec-a31d-e173de3ec401.png)

**Comment by endzyme** [comment]
Thanks @momchilvangelov for the screenshots. This time is for the assumerole session via sts, not the initial SSO access token provided by the CreateToken API for SSO. The screenshot you show above eventually gets propagated to all your AWS accounts into role session times.

See [this API reference](https://docs.aws.amazon.com/singlesignon/latest/OIDCAPIReference/API_CreateToken.html) for the token I'm referring to.

**Comment by jfirebaugh** [comment]
According to our AWS rep, this has been fixed on the AWS side. Anyone still experiencing the issue?

**Comment by endzyme** [comment]
> According to our AWS rep, this has been fixed on the AWS side. Anyone still experiencing the issue?

Same. AWS has confirmed that SSO was broken for a period and the rolled back some change set on their side. We're also getting the correct values again from the API.

**Comment by foxylion** [comment]
I can confirm, this no longer does happen!

**Comment by coolnsmile** [comment]
Hi foxylion

could you let me know what kinds of issue there was ?

I'm curious to know what made you mentioned "I can confirm, this no longer does happen! " 

Have a good day!!

**Comment by endzyme** [comment]
> Hi foxylion
> 
> could you let me know what kinds of issue there was ?
> 
> I'm curious to know what made you mentioned "I can confirm, this no longer does happen! "
> 
> Have a good day!!

https://github.com/99designs/aws-vault/issues/854#issuecomment-1032080362
