### ISSUE TITLE
aws-vault error caused by TLS handshake timeout

### ISSUE THREAD

**Issue by almeida-matheus** [99designs/aws-vault#856]
- [x] I am using the latest release of AWS Vault
- [ ] I have provided my `.aws/config` (redacted if necessary)
- [ ] I have provided the debug output using `aws-vault --debug` (redacted if necessary)

after updating macOS to version 12 Monterey I can't use aws-vault, every time I run it has a delay of a few seconds and the following output error:

`aws-vault exec` with AWS SSO:

```
aws-vault: error: exec: Failed to get credentials for profile-name: RequestError: send request failed
caused by: Post "<https://oidc.us-east-1.amazonaws.com/client/register>": net/http: TLS handshake timeout
```

`aws-vault rotate` with access key credentials:
```

aws-vault: error: rotate: RequestError: send request failed
caused by: Post "<https://sts.amazonaws.com/>": net/http: TLS handshake timeout
```

does anyone have any idea how to solve this?

**Comment by nepgpn** [comment]
I am also getting same issue after the upgrade? Any resolution?

**Comment by dealyb** [comment]
I am seeing this as well.  any work-arounds?
