### ISSUE TITLE
Better UX in terminals when credentials expire

### ISSUE THREAD

**Issue by danbosnichill** [99designs/aws-vault#863]
I ran `aws-vault exec myprofile`.  Later my credentials expired.  My team mates said to `exit` on the terminal and re-run it.  This seems scary considering my terminal prompt doesn't change to indicate I'm in a vault exec.  I don't want to accidentally run `exit` and close a useful terminal.

Is there better UX for this?  Is there a way to update credentials inside an already running exec?

- [x] I am using the latest release of AWS Vault
- [ ] I have provided my `.aws/config` (redacted if necessary)
- [ ] I have provided the debug output using `aws-vault --debug` (redacted if necessary)

**Comment by sftim** [comment]
How about this one-liner to exit only if you have a session token:
```shell
[ "" = "$AWS_SESSION_TOKEN" ] || exit
```

You could make that a shell function, if you like.

**Comment by danbosnichill** [comment]
Thanks!  That's pretty clean.  Feel free to close.  Might be a good idea to add that to the top-level readme.
