### ISSUE TITLE
Suggestion: mention aws-vault in user agent request headers

### ISSUE THREAD

**Issue by sftim** [99designs/aws-vault#865]
When someone uses `aws-vault` to perform an action, the request (and, later, the CloudTrail logs) don't mention `aws-vault` in the user agent string.

You can customise the user-agent string using the `AWS_EXECUTION_ENV` environment variable, but that mechanism isn't intended for identifying the client application.

I propose:
- Change the user agent string handling to prepend a user agent string for aws-vault (allowing the AWS Golang SDK to append the details that are there now).

**Additional context**
Example user agent strings, current vs desired:
```diff
- aws-sdk-go-v2/1.13.0 os/macos lang/go/1.17.6 md/GOOS/darwin md/GOARCH/amd64 api/sts/1.14.0
+ aws-vault/6.5.0 aws-sdk-go-v2/1.13.0 os/macos lang/go/1.17.6 md/GOOS/darwin md/GOARCH/amd64 api/sts/1.14.0
```

The `MakeAddToUserAgentFreeFormHandler()` function is likely to be helpful.

**Comment by mtibben** [comment]
Sure thing @sftim - feel free to open a PR
