### ISSUE TITLE
An error occurred (InvalidClientTokenId) when calling the CreateUser operation: The security token included in the request is invalid

### ISSUE THREAD

**Issue by juliusashu** [99designs/aws-vault#917]
Please I have the error below,
An error occurred (InvalidClientTokenId) when calling the CreateUser operation: The security token included in the request is invalid

I have changed several AWS Access Key ID and AWS Secret Access Key but still getting the same error. There is no MFA on the user account.

Please any help to resolve this error will be very grateful.

**Comment by nidgetgod** [comment]
Try delte password in keyring, in Ubuntu it should see in seahorse(awsvault)

After delete it and re-create using `aws-vault add <profile>`
