### ISSUE TITLE
Failed to execute process: '/usr/local/bin/aws-vault' the file could not be run by the operating system on Apple M1

### ISSUE THREAD

**Issue by bhaskey** [99designs/aws-vault#930]
-  I am using the v6.3.1 version of AWS Vault
-  I have provided my `.aws/config`

Whenever I try to run any aws-vault command I get the following error:
exec: Failed to execute process: '/usr/local/bin/aws-vault' the file could not be run by the operating system.

I tried reinstalling the aws-vault from brew, directly using wget, added right access. as below:
sudo chmod +x /usr/local/bin/aws-vault

Side note: this command used to work but started getting this error, after I downgraded the version of kubectl, not sure how can that mess this up. Maybe not.

**Comment by mtibben** [comment]
Use the `aws-vault-darwin-arm64.dmg` file for apple silicon

**Comment by mtibben** [comment]
Use the `aws-vault-darwin-arm64.dmg` file for apple silicon
