### ISSUE TITLE
Using credential_process with role_arn exposes credentials in ~/.aws/cli/cache

### ISSUE THREAD

**Issue by pheydenrych** [99designs/aws-vault#939]
- [ ] I am using the latest release of AWS Vault
- [ ] I have provided my `.aws/config` (redacted if necessary)
- [ ] I have provided the debug output using `aws-vault --debug` (redacted if necessary)

Given this config, with credentials stored in the `creds` profile:

```
[profile creds]
region=us-east-1
output=json
#credential_process=sh -c 'aws-vault exec creds --json 2> $(tty)'
#credential_process=aws-vault exec creds --no-session --json
credential_process=aws-vault exec creds --json

[profile vault]
region=us-east-1
output=json
role_arn=arn:aws:iam::1234567890:role/my-assumed-role
source_profile=creds
```

Running commands using the CLI directly e.g. `aws s3 ls --profile vault` exposes the credentials in `~/.aws/cli/cache`
Running `aws-vault exec vault -- aws s3 ls` does not update the cache in `~/.aws/cli/cache`

Multiple variations of `credential_process` makes no difference.

I suspect this is unavoidable unless we revert to using `aws-vault exec` without `credential_process`. 
This still means keys are retrievable by anyone aware of this behavior.

EDIT: It turns out the cache only contains the session token details. The access key itself is not exposed. This issue can be closed!

**Comment by phene** [comment]
This is a behavior of the aws-cli, not aws-vault. This is how it caches temporary credentials.
