### ISSUE TITLE
provide region when using aws-vault exec -j

### ISSUE THREAD

**Issue by tekumara** [99designs/aws-vault#955]
Would it be possible to output the profiles aws region when using `aws-vault exec -j` (similar to aws-vault exec without -j)?
This will allow me to use profiles that I have set up in different regions.

**Comment by ChristopherHackett** [comment]
`-j` / `--json` appears to be intended for use with `credential_process`. The [AWS docs](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html) on this say:

>The command you specify must generate JSON output on STDOUT that matches the following syntax.
> 
> ```json
> {
>  "Version": 1,
>  "AccessKeyId": "an AWS access key",
>  "SecretAccessKey": "your AWS secret access key",
>  "SessionToken": "the AWS session token for temporary credentials", 
>  "Expiration": "ISO8601 timestamp when the credentials expire"
> }  
>```

The docs found say "must" so there is a bit of risk of change here. 

@tekumara Are you using `-j` / `--json` with the `credential_process` or rolling your own tooling?

**Comment by tekumara** [comment]
I was looking into this as an alternative to https://github.com/99designs/aws-vault/issues/761#issuecomment-894592829 ie: as a way to get the credentials as env vars so I can set them in the current shell.

**Comment by tekumara** [comment]
Superceded by #1145
