### ISSUE TITLE
3.5.0 broken on Sierra

### ISSUE THREAD

**Issue by stevehodgkiss** [99designs/aws-vault#96]
3.5.0 isn't working on Sierra for me. I suspect this PR broke things https://github.com/99designs/aws-vault/pull/88 since I've build 1c5c5f2 locally and that works fine.

Steps taken (after removing the old `aws-vault.keychain` keychain file):

`aws-vault add my-profile` asks for a new password for the vault, and appears to work fine. It creates `aws-vault.keychain-db` (not `aws-vault.keychain` like the log output indicates):

```
❯ aws-vault add my-profile
Enter Access Key ID: [snip]
Enter Secret Access Key: [snip]
2016/09/26 14:11:34 Opening keychain /Users/steve/Library/Keychains/aws-vault.keychain
2016/09/26 14:11:34 Creating keychain /Users/steve/Library/Keychains/aws-vault.keychain (prompt true)
2016/09/26 14:11:42 Adding service="aws-vault", account="my-profile" to osx keychain /Users/steve/Library/Keychains/aws-vault.keychain
Added credentials to profile "my-profile" in vault
2016/09/26 14:11:42 Parsing config file /Users/steve/.aws/config
2016/09/26 14:11:42 Opening keychain /Users/steve/Library/Keychains/aws-vault.keychain
```

Then trying to use it fails. It doesn't ask for my vault password at this stage:

```
❯ aws-vault exec a-profile bash
2016/09/26 14:11:48 Parsing config file /Users/steve/.aws/config
2016/09/26 14:11:48 Looking up keyring for my-profile
2016/09/26 14:11:48 Opening keychain /Users/steve/Library/Keychains/aws-vault.keychain
2016/09/26 14:11:48 Error from keyring The user name or passphrase you entered is not correct.
No credentials found for profile "a-profile"
```

**Comment by lox** [comment]
Thanks @stevehodgkiss, I wonder if this is a keyring permissions bug. The error `The user name or passphrase you entered is not correct.` is a catch-all for a variety of permissions bugs. Could I trouble you to use the Keychain Access utility to repair your keychain permissions?

**Comment by lox** [comment]
The discrepancy between `.keychain` and `.keychain-db` should be a red herring. We use the `.keychain` filename and OSX translates it to the new `.keychain-db` internally.

**Comment by lox** [comment]
I'm going to close this. Please feel free to re-open @stevehodgkiss if you are still having issues.

**Comment by ndaversa** [comment]
I had to build from `1c5c5f26e90951f63d8c4b79890d8914db9b5e81` to get this working on sierra. Latest 3.5.0 release build was broken for me

**Comment by lox** [comment]
Broken in what way?

**Comment by ndaversa** [comment]
> Broken in what way?

I was getting the same `No credentials found for profile "profilenamehere"` problem

**Comment by lox** [comment]
Did you reboot?

**Comment by ndaversa** [comment]
> Did you reboot?

lol, no I did not. However the `1c5c5f26e90951f63d8c4b79890d8914db9b5e81` version worked without a reboot.

**Comment by lox** [comment]
Bet it would fix the issue :)

**Comment by ndaversa** [comment]
> Bet it would fix the issue :)

I wouldn't be surprised.

**Comment by lox** [comment]
If it persisted beyond a reboot, it would actually be an amazing thing, because then I could possibly fix it. As it stands, I believe this is another echo of the dreaded #49, which is actually a Keychain issue.

**Comment by lox** [comment]
For comparison, we are all on Sierra :)
