### ISSUE TITLE
Config "default" works on mac but no on ubuntu. 

### ISSUE THREAD

**Issue by nightmare-moon** [99designs/aws-vault#960]
- [x] I am using the latest release of AWS Vault
- [x] I have provided my `.aws/config` (redacted if necessary)
- [x] I have provided the debug output using `aws-vault --debug` (redacted if necessary)

This is two questions in one.
aws-vault:  v6.6.0
Ubuntu: 21.5.0
[debugfile.txt](https://github.com/99designs/aws-vault/files/9013250/debugfile.txt)
[config.txt](https://github.com/99designs/aws-vault/files/9013279/config.txt)
a config file that works just fine on the mac does not work on ubuntu
it bugs out with the error message.
"Your profile has a source_profile of default, adding credentials to default won't have any effect"

if I then remove the string default and change it to a random string "tiger" it then says
aws-vault: error: add: Object does not exist at path “/”

**Comment by marcinrogacki** [comment]
In my case I had to install _Vaulting Backend_ on machine https://github.com/99designs/aws-vault#vaulting-backends
I've used _pass_, but probably _Gnome Keyring_ ir _KWallet_ will be simpler. What I've done:

* installed pass
* installed gnupg
* created key pair: gpg --full-gen-key
* informed aws-vault abut backend: export AWS_VAULT_BACKEND=pass

**Comment by smnrdln** [comment]
as @marcinrogacki mentioned, this might be a temporary solution and worked for me in Ubuntu 24.04:

`sudo apt-get update`
`sudo apt-get install pass gnupg`
`gpg --full-gen-key`
Key Type: Choose RSA and RSA (default).
Key Size: Choose 2048 or 4096 bits (4096 is more secure).
Key Expiration: Set it as needed (e.g., 1 year) or choose "0" for no expiration.
Real Name: Enter your name.
Email Address: Enter your email address.
Passphrase: Choose a strong passphrase.

`pass init your-gpg-key-id`
The GPG key ID is the last 8 characters of the long string following pub (which is the public key).
e.g. 
pub   rsa4096 2024-08-13 [SC] [expires: 2025-08-13]
      1234ABCD5678EFGH9012IJKL3456MNOP7890QRST 
In the example above, the key ID is 7890QRST.
Alternatively, you can use the shorter form of the key ID by taking the first 8 characters of that string, 1234ABCD.

then:
`export AWS_VAULT_BACKEND=pass`
'export GPG_TTY=$(tty)'

Make them permanent:
`echo 'export AWS_VAULT_BACKEND=pass' >> ~/.bashrc`
`echo 'export GPG_TTY=$(tty)' >> ~/.bashrc`
`source ~/.bashrc`

then
`aws-vault add your-profile-name`
