### ISSUE TITLE
consider aligning generated profile name with what the web AWS SSO login page provides

### ISSUE THREAD

**Issue by BogdanSorlea** [99designs/aws-vault#966]
I am investigating this tool, but one thing I notice being different to what AWS SSO web login page provides is the generated profile name. In your [documentation](https://github.com/99designs/aws-vault/blob/master/USAGE.md), it's in the form `Administrator-123456789012]`, but the "Command line or programmatic access" content uses a profile in the form [ACCOUNT_NUMBER]_[ROLE] - the correspondent in the previous example would be `123456789012_Administrator`.

Could you align that, so that users can successfully use scripts relying on profiles, regardless whether logged in via this tool or the AWS SSO web? Alternatively to offer some configuration option so that it allows this flexibility while maybe maintaining backwards compatibility?

It is my fear that this tool relies on the awscli which seems to use the same format when `aws sso login` - but please clarify.

**Comment by BogdanSorlea** [comment]
for transparency, note that I've raised the same issue with awscli: https://github.com/aws/aws-cli/issues/7077

**Comment by BogdanSorlea** [comment]
for transparency, I've mentioned this problem to awscli as well: https://github.com/aws/aws-cli/issues/7077

**Comment by mtibben** [comment]
You can name your profiles whatever you want - there is no restriction from aws-vault
