### ISSUE TITLE
aws-vault not letting me enter secret passphrase. "aws-vault: error: login: profile scott: operation error IAM: GetUser, failed to resolve service endpoint, an AWS region is required, but was not found"

### ISSUE THREAD

**Issue by gottscraham** [99designs/aws-vault#967]
aws-vault: error: login: profile scott: operation error IAM: GetUser, failed to resolve service endpoint, an AWS region is required, but was not found

I am trying to set up the AWS vault for my credentials but it is not letting me type the secret passphrase. I have seen posts saying to type it in and assume it is invisible but when I try to test it by loading a login page it gives me the above error.. Please any help is crazy appreciated.

I am using Linux Ubuntu if that does anything.

- [x] I am using the latest release of AWS Vault

aws-vault --debug exec scott -- echo hello
2022/07/01 10:20:08 aws-vault 6.5.0-Homebrew
2022/07/01 10:20:08 Loading config file /home/gottscraham/.aws/config
2022/07/01 10:20:08 Parsing config file /home/gottscraham/.aws/config
2022/07/01 10:20:08 [keyring] Considering backends: [secret-service]
2022/07/01 10:20:08 Profile 'default' missing in config file
2022/07/01 10:20:08 profile scott: using stored credentials
2022/07/01 10:20:08 profile scott: using GetSessionToken 
aws-vault: error: exec: Failed to get credentials for scott: operation error STS: GetSessionToken, failed to resolve service endpoint, an AWS region is required, but was not found

**Comment by mtibben** [comment]
set the region in your .aws/config
